USE [VGLog]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_MKT_STATS_INDEX]

/*
USP_MKT_STATS_INDEX '2014-03-24', 'VG'
*/

@TARGET_DATE VARCHAR(10),
@AFF_CODE VARCHAR(2)

AS

SET ANSI_WARNINGS OFF
SET ARITHIGNORE ON
SET ARITHABORT OFF


SELECT *
INTO #TMP_TABLE
FROM (
	SELECT PRO_CODE, PRO_TYPE FROM MKT_MASTER WHERE AFF_CODE=@AFF_CODE
	UNION
	SELECT PRO_CODE, PRO_TYPE FROM MKT_MASTER_DEL WHERE AFF_CODE=@AFF_CODE
) A

CREATE INDEX TMP_TABLE_IDX ON #TMP_TABLE (PRO_CODE)


--삭제
DELETE MKT_STATS_DAY WHERE APP_DATE=@TARGET_DATE AND AFF_CODE=@AFF_CODE


--인서트
INSERT INTO MKT_STATS_DAY
SELECT *
FROM (
	SELECT @TARGET_DATE AS TARGET_DATE, B.PRO_TYPE, @AFF_CODE AS AFF_CODE, SUM(VIEW_CNT) AS VIEW_CNT, SUM(CLICK_CNT) AS CLICK_CNT, 
	SUM(CPC_PRICE) AS CPC_PRICE, SUM(CPC_PRICE) / SUM(CLICK_CNT) AS AVG_PRICE, GETDATE() AS CREATE_DATE
	FROM MKT_STATS_LOG A
	JOIN #TMP_TABLE B ON A.PRO_CODE=B.PRO_CODE
	WHERE AFF_CODE=@AFF_CODE
	GROUP BY B.PRO_TYPE
	UNION ALL
	SELECT @TARGET_DATE, 'ALL', @AFF_CODE, SUM(VIEW_CNT), SUM(CLICK_CNT), SUM(CPC_PRICE), SUM(CPC_PRICE) / SUM(CLICK_CNT), GETDATE()
	FROM MKT_STATS_LOG 
	WHERE AFF_CODE=@AFF_CODE
) A
WHERE VIEW_CNT IS NOT NULL


GO
