USE [VGLog]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_MKT_MASTER_HOTEL_LIST]
 
 /*
 USP_MKT_MASTER_HOTEL_LIST 'VG'
 */
 
 @AFF_CODE VARCHAR(2)
 
 AS
 
 SELECT * 
 FROM MKT_MASTER
 WHERE AFF_CODE=@AFF_CODE
 AND PRO_TYPE IN ('HTL', 'HTD')
  ORDER BY (CASE PRO_TYPE WHEN 'HTD' THEN 1 WHEN 'HTL' THEN 2 ELSE 3 END),
 (CASE SUBSTRING(PRO_CODE, 3, 1) WHEN 'P' THEN 1 WHEN 'W' THEN 2 ELSE 3 END)
 
GO
