USE [Sirens]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*================================================================================================================
■ USP_NAME					: SP_CTI_SMS_GOODS_MESSAGE_SELECT
■ DESCRIPTION				: CTI 상품정보 SMS메시지 내용
■ INPUT PARAMETER			: 
	@PRO_CODE				: 상품마스터코드 
■ OUTPUT PARAMETER			: 
■ EXEC						: 

	exec SP_CTI_SMS_GOODS_MESSAGE_SELECT @PRO_CODE ='AFP2703-141120SQ'
■ MEMO						: 
------------------------------------------------------------------------------------------------------------------
■ CHANGE HISTORY                   
------------------------------------------------------------------------------------------------------------------
   DATE				AUTHOR			DESCRIPTION           
------------------------------------------------------------------------------------------------------------------
   2014-11-20		곽병삼			상품정보 SMS 메시지 내역 생성
================================================================================================================*/ 
CREATE PROCEDURE [cti].[SP_CTI_SMS_GOODS_MESSAGE_SELECT]
--DECLARE
	@PRO_CODE	VARCHAR(20)
--SET @PRO_CODE = 'AFP2703-141120SQ'
AS

SET NOCOUNT ON

	DECLARE
		@EMP_CODE	VARCHAR(7),
		@EMP_NAME	VARCHAR(20)

	--항공정보 담기 
	DECLARE 
		@DEP_INFO_STR VARCHAR(100),
		@ARR_INFO_STR VARCHAR(100),
		@DEP_TRANS_CODE VARCHAR(2) , @DEP_TRANS_NUMBER  VARCHAR(4) , 
		@DEP_DEP_AIRPORT_CODE CHAR(3), @DEP_DEP_DATE DATETIME, @DEP_DEP_TIME CHAR(5),
		@DEP_ARR_AIRPORT_CODE CHAR(3), @DEP_ARR_DATE DATETIME, @DEP_ARR_TIME CHAR(5),
		@ARR_TRANS_CODE VARCHAR(2), @ARR_TRANS_NUMBER VARCHAR(4), 
		@ARR_DEP_AIRPORT_CODE CHAR(3), @ARR_DEP_DATE DATETIME, @ARR_DEP_TIME CHAR(5),
		@ARR_ARR_AIRPORT_CODE CHAR(3), @ARR_ARR_DATE DATETIME, @ARR_ARR_TIME CHAR(5) 

	--담당자
	SELECT 
		@EMP_CODE = A.NEW_CODE,
		@EMP_NAME = B.KOR_NAME
	FROM Diablo.DBO.PKG_DETAIL A WITH(NOLOCK)
	INNER JOIN Diablo.dbo.EMP_MASTER B WITH(NOLOCK)
	ON A.NEW_CODE = B.EMP_CODE
	WHERE PRO_CODE = @PRO_CODE

	--항공정보
	SELECT
		@DEP_TRANS_CODE = DEP_TRANS_CODE, @DEP_TRANS_NUMBER = DEP_TRANS_NUMBER, 
		@DEP_DEP_AIRPORT_CODE = DEP_DEP_AIRPORT_CODE, @DEP_DEP_DATE = DEP_DEP_DATE, @DEP_DEP_TIME = DEP_DEP_TIME,
		@DEP_ARR_AIRPORT_CODE = DEP_ARR_AIRPORT_CODE, @DEP_ARR_DATE = DEP_ARR_DATE, @DEP_ARR_TIME = DEP_ARR_TIME,  
		@ARR_TRANS_CODE = ARR_TRANS_CODE, @ARR_TRANS_NUMBER = ARR_TRANS_NUMBER, 
		@ARR_DEP_AIRPORT_CODE = ARR_DEP_AIRPORT_CODE, @ARR_DEP_DATE = ARR_DEP_DATE, @ARR_DEP_TIME = ARR_DEP_TIME,
		@ARR_ARR_AIRPORT_CODE = ARR_ARR_AIRPORT_CODE, @ARR_ARR_DATE = ARR_ARR_DATE, @ARR_ARR_TIME = ARR_ARR_TIME   
	FROM Diablo.DBO.PRO_TRANS_SEAT E 
	WHERE SEAT_CODE IN (SELECT SEAT_CODE FROM Diablo.DBO.PKG_DETAIL WHERE PRO_CODE = @PRO_CODE)


	SET @DEP_INFO_STR = '한국출발' + SUBSTRING(CONVERT(VARCHAR(10),@DEP_DEP_DATE,121),6,2) +'월' +SUBSTRING(CONVERT(VARCHAR(10),@DEP_DEP_DATE,121),9,2) +'일'
	+ '[' + @DEP_TRANS_CODE + @DEP_TRANS_NUMBER +']' + @DEP_DEP_AIRPORT_CODE + ' '+@DEP_DEP_TIME + '>' + @DEP_ARR_AIRPORT_CODE + ' ' + @DEP_ARR_TIME + ' ' 

	SET @ARR_INFO_STR = 
	 '/현지출발' + SUBSTRING(CONVERT(VARCHAR(10),@ARR_DEP_DATE,121),6,2) +'월' +SUBSTRING(CONVERT(VARCHAR(10),@ARR_DEP_DATE,121),9,2)  +'일'
	+ '[' + @ARR_TRANS_CODE + @ARR_TRANS_NUMBER +']' + @ARR_DEP_AIRPORT_CODE + ' '+@ARR_DEP_TIME + '>' + @ARR_ARR_AIRPORT_CODE + ' ' + @ARR_ARR_TIME  

	SELECT
		MAIN_CODE,
		MAIN_NAME,
		SORT,
		CASE WHEN MAIN_CODE = 'K' THEN REPLACE(REPLACE(REMARK ,'{0}', '{0}') ,'{1}', @EMP_NAME)
			 WHEN MAIN_CODE = 'L' THEN REPLACE(REPLACE(REMARK ,'{0}', @DEP_INFO_STR) ,'{1}', @ARR_INFO_STR)
			 ELSE REMARK 
		END AS REMARK 
	FROM CTI_CODE_MASTER
	WHERE CATEGORY = 'SMS000'
	AND MAIN_CODE IN ('K','L')
	AND USE_YN = 'Y'
	ORDER BY MAIN_CODE

SET NOCOUNT OFF 

GO
