USE [Sirens]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*================================================================================================================
■ USP_NAME					: SP_BEFORE_CUSTOMER_SELECT
■ DESCRIPTION				: 출발전 고객
■ INPUT PARAMETER			: 
	@PAGE_INDEX				: 현제 페이지
	@PAGE_SIZE				: 데이타 ROW 갯수
	@SDATE					: 시작일
	@EDATE					: 종료일
	@EMP_CODE				: 상담사 키
	@TEAM_CODE				: 상담사 팀
	@DIFF_DATE				: 출발 D-DAY
	@RES_STATE			    : 처리상태
	@COLS_NAME				: 정렬 필드명
	@SORT					: 정렬방식
	@TOTAL_COUNT			: 총갯수
■ OUTPUT PARAMETER			: 
■ EXEC						: 
	DECLARE @TOTAL_COUNT INT
	DECLARE @CONSULT_RESULT0_COUNT INT
	DECLARE @CONSULT_RESULT1_COUNT INT
	DECLARE @CONSULT_RESULT2_COUNT INT
	DECLARE @CONSULT_RESULT3_COUNT INT
	exec SP_BEFORE_CUSTOMER_SELECT 1,10, '2014-10-01','2014-10-27','','','0','','','','DATE_DIFF',' ASC',@TOTAL_COUNT OUTPUT
	,@CONSULT_RESULT0_COUNT OUTPUT,@CONSULT_RESULT1_COUNT OUTPUT,@CONSULT_RESULT2_COUNT OUTPUT,@CONSULT_RESULT3_COUNT OUTPUT
■ MEMO						: 
------------------------------------------------------------------------------------------------------------------
■ CHANGE HISTORY                   
------------------------------------------------------------------------------------------------------------------
   DATE_DIFF   CONSULT_RESULT_NAME		DEP_DATE		   CONSULT_RES_DATE		RES_STATE    RES_CODE		RES_NAME		RES_TEL
------------------------------------------------------------------------------------------------------------------
  10              미처리	    	2014-05-05 10:10:12      2014-05-05 10:10:12     NULL      00000        예약자           02-333-4444
================================================================================================================*/ 


CREATE PROCEDURE [cti].[SP_BEFORE_CUSTOMER_SELECT]
--DECLARE
	@PAGE_INDEX			INT=1,
	@PAGE_SIZE			INT=10,
	@SDATE				VARCHAR(10)='',
	@EDATE				VARCHAR(10)='',
	@EMP_CODE			VARCHAR(10)='',
	@TEAM_CODE			VARCHAR(100)='',
	--@DIFF_DATE			VARCHAR(10)='',
	@RES_STATE			VARCHAR(10)='',
	@RES_CODE			VARCHAR(20)='',
	@RES_NAME			VARCHAR(100)='',
	@COLS_NAME			VARCHAR(30)='DATE_DIFF',
	@SORT				VARCHAR(20)='DESC',
	@TOTAL_COUNT INT OUTPUT,
	@CONSULT_RESULT0_COUNT INT OUTPUT,
	@CONSULT_RESULT1_COUNT INT OUTPUT,
	@CONSULT_RESULT2_COUNT INT OUTPUT,
	@CONSULT_RESULT3_COUNT INT OUTPUT
AS


SET NOCOUNT ON


	DECLARE @BSQL VARCHAR(8000)
	DECLARE @SQL VARCHAR(8000)
	

	IF @COLS_NAME IS NULL OR @COLS_NAME = ''
		SET @COLS_NAME = 'DATE_DIFF '

	IF @SORT IS NULL OR @SORT = ''
		SET @SORT = ' DESC'
	
	


	SELECT * INTO #TEMP  FROM
		 ( 
			--SELECT 
			--	DATEDIFF(DAY, GETDATE(),RM.DEP_DATE) AS DATE_DIFF --구분
			--	,isnull(CR.CONSULT_RESULT,1) as CONSULT_RESULT --처리결과
			--	,RM.DEP_DATE--출발일자
			--	,CR.CONSULT_RES_DATE--처리일자
			--	,RM.RES_STATE--상태
			--	,RM.RES_CODE--예약코드
			--	,RM.RES_NAME--예약자
			--	,RM.NOR_TEL1 + '-' + RM.NOR_TEL2 + '-' + RM.NOR_TEL3 AS RES_TEL --전화걸기 
			--	,(SELECT MAIN_NAME  FROM CTI_CODE_MASTER WITH(NOLOCK) WHERE CATEGORY='CTI101' AND MAIN_CODE=isnull(CR.CONSULT_RESULT,1) AND USE_YN='Y') AS CONSULT_RESULT_NAME
			--from Diablo..RES_MASTER RM 
			--	LEFT OUTER JOIN CTI_CONSULT_RESERVATION CR  ON CR.RES_CODE=RM.RES_CODE
			--WHERE RM.DEP_DATE>=@SDATE + ' 00:00:00'  AND RM.DEP_DATE<=@EDATE + ' 23:59:59'
			--	AND (ISNULL(@EMP_CODE,'')='' OR CR.EMP_CODE = @EMP_CODE)
			--	AND (ISNULL(@TEAM_CODE,'')='' OR CR.TEAM_CODE=@TEAM_CODE)
			--	--AND  (ISNULL(@DIFF_DATE,'')='' OR  DATEDIFF(DAY,RM.DEP_DATE, GETDATE())=@DIFF_DATE)
			--	AND  (ISNULL(@RES_STATE,'')='' OR RM.RES_STATE = @RES_STATE)
			--	AND (ISNULL(@RES_CODE,'')='' OR RM.RES_CODE=@RES_CODE)
			--	AND (ISNULL(@RES_NAME,'')='' OR RM.RES_NAME LIKE '%' + @RES_CODE + '%')

			SELECT
				CASE WHEN DATEDIFF(DAY, RM.DEP_DATE, GETDATE()) < 0 THEN CAST(DATEDIFF(DAY, GETDATE(), RM.DEP_DATE) AS VARCHAR) + '일전' 
				WHEN DATEDIFF(DAY, RM.DEP_DATE, GETDATE()) > 0 THEN CAST(DATEDIFF(DAY, RM.DEP_DATE, GETDATE()) AS VARCHAR) + '일 경과' 
				ELSE '당일' END DATE_DIFF,
				(SELECT MAIN_NAME  FROM CTI_CODE_MASTER WITH(NOLOCK) WHERE CATEGORY='CTI101' AND MAIN_CODE=ISNULL(CTI.ERP_RES_CALL_RESULT,'1') AND USE_YN='Y') AS CONSULT_RESULT,
				--CONVERT(VARCHAR(10),RM.DEP_DATE,120) AS DEP_DATE,
				--CONVERT(VARCHAR(5), RM.DEP_DATE,108) AS DEP_TIME,
				CONVERT(VARCHAR(10),SEAT.DEP_DEP_DATE,120) AS DEP_DATE,
				SEAT.DEP_DEP_TIME AS DEP_TIME,
				ISNULL(CONVERT(VARCHAR(10),CTI.NEW_DATE,120),'') AS RESULT_DATE,
				ISNULL(CONVERT(VARCHAR(5), CTI.NEW_DATE,108),'') AS RESULT_TIME,
				RM.RES_CODE,
				RM.RES_NAME,
				(SELECT COUNT(*) FROM Diablo.dbo.RES_CUSTOMER_DAMO WITH(NOLOCK) WHERE RES_CODE = RM.RES_CODE AND RES_STATE IN (0, 4)) AS RES_COUNT,
				RM.RES_STATE,
				ISNULL(RM.NOR_TEL1 + RM.NOR_TEL2 + RM.NOR_TEL3,'') AS RES_TEL,
				RM.CUS_NO,
				ISNULL(CTI.ERP_RES_CALL_SEQ,'') AS ERP_RES_CALL_SEQ,
				RM.PRO_CODE
			FROM Diablo.dbo.RES_MASTER RM WITH(NOLOCK)
			LEFT OUTER JOIN CTI_ERP_RES_CALL_RESULT CTI WITH(NOLOCK)
			ON RM.RES_CODE = CTI.RES_CODE
			AND RM.CUS_NO = CTI.CUS_NO
			AND CONVERT(VARCHAR(10),RM.DEP_DATE,120) = CONVERT(VARCHAR(10),CTI.DEP_DATE,120)
			LEFT OUTER JOIN diablo.dbo.PKG_DETAIL PD WITH(NOLOCK)
			ON RM.PRO_CODE = PD.PRO_CODE
			LEFT OUTER JOIN diablo.dbo.PRO_TRANS_SEAT SEAT WITH(NOLOCK)
			ON PD.SEAT_CODE = SEAT.SEAT_CODE
			--WHERE CONVERT(VARCHAR(10), RM.DEP_DATE,120) BETWEEN @SDATE AND @EDATE
			WHERE RM.DEP_DATE BETWEEN CONVERT(DATETIME,@SDATE +' 00:00:00.000') AND CONVERT(DATETIME,@EDATE +' 23:59:59.997')
			AND RM.NEW_CODE = @EMP_CODE
			AND RM.NEW_TEAM_CODE = @TEAM_CODE
			AND  (ISNULL(@RES_STATE,'')='' OR RM.RES_STATE = @RES_STATE)
			AND (ISNULL(@RES_CODE,'')='' OR RM.RES_CODE=@RES_CODE)
			AND RM.RES_NAME LIKE '%' + @RES_NAME + '%'
			AND RM.RES_STATE NOT IN (7,8,9)

			)T1
			ORDER BY T1.DEP_DATE, T1.DEP_TIME





		
		SET @SQL = '
			SELECT  *
			FROM (
				SELECT
					ROW_NUMBER() OVER(ORDER BY  ' + @COLS_NAME + ' ' + @SORT + '  ) AS RNO,
					DATE_DIFF,
					CONSULT_RESULT,
					DEP_DATE,
					DEP_TIME,
					RESULT_DATE,
					RESULT_TIME,
					RES_CODE,
					RES_NAME,
					RES_COUNT,
					RES_STATE,
					RES_TEL,
					CUS_NO,
					ERP_RES_CALL_SEQ,
					PRO_CODE
				FROM #TEMP AS CD
				)T1
			WHERE RNO>=' + CONVERT(VARCHAR(100), (( @PAGE_INDEX-1 )*@PAGE_SIZE)+1 ) + '	and RNO<=' + CONVERT(VARCHAR(100), @PAGE_INDEX*@PAGE_SIZE ) + ' 
	'
	EXEC(@SQL)

	SET @TOTAL_COUNT = 0

		SELECT
			@CONSULT_RESULT0_COUNT = ISNULL(SUM(CASE WHEN CONSULT_RESULT='0' THEN 1 ELSE 0 END ),0) 
			,@CONSULT_RESULT1_COUNT = ISNULL(SUM(CASE WHEN CONSULT_RESULT='1' THEN 1 ELSE 0 END ),0)
			,@CONSULT_RESULT2_COUNT = ISNULL(SUM(CASE WHEN CONSULT_RESULT='2' THEN 1 ELSE 0 END ),0) 
			,@CONSULT_RESULT3_COUNT = ISNULL(SUM(CASE WHEN CONSULT_RESULT='3' THEN 1 ELSE 0 END ),0)
			,@TOTAL_COUNT = COUNT(*) 
		FROM #TEMP

		DROP TABLE #TEMP



SET NOCOUNT OFF
GO
