USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[FN_GET_PAY_COMMITION]
(
@PRICE DECIMAL,
@PAY_TYPE VARCHAR(10)
)
RETURNS DECIMAL
AS 
BEGIN
	DECLARE @RES DECIMAL;
	DECLARE @CNT INT;
	DECLARE @RATE DECIMAL(16,2);
	
	SET @RES = 0;
	SET @CNT = 0;
	SET @RATE = 0.00;
	
	SELECT @CNT = COUNT(*) 
	FROM TBL_PAY_COM_RATE
	WHERE PAY_TYPE=@PAY_TYPE
	
	IF (@CNT=0) 
		BEGIN
			SET @RATE = 0.00;
		END
	ELSE
		BEGIN 
	
			SELECT @RATE = (CASE WHEN PAY_TYPE='VTAC' THEN COM_PRICE ELSE COM_RATE END)
			FROM TBL_PAY_COM_RATE
			WHERE PAY_TYPE=@PAY_TYPE
			
		END
		
	IF (@PAY_TYPE='VTAC')
		BEGIN
			SET @RES = @RATE
		END
	ELSE
		BEGIN
			
			SET @RES = ROUND(@PRICE * (@RATE/100), 0)
			--SET @RES = @RATE;
		
		END

	RETURN(@RES)
END


GO
