USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[FN_GET_SLIP_NUMBER]
(
	@DATE VARCHAR(10)
)
RETURNS VARCHAR(100)
AS 
BEGIN
	DECLARE @RES VARCHAR(100);
	DECLARE @ID VARCHAR(14);
	DECLARE @NO VARCHAR(5);
	DECLARE @NUM INT;

	SET @DATE = REPLACE(@DATE,'-', '');

	SELECT @ID = MAX(ROW_ID)
	FROM ACC_SLIP_MAST
	WHERE ROW_ID LIKE 'H' + @DATE + '%'

	IF (@ID IS NULL)
		BEGIN

			SET @RES = 'H' + @DATE + '00001'

		END
	ELSE
		BEGIN

			SET @RES = LEFT(@ID, 9);
			SET @NO = RIGHT(@ID, 5);
			SET @NUM = CONVERT(INT, @NO) + 1;
			SET @NO = RIGHT('00000' + CONVERT(VARCHAR, @NUM), 5);
			SET @RES = @RES + @NO;

		END

	RETURN(@RES)
END


GO
