USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
  
-- 제휴사 이름 가져오기
CREATE FUNCTION [dbo].[FN_GET_AFFNAME] (  
 @MCPN_CODE    VARCHAR(1000)  
)  
Returns varchar(1000)  
AS  
BEGIN  
  
DECLARE @RTN VARCHAR(1000)   
DECLARE @MCPN_NAME VARCHAR(100)

SET @MCPN_CODE = REPLACE(@MCPN_CODE, ' ', '');

DECLARE VCURSOR CURSOR
FOR SELECT MCPN_NAME
	FROM DBO.FN_SPLIT(@MCPN_CODE, ',') A
	JOIN TBL_SYST_MCPN B ON A.VALUE=B.MCPN_CODE


SET @RTN='';

OPEN VCURSOR

FETCH NEXT FROM VCURSOR
INTO @MCPN_NAME

WHILE @@FETCH_STATUS = 0
BEGIN

	IF (@RTN <> '')  SET @RTN = @RTN + ',';
	SET @RTN = @RTN + @MCPN_NAME;

	FETCH NEXT FROM VCURSOR
	INTO @MCPN_NAME

END
  
RETURN @RTN  
  
END
GO
