USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USP_HTL_DOM_ROOM_PRICE_STATUS_UPDATE] 
  
/*  
USP_HTL_DOM_ROOM_PRICE_STATUS_UPDATE '1', '2', 'RQ', 'JACKSMT', '<XML />'  
*/  
  
@HOTEL_CODE VARCHAR(10),  
@ROOM_CODE VARCHAR(10),  
@AVAIL_TYPE VARCHAR(10),  
@UPDATE_USER VARCHAR(30),  
@XML VARCHAR(MAX)  
  
AS  
  
DECLARE @XML_DOCUMENT_HANDLE INT;  
DECLARE @XML_DOCUMENT VARCHAR(MAX);  
SET @XML_DOCUMENT = '<?xml version="1.0" encoding="euc-kr"?>' + @XML     
                  
EXEC SP_XML_PREPAREDOCUMENT @XML_DOCUMENT_HANDLE OUTPUT, @XML_DOCUMENT    
                  
                  
--요금 임시저장                  
                  
SELECT *             
INTO #TMP_TABLE          
FROM OPENXML (@XML_DOCUMENT_HANDLE, '/ArrayOfDZ/DZ',2)
WITH (    
     CHECK_IN_DATE varchar(10) './CD'
) A  

UPDATE HTL_DOM_INFO_PRICE_DIR SET
AVAIL_TYPE=@AVAIL_TYPE,
UPDATE_USER=@UPDATE_USER,
UPDATE_DATE=GETDATE()
FROM #TMP_TABLE A
JOIN HTL_DOM_INFO_PRICE_DIR B ON B.HOTEL_CODE=@HOTEL_CODE AND B.ROOM_CODE=@ROOM_CODE AND B.CHECK_IN_DATE=A.CHECK_IN_DATE

EXEC SP_XML_REMOVEDOCUMENT @XML_DOCUMENT_HANDLE   
  
  
GO
