USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_INSERT_RESV_PAY_REFUND_CARD]

/*
USP_INSERT_RESV_PAY_REFUND_CARD '2', 'NOTRUST'
*/

@PAY_SEQ INT,
@USER_ID VARCHAR(50)

AS

DECLARE @CNT INT;

SELECT @CNT = COUNT(*)
FROM HTL_RESV_PAY A
WHERE PAY_SEQ=@PAY_SEQ
AND PAY_TYPE IN ('CARD', 'ARS')
AND PAY_SEQ NOT IN (SELECT REF_PAY_SEQ FROM HTL_RESV_PAY WHERE REF_PAY_SEQ=A.PAY_SEQ)

IF (@CNT > 0) 
	BEGIN

		INSERT INTO HTL_RESV_PAY
		(
		RESV_NO, PAY_NO, PAY_TYPE, PAY_CURRENCY, PAY_TOTAL_AMOUNT, PAY_STATUS, PAY_DATE, PAY_USER, 
		CARD_AMOUNT, CARD_NAME, CARD_NUM, CASH_AMOUNT, CASH_ACCOUNT_BANK, CASH_ACCOUNT_NO, CASH_PAY_NAME, 
		CASH_PAY_DATE, CASH_RECEIPT_CONT, APP_NO, TRAN_NO, PAYMENT_ID, LAST_UPDATE_YN, LAST_UPDATE_DATE, 
		LAST_UPDATE_USER, USE_YN, CONN_NO, REAL_RECEIVE_MONEY, REAL_RECEIVE_DATE, 
		SLIP_TARGET_YN, CASH_ACCOUNT_BANK_CODE, REF_PAY_SEQ
		)
		SELECT RESV_NO, (SELECT ISNULL(MAX(PAY_NO),0) + 1 FROM HTL_RESV_PAY WHERE RESV_NO=A.RESV_NO), 
		PAY_TYPE, PAY_CURRENCY, -(PAY_TOTAL_AMOUNT), 'RMXX', GETDATE(), PAY_USER, 
		-(CARD_AMOUNT), CARD_NAME, CARD_NUM, -(CASH_AMOUNT), CASH_ACCOUNT_BANK, CASH_ACCOUNT_NO, CASH_PAY_NAME, 
		CASH_PAY_DATE, CASH_RECEIPT_CONT, APP_NO, TRAN_NO, PAYMENT_ID, LAST_UPDATE_YN, LAST_UPDATE_DATE, 
		@USER_ID, USE_YN, CONN_NO, REAL_RECEIVE_MONEY, REAL_RECEIVE_DATE, 
		'N', CASH_ACCOUNT_BANK_CODE, @PAY_SEQ
		FROM HTL_RESV_PAY A
		WHERE PAY_SEQ=@PAY_SEQ
		AND PAY_TYPE IN ('CARD', 'ARS')

		SELECT @@IDENTITY AS [IDENTITY]

		DECLARE @PAY_DATE VARCHAR(8);
		DECLARE @TODAY VARCHAR(8);
		DECLARE @TIME VARCHAR(5);
		SELECT @PAY_DATE = CONVERT(VARCHAR,PAY_DATE,112) FROM HTL_RESV_PAY WHERE PAY_SEQ=@PAY_SEQ;
		SELECT @TODAY = CONVERT(VARCHAR,GETDATE(),112)
		SELECT @TIME = CONVERT(VARCHAR(5),GETDATE(),114)

		IF (@PAY_DATE = @TODAY AND @TIME < '23:30')
		BEGIN 
			UPDATE HTL_RESV_PAY SET SLIP_TARGET_YN='N' WHERE PAY_SEQ=@PAY_SEQ;
		END

		UPDATE HTL_RESV_PAY SET REF_PAY_SEQ=@PAY_SEQ WHERE PAY_SEQ=@@IDENTITY;

	END

ELSE 

	BEGIN

		SELECT 0 AS [IDENTITY]

	END




GO
