USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HTL_HOTEL_SEARCH]

/*
USP_HTL_HOTEL_SEARCH '179897', '가든'
*/

@CITY_CODE VARCHAR(20),
@KEYWORD VARCHAR(100)

AS

IF (@CITY_CODE='0') 
	BEGIN

		SELECT TOP 20 HOTEL_CODE, NAME, ENG_NAME
		FROM (
			SELECT HOTEL_CODE, NAME, ENG_NAME,
			CHARINDEX(@KEYWORD, NAME) AS SORT1, CHARINDEX(@KEYWORD, ENG_NAME) AS SORT2
			FROM HTL_INFO_MAST_HOTEL
			WHERE CITY_CODE IS NULL
			AND USE_YN='Y'
			AND (UPPER(NAME) LIKE '%'+UPPER(@KEYWORD)+'%'
			OR UPPER(ENG_NAME) LIKE '%'+UPPER(@KEYWORD)+'%')
		) A
		ORDER BY SORT1, SORT2

	END
ELSE
	BEGIN
	
		SELECT TOP 20 HOTEL_CODE, NAME, ENG_NAME
		FROM (
			SELECT HOTEL_CODE, NAME, ENG_NAME,
			CHARINDEX(@KEYWORD, NAME) AS SORT1, CHARINDEX(@KEYWORD, ENG_NAME) AS SORT2
			FROM HTL_INFO_MAST_HOTEL
			WHERE CITY_CODE=@CITY_CODE
			AND USE_YN='Y'
			AND (UPPER(NAME) LIKE '%'+UPPER(@KEYWORD)+'%'
			OR UPPER(ENG_NAME) LIKE '%'+UPPER(@KEYWORD)+'%')
		) A
		ORDER BY SORT1, SORT2
		
	END


GO
