USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_MAP_CITY_JS]
          
/*          
USP_MAP_CITY_JS '3724'          
*/          
          
@CITY_CODE VARCHAR(20)          
          
AS          

SELECT CITY_CODE, CITY_NAME, CITY_ENAME, NATION_CODE, NATION_NAME, CENTER_LAT, CENTER_LNG
FROM HTL_CODE_MAST_CITY
WHERE CITY_CODE=@CITY_CODE


GO
