USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_SET_RESV_CHRG_USER]

/*
USP_SET_RESV_CHRG_USER '10018'
*/

@RESV_NO INT

AS

DECLARE @RESV_CNT INT;

SELECT @RESV_CNT = (CASE WHEN CHRG_USER IS NULL THEN 0 ELSE 1 END)
FROM HTL_RESV_MAST
WHERE RESV_NO=@RESV_NO

IF (@RESV_CNT=1) RETURN;


DECLARE @REG_DATE VARCHAR(8);
DECLARE @USER_ID VARCHAR(50);
DECLARE @CNT INT;

SET @REG_DATE = CONVERT(VARCHAR(8), GETDATE(), 112);

SELECT TOP 1 @USER_ID = A.USER_ID
FROM HTL_SYST_USER A
LEFT JOIN HTL_RESV_CHRG_USER B ON A.[USER_ID]=B.[USER_ID] AND B.REG_DATE=@REG_DATE
WHERE A.USER_TYPE='01'
AND A.ACC_ID IS NOT NULL
ORDER BY ISNULL(B.CNT,0), A.ACC_ID

--PRINT(@USER_ID)

SELECT @CNT = CNT
FROM HTL_RESV_CHRG_USER
WHERE [USER_ID]=@USER_ID
AND REG_DATE=@REG_DATE

SET @CNT = ISNULL(@CNT,0);
--PRINT(ISNULL(@CNT,0))

IF (@CNT=0) 
	BEGIN

	INSERT HTL_RESV_CHRG_USER
	([USER_ID], REG_DATE, CNT)
	VALUES
	(@USER_ID, @REG_DATE, @CNT + 1)

	END
ELSE 
	BEGIN

	UPDATE HTL_RESV_CHRG_USER SET CNT=@CNT+1
	WHERE [USER_ID]=@USER_ID
	AND REG_DATE=@REG_DATE

	END


UPDATE HTL_RESV_MAST SET 
CHRG_USER=@USER_ID 
WHERE RESV_NO=@RESV_NO AND CHRG_USER IS NULL

GO
