USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HOTEL_LIST_MAP]        
        
/*        
USP_HOTEL_LIST_MAP '179900'        
*/        
        
@CITY_CODE VARCHAR(20)        
        
AS     
    
SELECT     
A.HOTEL_CODE AS HOTELSEQ, ENG_NAME AS HOTELNAME_ENG, NAME AS HOTELNAME, STAR_RATING AS STARRATING, ADDRESS, MAIN_IMG AS HOTELIMAGE,    
LOCATION_DESC AS HOTELDESC, LATITUDE, LONGITUDE, AREA_NAME AS LOCATION, LOCATION_DESC AS LOCATIONDESC, ISNULL(SALE_AMT,9999999999) AS ABOUTPRICE,    
ISNULL((SELECT COUNT(*) FROM HTL_RESV_MAST WHERE HOTEL_CODE=CONVERT(VARCHAR,A.HOTEL_CODE) AND HOTEL_CODE NOT LIKE 'OF%'),0) AS BOOK_CNT,    
RV_POINT AS REVIEW_CNT, (CASE WHEN SALE_AMT IS NULL THEN 0 ELSE RV_POINT END) AS AVG_RATING,   
0 AS COND_RATING, 0 AS CLEAN_RATING, 0 AS COMFORT_RATING, 0 AS SVC_RATING, RV_POINT AS RECOM_RATING    
FROM HTL_INFO_MAST_HOTEL A    
LEFT JOIN HTL_INFO_PRICE B ON A.HOTEL_CODE=B.HOTEL_CODE    
WHERE CITY_CODE=@CITY_CODE    
AND USE_YN='Y'    
ORDER BY (CASE WHEN SALE_AMT IS NULL THEN 0 ELSE RV_POINT END) DESC, ISNULL(SALE_AMT,9999999999) ASC    




GO
