USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HTL_RESV_MAST_11ST2]

/*
USP_HTL_RESV_MAST_11ST2 'HTL14509742'
*/

@AFF_NO VARCHAR(100)

AS

DECLARE @RSV_NO VARCHAR(100)
DECLARE @TYPE VARCHAR(3)

SET @TYPE = SUBSTRING(@AFF_NO, 1, 3)
SET @RSV_NO = SUBSTRING(@AFF_NO, 4, LEN(@AFF_NO))

SELECT RESV_NO, @TYPE AS AFF_TYPE, @RSV_NO AS RSV_NO
FROM HOTEL.DBO.HTL_RESV_MAST
WHERE AFF_NO = @AFF_NO AND MCPN_CODE='EL0001'

UNION ALL

SELECT RESV_NO, @TYPE AS AFF_TYPE, @RSV_NO AS RSV_NO
FROM AIR.DBO.HTL_DOM_RESV_MAST
WHERE AFF_NO = @AFF_NO AND MCPN_CODE='EL0001'


GO
