USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HTL_DOM_HOLIDAY_UPDATE]  
  
/*  
[USP_HTL_DOM_HOLIDAY_UPDATE] '2015-05-06', 'EDITED', 'AIR.DBO.TBL_CODE_HOLIDAY'
*/  

@HOL_DATE VARCHAR(10),
@DATE_DESC VARCHAR(50),
@DB_NAME VARCHAR(MAX)  

AS

DECLARE @SQL VARCHAR(MAX)      
       
SET @SQL = ''  

SET @SQL = @SQL + ' UPDATE ' + @DB_NAME + ' SET' + CHAR(13)
SET @SQL = @SQL + ' DATE_DESC = ''' + @DATE_DESC + ''' ' + CHAR(13)
SET @SQL = @SQL + ' WHERE CONVERT(VARCHAR(10), TARGET_DATE, 121) = ''' + @HOL_DATE + ''' ' + CHAR(13)

PRINT(@SQL)          
EXEC(@SQL)
GO
