USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
  
CREATE PROC [dbo].[USP_HTL_DOM_ROOM_PRICE_INSERT_TO]  
  
/*  
USP_HTL_DOM_ROOM_PRICE_INSERT_TO '1', '2', 'AAA', 'JACKSMT', '<XML />'  
*/  
  
@HOTEL_CODE VARCHAR(10),  
@ROOM_CODE VARCHAR(10),  
@ROOM_NAME VARCHAR(500),  
@UPDATE_USER VARCHAR(30),  
@XML VARCHAR(MAX)  
  
AS  
  
DECLARE @XML_DOCUMENT_HANDLE INT;  
DECLARE @XML_DOCUMENT VARCHAR(MAX);  
SET @XML_DOCUMENT = '<?xml version="1.0" encoding="euc-kr"?>' + @XML     
                  
EXEC SP_XML_PREPAREDOCUMENT @XML_DOCUMENT_HANDLE OUTPUT, @XML_DOCUMENT    
                  
                  
--요금 임시저장                  
                  
SELECT *             
INTO #TMP_TABLE          
FROM OPENXML (@XML_DOCUMENT_HANDLE, '/ArrayOfDY/DY',2)                   
WITH (    
     CHECK_IN_DATE VARCHAR(10) './CD',            
     NET_PRICE DECIMAL './NP',  
     SALE_PRICE DECIMAL './SP',
     AVAIL_TYPE VARCHAR(2) './AV'        
) A  
  
  
--요금수정  
UPDATE HTL_DOM_INFO_PRICE_DIR SET   
ROOM_NAME = @ROOM_NAME,
AVAIL_TYPE = B.AVAIL_TYPE,
NET_PRICE = B.NET_PRICE,   
SALE_PRICE = B.SALE_PRICE,  
UPDATE_USER = @UPDATE_USER,  
UPDATE_DATE = GETDATE()  
FROM HTL_DOM_INFO_PRICE_DIR A  
JOIN #TMP_TABLE B ON A.HOTEL_CODE=@HOTEL_CODE AND A.ROOM_CODE=@ROOM_CODE AND A.CHECK_IN_DATE=B.CHECK_IN_DATE  
  
  
--요금등록  
INSERT HTL_DOM_INFO_PRICE_DIR   
(HOTEL_CODE, ROOM_CODE, ROOM_NAME, CHECK_IN_DATE, CURRENCY,   
NET_PRICE, SALE_PRICE, AVAIL_TYPE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)  
SELECT @HOTEL_CODE, @ROOM_CODE, @ROOM_NAME, A.CHECK_IN_DATE, 'KRW',   
A.NET_PRICE, A.SALE_PRICE, A.AVAIL_TYPE, @UPDATE_USER, GETDATE(), @UPDATE_USER, GETDATE()  
FROM #TMP_TABLE A  
LEFT JOIN HTL_DOM_INFO_PRICE_DIR B ON B.HOTEL_CODE=@HOTEL_CODE AND B.ROOM_CODE=@ROOM_CODE AND A.CHECK_IN_DATE=B.CHECK_IN_DATE  
WHERE B.HOTEL_CODE IS NULL  
  
  
EXEC SP_XML_REMOVEDOCUMENT @XML_DOCUMENT_HANDLE   
  
  
  
GO
