USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HTL_RESV_MAST_11ST]

/*
USP_HTL_RESV_MAST_11ST '17444108'
*/

@RSV_NO VARCHAR(100)

AS

SELECT 'HTL' AS AFF_TYPE, @RSV_NO AS RSV_NO, AFF_NO
FROM HOTEL.DBO.HTL_RESV_MAST
WHERE AFF_NO = 'HTL' + @RSV_NO AND MCPN_CODE='EL0001'

UNION ALL

SELECT 'HTD' AS AFF_TYPE, @RSV_NO AS RSV_NO, AFF_NO
FROM AIR.DBO.HTL_DOM_RESV_MAST
WHERE AFF_NO = 'HTD' + @RSV_NO AND MCPN_CODE='EL0001'


GO
