USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HTL_RESV_PAX_REFRESH]

/*
USP_HTL_RESV_PAX_REFRESH '10033', '1', '3', '4', '5', '', '7'
*/

@RESV_NO INT,
@PAX_NO INT,
@PAX_TYPE VARCHAR(3),
@SUR_NAME VARCHAR(100),
@GIVEN_NAME VARCHAR(200),
@GENDER VARCHAR(1),
@ROOM_NO INT

AS

DECLARE @CNT INT;
DECLARE @SQL NVARCHAR(MAX);
DECLARE @PARAM NVARCHAR(MAX);
SET @SQL = '';
SET @PARAM = '';

SELECT @CNT = COUNT(*)
FROM HTL_RESV_PAX
WHERE RESV_NO=@RESV_NO AND PAX_NO=@PAX_NO

IF (@CNT=0)
BEGIN

SET @SQL = @SQL + 'INSERT INTO HTL_RESV_PAX ';
SET @SQL = @SQL + '( ';
SET @SQL = @SQL + '	RESV_NO, ';
SET @SQL = @SQL + '	PAX_NO, ';
SET @SQL = @SQL + '	PAX_TYPE, ';
SET @SQL = @SQL + '	SUR_NAME, ';
SET @SQL = @SQL + '	GIVEN_NAME, ';
IF (ISNULL(@GENDER,'') <> '') SET @SQL = @SQL + '	GENDER, ';
SET @SQL = @SQL + '	ROOM_NO, ';
SET @SQL = @SQL + '	USE_YN, ';
SET @SQL = @SQL + '	CREATE_DATE, ';
SET @SQL = @SQL + '	CREATE_USER, ';
SET @SQL = @SQL + '	UPDATE_DATE, ';
SET @SQL = @SQL + '	UPDATE_USER ';
SET @SQL = @SQL + ') ';
SET @SQL = @SQL + 'VALUES ';
SET @SQL = @SQL + '( ';
SET @SQL = @SQL + '	@RESV_NO, ';
SET @SQL = @SQL + '	@PAX_NO, ';
SET @SQL = @SQL + '	@PAX_TYPE, ';
SET @SQL = @SQL + '	@SUR_NAME, ';
SET @SQL = @SQL + '	@GIVEN_NAME, ';
IF (ISNULL(@GENDER,'') <> '') SET @SQL = @SQL + '	@GENDER, ';
SET @SQL = @SQL + '	@ROOM_NO, ';
SET @SQL = @SQL + '	''Y'', ';
SET @SQL = @SQL + '	GETDATE(), ';
SET @SQL = @SQL + '	''SYSTEM'', ';
SET @SQL = @SQL + '	GETDATE(), ';
SET @SQL = @SQL + '	''SYSTEM'' ';
SET @SQL = @SQL + ') ';

END
ELSE
BEGIN

SET @SQL = @SQL + 'UPDATE HTL_RESV_PAX SET ';
SET @SQL = @SQL + '	PAX_TYPE = @PAX_TYPE, ';
SET @SQL = @SQL + '	SUR_NAME = @SUR_NAME, ';
SET @SQL = @SQL + '	GIVEN_NAME = @GIVEN_NAME, ';
IF (ISNULL(@GENDER,'') <> '') SET @SQL = @SQL + '	GENDER = @GENDER, ';
SET @SQL = @SQL + '	ROOM_NO = @ROOM_NO ';
SET @SQL = @SQL + 'WHERE ';
SET @SQL = @SQL + '	RESV_NO = @RESV_NO ';
SET @SQL = @SQL + '	AND PAX_NO = @PAX_NO ';

END

--PRINT(@SQL)

SET @PARAM = '@RESV_NO INT, @PAX_NO INT, @PAX_TYPE VARCHAR(3), @SUR_NAME VARCHAR(100), @GIVEN_NAME VARCHAR(200), @GENDER VARCHAR(1), @ROOM_NO INT';

EXEC SP_EXECUTESQL @SQL, @PARAM, @RESV_NO, @PAX_NO, @PAX_TYPE, @SUR_NAME, @GIVEN_NAME, @GENDER, @ROOM_NO


GO
