USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HTL_RANKING2]

/* 
USP_HTL_RANKING '', 'TOTAL_CNT', '2015-01-01', '2015-01-31' 
*/    

@SUPP_CODE VARCHAR(10),     
@ORDER_TYPE VARCHAR(20),     
@DATE_FROM VARCHAR(10),     
@DATE_TO VARCHAR(10),
@HOTEL_NAME VARCHAR(300),
@PARTNER_SHIP VARCHAR(10) = ''      

AS      
 
DECLARE @SQL VARCHAR(MAX)   
SET @SQL = ''  
SET @SQL = @SQL + ' SET ANSI_WARNINGS OFF ' + CHAR(13) 
SET @SQL = @SQL + ' SET ARITHIGNORE ON ' + CHAR(13)  
SET @SQL = @SQL + ' SET ARITHABORT OFF ' + CHAR(13)   
SET @SQL = @SQL + ' SELECT ' + CHAR(13)  
SET @SQL = @SQL + '  A.HOTEL_NAME, ' + CHAR(13)  
SET @SQL = @SQL + '  B.CITY_NAME, ' + CHAR(13)  
SET @SQL = @SQL + '  A.SUPP_CODE, ' + CHAR(13)  
SET @SQL = @SQL + '  COUNT(*) AS TOTAL_CNT, ' + CHAR(13)  
SET @SQL = @SQL + '  SUM(A.TOTAL_AMT) AS TOTAL_AMT, ' + CHAR(13)  
SET @SQL = @SQL + '  COUNT(CASE WHEN A.LAST_STATUS = ''RMTK'' AND C.PAY_STATUS = ''RMTK'' THEN A.RESV_NO END) AS RMTK_CNT, ' + CHAR(13)  
SET @SQL = @SQL + '  ISNULL(SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' AND C.PAY_STATUS = ''RMTK'' THEN (CASE WHEN A.SUPP_CODE = ''EX'' AND MCPN_CODE NOT IN (''VG0000'') THEN FLOOR(C.PAY_AMT * A.EX_RATE) ELSE C.PAY_AMT END) ELSE 0 END), 0) AS RMTK_AMT, ' + CHAR(13)  
SET @SQL = @SQL + '  SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' AND C.PAY_STATUS = ''RMTK'' THEN A.COM_AMT ELSE 0 END) AS RMTK_COM, ' + CHAR(13)  
SET @SQL = @SQL + '  CONVERT(VARCHAR(10),A.CREATE_DATE,121) AS CREATE_DATE, ' + CHAR(13)  
SET @SQL = @SQL + '  ISNULL(ROUND(SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' AND C.PAY_STATUS = ''RMTK'' THEN A.COM_AMT ELSE 0 END) / SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' AND C.PAY_STATUS = ''RMTK'' THEN (CASE WHEN A.SUPP_CODE = ''EX'' THEN FLOOR(C.PAY_AMT * A.EX_RATE) ELSE C.PAY_AMT END) ELSE 0 END) * 100, 1), 0) AS COM_RATE ' + CHAR(13)  
SET @SQL = @SQL + ' FROM HTL_RESV_MAST A ' + CHAR(13)  
SET @SQL = @SQL + ' JOIN HTL_INFO_MAST_HOTEL B ' + CHAR(13)  
SET @SQL = @SQL + ' ON (CASE WHEN ISNUMERIC(A.HOTEL_CODE)=0 THEN ''0'' ELSE A.HOTEL_CODE END) = B.HOTEL_CODE ' + CHAR(13)  
SET @SQL = @SQL + ' LEFT JOIN ' + CHAR(13)  
SET @SQL = @SQL + ' ( ' + CHAR(13)  
SET @SQL = @SQL + '  SELECT ' + CHAR(13)  
SET @SQL = @SQL + '   RESV_NO, SUM(CASH_AMOUNT + CARD_AMOUNT) AS PAY_AMT, PAY_STATUS ' + CHAR(13)  
SET @SQL = @SQL + '  FROM HTL_RESV_PAY ' + CHAR(13)  
SET @SQL = @SQL + '  WHERE USE_YN = ''Y'' ' + CHAR(13)  
SET @SQL = @SQL + '  GROUP BY RESV_NO, PAY_STATUS ' + CHAR(13)  
SET @SQL = @SQL + ' ) C ' + CHAR(13)  
SET @SQL = @SQL + ' ON A.RESV_NO = C.RESV_NO ' + CHAR(13)  
SET @SQL = @SQL + ' WHERE CONVERT(VARCHAR(10), A.CREATE_DATE, 121) >= '''+@DATE_FROM+''' AND CONVERT(VARCHAR(10), A.CREATE_DATE, 121) < DATEADD(D, 1, '''+@DATE_TO+''') ' + CHAR(13)  
SET @SQL = @SQL + ' AND SUPP_CODE LIKE ''%'+@SUPP_CODE+'%'' ' + CHAR(13)  
SET @SQL = @SQL + ' AND A.HOTEL_NAME = '''+@HOTEL_NAME+''' ' + CHAR(13)  

IF(@PARTNER_SHIP <> '') 
SET @SQL = @SQL + ' AND A.MCPN_CODE = ''' + @PARTNER_SHIP + ''' ' + CHAR(13)   

SET @SQL = @SQL + ' GROUP BY A.HOTEL_NAME, B.CITY_NAME, A.SUPP_CODE, CONVERT(VARCHAR(10),A.CREATE_DATE,121)  ' + CHAR(13)  
SET @SQL = @SQL + ' ORDER BY '+@ORDER_TYPE+' DESC ' + CHAR(13)  

PRINT(@SQL)  

EXEC(@SQL) 


GO
