USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HTL_SALE_SUPP_VGT]

/*
USP_HTL_SALE_SUPP_VGT 'EX', 'R', '2015-03-01', '2015-03-28', ''
*/

@SUPP_CODE VARCHAR(2)='',
@DATE_TYPE VARCHAR(1)='C',
@DATE_FROM VARCHAR(10),
@DATE_TO VARCHAR(10),
@HOTEL_NAME VARCHAR(1000)=''

AS

DECLARE @SQL VARCHAR(MAX);

SET @SQL = '';
SET @SQL = @SQL + 'SET ANSI_WARNINGS OFF  ' + CHAR(13)
SET @SQL = @SQL + 'SET ARITHIGNORE ON  ' + CHAR(13)
SET @SQL = @SQL + 'SET ARITHABORT OFF  ' + CHAR(13)
SET @SQL = @SQL + 'SELECT RESV_NO, VGT_NO, VGT_CODE, SUPP_CODE, SUPP_NO, RESV_NAME, NAME, CREATE_DATE, CHECK_IN_DATE, A.LAST_STATUS, LAST_STATUS_NAME,  ' + CHAR(13)
SET @SQL = @SQL + 'TOTAL_AMT, SUPP_NET, PAY_AMT, TOTAL_AMT-SUPP_NET-DSC_COST AS GROSS_COM_AMT, ' + CHAR(13)
SET @SQL = @SQL + 'NET_COM_AMT AS NET_COM_AMT, HOTEL_NAME ' + CHAR(13)
SET @SQL = @SQL + 'FROM ( ' + CHAR(13)
SET @SQL = @SQL + '	SELECT  ' + CHAR(13)
SET @SQL = @SQL + '	A.RESV_NO, SUPP_NO,  ' + CHAR(13)
SET @SQL = @SQL + '	SUPP_CODE,  ' + CHAR(13)
SET @SQL = @SQL + '	RESV_NAME, ' + CHAR(13)
SET @SQL = @SQL + '	(SUR_NAME + ''/'' + GIVEN_NAME) AS NAME,  ' + CHAR(13)
SET @SQL = @SQL + '	VGT_NO,' + CHAR(13)
SET @SQL = @SQL + '	VGT_CODE,' + CHAR(13)
SET @SQL = @SQL + '	CONVERT(VARCHAR(10), A.CREATE_DATE, 121) AS CREATE_DATE,  ' + CHAR(13)
SET @SQL = @SQL + '	CONVERT(VARCHAR(10), A.CHECK_IN_DATE, 121) AS CHECK_IN_DATE,  ' + CHAR(13)
SET @SQL = @SQL + '	SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN A.TOTAL_AMT WHEN (LAST_STATUS IN (''RMXX'', ''RMXQ'') AND CANCEL_NET > 0) THEN A.CANCEL_AMT ELSE 0 END) AS TOTAL_AMT,  ' + CHAR(13)
SET @SQL = @SQL + '	SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN A.SUPP_NET WHEN (LAST_STATUS IN (''RMXX'', ''RMXQ'') AND CANCEL_NET > 0) THEN A.CANCEL_NET ELSE 0 END) AS SUPP_NET,  ' + CHAR(13)
SET @SQL = @SQL + '	SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN A.DSC_COST WHEN (LAST_STATUS IN (''RMXX'', ''RMXQ'') AND CANCEL_NET > 0) THEN A.DSC_COST ELSE 0 END) AS DSC_COST,  ' + CHAR(13)
SET @SQL = @SQL + '	SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' OR (LAST_STATUS IN (''RMXX'', ''RMXQ'') AND CANCEL_NET > 0) THEN B.PAY_AMT ELSE 0 END) AS PAY_AMT,  ' + CHAR(13)
SET @SQL = @SQL + '	SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' OR (LAST_STATUS IN (''RMXX'', ''RMXQ'') AND CANCEL_NET > 0) THEN A.COM_AMT ELSE 0 END) AS NET_COM_AMT,  ' + CHAR(13)
SET @SQL = @SQL + '	A.LAST_STATUS, D.CODE_NAME AS LAST_STATUS_NAME, E.NAME AS HOTEL_NAME, CARD_COST ' + CHAR(13)
SET @SQL = @SQL + '	FROM HTL_RESV_MAST A  ' + CHAR(13)
SET @SQL = @SQL + '	LEFT JOIN HTL_RESV_PAX C ON A.RESV_NO = C.RESV_NO AND PAX_NO = 1  ' + CHAR(13)
SET @SQL = @SQL + '	LEFT JOIN  ' + CHAR(13)
SET @SQL = @SQL + '	(  ' + CHAR(13)
SET @SQL = @SQL + '	SELECT   ' + CHAR(13)
SET @SQL = @SQL + '	RESV_NO,  ' + CHAR(13)
SET @SQL = @SQL + '	SUM(PAY_TOTAL_AMOUNT) AS PAY_AMT  ' + CHAR(13)
SET @SQL = @SQL + '	FROM HTL_RESV_PAY  ' + CHAR(13)
SET @SQL = @SQL + '	WHERE USE_YN = ''Y''   ' + CHAR(13)
SET @SQL = @SQL + '	GROUP BY RESV_NO, PAY_STATUS  ' + CHAR(13)
SET @SQL = @SQL + '	) AS B ON A.RESV_NO = B.RESV_NO  ' + CHAR(13)
SET @SQL = @SQL + '	LEFT JOIN HTL_CODE_MAST D ON A.LAST_STATUS=D.S_CODE AND D.M_CODE=''RSST'' ' + CHAR(13)
SET @SQL = @SQL + '	LEFT JOIN HTL_INFO_MAST_HOTEL E ON A.HOTEL_CODE=E.HOTEL_CODE ' + CHAR(13)
SET @SQL = @SQL + '	WHERE A.RESV_NO IS NOT NULL ' + CHAR(13)
SET @SQL = @SQL + '	AND A.HOTEL_CODE NOT LIKE ''OF%'' AND (LAST_STATUS = ''RMTK'' OR (LAST_STATUS IN (''RMXX'', ''RMXQ'') AND CANCEL_NET > 0))  ' + CHAR(13)
SET @SQL = @SQL + '	AND MCPN_CODE = ''VG0000'' ' + CHAR(13)
IF (@SUPP_CODE<>'') 
	SET @SQL = @SQL + '	AND SUPP_CODE = '''+@SUPP_CODE+''' ' + CHAR(13)
ELSE
	SET @SQL = @SQL + '	AND SUPP_CODE NOT IN (''EX'') '
IF (@DATE_TYPE='C')
	SET @SQL = @SQL + '	AND CONVERT(VARCHAR(10), A.CHECK_IN_DATE, 121) >= '''+@DATE_FROM+''' AND CONVERT(VARCHAR(10), A.CHECK_IN_DATE, 121) < CONVERT(DATETIME, '''+@DATE_TO+''') + 1  ' + CHAR(13)
ELSE
	SET @SQL = @SQL + '	AND CONVERT(VARCHAR(10), A.CREATE_DATE, 121) >= '''+@DATE_FROM+''' AND CONVERT(VARCHAR(10), A.CREATE_DATE, 121) < CONVERT(DATETIME, '''+@DATE_TO+''') + 1  ' + CHAR(13)
IF (@HOTEL_NAME <> '')
	SET @SQL = @SQL + '	AND (E.NAME LIKE ''%'+@HOTEL_NAME+'%'' OR E.ENG_NAME LIKE ''%'+@HOTEL_NAME+'%'') ' + CHAR(13)
SET @SQL = @SQL + '	GROUP BY A.RESV_NO, SUPP_NO, SUPP_CODE, RESV_NAME, (SUR_NAME + ''/'' + GIVEN_NAME), VGT_NO, VGT_CODE, ' + CHAR(13)
SET @SQL = @SQL + '	CONVERT(VARCHAR(10), A.CREATE_DATE, 121), CONVERT(VARCHAR(10), A.CHECK_IN_DATE, 121), A.LAST_STATUS, D.CODE_NAME, E.NAME, CARD_COST ' + CHAR(13)
SET @SQL = @SQL + ') A ' + CHAR(13)
SET @SQL = @SQL + 'ORDER BY CHECK_IN_DATE ASC '

PRINT(@SQL)
EXEC(@SQL)


GO
