USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create PROC [dbo].[USP_HTL_DOM_ROOM_COPY]

/*
USP_HTL_DOM_ROOM_COPY '900332', '2'
*/

@HOTEL_CODE VARCHAR(50),
@ROOM_CODE VARCHAR(50)

AS

DECLARE @CODE VARCHAR(10);
SELECT @CODE = ISNULL(MAX(CONVERT(INT, ROOM_CODE)),0) + 1 FROM HTL_DOM_INFO_ROOM_DIR WHERE HOTEL_CODE=@HOTEL_CODE


INSERT INTO HTL_DOM_INFO_ROOM_DIR
(HOTEL_CODE, ROOM_CODE, ROOM_TYPE_CODE, ROOM_NAME, ROOM_DESC, ROOM_CNT, 
MIN_PAX_CNT, MAX_PAX_CNT, MEAL_YN, ROOM_USE_YN, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT HOTEL_CODE, @CODE, ROOM_TYPE_CODE, ROOM_NAME, ROOM_DESC, ROOM_CNT, 
MIN_PAX_CNT, MAX_PAX_CNT, MEAL_YN, ROOM_USE_YN, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE
FROM HTL_DOM_INFO_ROOM_DIR
WHERE HOTEL_CODE=@HOTEL_CODE
AND ROOM_CODE=@ROOM_CODE


INSERT INTO HTL_DOM_INFO_PRICE_DIR
(HOTEL_CODE, ROOM_CODE, ROOM_NAME, CHECK_IN_DATE, CURRENCY, 
NET_PRICE, SALE_PRICE, AVAIL_TYPE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT HOTEL_CODE, @CODE, ROOM_NAME, CHECK_IN_DATE, CURRENCY, 
NET_PRICE, SALE_PRICE, AVAIL_TYPE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE
FROM HTL_DOM_INFO_PRICE_DIR
WHERE HOTEL_CODE=@HOTEL_CODE
AND ROOM_CODE=@ROOM_CODE
GO
