USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USP_HTL_DOM_CXL_COPY]

/*
	USP_HTL_DOM_CXL_COPY '1057'
*/

@CX_SEQ INT

AS

INSERT INTO HTL_DOM_INFO_CXL_MAST
(HOTEL_CODE, ROOM_CODE, DATE_FROM, DATE_TO, SORT_ORDER, USE_YN, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
SELECT HOTEL_CODE, ROOM_CODE, DATE_FROM, DATE_TO, '999', USE_YN, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE
FROM HTL_DOM_INFO_CXL_MAST
WHERE CX_SEQ = @CX_SEQ

DECLARE @SORT INT
SELECT @SORT = MAX(CX_SEQ)  FROM HTL_DOM_INFO_CXL_MAST

INSERT INTO HTL_DOM_INFO_CXL_SUB
(CX_SEQ, CX_DAY, NET_RATE, SALE_RATE)
SELECT @SORT, CX_DAY, NET_RATE, SALE_RATE
FROM HTL_DOM_INFO_CXL_SUB
WHERE CX_SEQ = @CX_SEQ
ORDER BY CX_DAY DESC
GO
