USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_SET_LAST_STATUS_VGT]

/*
USP_SET_LAST_STATUS_VGT '1030'
*/

@RESV_NO INT

AS

DECLARE @SUPP_CODE VARCHAR(2);    
DECLARE @SUPP_STATUS VARCHAR(4); 
DECLARE @LAST_STATUS VARCHAR(4);    
DECLARE @TOTAL_AMT DECIMAL;
DECLARE @PAID_AMT DECIMAL;
DECLARE @NEW_STATUS VARCHAR(4);    

SET @PAID_AMT = 0;
    
SELECT @SUPP_CODE=SUPP_CODE, @SUPP_STATUS=SUPP_STATUS, @LAST_STATUS=LAST_STATUS, @TOTAL_AMT = TOTAL_AMT-DSC_COST    
FROM HTL_RESV_MAST    
WHERE RESV_NO=@RESV_NO    

--IF (@SUPP_CODE <> 'EX')
--BEGIN


SELECT @PAID_AMT = ISNULL(SUM(CARD_AMOUNT + CASH_AMOUNT),0)
FROM HTL_RESV_PAY    
WHERE RESV_NO=@RESV_NO AND PAY_CURRENCY = 'KRW' AND USE_YN='Y'

IF (@PAID_AMT >= @TOTAL_AMT AND @SUPP_STATUS='CF')
	SET @NEW_STATUS = 'RMTK'
ELSE
	SET @NEW_STATUS = @LAST_STATUS
	
UPDATE HTL_RESV_MAST SET LAST_STATUS=@NEW_STATUS
WHERE RESV_NO=@RESV_NO  


--END




GO
