USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HTL_UNIFIED_SEARCH3]

/*
USP_HTL_UNIFIED_SEARCH3 'DOM', 'PUS', '토', 20, 1
*/

@INT_DOM VARCHAR(3)='',
@CITY_CODE VARCHAR(20)='',
@KEYWORD VARCHAR(100)='',
@P_SIZE INT = 20,
@P_INDEX INT = 1

AS

SET @KEYWORD = REPLACE(@KEYWORD, ' ', '')

DECLARE @CNT INT;
DECLARE @S_NUM INT;
DECLARE @E_NUM INT;

SET @CNT = 0;
SET @S_NUM = 0;
SET @E_NUM = 0;

--총카운트
SELECT @CNT = COUNT(*)
FROM HTL_IDX_SEARCH WITH (NOLOCK)
WHERE USE_YN='Y'
AND (CASE WHEN INT_DOM=@INT_DOM OR @INT_DOM='' THEN 1 ELSE 0 END) = 1
AND (CASE WHEN CITY_CODE=@CITY_CODE OR @CITY_CODE='' THEN 1 ELSE 0 END) = 1
AND INDEX_NAME LIKE '%'+@KEYWORD+'%'


--시작/끝 번호지정
SET @S_NUM = (@P_INDEX - 1) * @P_SIZE
SET @E_NUM = (CASE WHEN (@P_INDEX * @P_SIZE) > @CNT THEN @CNT ELSE (@P_INDEX * @P_SIZE) END)


--리스트
SELECT *
FROM (
	SELECT INT_DOM, HOTEL_CODE, NAME, ENG_NAME, STAR_RATING, CITY_CODE, CITY_NAME, AREA_NAME, 
	[ADDRESS], RV_POINT, TYPE_CODE, TYPE_CODE_NAME, SALE_AMT, MAIN_IMG, SORT_ORDER,
	RANK() OVER (ORDER BY SORT_ORDER, HOTEL_CODE) AS SORT
	FROM HTL_IDX_SEARCH WITH (NOLOCK)
	WHERE USE_YN='Y'
	AND (CASE WHEN INT_DOM=@INT_DOM OR @INT_DOM='' THEN 1 ELSE 0 END) = 1
	AND (CASE WHEN CITY_CODE=@CITY_CODE OR @CITY_CODE='' THEN 1 ELSE 0 END) = 1
	AND INDEX_NAME LIKE '%'+@KEYWORD+'%'
) A
WHERE SORT > @S_NUM AND SORT <= @E_NUM



GO
