USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HTL_UNIFIED_SEARCH]

/*
USP_HTL_UNIFIED_SEARCH '토'
*/

@KEYWORD VARCHAR(100)

AS

SET @KEYWORD = REPLACE(@KEYWORD, ' ', '')

SELECT INT_DOM, HOTEL_CODE, NAME, ENG_NAME, STAR_RATING, CITY_CODE, CITY_NAME, AREA_NAME, 
[ADDRESS], RV_POINT, TYPE_CODE, TYPE_CODE_NAME, SALE_AMT, MAIN_IMG, SORT_ORDER
FROM HTL_IDX_SEARCH WITH (NOLOCK)
WHERE INDEX_NAME LIKE '%'+@KEYWORD+'%'
AND USE_YN='Y'
ORDER BY CHARINDEX('|', REVERSE(LEFT('|' + INDEX_NAME, CHARINDEX(@KEYWORD, '|' + INDEX_NAME) - 1))), SORT_ORDER





GO
