USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
    
CREATE PROC [dbo].[USP_HTL_DOM_ROOM_INSERT]    
    
/*    
USP_HTL_DOM_ROOM_INSERT 'TO', '<XML />'    
*/    
    
@SUPP_TYPE VARCHAR(2),    
@XML VARCHAR(MAX)    
    
AS    
    
DECLARE @XML_DOCUMENT_HANDLE INT;    
DECLARE @XML_DOCUMENT VARCHAR(MAX);    
SET @XML_DOCUMENT = '<?xml version="1.0" encoding="euc-kr"?>' + @XML       
                    
EXEC SP_XML_PREPAREDOCUMENT @XML_DOCUMENT_HANDLE OUTPUT, @XML_DOCUMENT      
                    
                    
--요금 임시저장                    
                    
SELECT *               
INTO #TMP_TABLE            
FROM OPENXML (@XML_DOCUMENT_HANDLE, '/ArrayOfRoomBulkRQ/RoomBulkRQ',2)                     
WITH (      
     SUPP_HOTEL_CODE VARCHAR(10) './HC',              
     ROOM_CODE VARCHAR(10) './RC',    
     ROOM_TYPE_CODE VARCHAR(300) './RTC',  
     ROOM_NAME VARCHAR(300) './RN',  
     ROOM_DESC VARCHAR(3000) './RD',  
     ROOM_CNT INT './CNT',  
     MIN_PAX_CNT INT './MIN',  
     MAX_PAX_CNT INT './MAX'  
) A    
  
  
--룸 업데이트  
UPDATE HTL_DOM_INFO_ROOM_DIR SET  
 ROOM_TYPE_CODE = A.ROOM_TYPE_CODE,  
 ROOM_NAME = A.ROOM_NAME,  
 ROOM_DESC = A.ROOM_DESC,  
 ROOM_CNT = A.ROOM_CNT,  
 MIN_PAX_CNT = A.MIN_PAX_CNT,  
 MAX_PAX_CNT = A.MAX_PAX_CNT,  
 MEAL_YN = 'N',  
 --ROOM_USE_YN = 'Y',  
 UPDATE_USER = 'SYSTEM',  
 UPDATE_DATE = GETDATE()  
FROM #TMP_TABLE A  
JOIN HTL_DOM_INFO_HOTEL_MAPP B ON A.SUPP_HOTEL_CODE=B.SUPP_HOTEL_CODE AND B.SUPP_TYPE=@SUPP_TYPE  
JOIN HTL_DOM_INFO_ROOM_DIR C ON B.HOTEL_CODE=C.HOTEL_CODE AND A.ROOM_CODE=C.ROOM_CODE  
  
  
  
--룸 인서트  
INSERT HTL_DOM_INFO_ROOM_DIR  
(HOTEL_CODE, ROOM_CODE, ROOM_TYPE_CODE, ROOM_NAME, ROOM_DESC, ROOM_CNT, MIN_PAX_CNT, MAX_PAX_CNT, MEAL_YN, ROOM_USE_YN, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)  
SELECT B.HOTEL_CODE, A.ROOM_CODE, A.ROOM_TYPE_CODE, A.ROOM_NAME, A.ROOM_DESC, A.ROOM_CNT, A.MIN_PAX_CNT, A.MAX_PAX_CNT, 'N', 'Y', 'SYSTEM', GETDATE(), 'SYSTEM', GETDATE()  
FROM #TMP_TABLE A  
JOIN HTL_DOM_INFO_HOTEL_MAPP B ON A.SUPP_HOTEL_CODE=B.SUPP_HOTEL_CODE AND B.SUPP_TYPE=@SUPP_TYPE  
LEFT JOIN HTL_DOM_INFO_ROOM_DIR C ON B.HOTEL_CODE=C.HOTEL_CODE AND A.ROOM_CODE=C.ROOM_CODE  
WHERE C.HOTEL_CODE IS NULL  
  
  
EXEC SP_XML_REMOVEDOCUMENT @XML_DOCUMENT_HANDLE     
    
    
GO
