USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HIVE_BLOG_HOTEL]

/*
USP_HIVE_BLOG_HOTEL '287341'
*/

@HOTEL_CODE VARCHAR(50)

AS

SELECT NATION_CODE, A.REGION_CODE, B.KOR_NAME AS REGION_NAME  
INTO #TABLE_REGION  
FROM AIR.DBO.TBL_CODE_CITY A  
JOIN AIR.DBO.TBL_CODE_REGION B ON A.REGION_CODE=B.REGION_CODE  
GROUP BY NATION_CODE, A.REGION_CODE, B.KOR_NAME  
    
    
SELECT A.HOTEL_CODE, A.NAME, A.ENG_NAME, C.NATION_CODE, C.NATION_NAME,     
A.CITY_CODE, A.CITY_NAME, STAR_RATING, REGION_CODE, REGION_NAME    
FROM HTL_INFO_MAST_HOTEL A    
JOIN HTL_CODE_MAST_CITY C ON A.CITY_CODE=C.CITY_CODE  
LEFT JOIN #TABLE_REGION D ON C.NATION_CODE=D.NATION_CODE
WHERE A.USE_YN='Y' 
AND C.USE_YN='Y' 
AND C.NATION_CODE <> 'KR'
AND A.HOTEL_CODE=@HOTEL_CODE
ORDER BY C.SORT_ORDER ASC, A.NAME



GO
