USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HTL_DOM_HOLIDAY_DELETE]  
  
/*  
[USP_HTL_DOM_HOLIDAY_DELETE] '2015-05-06', 'HOTEL.DBO.HTL_CODE_HOLIDAY'
*/  

@HOL_DATE VARCHAR(10),
@DB_NAME VARCHAR(MAX)  

AS

DECLARE @SQL VARCHAR(MAX)      
       
SET @SQL = ''  

SET @SQL = @SQL + ' DELETE FROM ' + @DB_NAME + CHAR(13)
SET @SQL = @SQL + ' WHERE CONVERT(VARCHAR(10), TARGET_DATE, 121) = ''' + @HOL_DATE + ''' ' + CHAR(13)

PRINT(@SQL)          
EXEC(@SQL)
GO
