USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HTL_EVENT]

/*
USP_HTL_EVENT '178263', '230954', 'VG0000'
*/

@CITY_CODE VARCHAR(20) = '',
@HOTEL_CODE VARCHAR(20) = '',
@MCPN_CODE VARCHAR(10) = 'VG0000'


AS

DECLARE @SQL VARCHAR(MAX);

SET @SQL = 'SELECT HOTEL_CODE, NAME, CITY_CODE, CITY_NAME, SUPP_CODE, TITLE, DATE_FROM, DATE_TO, APP_DAY, RECOM_DESC, EVENT_DESC ' + CHAR(13)
SET @SQL = @SQL + 'FROM HTL_EVENT_MAST ' + CHAR(13)
SET @SQL = @SQL + 'WHERE USE_YN=''Y'' ' + CHAR(13)

IF (@CITY_CODE <> '')
	SET @SQL = @SQL + 'AND CITY_CODE=''' + @CITY_CODE + ''' ' + CHAR(13)

IF (@HOTEL_CODE <> '')
	SET @SQL = @SQL + 'AND HOTEL_CODE=''' + @HOTEL_CODE + ''' ' + CHAR(13)

SET @SQL = @SQL + 'AND MCPN_CODE=''' + @MCPN_CODE + ''' ' + CHAR(13)

PRINT(@SQL)
EXEC(@SQL)



GO
