USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HOTEL_LIST_11ST]

/*
USP_HOTEL_LIST_11ST
*/


AS

SELECT A.HOTEL_CODE,
	A.NAME,
	A.ENG_NAME,
	A.CITY_CODE,
	A.CITY_NAME,
	C.CITY_ENAME,
	C.NATION_CODE,
	C.NATION_NAME,
	C.NATION_ENAME,
	N.REGION_CODE,
	A.HOTEL_TYPE AS HOTEL_RATE,
	(SELECT CODE_NAME FROM [AIR].[dbo].[HTL_MAST_CODE] WHERE M_CODE = 'CTGR' AND S_CODE = CONVERT(CHAR, A.HOTEL_TYPE)) AS HOTEL_TYPE,
	E.SALE_AMT AS SALE_AMT,
	A.[ADDRESS],
	A.MAIN_IMG,
	(SELECT DESC_VALUE FROM HTL_INFO_MAST_DESC WHERE HOTEL_CODE = A.HOTEL_CODE AND DESC_TYPE = 'GN') AS DESC_GN,
	(SELECT DESC_VALUE FROM HTL_INFO_MAST_DESC WHERE HOTEL_CODE = A.HOTEL_CODE AND DESC_TYPE = 'CK') AS DESC_CK,
	(SELECT DESC_VALUE FROM HTL_INFO_MAST_DESC WHERE HOTEL_CODE = A.HOTEL_CODE AND DESC_TYPE = 'TI') AS DESC_TI,
	(SELECT DESC_VALUE FROM HTL_INFO_MAST_DESC WHERE HOTEL_CODE = A.HOTEL_CODE AND DESC_TYPE = 'NB') AS DESC_NB,
	A.PHONE,
	A.FAX,
	A.AIRPORT_CODE, 
	A.STAR_RATING,
	A.ROOM_CNT,
	A.CHECK_IN_TIME,
	A.CHECK_OUT_TIME,
	A.LATITUDE,
	A.LONGITUDE,
	A.RV_POINT,
	A.RV_CNT,
	A.USE_YN,
	ISNULL(S_NATION_CODE, F.NATION_CODE) AS S_NATION_CODE,
	ISNULL(S_NATION_NAME, F.NATION_NAME) AS S_NATION_NAME,
	S_CITY_CODE,
	S_CITY_NAME
FROM HTL_INFO_MAST_HOTEL A
JOIN (
	SELECT HOTEL_CODE 
	FROM HTL_MAPP_HOTEL
	WHERE SUPP_CODE <> 'EX'
	GROUP BY HOTEL_CODE
) B ON A.HOTEL_CODE=B.HOTEL_CODE
JOIN (
	SELECT HOTEL_CODE, ROOM_NAME, SALE_AMT
	FROM HTL_INFO_PRICE_11ST
	UNION ALL
	SELECT HOTEL_CODE, ROOM_NAME, SALE_AMT
	FROM HTL_INFO_PRICE
	WHERE HOTEL_CODE NOT IN (SELECT HOTEL_CODE FROM HTL_INFO_PRICE_11ST)
) E ON A.HOTEL_CODE=E.HOTEL_CODE
LEFT JOIN HTL_CODE_MAST_CITY C ON A.CITY_CODE = C.CITY_CODE
LEFT JOIN HTL_CODE_MAST_NATION N ON C.NATION_CODE = N.NATION_CODE
JOIN (
	SELECT CITY_CODE, S_CITY_CODE, S_CITY_NAME, S_NATION_CODE, S_NATION_NAME
	FROM (
		SELECT A.CITY_CODE, A.S_CITY_CODE, B.CITY_NAME AS S_CITY_NAME, 
		B.NATION_CODE AS S_NATION_CODE, B.NATION_NAME AS S_NATION_NAME, 
		RANK() OVER (PARTITION BY A.CITY_CODE ORDER BY S_CITY_CODE) AS SORT
		FROM HTL_MAPP_CITY A
		JOIN HTL_CODE_SUB_CITY B ON A.S_CITY_CODE=B.CITY_CODE AND A.SUPP_CODE=B.SUPP_CODE
		WHERE A.SUPP_CODE='EL' 
	) A
	WHERE SORT=1
) D ON A.CITY_CODE=D.CITY_CODE
LEFT JOIN (
	SELECT NATION_CODE, NATION_NAME
	FROM HTL_CODE_SUB_CITY
	WHERE SUPP_CODE='EL' 
	GROUP BY NATION_CODE, NATION_NAME
) F ON N.NATION_CODE=F.NATION_CODE
WHERE A.CITY_CODE IS NOT NULL AND A.USE_YN = 'Y'
AND N.NATION_CODE <> 'KR' AND A.MAIN_IMG NOT LIKE '%.BMP'


GO
