USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_BULK_INSERT_SLIP]

/*
USP_BULK_INSERT_SLIP '2018-08-06', '<XML />'
*/

@SLIP_DATE VARCHAR(10),
@XML VARCHAR(MAX)

AS

DECLARE @XML_DOCUMENT_HANDLE INT;
DECLARE @XML_DOCUMENT VARCHAR(MAX);
SET @XML_DOCUMENT = '<?xml version="1.0" encoding="euc-kr"?>' + @XML

EXEC SP_XML_PREPAREDOCUMENT @XML_DOCUMENT_HANDLE OUTPUT,  @XML_DOCUMENT

DECLARE @ROW_ID VARCHAR(100)
SET @ROW_ID = DBO.FN_GET_SLIP_NUMBER(@SLIP_DATE);

SELECT *
INTO #TMP_TABLE
FROM OPENXML (@XML_DOCUMENT_HANDLE,  '/ArrayOfSlipMastRQ/SlipMastRQ', 2)                 
WITH (  
	ROW_ID VARCHAR(1000) './RowId',
	ROW_NO VARCHAR(1000) './RowNo',
	NO_TAX VARCHAR(1000) './NoTax',
	CD_PC VARCHAR(1000) './CdPc',
	CD_WDEPT VARCHAR(1000) './CdWdept',
	NO_DOCU VARCHAR(1000) './NoDocu',
	NO_DOLINE VARCHAR(1000) './NoDoline',
	CD_COMPANY VARCHAR(1000) './CdCompany',
	ID_WRITE VARCHAR(1000) './IdWrite',
	CD_DOCU VARCHAR(1000) './CdDocu',
	DT_ACCT VARCHAR(1000) './DtAcct',
	ST_DOCU VARCHAR(1000) './StDocu',
	TP_DRCR VARCHAR(1000) './TpDrcr',
	CD_ACCT VARCHAR(1000) './CdAcct',
	AMT VARCHAR(1000) './Amt',
	CD_PARTNER VARCHAR(1000) './CdPartner',
	NM_NOTE VARCHAR(1000) './NmNote',
	CD_BIZAREA VARCHAR(1000) './CdBizarea',
	CD_DEPT VARCHAR(1000) './CdDept',
	CD_CC VARCHAR(1000) './CdCc',
	CD_PJT VARCHAR(1000) './CdPjt',
	CD_EMPLOY VARCHAR(1000) './CdEmploy',
	NO_BDOCU VARCHAR(1000) './NoBdocu',
	NO_BDOLINE VARCHAR(1000) './NoBdoline',
	TP_DOCU VARCHAR(1000) './TpDocu',
	NO_ACCT VARCHAR(1000) './NoAcct',
	CD_EXCH VARCHAR(1000) './CdExch',
	RT_EXCH VARCHAR(1000) './RtExch',
	AM_EX VARCHAR(1000) './AmEx',
	TP_GUBUN VARCHAR(1000) './TpGubun',
	CD_MNGD1 VARCHAR(1000) './CdMngd1',
	NM_MNGD1 VARCHAR(1000) './NmMngd1',
	CD_MNGD2 VARCHAR(1000) './CdMngd2',
	NM_MNGD2 VARCHAR(1000) './NmMngd2',
	CD_MNGD3 VARCHAR(1000) './CdMngd3',
	NM_MNGD3 VARCHAR(1000) './NmMngd3',
	CD_MNGD4 VARCHAR(1000) './CdMngd4',
	NM_MNGD4 VARCHAR(1000) './NmMngd4',
	CD_MNGD5 VARCHAR(1000) './CdMngd5',
	NM_MNGD5 VARCHAR(1000) './NmMngd5',
	CD_MNGD6 VARCHAR(1000) './CdMngd6',
	NM_MNGD6 VARCHAR(1000) './NmMngd6',
	CD_MNGD7 VARCHAR(1000) './CdMngd7',
	NM_MNGD7 VARCHAR(1000) './NmMngd7',
	CD_MNGD8 VARCHAR(1000) './CdMngd8',
	NM_MNGD8 VARCHAR(1000) './NmMngd8',
	TP_EVIDENCE VARCHAR(1000) './TpEvidence',
	PREV_SLIP_ID VARCHAR(1000) './PrevSlipId',
	NEXT_SLIP_ID VARCHAR(1000) './NextSlipId',
	RESV_NO VARCHAR(1000) './ResvNo',
	PAY_SEQ VARCHAR(1000) './PaySeq',
	GROUP_KEY VARCHAR(1000) './GroupKey',
	USE_YN VARCHAR(1000) './UseYn',
	CREATE_USER VARCHAR(1000) './CreateUser',
	EXTRA VARCHAR(1000) './Extra',
	SPEND_ID VARCHAR(1000) './SpendId'
) A



INSERT INTO ACC_SLIP_MAST
(
	ROW_ID, ROW_NO, NO_TAX, CD_PC, CD_WDEPT, NO_DOCU, NO_DOLINE, CD_COMPANY, ID_WRITE, CD_DOCU, DT_ACCT, 
	ST_DOCU, TP_DRCR, CD_ACCT, AMT, CD_PARTNER, NM_NOTE, CD_BIZAREA, CD_DEPT, CD_CC, CD_PJT, CD_EMPLOY, 
	NO_BDOCU, NO_BDOLINE, TP_DOCU, NO_ACCT, CD_EXCH, RT_EXCH, AM_EX, TP_GUBUN, CD_MNGD1, NM_MNGD1, CD_MNGD2, NM_MNGD2, 
	CD_MNGD3, NM_MNGD3, CD_MNGD4, NM_MNGD4, CD_MNGD5, NM_MNGD5, CD_MNGD6, NM_MNGD6, CD_MNGD7, NM_MNGD7, CD_MNGD8, NM_MNGD8, 
	TP_EVIDENCE, PREV_SLIP_ID, NEXT_SLIP_ID, RESV_NO, PAY_SEQ, GROUP_KEY, USE_YN, CREATE_DATE, CREATE_USER, EXTRA, SPEND_ID
)
SELECT @ROW_ID, ROW_NO, NO_TAX, CD_PC, CD_WDEPT, @ROW_ID, NO_DOLINE, CD_COMPANY, ID_WRITE, CD_DOCU, DT_ACCT, 
ST_DOCU, TP_DRCR, CD_ACCT, CONVERT(DECIMAL,ISNULL(AMT, 0)), CD_PARTNER, NM_NOTE, CD_BIZAREA, CD_DEPT, CD_CC, CD_PJT, CD_EMPLOY, 
NO_BDOCU, NO_BDOLINE, TP_DOCU, NO_ACCT, CD_EXCH, RT_EXCH, AM_EX, TP_GUBUN, CD_MNGD1, NM_MNGD1, CD_MNGD2, NM_MNGD2, 
CD_MNGD3, NM_MNGD3, CD_MNGD4, NM_MNGD4, CD_MNGD5, NM_MNGD5, CD_MNGD6, NM_MNGD6, CD_MNGD7, NM_MNGD7, CD_MNGD8, NM_MNGD8, 
TP_EVIDENCE, PREV_SLIP_ID, NEXT_SLIP_ID, RESV_NO, PAY_SEQ, @ROW_ID + '_' + GROUP_KEY, USE_YN, GETDATE(), CREATE_USER, EXTRA, SPEND_ID
FROM #TMP_TABLE


SELECT @ROW_ID AS VALUE;


EXEC SP_XML_REMOVEDOCUMENT @XML_DOCUMENT_HANDLE 


GO
