USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_GET_HTL_CODE_TIME]

/*
USP_GET_HTL_CODE_TIME 'BT', 'AAA', '0'
*/

@SUPP_CODE VARCHAR(2),
@CITY_CODE VARCHAR(4),
@HOTEL_CODE INT

AS

SELECT TOP 1 TIME_SEQ, TIME_VALUE
FROM HTL_CODE_TIME
WHERE (SUPP_CODE='' OR SUPP_CODE=@SUPP_CODE)
AND (CITY_CODE='' OR CITY_CODE=@CITY_CODE)
AND (HOTEL_CODE=0 OR HOTEL_CODE=@HOTEL_CODE)
AND USE_YN='Y'
ORDER BY SUPP_CODE DESC, CITY_CODE DESC, HOTEL_CODE DESC


GO
