USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HTL_RESV_CXL_REFRESH]

@RESV_NO INT,
@SEQ_NO INT,
@CX_REF VARCHAR(2),
@CX_DATE_FROM DATETIME,
@CX_DATE_TO DATETIME,
@CX_TYPE VARCHAR(30),
@CX_VALUE NVARCHAR(4000)

AS

DECLARE @CNT INT;
DECLARE @SQL NVARCHAR(MAX);
DECLARE @PARAM NVARCHAR(MAX);
SET @SQL = '';
SET @PARAM = '';


SELECT @CNT = COUNT(*)
FROM HTL_RESV_CXL
WHERE RESV_NO=@RESV_NO AND SEQ_NO=@SEQ_NO

IF (@CNT=0)
BEGIN

INSERT INTO HTL_RESV_CXL
(
	RESV_NO,
	SEQ_NO,
	CX_REF,
	CX_DATE_FROM,
	CX_DATE_TO,
	CX_TYPE,
	CX_VALUE
)
SELECT
	@RESV_NO,
	(SELECT ISNULL(MAX(SEQ_NO),0) + 1 FROM HTL_RESV_CXL WHERE RESV_NO=@RESV_NO),
	@CX_REF,
	@CX_DATE_FROM,
	@CX_DATE_TO,
	@CX_TYPE,
	@CX_VALUE


END
ELSE
BEGIN

UPDATE HTL_RESV_CXL SET
	CX_REF = @CX_REF,
	CX_DATE_FROM = @CX_DATE_FROM,
	CX_DATE_TO = @CX_DATE_TO,
	CX_TYPE = @CX_TYPE,
	CX_VALUE = @CX_VALUE
WHERE
	RESV_NO = @RESV_NO
	AND SEQ_NO = @SEQ_NO

END
GO
