USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HTL_SALE_MONTH2]  
    
/*    
USP_HTL_SALE_MONTH2 'C', 'CREATE_DATE', '2015-01-01', '2015-06-30', ''
*/    

@TYPE VARCHAR(1),  
@ORDER_TYPE VARCHAR(50),      
@DATE_FROM VARCHAR(10),      
@DATE_TO VARCHAR(10),
@PARTNER_SHIP VARCHAR(10) = ''    
    
AS    
  
DECLARE @T_DATE VARCHAR(20)     
DECLARE @ORDER_TYPE_SORT VARCHAR(10)
       
	IF (@TYPE = 'C')      
		BEGIN 
			SET @T_DATE = 'A.CREATE_DATE'     
		END
	ELSE
		BEGIN       
			SET @T_DATE = 'A.CHECK_IN_DATE'
		END

	IF (@ORDER_TYPE = 'CREATE_DATE')
		BEGIN
			SET @ORDER_TYPE = 'CONVERT(VARCHAR(7),CREATE_DATE, 121)' 
		END

	IF (@ORDER_TYPE = 'CHECK_IN_DATE')
		BEGIN
			SET @ORDER_TYPE = 'CONVERT(VARCHAR(7),CHECK_IN_DATE, 121)' 
		END
    
DECLARE @SQL VARCHAR(MAX)      
      
SET @SQL = ''    
    
SET @SQL = @SQL + ' SET ANSI_WARNINGS OFF ' + CHAR(13)    
SET @SQL = @SQL + ' SET ARITHIGNORE ON ' + CHAR(13)    
SET @SQL = @SQL + ' SET ARITHABORT OFF ' + CHAR(13)    
    
SET @SQL = @SQL + ' SELECT ' + CHAR(13)    
SET @SQL = @SQL + '  CONVERT(VARCHAR(7), ' + @T_DATE + ', 121) AS RES_MONTH, ' + CHAR(13)    
SET @SQL = @SQL + '  COUNT(' + @T_DATE + ') AS ALL_CNT, ' + CHAR(13)    
SET @SQL = @SQL + '  SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN 1 ELSE 0 END) AS RMTK, ' + CHAR(13)    
SET @SQL = @SQL + '  SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN A.TOTAL_AMT ELSE 0 END) AS TOTAL_AMT, ' + CHAR(13)    
SET @SQL = @SQL + '  SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN A.SUPP_NET ELSE 0 END) AS SUPP_NET, ' + CHAR(13)    
SET @SQL = @SQL + '  SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN (A.TOTAL_AMT - A.SUPP_NET) ELSE 0 END) AS COM_AMT, ' + CHAR(13)    
SET @SQL = @SQL + '  SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN B.PAY_AMT ELSE 0 END)  AS PAY_AMT, ' + CHAR(13)    
SET @SQL = @SQL + '  SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN A.AIR_COST ELSE 0 END)  AS AIR_COST,  ' + CHAR(13)   
SET @SQL = @SQL + '  SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN A.COUP_COST ELSE 0 END)  AS COUP_COST,   ' + CHAR(13)   
SET @SQL = @SQL + '  SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN A.DSC_COST ELSE 0 END)  AS DSC_COST,  ' + CHAR(13)   
SET @SQL = @SQL + '  SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN A.CARD_COST ELSE 0 END)  AS CARD_COST,  ' + CHAR(13) 
SET @SQL = @SQL + '  SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN (TOTAL_AMT-SUPP_NET-AIR_COST-COUP_COST-DSC_COST-CARD_COST) ELSE 0 END) AS REALCOM  ' + CHAR(13) 
   
SET @SQL = @SQL + ' FROM HTL_RESV_MAST A ' + CHAR(13)    
SET @SQL = @SQL + ' LEFT JOIN ' + CHAR(13)    
SET @SQL = @SQL + ' ( ' + CHAR(13)    
SET @SQL = @SQL + '  SELECT  ' + CHAR(13)    
SET @SQL = @SQL + '   RESV_NO, ' + CHAR(13)    
SET @SQL = @SQL + '   SUM(PAY_TOTAL_AMOUNT) AS PAY_AMT ' + CHAR(13)    
SET @SQL = @SQL + '  FROM HTL_RESV_PAY ' + CHAR(13)    
SET @SQL = @SQL + '  WHERE USE_YN = ''Y''  ' + CHAR(13)    
SET @SQL = @SQL + '  GROUP BY RESV_NO, PAY_STATUS ' + CHAR(13)    
SET @SQL = @SQL + ' ) AS B ON A.RESV_NO = B.RESV_NO ' + CHAR(13)    
SET @SQL = @SQL + ' WHERE ' + @T_DATE + ' >= '''+@DATE_FROM+''' AND ' + @T_DATE + ' < CONVERT(DATETIME, '''+@DATE_TO+''') + 1 ' + CHAR(13)    

IF(@PARTNER_SHIP <> '') 
SET @SQL = @SQL + ' AND A.MCPN_CODE = ''' + @PARTNER_SHIP + ''' ' + CHAR(13)   

SET @SQL = @SQL + ' AND A.HOTEL_CODE NOT LIKE ''OF%'' ' + CHAR(13)
SET @SQL = @SQL + ' GROUP BY CONVERT(VARCHAR(7), ' + @T_DATE + ', 121) ' + CHAR(13)    
SET @SQL = @SQL + ' ORDER BY '+@ORDER_TYPE +' DESC ' + CHAR(13)    
    
PRINT(@SQL)    
EXEC(@SQL)


GO
