USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_NAVER_SHOPPING_HOTEL2]



AS


SELECT A.HOTEL_CODE, A.NAME, A.ENG_NAME, C.NATION_CODE, C.NATION_NAME, 
A.CITY_CODE, A.CITY_NAME, ROOM_NAME, SALE_AMT, CHECK_IN_DATE
FROM HTL_INFO_MAST_HOTEL A
JOIN HTL_INFO_PRICE B ON A.HOTEL_CODE=B.HOTEL_CODE
JOIN HTL_CODE_MAST_CITY C ON A.CITY_CODE=C.CITY_CODE


GO
