USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_GET_ZZIM_LIST]

/*
USP_GET_ZZIM_LIST 'JACKSMT', '179900', '468235'
*/

@USER_ID VARCHAR(50),
@CITY_CODE VARCHAR(30),
@HOTEL_CODE VARCHAR(30)

AS

DECLARE @SQL NVARCHAR(MAX);
DECLARE @PARAM NVARCHAR(4000);

SET @SQL = '';
SET @SQL = @SQL + 'SELECT A.ZZIM_NO, B.HOTEL_CODE, B.NAME, B.ENG_NAME, B.CITY_CODE, B.CITY_NAME, ' + CHAR(13); 
SET @SQL = @SQL + 'B.STAR_RATING, B.LOCATION_DESC, B.RV_POINT, B.MAIN_IMG, A.HOTEL_LINK, A.CREATE_DATE ' + CHAR(13);
SET @SQL = @SQL + 'FROM HTL_ZZIM A ' + CHAR(13);
SET @SQL = @SQL + 'JOIN HTL_INFO_MAST_HOTEL B ON A.HOTEL_CODE=B.HOTEL_CODE ' + CHAR(13);
SET @SQL = @SQL + 'WHERE [USER_ID]=@USER_ID ' + CHAR(13);
IF (ISNULL(@CITY_CODE,'') <> '' AND @CITY_CODE <> '0') SET @SQL = @SQL + 'AND A.CITY_CODE=@CITY_CODE ' + CHAR(13);
IF (ISNULL(@HOTEL_CODE,'')<>'' AND @HOTEL_CODE<>'0') SET @SQL = @SQL + 'AND B.HOTEL_CODE=@HOTEL_CODE ' + CHAR(13);
SET @SQL = @SQL + 'ORDER BY A.ZZIM_NO DESC';
PRINT(@SQL)

SET @PARAM = '@USER_ID VARCHAR(50), @CITY_CODE VARCHAR(30), @HOTEL_CODE VARCHAR(30)';
EXEC SP_EXECUTESQL @SQL, @PARAM, @USER_ID, @CITY_CODE, @HOTEL_CODE


GO
