USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HTL_DOM_PRICE_CALENDAR_DIR_HISTORY]  
  
/*  
USP_HTL_DOM_PRICE_CALENDAR_DIR_HISTORY '', '', ''  
*/  
  
@HOTEL_CODE VARCHAR(10),    
@ROOM_CODE VARCHAR(10),    
@XML VARCHAR(MAX)    

 
AS  
  
DECLARE @XML_DOCUMENT_HANDLE INT;    
DECLARE @XML_DOCUMENT VARCHAR(MAX);    
SET @XML_DOCUMENT = '<?xml version="1.0" encoding="euc-kr"?>' + @XML       
                    
EXEC SP_XML_PREPAREDOCUMENT @XML_DOCUMENT_HANDLE OUTPUT, @XML_DOCUMENT      
                    
                    
--요금 임시저장                    
                    
SELECT *               
INTO #TMP_TABLE            
FROM OPENXML (@XML_DOCUMENT_HANDLE, '/ArrayOfDZ/DZ',2)                     
WITH (      
     CAL_DATE varchar(10) './CD'  
) A    
    
  
SELECT A.CAL_DATE,   
ISNULL(PRICE_SEQ, 0) AS PRICE_SEQ,   
ISNULL(NET_PRICE, 0) AS NET_PRICE,   
ISNULL(SALE_PRICE, 0) AS SALE_PRICE,   
AVAIL_TYPE,   
ISNULL(C.CODE_NAME, '미정') AS CODE_NAME, D.DATE_DESC, 
B.HARD_TOTAL, B.SOFT_TOTAL, B.REQ_TOTAL, B.HARD_REMAIN, B.SOFT_REMAIN, B.REQ_REMAIN
FROM #TMP_TABLE A  
LEFT JOIN HTL_DOM_INFO_PRICE_DIR_HISTORY B ON B.HOTEL_CODE=@HOTEL_CODE AND B.ROOM_CODE=@ROOM_CODE AND B.CHECK_IN_DATE=A.CAL_DATE  
LEFT JOIN HTL_MAST_CODE C ON M_CODE='RMST' AND B.AVAIL_TYPE=C.S_CODE  
LEFT JOIN TBL_CODE_HOLIDAY D ON DATE_DESC NOT IN ('토요일', '일요일', '근로자의 날') AND A.CAL_DATE=D.TARGET_DATE
ORDER BY A.CAL_DATE ASC
  
    
EXEC SP_XML_REMOVEDOCUMENT @XML_DOCUMENT_HANDLE
GO
