USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HIVE_BLOG]

/*
USP_HIVE_BLOG 200, 'NV'
*/

@TOP INT,
@BLOG_TYPE VARCHAR(2)

AS


SELECT NATION_CODE, REGION_CODE, REGION_NAME
INTO #TABLE_REGION  
FROM (
	SELECT NATION_CODE, A.REGION_CODE, B.KOR_NAME AS REGION_NAME, 
	RANK() OVER (PARTITION BY NATION_CODE ORDER BY A.REGION_CODE) AS SORT
	FROM AIR.DBO.TBL_CODE_CITY A  
	JOIN AIR.DBO.TBL_CODE_REGION B ON A.REGION_CODE=B.REGION_CODE  
	GROUP BY NATION_CODE, A.REGION_CODE, B.KOR_NAME  
) A
WHERE SORT=1

    
SELECT TOP (@TOP) A.HOTEL_CODE, A.NAME, A.ENG_NAME, C.NATION_CODE, C.NATION_NAME,     
A.CITY_CODE, A.CITY_NAME, STAR_RATING, REGION_CODE, REGION_NAME    
FROM HTL_INFO_MAST_HOTEL A    
JOIN HTL_CODE_MAST_CITY C ON A.CITY_CODE=C.CITY_CODE  
JOIN #TABLE_REGION D ON C.NATION_CODE=D.NATION_CODE
LEFT JOIN HTL_INFO_BLOG E ON A.HOTEL_CODE=E.HOTEL_CODE AND E.BLOG_TYPE=@BLOG_TYPE
WHERE A.USE_YN='Y' 
AND C.USE_YN='Y' 
AND E.HOTEL_CODE IS NULL
AND C.NATION_CODE <> 'KR'
ORDER BY C.SORT_ORDER ASC, A.NAME



GO
