USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_CREATE_SEARCH_VGT]

/*
USP_CREATE_SEARCH_VGT
*/


AS

INSERT HTL_IDX_SEARCH
SELECT 'INT' AS INT_DOM, A.HOTEL_CODE, NAME, ENG_NAME, CONVERT(VARCHAR, STAR_RATING) AS STAR_RATING, 
A.CITY_CODE, C.CITY_NAME, AREA_NAME, [ADDRESS], RV_POINT, '' AS TYPE_CODE, '' AS TYPE_CODE_NAME, SALE_AMT, MAIN_IMG, 'N' AS USE_YN,
REPLACE(ISNULL(NAME,''),' ','') + '|' + REPLACE(ISNULL(ENG_NAME,''),' ','') 
--+ '|' + 
--REPLACE(ISNULL(C.CITY_NAME,''),' ','') + '|' + REPLACE(ISNULL(C.CITY_ENAME,''),' ','') + '|' + 
--REPLACE(ISNULL([ADDRESS],''),' ','') 
AS INDEX_NAME,
RANK() OVER (ORDER BY (CASE WHEN RECOM_YN='Y' THEN 0 ELSE 1 END), 
C.SORT_ORDER, (CASE WHEN RV_POINT >= 4 THEN 0 ELSE 1 END), SALE_AMT ASC, A.HOTEL_CODE ASC) AS SORT
FROM HTL_INFO_MAST_HOTEL A
JOIN HTL_INFO_PRICE B ON A.HOTEL_CODE=B.HOTEL_CODE
JOIN HTL_CODE_MAST_CITY C ON A.CITY_CODE=C.CITY_CODE
AND A.USE_YN='Y'
AND NATION_CODE <> 'KR'




INSERT HTL_IDX_SEARCH
SELECT 'DOM' AS INT_DOM, A.HOTEL_CODE, HOTEL_NAME, '', '0.0', CITY_CODE, CITY_NAME, '',  ADDRESS3, REVIEW_POINT, 
S_CODE AS TYPE_CODE, CODE_NAME AS TYPE_CODE_NAME,
OMNI.DBO.FN_HTL_DOM_PRICE_RULE(B.NET_PRICE, B.SALE_PRICE, A.SUPP_TYPE, A.STAR_RATING) AS SALE_PRICE,
'http://img.justgo.kr/hotel/domestic/' + A.HOTEL_CODE + '/' + MAIN_IMG AS MAIN_IMG, 'N',
REPLACE(HOTEL_NAME,' ',''),
-- + '|' + 
--REPLACE(CITY_NAME,' ','') + '|' + 
--REPLACE(ADDRESS3,' ',''),
RANK() OVER (ORDER BY CNT DESC, SORT ASC, B.SALE_PRICE ASC) + 100000
FROM AIR.DBO.HTL_DOM_INFO_HOTEL A
JOIN AIR.DBO.HTL_DOM_INFO_MIN_PRICE B ON A.HOTEL_CODE=B.HOTEL_CODE
JOIN AIR.DBO.HTL_MAST_CODE C ON A.STAR_RATING=C.S_CODE AND C.M_CODE='CTGR'
JOIN AIR.DBO.HTL_DOM_RESV_CNT D ON A.HOTEL_CODE=D.HOTEL_CODE
WHERE A.USE_YN='Y'





UPDATE HTL_IDX_SEARCH SET USE_YN = (CASE WHEN USE_YN='N' THEN 'Y' ELSE 'N' END)

DECLARE @CNT INT;
SELECT @CNT = COUNT(*) FROM HTL_IDX_SEARCH WHERE USE_YN='Y'

IF (@CNT > 50000)
BEGIN
	DELETE HTL_IDX_SEARCH WHERE USE_YN='N'
END


GO
