USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[UPS_HTL_SALE_MONTH_BY_NATION]  
/*  
UPS_HTL_SALE_MONTH_BY_NATION 'RMTK', '2014-01-01', '2014-01-31'  
*/  
  
@ORDER_TYPE VARCHAR(50),  
@DATE_FROM VARCHAR(10),  
@DATE_TO VARCHAR(10),
@PARTNER_SHIP VARCHAR(10) = ''
  
AS  
  
DECLARE @SQL VARCHAR(MAX)  
  
SET @SQL = ''  
  
SET @SQL = @SQL + ' SET ANSI_WARNINGS OFF ' + CHAR(13) SET @SQL = @SQL + ' SET ARITHIGNORE ON ' + CHAR(13) SET @SQL = @SQL + ' SET ARITHABORT OFF ' + CHAR(13)  
  
SET @SQL = @SQL + ' SELECT ' + CHAR(13)  
SET @SQL = @SQL + '  D.NATION_CODE, ' + CHAR(13)  
SET @SQL = @SQL + '  D.NATION_NAME, ' + CHAR(13)  
SET @SQL = @SQL + '  SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN 1 ELSE 0 END) AS RMTK, ' + CHAR(13)  
SET @SQL = @SQL + '  SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN A.TOTAL_AMT ELSE 0 END) AS TOTAL_AMT, ' + CHAR(13)  
SET @SQL = @SQL + '  SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN A.SUPP_NET ELSE 0 END) AS SUPP_NET, ' + CHAR(13)  
SET @SQL = @SQL + '  SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN (CASE WHEN A.SUPP_CODE = ''EX'' THEN FLOOR(C.PAY_AMT * EX_RATE) ELSE C.PAY_AMT END) ELSE 0 END) AS PAY_AMT, ' + CHAR(13)  
SET @SQL = @SQL + '  SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN A.COM_AMT ELSE 0 END) AS COM_AMT, ' + CHAR(13)  
SET @SQL = @SQL + '  ROUND(SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN A.COM_AMT ELSE 0 END) / SUM(CASE WHEN A.LAST_STATUS = ''RMTK'' THEN (CASE WHEN A.SUPP_CODE = ''EX'' THEN FLOOR(C.PAY_AMT * EX_RATE) ELSE C.PAY_AMT END) ELSE 0 END) * 100, 1) AS COM_RATE ' + CHAR(13)  
SET @SQL = @SQL + ' FROM HTL_RESV_MAST A ' + CHAR(13)  
SET @SQL = @SQL + ' LEFT JOIN HTL_INFO_MAST_HOTEL B ' + CHAR(13)  
SET @SQL = @SQL + ' ON A.HOTEL_CODE = B.HOTEL_CODE ' + CHAR(13) 
SET @SQL = @SQL + ' LEFT JOIN HTL_CODE_MAST_CITY D ' + CHAR(13)
SET @SQL = @SQL + ' ON B.CITY_CODE = D.CITY_CODE ' + CHAR(13) 
SET @SQL = @SQL + ' LEFT JOIN( ' + CHAR(13)  
SET @SQL = @SQL + '  SELECT RESV_NO, SUM(CARD_AMOUNT + CASH_AMOUNT) AS PAY_AMT ' + CHAR(13)  
SET @SQL = @SQL + '  FROM HTL_RESV_PAY ' + CHAR(13)  
SET @SQL = @SQL + '  WHERE USE_YN = ''Y'' ' + CHAR(13)  
SET @SQL = @SQL + '  GROUP BY RESV_NO ' + CHAR(13)  
SET @SQL = @SQL + ' ) AS C ON A.RESV_NO = C.RESV_NO ' + CHAR(13)  
SET @SQL = @SQL + ' WHERE CONVERT(VARCHAR(10), A.CREATE_DATE, 121) >= ''' + @DATE_FROM + ''' AND CONVERT(VARCHAR(10), A.CREATE_DATE, 121) < CONVERT(DATETIME, ''' + @DATE_TO + ''') + 1 ' + CHAR(13) 
IF(@PARTNER_SHIP <> '') SET @SQL = @SQL + ' AND A.MCPN_CODE = ''' + @PARTNER_SHIP + ''' ' + CHAR(13) 
SET @SQL = @SQL + ' AND A.HOTEL_CODE NOT LIKE ''OF%'' ' + CHAR(13)
SET @SQL = @SQL + ' GROUP BY NATION_NAME, NATION_CODE ' + CHAR(13)  
SET @SQL = @SQL + ' ORDER BY ''' + @ORDER_TYPE + ''' DESC ' + CHAR(13)  
  
PRINT(@SQL)  
EXEC (@SQL) 


GO
