USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_SET_PG_COMMISSION_VGT]
    
/*    
USP_SET_PG_COMMISSION_VGT '1034'    
*/    
    
@RESV_NO INT    
    
AS    
    
DECLARE @CARD_COST DECIMAL;    
DECLARE @SUPP_CODE VARCHAR(2);    
DECLARE @LAST_STATUS VARCHAR(4);    
    
SET @CARD_COST = 0;    
    
SELECT @SUPP_CODE=SUPP_CODE, @LAST_STATUS=LAST_STATUS    
FROM HTL_RESV_MAST    
WHERE RESV_NO=@RESV_NO    
    
--익스피디아가 아니고, 취소요청이나 취소완료가 아니면,    
IF (@LAST_STATUS<>'RMXQ' AND @LAST_STATUS<>'RMXX')    
BEGIN     
    
 SELECT @CARD_COST = ISNULL(SUM(DBO.FN_GET_PAY_COMMITION_VGT(CARD_AMOUNT+CASH_AMOUNT, PAY_TYPE)),0)
 FROM HTL_RESV_PAY    
 WHERE RESV_NO=@RESV_NO AND USE_YN='Y'    
 
 UPDATE HTL_RESV_MAST SET     
 CARD_COST=@CARD_COST,    
 COM_AMT=TOTAL_AMT - SUPP_NET - DSC_COST - AFF_COST - @CARD_COST - VAT_COST    
 WHERE RESV_NO=@RESV_NO    
     
END    
    
SELECT @CARD_COST AS CARD_COST, @LAST_STATUS AS LAST_STATUS 


GO
