USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_INFO_INT_LIST]    
    
/*    
USP_INFO_INT_LIST '179900'    
*/    
    
@CITY_CODE VARCHAR(20)    
    
AS    
    
SELECT SPOT_NO, ISNULL(KOR_NAME, ENG_NAME) AS KOR_NAME,     
TYPE_CODE, TYPE_NAME, KIND_CODE, KIND_NAME, LATITUDE, LONGITUDE,    
RANK() OVER(PARTITION BY TYPE_CODE ORDER BY SPOT_NO) AS SORT,  
(SELECT TOP 1 URL FROM AIR.DBO.INFO_INT_IMAGE WHERE SPOT_NO=A.SPOT_NO ORDER BY (CASE WHEN MAIN_YN='Y' THEN 0 ELSE 1 END), IMG_NO) AS MAIN_IMG,  
(SELECT TOP 1 CONVERT(VARCHAR(70), INFO_DESC) FROM AIR.DBO.INFO_INT_DESC WHERE SPOT_ID=A.SPOT_NO) AS INFO_DESC, AREA_NAME  
FROM AIR.DBO.INFO_INT_MAST A  
WHERE CITY_CODE=(SELECT OLD_CODE FROM HTL_CODE_MAST_CITY WHERE CITY_CODE=@CITY_CODE)     
AND USE_YN='Y' AND TYPE_CODE <> 'H'    
ORDER BY SORT


GO
