USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_GET_HOTEL_IMAGES]

/*
USP_GET_HOTEL_IMAGES 5, 'W830001', 'RT'
*/

@HOTEL_CODE DECIMAL,
@S_HOTEL_CODE VARCHAR(100),
@SUPP_CODE VARCHAR(2)

AS

--SELECT IMG_URL, 'EA' AS SUPP_CODE
--FROM HTL_INFO_MAST_IMAGE WHERE HOTEL_CODE=@HOTEL_CODE
--UNION ALL
SELECT IMG_URL, SUPP_CODE
FROM HTL_INFO_SUB_IMAGE WHERE HOTEL_CODE=@S_HOTEL_CODE AND SUPP_CODE=@SUPP_CODE
GO
