USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HTL_RESV_LIST_11ST]

/*
USP_HTL_RESV_LIST_11ST 'C', '2015-10-10', '2015-10-17'
*/

@RESV_STATUS VARCHAR(1),
@DATE_FROM VARCHAR(10),
@DATE_TO VARCHAR(10)

AS

IF (@RESV_STATUS='P')

	BEGIN

		SELECT *
		FROM (
			SELECT 'HTL' AS RESV_TYPE, RESV_NO, AFF_NO, 
			'P' AS RESV_STATUS, 
			CREATE_DATE AS TARGET_DATE,
			(
				SELECT TOP 1 PAYMENT_ID 
				FROM HTL_RESV_PAY 
				WHERE RESV_NO=A.RESV_NO 
				AND PAYMENT_ID IS NOT NULL
				GROUP BY PAYMENT_ID
			) AS PAYMENT_ID
			FROM HTL_RESV_MAST A
			WHERE MCPN_CODE='EL0001'
			AND CREATE_DATE >= @DATE_FROM AND CREATE_DATE < DATEADD(d, 1, @DATE_TO)
			AND LAST_STATUS NOT IN ('RMXQ', 'RMXX')

			UNION ALL

			SELECT 'HTD' AS RESV_TYPE, RESV_NO, AFF_NO,
			'P' AS RESV_STATUS, 
			CREATE_DATE AS TARGET_DATE,
			(
				SELECT TOP 1 PAYMENT_ID 
				FROM AIR.DBO.HTL_DOM_RESV_PAY
				WHERE RESV_NO=A.RESV_NO 
				AND PAYMENT_ID IS NOT NULL
				GROUP BY PAYMENT_ID
			) AS PAYMENT_ID
			FROM AIR.DBO.HTL_DOM_RESV_MAST A
			WHERE MCPN_CODE='EL0001'
			AND CREATE_DATE >= @DATE_FROM AND CREATE_DATE < DATEADD(d, 1, @DATE_TO)
			AND LAST_STATUS NOT IN ('RMXQ', 'RMXX')
		) A
		ORDER BY TARGET_DATE

	END

ELSE

	BEGIN

		SELECT *
		FROM (
			SELECT 'HTL' AS RESV_TYPE, RESV_NO, AFF_NO, 
			'C' AS RESV_STATUS, 
			CANCEL_REQ_DATE AS TARGET_DATE,
			(
				SELECT TOP 1 PAYMENT_ID 
				FROM HTL_RESV_PAY 
				WHERE RESV_NO=A.RESV_NO 
				AND PAYMENT_ID IS NOT NULL
				GROUP BY PAYMENT_ID
			) AS PAYMENT_ID
			FROM HTL_RESV_MAST A
			WHERE MCPN_CODE='EL0001'
			AND CANCEL_REQ_DATE >= @DATE_FROM AND CREATE_DATE < DATEADD(d, 1, @DATE_TO)
			AND LAST_STATUS IN ('RMXQ', 'RMXX')

			UNION ALL

			SELECT 'HTD' AS RESV_TYPE, RESV_NO, AFF_NO,
			'C' AS RESV_STATUS, 
			CANCEL_REQ_DATE AS TARGET_DATE,
			(
				SELECT TOP 1 PAYMENT_ID 
				FROM AIR.DBO.HTL_DOM_RESV_PAY
				WHERE RESV_NO=A.RESV_NO 
				AND PAYMENT_ID IS NOT NULL
				GROUP BY PAYMENT_ID
			) AS PAYMENT_ID
			FROM AIR.DBO.HTL_DOM_RESV_MAST A
			WHERE MCPN_CODE='EL0001'
			AND CANCEL_REQ_DATE >= @DATE_FROM AND CREATE_DATE < DATEADD(d, 1, @DATE_TO)
			AND LAST_STATUS IN ('RMXQ', 'RMXX')
		) A
		ORDER BY TARGET_DATE

	END




GO
