USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_HTL_RECOM_HOTEL]

/*
USP_HTL_RECOM_HOTEL '179900'
*/

@CITY_CODE VARCHAR(20)

AS

SELECT B.HOTEL_CODE, B.NAME, B.ENG_NAME, B.AREA_NAME, B.LOCATION_DESC, B.STAR_RATING, B.RV_POINT,
B.MAIN_IMG, SALE_AMT, RECOM_TYPE, RECOM_URL, RECOM_DESC
FROM HTL_INFO_RECOM A
JOIN HTL_INFO_MAST_HOTEL B ON A.HOTEL_CODE=B.HOTEL_CODE
JOIN HTL_INFO_PRICE C ON A.HOTEL_CODE=C.HOTEL_CODE
WHERE A.CITY_CODE=@CITY_CODE
AND B.USE_YN='Y'
ORDER BY RV_POINT DESC, SALE_AMT


GO
