USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_TBL_PROG_AUTH_COPY]

/*
USP_TBL_PROG_AUTH_COPY 'NOTRUST', 'TEST', 'NOTRUST'
*/

@ORGIN_ID VARCHAR(50),
@TARGET_ID VARCHAR(50),
@USER_ID VARCHAR(50)

AS

DECLARE @CNT INT;

SELECT @CNT = COUNT(*)
FROM HTL_SYST_USER WHERE [USER_ID] IN (@ORGIN_ID, @TARGET_ID)

IF (@CNT < 2) 
BEGIN

RAISERROR (15600,-1,-1, 'USP_TBL_PROG_AUTH_COPY');  
RETURN;

END


--권한삭제
DELETE TBL_PROG_USER
WHERE [USER_ID]=@TARGET_ID


--권한재등록
INSERT TBL_PROG_USER
SELECT @TARGET_ID, 
A.PROG_ID, 
ISNULL(C.PERM_SEL, 'N') AS PERM_SEL, 
ISNULL(C.PERM_UPD, 'N') AS PERM_UPD, 
ISNULL(C.PERM_DEL, 'N') AS PERM_DEL,  
ISNULL(C.PERM_PRT, 'N') AS PERM_PRT,
@USER_ID,
GETDATE()
FROM TBL_PROG_MAST A
JOIN TBL_PROG_GROUP B ON A.GROUP_ID=B.GROUP_ID
LEFT JOIN TBL_PROG_USER C ON A.PROG_ID=C.PROG_ID AND C.[USER_ID]=@ORGIN_ID
WHERE A.USE_YN='Y' AND B.USE_YN='Y'
GO
