USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_MAST_HOTEL]
          
/*          
USP_MAST_HOTEL '14690', ''  
USP_MAST_HOTEL '17179', ''  
USP_MAST_HOTEL '17759',''  
USP_MAST_HOTEL '14690', ''  
USP_MAST_HOTEL '179900', '', '신주쿠'        
*/          
          
@CITY_CODE VARCHAR(20),          
@HOTEL_CODE VARCHAR(20),        
@HOTEL_NAME VARCHAR(1000) = ''        
          
AS          
          
DECLARE @SQL VARCHAR(8000);          
SET @SQL = '';          
          
IF (@CITY_CODE = '') RETURN;          
          
SET @SQL = @SQL + 'SELECT A.HOTEL_CODE, REPLACE(A.NAME,''?'','' '') AS NAME , A.OVERVIEW, A.ENG_NAME, A.CITY_CODE, A.CITY_NAME, A.AREA_CODE, A.AREA_NAME, ISNULL(LOCATION_DESC,''-'') AS LOCATION_DESC, ' + CHAR(13)          
SET @SQL = @SQL + 'ADDRESS, SUBSTRING(CONVERT(CHAR,STAR_RATING),1,1) AS STAR_RATING,SUBSTRING(CONVERT(CHAR,STAR_RATING),1,1) AS STAR_POINT, ROOM_CNT, CHECK_IN_TIME, CHECK_OUT_TIME, LATITUDE, LONGITUDE, ' + CHAR(13)          
SET @SQL = @SQL + 'MAIN_IMG, RV_POINT, RECOM_YN, RECOM_SORT, PHONE, FAX, HOTEL_TYPE,' + CHAR(13) 
SET @SQL = @SQL + 'CASE WHEN HOTEL_TYPE NOT IN (''호텔'',''리조트'') THEN ''기타'' ELSE HOTEL_TYPE END AS ''HOTEL_ETC_TYPE'',' + CHAR(13) 
     

SET @SQL = @SQL + '( ' + CHAR(13)        
    
SET @SQL = @SQL + ' SELECT STUFF((SELECT ''@''+S_CODE+''|''+CODE_NAME ' + CHAR(13)     
SET @SQL = @SQL + ' FROM HTL_INFO_MAST_FAC_IDX WHERE HOTEL_CODE=A.HOTEL_CODE ' + CHAR(13)     
SET @SQL = @SQL + ' FOR XML PATH('''')),1,1,'''') ' + CHAR(13)     
SET @SQL = @SQL + ') AS FACILITY, ' + CHAR(13)   
  
SET @SQL = @SQL + '( ' + CHAR(13)        
SET @SQL = @SQL + ' SELECT TOP 4 STUFF((SELECT ''@''+MARK_NAME +'' ''+ DISTANCE'+ CHAR(13)        
SET @SQL = @SQL + ' FROM HTL_INFO_LANDMARK AL ' + CHAR(13)        
SET @SQL = @SQL + ' JOIN HTL_CODE_LANDMARK BL ON AL.MARK_CODE=BL.MARK_CODE ' + CHAR(13)        
SET @SQL = @SQL + ' WHERE HOTEL_CODE=A.HOTEL_CODE  ORDER BY CONVERT(float,DISTANCE)  ' + CHAR(13)        
SET @SQL = @SQL + ' FOR XML PATH('''')),1,1,'''') ' + CHAR(13)        
SET @SQL = @SQL + ') AS LAND_MARK_DISTANCE,' + CHAR(13)    


SET @SQL = @SQL + '( ' + CHAR(13)        
SET @SQL = @SQL + ' SELECT STUFF((SELECT ''@''+CONVERT(VARCHAR,BL.MARK_CODE)+''|''+MARK_NAME ' + CHAR(13)        
SET @SQL = @SQL + ' FROM HTL_INFO_LANDMARK AL ' + CHAR(13)        
SET @SQL = @SQL + ' JOIN HTL_CODE_LANDMARK BL ON AL.MARK_CODE=BL.MARK_CODE ' + CHAR(13)        
SET @SQL = @SQL + ' WHERE HOTEL_CODE=A.HOTEL_CODE  ' + CHAR(13)        
SET @SQL = @SQL + ' FOR XML PATH('''')),1,1,'''') ' + CHAR(13)        
SET @SQL = @SQL + ') AS LAND_MARK,C.TITLE,C.EVENT_DESC ' + CHAR(13)        
SET @SQL = @SQL + 'FROM HTL_INFO_MAST_HOTEL A WITH (NOLOCK) ' + CHAR(13)        
SET @SQL = @SQL + '-- LEFT JOIN HTL_INFO_PRICE B WITH (NOLOCK) ON A.HOTEL_CODE=B.HOTEL_CODE  ' + CHAR(13)   
SET @SQL = @SQL + 'LEFT JOIN HTL_EVENT_MAST C WITH (NOLOCK) ON A.HOTEL_CODE =C.HOTEL_CODE  ' + CHAR(13)   

SET @SQL = @SQL + 'WHERE A.USE_YN=''Y''  ' + CHAR(13)          
SET @SQL = @SQL + 'AND A.CITY_CODE=''' + @CITY_CODE + ''' ' + CHAR(13)          
          
IF (@HOTEL_CODE <> '')          
 SET @SQL = @SQL + 'AND A.HOTEL_CODE=''' + @HOTEL_CODE + ''' '          
        
IF (@HOTEL_NAME <> '')          
 SET @SQL = @SQL + 'AND (A.NAME LIKE ''%' + @HOTEL_NAME + '%'' OR A.ENG_NAME LIKE ''%' + @HOTEL_NAME + '%'') '     + CHAR(13)        
  
 -- SET @SQL = @SQL + 'AND A.HOTEL_CODE IN (1184558,2803727,10636,2156098,9373959,1077949,51955,2399737,6740442, 6383503,81791,497719,3582432,69184,9322,1963,910,1184558,2803727, 12157,12153,65498, 3541400,523478) '        
 --  SET @SQL = @SQL + 'AND A.HOTEL_CODE IN (6383503,81791,497719,3582432,69184,9322,1963,910,1184558,2803727) '

 -- SET @SQL = @SQL + 'OR A.HOTEL_CODE IN (12157,12153,65498) '        
 --PRINT(@SQL)
 EXEC(@SQL)
GO
