USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


-- 정산 데이터 검색을 위해 생성 특정일자 기준 입금액 체크 위해
CREATE FUNCTION [dbo].[FN_RES_GET_PAY_PRICE_TEST]
(
	@RES_CODE VARCHAR(20)
)
RETURNS DECIMAL
AS
BEGIN

	DECLARE @PAY_PRICE DECIMAL
	
	SELECT
		@PAY_PRICE = ISNULL(SUM(A.PART_PRICE), 0)
	FROM PAY_MATCHING A WITH(NOLOCK)
	INNER JOIN PAY_MASTER_damo B WITH(NOLOCK) ON A.PAY_SEQ = B.PAY_SEQ 
	WHERE A.RES_CODE = @RES_CODE AND B.PAY_DATE < '2015-01-01'
	AND A.CXL_YN = 'N';
	-- 0 접수에서 7 환불까지
	
	RETURN (@PAY_PRICE)

END


GO
