USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
환불일경우 가격 보이기 2015-08-10 박형만 , 호텔팀 전선영씨 요청 
*/
CREATE FUNCTION [dbo].[FN_RES_HTL_GET_TOTAL_PRICE]
(
	@RES_CODE VARCHAR(20)
)
RETURNS DECIMAL
AS
BEGIN

	DECLARE @TOT_PRICE DECIMAL

	-- TOT_PRICE는 판매액
	-- PAY_PRICE는 입금액
	IF EXISTS(SELECT * FROM RES_HTL_ROOM_MASTER WITH(NOLOCK)  WHERE RES_CODE = @RES_CODE)
	BEGIN
		SELECT @TOT_PRICE = SUM((ISNULL(SALE_PRICE, 0) - ISNULL(DC_PRICE, 0) + ISNULL(TAX_PRICE, 0) + ISNULL(CHG_PRICE, 0) + ISNULL(PENALTY_PRICE, 0)))
		FROM RES_HTL_ROOM_MASTER A WITH(NOLOCK) 
			INNER JOIN RES_MASTER_DAMO B  WITH(NOLOCK) 
				ON A.RES_CODE = B.RES_CODE
		--WHERE A.RES_CODE = @RES_CODE AND B.RES_STATE NOT IN (7,8,9)
		WHERE A.RES_CODE = @RES_CODE AND B.RES_STATE NOT IN (8,9)
--		SELECT @TOT_PRICE = (SUM_SALE_PRICE - SUM_DC_PRICE + SUM_CHG_PRICE + SUM_TAX_PRICE + SUM_PENALTY_PRICE)
--		FROM (
--			SELECT
--				SUM(ISNULL(ROOM_PRICE, 0) * ISNULL(ROOM_COUNT, 0)) AS [SUM_SALE_PRICE], 
--				SUM(ISNULL(CHG_PRICE, 0) * ISNULL(ROOM_COUNT, 0)) AS [SUM_CHG_PRICE], 
--				SUM(ISNULL(DC_PRICE, 0) * ISNULL(ROOM_COUNT, 0)) AS [SUM_DC_PRICE], 
--				SUM(ISNULL(TAX_PRICE, 0) * ISNULL(ROOM_COUNT, 0)) AS [SUM_TAX_PRICE], 
--				SUM(ISNULL(PENALTY_PRICE, 0) * ISNULL(ROOM_COUNT, 0)) AS [SUM_PENALTY_PRICE]
--			FROM RES_HTL_DETAIL A
--			WHERE RES_CODE = @RES_CODE
--			AND EXISTS(SELECT 1 FROM RES_HTL_MASTER WHERE RES_CODE = A.RES_CODE AND MASTER_CODE = A.MASTER_CODE AND CHECK_IN = A.CHECK_IN AND RES_STATE IN (0, 3, 4))
--		) A
	END
	ELSE
	BEGIN
		SELECT @TOT_PRICE = 0
	END

	RETURN (@TOT_PRICE)

END

GO
