USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[FN_RES_IS_SEAT]
(
	@RES_CODE VARCHAR(20)
)
RETURNS CHAR(1)
AS
BEGIN

	DECLARE @YN CHAR(1)

	SELECT @YN = ISNULL(MIN(SEAT_YN), 'N') FROM RES_CUSTOMER_damo WITH(NOLOCK) 
	WHERE RES_CODE = @RES_CODE AND RES_STATE = 0
	--GROUP BY RES_CODE

	RETURN (@YN)
END
GO
