USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date, ,>
-- Description:	예약코드로 상품명을 가져온다.
-- =============================================
CREATE FUNCTION [dbo].[FN_RES_GET_PRO_NAME]
(
	@RES_CODE VARCHAR(20)
)
RETURNS VARCHAR(100)
AS
BEGIN
	DECLARE @PRO_NAME VARCHAR(100);

	WITH DOCUMENTLIST AS
	(
		SELECT
			(SELECT PRO_NAME FROM PKG_DETAIL  WITH(NOLOCK) WHERE PRO_CODE = A.PRO_CODE) AS PKG_NAME,
			(SELECT MASTER_NAME FROM HTL_MASTER  WITH(NOLOCK) WHERE MASTER_CODE = A.MASTER_CODE) AS HTL_NAME,
			(SELECT MASTER_NAME FROM OPT_MASTER  WITH(NOLOCK) WHERE MASTER_CODE = A.PRO_CODE) AS OPT_NAME,
			(SELECT dbo.FN_RES_AIR_GET_PRO_NAME(A.RES_CODE)) AS AIR_NAME,
			A.PRO_TYPE			
		FROM RES_MASTER_DAMO A WITH(NOLOCK) 
		WHERE RES_CODE = @RES_CODE
	)
	SELECT
		@PRO_NAME = (CASE PRO_TYPE WHEN '1' THEN PKG_NAME 
								   WHEN '2' THEN AIR_NAME
								   WHEN '3' THEN HTL_NAME
								   WHEN '4' THEN '자유여행'
								   WHEN '5' THEN OPT_NAME END)
	FROM DOCUMENTLIST;

	RETURN @PRO_NAME
END

GO
