USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date, ,>
-- Description:	<행사코드로 지역명을 가져온다.>
-- =============================================
CREATE FUNCTION [dbo].[FN_PRO_GET_REGION_NAME]
(
	@PRO_CODE	VARCHAR(20)
)
RETURNS VARCHAR(20)
AS
BEGIN
	DECLARE @REGION_NAME VARCHAR(20)
	SELECT
		@REGION_NAME = F.KOR_NAME
	FROM PKG_DETAIL A WITH(NOLOCK) 
	INNER JOIN PRO_TRANS_SEAT B WITH(NOLOCK) ON B.SEAT_CODE = A.SEAT_CODE
	INNER JOIN PUB_AIRPORT C WITH(NOLOCK) ON C.AIRPORT_CODE = B.DEP_ARR_AIRPORT_CODE
	INNER JOIN PUB_CITY D WITH(NOLOCK) ON D.CITY_CODE = C.CITY_CODE
	INNER JOIN PUB_NATION E WITH(NOLOCK) ON E.NATION_CODE = D.NATION_CODE
	INNER JOIN PUB_REGION F WITH(NOLOCK) ON F.REGION_CODE = E.REGION_CODE
	WHERE A.PRO_CODE = @PRO_CODE;
	RETURN @REGION_NAME;
END
GO
