USE [Diablo]
GO
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

CREATE FUNCTION [dbo].[FN_WEEK_CHECK]
(
	@DATE		DATETIME,
	@CHECK_STR	CHAR(7)
)
RETURNS INT
AS
BEGIN

	DECLARE @CHECK INT

	SELECT @CHECK = 
		CASE 
			WHEN ('일요일' = DATENAME(DW, @DATE) AND '1' = SUBSTRING(@CHECK_STR, 1, 1)) THEN 1
			WHEN '월요일' = DATENAME(DW, @DATE) AND '1' = SUBSTRING(@CHECK_STR, 2, 1) THEN 1
			WHEN '화요일' = DATENAME(DW, @DATE) AND '1' = SUBSTRING(@CHECK_STR, 3, 1) THEN 1
			WHEN '수요일' = DATENAME(DW, @DATE) AND '1' = SUBSTRING(@CHECK_STR, 4, 1) THEN 1
			WHEN '목요일' = DATENAME(DW, @DATE) AND '1' = SUBSTRING(@CHECK_STR, 5, 1) THEN 1
			WHEN '금요일' = DATENAME(DW, @DATE) AND '1' = SUBSTRING(@CHECK_STR, 6, 1) THEN 1
			WHEN '토요일' = DATENAME(DW, @DATE) AND '1' = SUBSTRING(@CHECK_STR, 7, 1) THEN 1
			ELSE 0
		END

	RETURN @CHECK
END
GO
