USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[FN_CUS_GET_EMP_TEAM_CODE]
(
	@EMP_CODE CHAR(7)
)
RETURNS VARCHAR(20)
AS
BEGIN

	DECLARE @TEAM_CODE VARCHAR(3)

	SELECT @TEAM_CODE = TEAM_CODE FROM EMP_MASTER_damo WITH(NOLOCK)  WHERE EMP_CODE = @EMP_CODE

	RETURN (@TEAM_CODE)
END
GO
