USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[FN_CUS_GET_EMP_NAME]
(
	@EMP_CODE CHAR(7)
)
RETURNS VARCHAR(20)
AS
BEGIN

	DECLARE @EMP_NAME VARCHAR(20)

	SELECT @EMP_NAME = KOR_NAME FROM EMP_MASTER_damo WITH(NOLOCK) WHERE EMP_CODE = @EMP_CODE

	RETURN (@EMP_NAME)
END
GO
