USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,박형만>
-- Create date: <Create Date, 2019-04-26 ,>
-- Description:	항공 여정의 좌석의 총 비행시간만 가져온다  ( 네이버용 ) 
-- SELECT DBO.FN_AIR_PRO_TRANS_FLYING_MINUTE(8271711,1)
-- SELECT DBO.FN_AIR_PRO_TRANS_FLYING_MINUTE(8271711,2)
-- SELECT DBO.FN_AIR_PRO_TRANS_FLYING_MINUTE(8271662,1)
-- SELECT DBO.FN_AIR_PRO_TRANS_FLYING_MINUTE(8271662,2)
-- =============================================
CREATE FUNCTION [dbo].[FN_AIR_PRO_TRANS_FLYING_MINUTE]
(
	@SEAT_CODE INT , 
	@TRANS_SEQ INT -- 출발편1 , 귀국편2
)
RETURNS INT
AS
BEGIN

	DECLARE @RESULT INT;
	--DECLARE @SEAT_CODE INT 
	--DECLARE @TRANS_SEQ INT 

	--SET @SEAT_CODE = 8271711 
	--SET @TRANS_SEQ = 1 

	-- 좌석 상세 세그 정보 있으면 세그 정보 
	IF EXISTS ( SELECT * FROM PRO_tRANS_SEAT_SEGMENT WITH(NOLOCK)
		WHERE TRANS_SEQ = @TRANS_SEQ 
		AND SEAT_CODE =@SEAT_CODE 
	)
	BEGIN
		SELECT @RESULT = 
			SUM(
				CASE WHEN LEN(REPLACe(FLYING_TIME,':','')) = 4  AND ISNUMERIC(REPLACe(FLYING_TIME,':','')) = 1 
					THEN (CONVERT(INT,LEFT(FLYING_TIME,2)) * 60) + CONVERT(INT,RIGHT(FLYING_TIME,2)) ELSE 0 END 
			)
		FROM PRO_tRANS_SEAT_SEGMENT WITH(NOLOCK)
		WHERE SEAT_CODE = @SEAT_CODE 
		AND TRANS_SEQ = @TRANS_SEQ
	END 
	
	-- 없으면 
	IF @RESULT IS NULL OR @RESULT = 0 
	BEGIN

		SELECT 
			@RESULT = (
				CASE WHEN @TRANS_SEQ = 1 
				THEN 
					CASE WHEN LEN(REPLACe(DEP_SPEND_TIME,':','')) = 4  AND ISNUMERIC(REPLACe(DEP_SPEND_TIME,':','')) = 1 
						THEN (CONVERT(INT,LEFT(DEP_SPEND_TIME,2)) * 60) + CONVERT(INT,RIGHT(DEP_SPEND_TIME,2)) ELSE 0 END 
				ELSE  
					CASE WHEN LEN(REPLACe(ARR_SPEND_TIME,':','')) = 4  AND ISNUMERIC(REPLACe(ARR_SPEND_TIME,':','')) = 1
						THEN (CONVERT(INT,LEFT(ARR_SPEND_TIME,2)) * 60) + CONVERT(INT,RIGHT(ARR_SPEND_TIME,2))  ELSE 0 END 
					END 
			)
		FROM PRO_TRANS_SEAT  WITH(NOLOCK)
		WHERE SEAT_CODE = @SEAT_CODE  
	END 
	
	RETURN @RESULT
END 
GO
