USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[FN_CUS_GET_EMP_TEAM]
(
	@EMP_CODE CHAR(7)
)
RETURNS VARCHAR(50)
AS
BEGIN

	DECLARE @EMP_TEAM VARCHAR(50)

	SELECT @EMP_TEAM = TEAM_NAME FROM EMP_TEAM WITH(NOLOCK) 
	WHERE TEAM_CODE = (SELECT TEAM_CODE FROM EMP_MASTER_damo WITH(NOLOCK) WHERE EMP_CODE = @EMP_CODE)

	RETURN (@EMP_TEAM)

END
GO
