USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[FN_CUS_GET_EMP_INNERNUM2]
(
	@EMP_CODE CHAR(7)
)
RETURNS VARCHAR(30)
AS
BEGIN

	DECLARE @EMP_INNERNUM2 VARCHAR(4)

	SELECT @EMP_INNERNUM2 = INNER_NUMBER2 FROM EMP_MASTER_damo WITH(NOLOCK) WHERE EMP_CODE = @EMP_CODE

	RETURN (@EMP_INNERNUM2)
END
GO
