USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

 
/*----------------------------------------------------------------
-- 시차 계산 하였을때 올바르지 않은것
-- 소요시간 계산 , 시차 적용 

--SELECT DBO.FN_GET_TIME_BY_MINUTE(DBO.FN_AIR_GET_SPEND_MINUTE_AIRPORT('2019-08-08 18:30 ','2019-08-09 11:50 ','FRA' ,2 )) 
----------------------------------------------------------------*/
CREATE FUNCTION [dbo].[FN_AIR_GET_SPEND_MINUTE_AIRPORT]
(
	@START_DATE DATETIME,
	@END_DATE DATETIME,
	@AIRPORT_CODE VARCHAR(3),
	@DIRECTION INT  -- 1 = 출발 , 2=도착 
)
RETURNS INT
AS
BEGIN

--DECLARE @START_DATE DATETIME
--DECLARE @END_DATE DATETIME
--DECLARE @AIRPORT_CODE VARCHAR(3)
--DECLARE @DIRECTION INT 
--SET @START_DATE = '2019-08-08 18:30 '
--SET @END_DATE = '2019-08-09 11:50 '
--SET @AIRPORT_CODE = 'FRA' 
--SET @DIRECTION =  2
	
	DECLARE @TIME_DIFFER INT 
	DECLARE @TOTAL_MINUTE INT 
	SET @TIME_DIFFER = ISNULL((SELECT TIME_DIFFER FROM PUB_AIRPORT WHERE AIRPORT_CODE = @AIRPORT_CODE ),0)
	SET @TOTAL_MINUTE =  DATEDIFF( MI, @START_DATE , @END_DATE )  -- 총 진행시간 
	SET @TOTAL_MINUTE = @TOTAL_MINUTE + 
		(CASE WHEN @DIRECTION = 2 THEN  + (@TIME_DIFFER*60)	ELSE - (@TIME_DIFFER*60) END )

	-- 시차 계산
	--SELECT @TIME_DIFFER , @TOTAL_MINUTE , DBO.FN_GET_TIME_BY_MINUTE(@TOTAL_MINUTE)

	RETURN @TOTAL_MINUTE 
END
GO
