USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[FN_CUS_GET_EMP_INNERNUM]
(
	@EMP_CODE CHAR(7)
)
RETURNS VARCHAR(30)
AS
BEGIN

	DECLARE @EMP_INNERNUM VARCHAR(15)

	
	SET @EMP_INNERNUM = (SELECT 
		CASE WHEN ISNULL(INNER_NUMBER1,'') = '' THEN '02' ELSE INNER_NUMBER1 END  + '-' +
		CASE WHEN ISNULL(INNER_NUMBER2,'') = '' THEN '2188' ELSE INNER_NUMBER2 END   + '-' +
		CASE WHEN ISNULL(INNER_NUMBER3,'') = '' THEN '2188' ELSE INNER_NUMBER3 END   
	FROM EMP_MASTER_damo WITH(NOLOCK) WHERE EMP_CODE = @EMP_CODE)

	RETURN (@EMP_INNERNUM)
END
GO
