USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE FUNCTION [dbo].[FN_GET_SET_COMPLETE] (@PRO_CODE VARCHAR(20) )  
  RETURNS TABLE
 
  
AS
RETURN
(

SELECT
	--항공수익
	(SELECT SUM(PROFIT) FROM SET_AIR_CUSTOMER  WITH(NOLOCK) WHERE PRO_CODE = @PRO_CODE) AS AIR_PROFIT ,
	--항공비용 
	(SELECT SUM(PAY_PRICE) FROM SET_AIR_CUSTOMER  WITH(NOLOCK) WHERE PRO_CODE = @PRO_CODE) AS AIR_PRICE,
	-- 수수료
	(SELECT SUM(COM_PRICE)FROM SET_LAND_CUSTOMER WITH(NOLOCK)  WHERE PRO_CODE = @PRO_CODE) AS COM_PRICE ,
	-- 공동경비
	(SELECT SUM(PRICE)FROM SET_GROUP WITH(NOLOCK)  WHERE PRO_CODE = @PRO_CODE AND PROFIT_YN = 'N') AS GROUP_PRICE ,
	-- 공동수익
	(SELECT SUM(PRICE)FROM SET_GROUP WITH(NOLOCK)  WHERE PRO_CODE = @PRO_CODE AND PROFIT_YN = 'Y') AS GROUP_PROFIT ,
	-- 지상비
	(SELECT SUM(PAY_PRICE + VAT_PRICE )FROM SET_LAND_CUSTOMER WITH(NOLOCK)  WHERE PRO_CODE = @PRO_CODE) AS LAND_PRICE ,
	-- 개인경비
	(SELECT SUM(INS_PRICE + ETC_PRICE + PASS_PRICE + VISA_PRICE) FROM SET_CUSTOMER WITH(NOLOCK)  WHERE PRO_CODE = @PRO_CODE) AS PERSON_PRICE
)



GO
