USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		김성호
-- Create date: 2009.03.18
-- Description:	팀별 계좌번호 리턴
-- =============================================
CREATE FUNCTION [dbo].[FN_PUB_GET_TEAM_ACCOUNT_NUMBER]
(
	@EMP_CODE  VARCHAR(10)
)
RETURNS VARCHAR(20)
AS
BEGIN
	DECLARE @REG_NUMVER VARCHAR(20)

	SELECT @REG_NUMVER = B.REG_NUMBER FROM EMP_TEAM A WITH(NOLOCK) 
	INNER JOIN AGT_ACCOUNT B WITH(NOLOCK) ON A.AGT_CODE = B.AGT_CODE AND A.ACC_SEQ = B.ACC_SEQ
	WHERE A.TEAM_CODE IN (SELECT TEAM_CODE FROM EMP_MASTER_damo WITH(NOLOCK) WHERE EMP_CODE = @EMP_CODE)

	RETURN (@REG_NUMVER)
END
GO
