USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
2019-08-20 시간문자열 HH:mm 을 분으로 변환 
SELECT DBO.FN_GET_MINUTE_BY_TIME('30:12')
*/
CREATE FUNCTION [dbo].[FN_GET_MINUTE_BY_TIME]
(
	@TIME_STRING CHAR(5)
)
RETURNS INT 
AS
BEGIN

--DECLARE @TIME_STRING CHAR(5)
--SET @TIME_STRING = '*0:00' 

	DECLARE @MINUTE INT 
	SET @MINUTE = -1  
	IF(ISNULL(@TIME_STRING,'') <> ''
	 AND LEN(RTRIM(REPLACe(REPLACe(REPLACe(@TIME_STRING,':',''),' ',''),'.',''))) = 4
	 AND ISNUMERIC(REPLACe(REPLACe(REPLACe(@TIME_STRING,':',''),' ',''),'.','')) = 1 
	 )
	BEGIN
		SET @MINUTE  = (CONVERT(INT,SUBSTRING(@TIME_STRING,1,2)) * 60 )
					+ CONVERT(INT,SUBSTRING(@TIME_STRING,4,2))    
		 
	END 
	
--SELECT @MINUTE 
	RETURN @MINUTE 
END

GO
