USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[FN_CUS_GET_DEP_TRANS_CONUM]
(
	@SEAT_CODE int
)
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @TRANS_CONUM VARCHAR(6)

	SELECT @TRANS_CONUM = DEP_TRANS_CODE + DEP_TRANS_NUMBER FROM PRO_TRANS_SEAT WITH(NOLOCK) WHERE SEAT_CODE = @SEAT_CODE

	RETURN (@TRANS_CONUM)

END
GO
