USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
2011-09-02 호텔일경우 금액 합산 분기
*/
-- 대리점 수수료 계산에 사용
CREATE FUNCTION [dbo].[FN_RES_GET_SALE_PRICE]
(
	@RES_CODE VARCHAR(20)
)
RETURNS DECIMAL
AS
BEGIN

	DECLARE @TOT_PRICE DECIMAL

	-- TOT_PRICE는 판매액
	-- PAY_PRICE는 입금액

	IF ( SUBSTRING(@RES_CODE,1,2) = 'RH') --호텔
	BEGIN
		SELECT @TOT_PRICE = SUM((ISNULL(SALE_PRICE, 0) - ISNULL(DC_PRICE, 0) + ISNULL(TAX_PRICE, 0) + ISNULL(CHG_PRICE, 0) + ISNULL(PENALTY_PRICE, 0)))
		FROM RES_HTL_ROOM_MASTER A WITH(NOLOCK)
			INNER JOIN RES_MASTER_DAMO B  WITH(NOLOCK)
				ON A.RES_CODE = B.RES_CODE
		WHERE A.RES_CODE = @RES_CODE AND B.RES_STATE NOT IN (8, 9)
	END 
	ELSE 
	BEGIN 
		SELECT @TOT_PRICE = (SUM_SALE_PRICE)
		FROM (
			SELECT
				ISNULL(SUM(SALE_PRICE), 0) AS [SUM_SALE_PRICE]
			FROM RES_CUSTOMER_DAMO WITH (NOLOCK)
			WHERE RES_CODE = @RES_CODE
			AND RES_STATE IN (0, 3) -- 예약, 환불, 페널티
			AND COMM_YN = 'N'
		) A
	END 

	RETURN (@TOT_PRICE)

END
GO
