USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- AUTHOR:		<AUTHOR,,NAME>
-- CREATE DATE: <CREATE DATE, ,>
-- DESCRIPTION:	예약판매자를 가져온다
-- =============================================
CREATE FUNCTION [dbo].[FN_RES_GET_SALE_CODE]
(
	@PRO_CODE VARCHAR(20)
	, @EMP_CODE VARCHAR(7)
)
RETURNS VARCHAR(100)
AS
BEGIN
	DECLARE @NEW_EMP_CODE CHAR(7);
	
	SELECT @NEW_EMP_CODE = (
		CASE @EMP_CODE
			WHEN '9999999' THEN NEW_CODE
			ELSE @EMP_CODE
		END
	)
	FROM PKG_DETAIL  WITH(NOLOCK) WHERE PRO_CODE = @PRO_CODE

	RETURN @NEW_EMP_CODE
END
GO
