USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[FN_RES_FIT_GET_TOTAL_PRICE]
(
	@GRP_RES_CODE	VARCHAR(20),
	@FLAG			INT
)
RETURNS INT
AS
BEGIN

	DECLARE @TOT_PRICE INT

	-- TOT_PRICE는 판매액
	-- PAY_PRICE는 입금액

	SELECT @TOT_PRICE = (SUM_SALE_PRICE - SUM_DC_PRICE + SUM_CHG_PRICE + SUM_TAX_PRICE + SUM_PENALTY_PRICE)
	FROM (
		SELECT
			ISNULL(SUM(SALE_PRICE), 0) AS [SUM_SALE_PRICE],
			ISNULL(SUM(CHG_PRICE), 0) AS [SUM_CHG_PRICE],
			ISNULL(SUM(DC_PRICE), 0) AS [SUM_DC_PRICE],
			ISNULL(SUM(TAX_PRICE), 0) AS [SUM_TAX_PRICE],
			ISNULL(SUM(PENALTY_PRICE), 0) AS [SUM_PENALTY_PRICE]
		FROM RES_CUSTOMER_DAMO WITH(NOLOCK) 
		WHERE RES_CODE IN (SELECT RES_CODE FROM RES_MASTER_DAMO WITH(NOLOCK)  WHERE GRP_RES_CODE = @GRP_RES_CODE 
							AND PRO_TYPE = CASE @FLAG WHEN 0 THEN PRO_TYPE ELSE @FLAG END)
		AND RES_STATE IN (0, 3, 4) -- 예약, 환불, 페널티
	) A

	RETURN (@TOT_PRICE)

END
GO
