USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[FN_PRO_GET_TEAM_NAME]
(
	@PRO_CODE VARCHAR(20)
)
RETURNS VARCHAR(50)
AS
BEGIN

	DECLARE @TEAM_NAME VARCHAR(50)

	SELECT @TEAM_NAME = ET.TEAM_NAME FROM 
	PKG_DETAIL PD WITH(NOLOCK)
	INNER JOIN EMP_MASTER_damo EMD WITH(NOLOCK)
	ON PD.NEW_CODE = EMD.EMP_CODE
	INNER JOIN EMP_TEAM ET WITH(NOLOCK)
	ON EMD.TEAM_CODE = ET.TEAM_CODE
	WHERE PD.PRO_CODE = @PRO_CODE

	RETURN (@TEAM_NAME)

END
GO
