USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


/*
2014-02-17 분을 시간타입  문자열 HH:mm 으로 변환 
*/
CREATE FUNCTION [dbo].[FN_GET_TIME_BY_MINUTE]
(
	@MINUTE INT
)
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @TIME_STRING CHAR(5)
	
	DECLARE @TIME_HOUR VARCHAR(2)
	DECLARE @TIME_MINUTE VARCHAR(2)
	SELECT @TIME_HOUR = CONVERT(INT,FLOOR((@MINUTE * 1.0) / 60.0))
	IF(LEN(@TIME_HOUR) = 1 )
	BEGIN
		SET @TIME_HOUR = '0' + @TIME_HOUR
	END 
	SELECT @TIME_MINUTE = CONVERT(INT, (@MINUTE * 1.0) % 60.0)
	IF(LEN(@TIME_MINUTE) = 1 )
	BEGIN
		SET @TIME_MINUTE = '0' + @TIME_MINUTE
	END 

	RETURN @TIME_HOUR +':'+@TIME_MINUTE 
END



GO
