USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
생성일 : 2011-05-06 
설  명 : 예약의 최종결제일 
 제휴사용 AGENT 조회 화면에서 사용
BizReserve.GetReserveListAgent()
*/
CREATE FUNCTION [dbo].[FN_RES_GET_LAST_PAY_DATE]
(
	@RES_CODE VARCHAR(20)
)
RETURNS DATETIME
AS
BEGIN

	DECLARE @PAY_DATE DATETIME 

	SELECT @PAY_DATE = (
		SELECT TOP 1 NEW_DATE
		FROM PAY_MATCHING WITH(NOLOCK)
		WHERE RES_CODE = @RES_CODE
		AND CXL_YN = 'N'  --취소되지 않은 결제 내역 
		ORDER BY PAY_SEQ DESC , MCH_SEQ DESC 
	)

	RETURN (@PAY_DATE)
END
GO
