USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [dbo].[FN_DSR_GET_MATCHING_DEPARTURE]
(	
	-- Add the parameters for the function here
	@DEP_DATE DATETIME,
	@ENG_NAME VARCHAR(100)
)
RETURNS @RESERVE_TABLE TABLE 
(
	RES_CODE	VARCHAR(20),
	SEQ_NO		INT
)
AS
BEGIN

	DECLARE @COUNT INT

	SELECT @COUNT = COUNT(*) FROM SET_AIR_CUSTOMER A WITH (NOLOCK)
	INNER JOIN RES_CUSTOMER C  WITH (NOLOCK) ON C.RES_CODE = A.RES_CODE AND C.SEQ_NO = A.RES_SEQ_NO
	WHERE A.PRO_CODE IN 
	(
		SELECT X.PRO_CODE FROM PKG_DETAIL X WITH (NOLOCK)
		INNER JOIN SET_MASTER Y WITH (NOLOCK) ON Y.PRO_CODE = X.PRO_CODE
		WHERE X.DEP_DATE >= @DEP_DATE AND X.DEP_DATE < @DEP_DATE + 1
	)
	AND 
	C.RES_STATE NOT IN (1,2) AND
	(
		DBO.FN_AIR_GET_PAX_NAME(ISNULL(C.LAST_NAME, '') + ISNULL(C.FIRST_NAME, '')) = DBO.FN_AIR_GET_PAX_NAME(ISNULL(@ENG_NAME, ''))
		OR
		DBO.FN_AIR_GET_PAX_NAME(ISNULL(C.FIRST_NAME, '') + ISNULL(C.LAST_NAME, '')) = DBO.FN_AIR_GET_PAX_NAME(ISNULL(@ENG_NAME, ''))
	)

	IF @COUNT IS NULL 
	BEGIN
		RETURN
	END
	ELSE IF @COUNT > 1 OR @COUNT = 0
	BEGIN
		RETURN
	END
	ELSE BEGIN

		INSERT INTO @RESERVE_TABLE(RES_CODE, SEQ_NO)
		SELECT C.RES_CODE, C.SEQ_NO FROM SET_AIR_CUSTOMER A WITH (NOLOCK)
		INNER JOIN RES_CUSTOMER C WITH (NOLOCK) ON C.RES_CODE = A.RES_CODE AND C.SEQ_NO = A.RES_SEQ_NO
		WHERE A.PRO_CODE IN 
		(
			SELECT X.PRO_CODE FROM PKG_DETAIL X WITH (NOLOCK)
			INNER JOIN SET_MASTER Y WITH (NOLOCK) ON Y.PRO_CODE = X.PRO_CODE
			WHERE X.DEP_DATE >= @DEP_DATE AND X.DEP_DATE < @DEP_DATE + 1
		)
		AND 
		C.RES_STATE NOT IN (1,2) AND
		(
			DBO.FN_AIR_GET_PAX_NAME(ISNULL(C.LAST_NAME, '') + ISNULL(C.FIRST_NAME, '')) = DBO.FN_AIR_GET_PAX_NAME(ISNULL(@ENG_NAME, ''))
			OR
			DBO.FN_AIR_GET_PAX_NAME(ISNULL(C.FIRST_NAME, '') + ISNULL(C.LAST_NAME, '')) = DBO.FN_AIR_GET_PAX_NAME(ISNULL(@ENG_NAME, ''))
		)
		ORDER BY RES_CODE, SEQ_NO
	END

	RETURN 
END



GO
