USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[FN_RES_GET_TOTAL_PRICE_ONE]
(
	@RES_CODE VARCHAR(20),
	@SEQ_NO INT
)
RETURNS INT
AS
BEGIN

	DECLARE @TOT_PRICE INT

	-- TOT_PRICE는 판매액
	-- PAY_PRICE는 입금액
	
	SELECT @TOT_PRICE = (ISNULL(SALE_PRICE, 0) - ISNULL(DC_PRICE, 0) + ISNULL(CHG_PRICE, 0) + ISNULL(TAX_PRICE, 0) + ISNULL(PENALTY_PRICE, 0))
	FROM RES_CUSTOMER_DAMO WITH(NOLOCK) 
	WHERE RES_CODE = @RES_CODE AND SEQ_NO = @SEQ_NO

	--SELECT @TOT_PRICE = (SUM_SALE_PRICE - SUM_DC_PRICE + SUM_CHG_PRICE + SUM_TAX_PRICE + SUM_PENALTY_PRICE)
	--FROM (
	--	SELECT
	--		ISNULL(SUM(SALE_PRICE), 0) AS [SUM_SALE_PRICE],
	--		ISNULL(SUM(CHG_PRICE), 0) AS [SUM_CHG_PRICE],
	--		ISNULL(SUM(DC_PRICE), 0) AS [SUM_DC_PRICE],
	--		ISNULL(SUM(TAX_PRICE), 0) AS [SUM_TAX_PRICE],
	--		ISNULL(SUM(PENALTY_PRICE), 0) AS [SUM_PENALTY_PRICE]
	--	FROM RES_CUSTOMER
	--	WHERE RES_CODE = @RES_CODE and SEQ_NO = @SEQ_NO
	--) A

	RETURN (@TOT_PRICE)

END
GO
