USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[FN_PRO_GET_PAY_STATE]
(
	@PRO_CODE VARCHAR(20)
)
RETURNS INT
AS
BEGIN

	DECLARE @TOT_PRICE DECIMAL, @PAY_PRICE DECIMAL, @PAY_STATE INT

	-- TOT_PRICE는 판매액
	SELECT @TOT_PRICE = DBO.FN_PRO_GET_TOTAL_PRICE(@PRO_CODE)

	-- PAY_PRICE는 입금액
	SELECT @PAY_PRICE = DBO.FN_PRO_GET_PAY_PRICE(@PRO_CODE)

	SELECT @PAY_STATE = (
		CASE
			WHEN @PAY_PRICE = 0.0 THEN 0				-- 미납
			WHEN @TOT_PRICE > @PAY_PRICE THEN 1		-- 부분납
			WHEN @TOT_PRICE = @PAY_PRICE THEN 2		-- 완납
			WHEN @TOT_PRICE < @PAY_PRICE THEN 3		-- 과납
		END
	)

	RETURN (@PAY_STATE)

END
GO
