USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[V_NVTESTUSER] (
    USER_ID, SEQ_NO, CAMPAIGN_NO, CAMPAIGN_TYPE,
    TESTRECEIVER_EMAIL, TESTRECEIVER_TEL, TESTRECEIVER_FAX, TESTRECEIVER_NM
) AS
SELECT
    U.USER_ID, U.SEQ_NO, U.CAMPAIGN_NO, U.CAMPAIGN_TYPE,
    P.TESTRECEIVER_EMAIL, P.TESTRECEIVER_TEL, P.TESTRECEIVER_FAX, P.TESTRECEIVER_NM
FROM NVTESTUSER U, NVTESTUSERPOOL P
WHERE U.USER_ID = P.USER_ID
AND U.SEQ_NO = P.SEQ_NO;
GO
