USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- SMS 리포트 전송 성공자 다운로드
CREATE VIEW [dbo].[V_SMS_SUCCESS_FILE_LOG] (
    TRAN_ID, TRAN_PHONE, TRAN_DATE, TRAN_RSLT, SERVICE_TYPE, TRAN_STATUS, TRAN_MSG, TRAN_CALLBACK,
    SERVICE_NO, RESULT_SEQ, SLOT1, SLOT2, TRAN_TYPE, REQ_USER_ID, SEQ, REQ_DEPT_ID
) AS
SELECT
    TRAN_ID, TRAN_PHONE, TRAN_DATE, TRAN_RSLT, SERVICE_TYPE, TRAN_STATUS, TRAN_MSG, TRAN_CALLBACK,
    SERVICE_NO, RESULT_SEQ, SLOT1, SLOT2, TRAN_ETC3 AS TRAN_TYPE, REQ_USER_ID, SEQ, REQ_DEPT_ID
FROM EM_LOG
WHERE TRAN_RSLT = '0'
GO
