USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE view [dbo].[EMP_TEAM_ACC] ( [ACC_SEQ], [TEAM_CODE], [ACC_NAME], [ACC_HOLDER], [BANK_NAME], [SORT_NUM], [NEW_CODE], [NEW_DATE], [EDT_CODE], [EDT_DATE], [DEL_YN], [ACC_NUM] )  as select  [ACC_SEQ], [TEAM_CODE], [ACC_NAME], [ACC_HOLDER], [BANK_NAME], [SORT_NUM], [NEW_CODE], [NEW_DATE], [EDT_CODE], [EDT_DATE], [DEL_YN], [ACC_NUM]  from [dbo].[EMP_TEAM_ACC_root] 
GO
