USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VIEW_AIRPORT] AS
SELECT 
	D.AIRPORT_CODE,
	D.KOR_NAME AS AIRPORT_NAME,
	A.CITY_CODE,
	A.KOR_NAME AS CITY_NAME,
	B.NATION_CODE,
	B.KOR_NAME AS NATION_NAME,
	C.REGION_CODE,
	C.KOR_NAME AS REGION_NAME
FROM 
	PUB_CITY A 
INNER JOIN PUB_NATION B ON B.NATION_CODE = A.NATION_CODE
INNER JOIN PUB_REGION C ON C.REGION_CODE = B.REGION_CODE
INNER JOIN PUB_AIRPORT D ON D.CITY_CODE = A.CITY_CODE;
GO
