USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
  create view [dbo].[PAY_CASH_RECEIPT_root] (  [RECEIPT_NO] , [RES_CODE] , [CUS_NO] , [CUS_NAME] , [SOC_NUM1] , [NOR_TEL1] , [NOR_TEL2] , [NOR_TEL3] , [CPN_NUM1] , [CPN_NUM2] , [CPN_NUM3] , [TARGET_USE] , [TARGET_PRICE] , [APPROVAL_NO] , [APPROVAL_SEQ] , [REPLY_CODER] , [APPROVAL_DATE] , [RECEIPT_STATE] , [REMARK] , [NEW_CODE] , [NEW_DATE] , [EDT_CODE] , [EDT_DATE] , [SOC_NUM2] , [AGT_CODE] , [CXL_REPLY_CODER] , [CXL_CODE] , [CXL_DATE] , [CXL_REMARK] , [CXL_TYPE] , [PG_NO] , [RECEIPT_TYPE]  ) as select   [RECEIPT_NO], [RES_CODE], [CUS_NO], [CUS_NAME], [SOC_NUM1], [NOR_TEL1], [NOR_TEL2], [NOR_TEL3], [CPN_NUM1], [CPN_NUM2], [CPN_NUM3], [TARGET_USE], [TARGET_PRICE], [APPROVAL_NO], [APPROVAL_SEQ], [REPLY_CODER], [APPROVAL_DATE], [RECEIPT_STATE], [REMARK], [NEW_CODE], [NEW_DATE], [EDT_CODE], [EDT_DATE],convert(varchar(7), damo.[dbo].[damo_decrypt_Diablo_PAY_CASH_RECEIPT_SOC_NUM2_6D52FFD5A971AFEB5728601DDE0B4D34558754AA]('Diablo','dbo.PAY_CASH_RECEIPT','SOC_NUM2', [sec_SOC_NUM2] ,'I')) COLLATE Korean_Wansung_CI_AS , [AGT_CODE], [CXL_REPLY_CODER], [CXL_CODE], [CXL_DATE], [CXL_REMARK], [CXL_TYPE], [PG_NO], [RECEIPT_TYPE]   from [dbo].[PAY_CASH_RECEIPT_damo] 
GO
