USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
  create view [dbo].[EDI_MASTER_root] (  [EDI_CODE] , [DOC_TYPE] , [DETAIL_TYPE] , [DETAIL_NAME] , [EDI_STATUS] , [REF_CODE] , [RCV_TEAM_CODE] , [APP_TYPE] , [SUBJECT] , [CONTENTS] , [FILE1] , [FILE2] , [FILE3] , [OFF_DOCUMENT] , [JOIN_DATE] , [OUT_DATE] , [VAC_DAY] , [PRICE] , [CURRENCY] , [EXC_RATE] , [PAY_BANK] , [PAY_RECEIPT] , [TERM_PAYMENT] , [RCV_CODE] , [RCV_YN] , [RCV_DATE] , [RCV_REMARK] , [VIEW_YN] , [NEW_CODE] , [NEW_NAME] , [NEW_TEAM_NAME] , [NEW_DUTY_NAME] , [NEW_POS_NAME] , [NEW_DATE] , [BIRTH_DATE] , [PRO_CODE] , [MASTER_CODE] , [PRO_TYPE] , [REAL_PRICE] , [RES_CODE] , [AGT_CODE] , [PAY_SEQ] , [FOLDER_TYPE] , [PAY_ACCOUNT] , row_id ) as select   [EDI_CODE], [DOC_TYPE], [DETAIL_TYPE], [DETAIL_NAME], [EDI_STATUS], [REF_CODE], [RCV_TEAM_CODE], [APP_TYPE], [SUBJECT], [CONTENTS], [FILE1], [FILE2], [FILE3], [OFF_DOCUMENT], [JOIN_DATE], [OUT_DATE], [VAC_DAY], [PRICE], [CURRENCY], [EXC_RATE], [PAY_BANK], [PAY_RECEIPT], [TERM_PAYMENT], [RCV_CODE], [RCV_YN], [RCV_DATE], [RCV_REMARK], [VIEW_YN], [NEW_CODE], [NEW_NAME], [NEW_TEAM_NAME], [NEW_DUTY_NAME], [NEW_POS_NAME], [NEW_DATE], [BIRTH_DATE], [PRO_CODE], [MASTER_CODE], [PRO_TYPE], [REAL_PRICE], [RES_CODE], [AGT_CODE], [PAY_SEQ], [FOLDER_TYPE],convert(varchar(20), damo.[dbo].[damo_decrypt_Diablo_EDI_MASTER_PAY_ACCOUNT_E0A791B75ECF59F15544F8990DF9883E4E742D3E]('Diablo','dbo.EDI_MASTER','PAY_ACCOUNT', [sec_PAY_ACCOUNT] ,'I')) COLLATE Korean_Wansung_CI_AS  , row_id  from [dbo].[EDI_MASTER_damo] 
GO
