USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
좌석관리 한눈에 볼수 있는 뷰 


*/

CREATE VIEW [dbo].[VIEW_PRO_TRANS_SEAT]
AS

SELECT   
	A.SEAT_CODE,
	CONVERT(VARCHAR(10),DEP_DEP_DATE ,121) AS DEP_DT ,  
	CONVERT(VARCHAR(10),ARR_ARR_DATE ,121) AS ARR_DT ,  
	DATEDIFF(D,DEP_DEP_DATE,ARR_ARR_DATE) + 1 AS TOT_DAY ,
	DATEPART(W,DEP_DEP_DATE) AS DEP_WK , 

	DEP_TRANS_CODE + RTRIM(DEP_TRANS_NUMBER) AS DEP_TRAN , 
	DEP_DEP_AIRPORT_CODE +'-'+DEP_ARR_AIRPORT_CODE AS DEP_AIR,
	CONVERT(VARCHAR(10),DEP_DEP_DATE ,121) + ' ' +  DEP_DEP_TIME AS DEP_DEP_DT,
	CONVERT(VARCHAR(10),DEP_ARR_DATE ,121) + ' ' +  DEP_ARR_TIME AS DEP_ARR_DT,
	DATEDIFF(D,DEP_DEP_DATE,DEP_ARR_DATE) AS DEP_DF,
	DEP_SPEND_TIME AS DEP_TM,

	ARR_TRANS_CODE + RTRIM(ARR_TRANS_NUMBER) AS ARR_TRAN , 
	ARR_DEP_AIRPORT_CODE +'-'+ARR_ARR_AIRPORT_CODE AS ARR_AIR,
	CONVERT(VARCHAR(10),ARR_DEP_DATE ,121) + ' ' +  ARR_DEP_TIME AS ARR_DEP_DT,
	CONVERT(VARCHAR(10),ARR_ARR_DATE ,121) + ' ' +  ARR_ARR_TIME AS ARR_ARR_DT,
	DATEDIFF(D,ARR_DEP_DATE,ARR_ARR_DATE) AS ARR_DF,
	ARR_SPEND_TIME AS ARR_TM,
	FARE_SEAT_TYPE AS SEAT , 

	(SELECT COUNT(*) FROM PRO_TRANS_SEAT_SEGMENT  WITH(NOLOCK) WHERE SEAT_CODE = A.SEAT_CODE  AND TRANS_SEQ = 1 ) AS DEP_SEG,
	(SELECT COUNT(*) FROM PRO_TRANS_SEAT_SEGMENT  WITH(NOLOCK) WHERE SEAT_CODE = A.SEAT_CODE  AND TRANS_SEQ = 2 ) AS ARR_SEG,



	DEP_TRANS_CODE + RTRIM(DEP_TRANS_NUMBER) +'-'+ ARR_TRANS_CODE + RTRIM(ARR_TRANS_NUMBER)  + '_' 
	+ DEP_DEP_AIRPORT_CODE+'-'+ DEP_ARR_AIRPORT_CODE + '/'+ ARR_DEP_AIRPORT_CODE+'-'+ ARR_ARR_AIRPORT_CODE + '_' 
	+ CONVERT( VARCHAR,DATEDIFF(D,DEP_DEP_DATE,ARR_ARR_DATE) + 1 ) +'D'      

	+'[+' + CONVERT(VARCHAR,DATEDIFF(D,DEP_DEP_DATE,DEP_ARR_DATE))  +',+' + CONVERT(VARCHAR,DATEDIFF(D,ARR_DEP_DATE,ARR_ARR_DATE)) + ']' AS SEAT_GROUP , 

	(SELECT TOP 1 PRO_CODE FROM PKG_DETAIL WITH(NOLOCK) WHERE DEP_DATE = A.DEP_DEP_DATE AND SEAT_CODE = A.SEAT_CODE ) AS FIRST_PRO_CODE ,
	(SELECT COUNT(*) FROM PKG_DETAIL WITH(NOLOCK) WHERE DEP_DATE = A.DEP_DEP_DATE AND SEAT_CODE = A.SEAT_CODE ) AS USE_PRO_CNT,
	
	A.NEW_DATE,
	A.EDT_DATE,

DEP_DEP_DATE,
ARR_ARR_DATE,
DEP_TRANS_CODE, 
DEP_TRANS_NUMBER,
ARR_TRANS_CODE,
ARR_TRANS_NUMBER,
DEP_DEP_AIRPORT_CODE,
DEP_ARR_AIRPORT_CODE,
ARR_DEP_AIRPORT_CODE,
ARR_ARR_AIRPORT_CODE


	FROM PRO_TRANS_SEAT A
	--WHERE 1=1
	--AND DEP_DEP_DATE >= '2018-01-01'  -- 과거 좌석 안나오게 

	--AND DEP_TRANS_CODE = 'EY'
	--AND DEP_TRANS_NUMBER = '873'
	--AND ARR_TRANS_CODE = 'EY'
	--AND ARR_TRANS_NUMBER  IN (  '090' , '876' )  
	----AND DEP_ARR_AIRPORT_CODE  IN (  '090' , '876' )  
	----AND DEP_ARR_AIRPORT_CODE  IN (  'DBX' )  
	--AND DEP_DEP_DATE >= '2019-05-01' 
	----AND DEP_DEP_DATE >= '2019-06-01' 
	--AND DEP_DEP_DATE < '2020-07-01' 
	--AND ARR_ARR_DATE = DATEADD(D,8,DEP_DEP_DATE)  -- 9일패턴  

	--ORDER BY A.DEP_DEP_DATE 
	--, A.ARR_ARR_DATE
	--, A.DEP_TRANS_CODE
	--, A.DEP_TRANS_NUMBER

	--, A.ARR_TRANS_CODE
	--, A.ARR_TRANS_NUMBER

	--, A.DEP_ARR_AIRPORT_CODE
	--, A.ARR_ARR_AIRPORT_CODE

	--, A.SEAT_CODE 



GO
