USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE view [dbo].[PAY_CASH_RECEIPT_OLD] ( [RECEIPT_NO], [GROUP_NO], [REQ_NO], [REQ_VER], [PAY_SEQ], [MCH_SEQ], [RES_CODE], [SOC_NUM1], [NOR_TEL1], [NOR_TEL2], [NOR_TEL3], [TARGET_PRICE], [STATUS_TYPE], [NEW_CODE], [REQ_COMMENT], [MNG_CODE], [MNG_COMMENT], [NEW_DATE], [EDT_DATE], [REMARK], [SOC_NUM2] )  as select  [RECEIPT_NO], [GROUP_NO], [REQ_NO], [REQ_VER], [PAY_SEQ], [MCH_SEQ], [RES_CODE], [SOC_NUM1], [NOR_TEL1], [NOR_TEL2], [NOR_TEL3], [TARGET_PRICE], [STATUS_TYPE], [NEW_CODE], [REQ_COMMENT], [MNG_CODE], [MNG_COMMENT], [NEW_DATE], [EDT_DATE], [REMARK], [SOC_NUM2]  from [dbo].[PAY_CASH_RECEIPT_OLD_root] 
GO
