USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[VIEW_EMP_MASTER] AS

SELECT
	EMP_CODE, KOR_NAME, ENG_FIRST_NAME, ENG_LAST_NAME, SOC_NUMBER1, damo.dbo.dec_varchar('DIABLO','dbo.EMP_MASTER','SOC_NUMBER2', A.SEC_SOC_NUMBER2) AS SOC_NUMBER2, GENDER, PASSWORD, TEAM_CODE
	, GROUP_CODE, WORK_TYPE, DUTY_TYPE, POS_TYPE, JOIN_TYPE, JOIN_DATE, OUT_DATE, EMAIL, EMAIL_PASSWORD, MESSENGER
	, INNER_NUMBER1, INNER_NUMBER2, INNER_NUMBER3, ZIP_CODE, ADDRESS1, ADDRESS2, TEL_NUMBER1, TEL_NUMBER2, TEL_NUMBER3
	, HP_NUMBER1, HP_NUMBER2, HP_NUMBER3, FAX_NUMBER1, FAX_NUMBER2, FAX_NUMBER3, GREETING, PASSPORT, PASS_EXPIRE_DATE
	, NEW_CODE, NEW_DATE, EDT_CODE, EDT_DATE, BIRTH_DATE, SALARY_CLASS, MATE_NUMBER, GROUP_TYPE, ACC_OUT_YN
	, (SELECT TEAM_NAME FROM EMP_TEAM with(nolock) WHERE TEAM_CODE = A.TEAM_CODE) AS [TEAM_NAME]
FROM EMP_MASTER_damo A with(nolock)
UNION ALL
SELECT
	MEM_CODE, KOR_NAME, ENG_LAST_NAME, ENG_FIRST_NAME, NULL, NULL, 'M', PASSWORD, AGT_CODE
	, MEM_TYPE, WORK_TYPE, 1, 1, 1, NULL, NULL, EMAIL, NULL, NULL
	, TEL_NUMBER1, TEL_NUMBER2, TEL_NUMBER3, ZIP_CODE, ADDRESS1, ADDRESS2, TEL_NUMBER1, TEL_NUMBER2, TEL_NUMBER3
	, HP_NUMBER1, HP_NUMBER2, HP_NUMBER3, NULL, NULL, NULL, NULL, NULL, NULL
	, NEW_CODE, NEW_DATE, EDT_CODE, EDT_DATE, NULL, NULL, NULL, NULL, NULL
	, (SELECT KOR_NAME FROM AGT_MASTER with(nolock) WHERE AGT_CODE = A.AGT_CODE)
FROM AGT_MEMBER A with(nolock)



GO
