USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
  create view [dbo].[EVT_LOTTE_COUPON_root] (  [REQ_NO] , [RES_CODE] , [SEQ_NO] , [CUS_NO] , [ISSUE_YN] , [ISSUE_PRICE] , [ACC_PRICE] , [ISSUE_TYPE] , [ISSUER_CODE] , [ISSUE_DATE] , [NEW_CODE] , [NEW_DATE] , [EDT_CODE] , [EDT_DATE] , [REMARK] , [PASS_NUM]  ) as select   [REQ_NO], [RES_CODE], [SEQ_NO], [CUS_NO], [ISSUE_YN], [ISSUE_PRICE], [ACC_PRICE], [ISSUE_TYPE], [ISSUER_CODE], [ISSUE_DATE], [NEW_CODE], [NEW_DATE], [EDT_CODE], [EDT_DATE], [REMARK],convert(varchar(20), damo.[dbo].[damo_decrypt_Diablo_EVT_LOTTE_COUPON_PASS_NUM_6F93143FCB4115EDB47688695F078C28FAD0DD49]('Diablo','dbo.EVT_LOTTE_COUPON','PASS_NUM', [sec_PASS_NUM] ,'I')) COLLATE Korean_Wansung_CI_AS    from [dbo].[EVT_LOTTE_COUPON_damo] 
GO
