USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE view [dbo].[EVT_LOTTE] ( [EVT_NO], [CUS_NAME], [SOC_NUM1], [NOR_TEL1], [NOR_TEL2], [NOR_TEL3], [PASS_NUM], [EMAIL], [ZIP_CODE], [ADDRESS1], [ADDRESS2], [NEW_CODE], [NEW_DATE], [SOC_NUM2] )  as select  [EVT_NO], [CUS_NAME], [SOC_NUM1], [NOR_TEL1], [NOR_TEL2], [NOR_TEL3], [PASS_NUM], [EMAIL], [ZIP_CODE], [ADDRESS1], [ADDRESS2], [NEW_CODE], [NEW_DATE], [SOC_NUM2]  from [dbo].[EVT_LOTTE_root] 
GO
