USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE view [dbo].[PPT_MASTER_LOG] ( [RES_CODE], [PPT_NO], [LAST_NAME], [FIRST_NAME], [GENDER], [BIRTH_DATE], [PASS_ISSUE], [PASS_EXPIRE], [PASS_NUM], [KOR_NAME] )  as select  [RES_CODE], [PPT_NO], [LAST_NAME], [FIRST_NAME], [GENDER], [BIRTH_DATE], [PASS_ISSUE], [PASS_EXPIRE], [PASS_NUM], [KOR_NAME]  from [dbo].[PPT_MASTER_LOG_root] 
GO
