USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE view [dbo].[EVT_LOTTE_COUPON] ( [REQ_NO], [RES_CODE], [SEQ_NO], [CUS_NO], [ISSUE_YN], [ISSUE_PRICE], [ACC_PRICE], [ISSUE_TYPE], [ISSUER_CODE], [ISSUE_DATE], [NEW_CODE], [NEW_DATE], [EDT_CODE], [EDT_DATE], [REMARK], [PASS_NUM] )  as select  [REQ_NO], [RES_CODE], [SEQ_NO], [CUS_NO], [ISSUE_YN], [ISSUE_PRICE], [ACC_PRICE], [ISSUE_TYPE], [ISSUER_CODE], [ISSUE_DATE], [NEW_CODE], [NEW_DATE], [EDT_CODE], [EDT_DATE], [REMARK], [PASS_NUM]  from [dbo].[EVT_LOTTE_COUPON_root] 
GO
