USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_PROM_SUB](
	[SUB_NO] [int] NOT NULL,
	[PRM_NO] [int] NULL,
	[TAB_NO] [int] NULL,
	[HOTEL_CODE] [int] NULL,
	[HOTEL_DESC] [varchar](max) NULL,
	[SORT_ORDER] [int] NULL,
	[CREATE_USER] [varchar](30) NULL,
	[CREATE_DATE] [datetime] NULL,
	[UPDATE_USER] [varchar](30) NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_HTL_PROM_SUB] PRIMARY KEY CLUSTERED 
(
	[SUB_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
