USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_CODE_ZONE](
	[ZONE_CODE] [int] NOT NULL,
	[ZONE_NAME] [varchar](200) NULL,
	[CITY_CODE] [bigint] NOT NULL,
	[MIN_LAT] [decimal](18, 10) NULL,
	[MIN_LNG] [decimal](18, 10) NULL,
	[MAX_LAT] [decimal](18, 10) NULL,
	[MAX_LNG] [decimal](18, 10) NULL,
	[COORD] [varchar](8000) NULL,
	[USE_YN] [varchar](1) NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[CREATE_USER] [varchar](30) NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
	[UPDATE_USER] [varchar](30) NOT NULL,
 CONSTRAINT [PK_HTL_CODE_ZONE] PRIMARY KEY CLUSTERED 
(
	[ZONE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
