USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COM_BOARD_MAST](
	[BD_NO] [int] NOT NULL,
	[BD_TYPE] [varchar](4) NULL,
	[TITLE] [varchar](300) NULL,
	[CONTENTS] [varchar](max) NULL,
	[VIEW_CNT] [int] NULL,
	[DEPTH1] [int] NULL,
	[DEPTH2] [int] NULL,
	[DEPTH3] [int] NULL,
	[TOP_YN] [varchar](1) NULL,
	[USE_YN] [varchar](1) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER] [varchar](30) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER] [varchar](30) NULL,
 CONSTRAINT [PK_COM_BOARD_MAST] PRIMARY KEY CLUSTERED 
(
	[BD_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
