USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_INQUIRY](
	[INQUIRY_NO] [int] NOT NULL,
	[INQUIRY_TYPE] [varchar](1) NOT NULL,
	[MCPN_CODE] [varchar](6) NULL,
	[INQUIRY_TITLE] [varchar](300) NULL,
	[INQUIRY_USER_NAME] [varchar](50) NULL,
	[INQUIRY_EMAIL] [varchar](100) NULL,
	[INQUIRY_PASS] [varchar](50) NULL,
	[INQUIRY_DESC] [varchar](max) NULL,
	[INQUIRY_REPLY] [varchar](max) NULL,
	[INQUIRY_STATUS] [varchar](4) NULL,
	[INQUIRY_DATE] [datetime] NULL,
	[INQUIRY_USER] [varchar](50) NULL,
	[INQUIRY_REPLY_DATE] [datetime] NULL,
	[INQUIRY_REPLY_USER] [varchar](50) NULL,
 CONSTRAINT [PK_TBL_INQUIRY] PRIMARY KEY CLUSTERED 
(
	[INQUIRY_NO] ASC,
	[INQUIRY_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
