USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_FAC_CODE](
	[FAC_TYPE] [varchar](10) NOT NULL,
	[FAC_GROUP] [varchar](10) NULL,
	[FAC_VALUE] [varchar](100) NULL,
 CONSTRAINT [PK_HTL_FAC_CODE] PRIMARY KEY CLUSTERED 
(
	[FAC_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
