USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_RESV_CXL](
	[RESV_NO] [int] NOT NULL,
	[SEQ_NO] [smallint] NOT NULL,
	[CX_REF] [varchar](10) NOT NULL,
	[CX_DATE_FROM] [datetime] NULL,
	[CX_DATE_TO] [datetime] NULL,
	[CX_TYPE] [varchar](30) NULL,
	[CX_VALUE] [nvarchar](4000) NULL,
 CONSTRAINT [PK_HTL_RESV_CXL] PRIMARY KEY CLUSTERED 
(
	[RESV_NO] ASC,
	[SEQ_NO] ASC,
	[CX_REF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
