USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_INFO_LANDMARK](
	[HOTEL_CODE] [int] NOT NULL,
	[MARK_CODE] [int] NOT NULL,
	[DISTANCE] [varchar](20) NULL,
 CONSTRAINT [PK_HTL_INFO_LANDMARK] PRIMARY KEY CLUSTERED 
(
	[HOTEL_CODE] ASC,
	[MARK_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
