USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_INFO_MAST_FAC](
	[HOTEL_CODE] [int] NOT NULL,
	[FAC_TYPE] [varchar](100) NOT NULL,
	[FAC_GROUP] [varchar](2) NULL,
	[FAC_VALUE] [varchar](500) NULL,
	[CREATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_HTL_INFO_MAST_FAC] PRIMARY KEY CLUSTERED 
(
	[HOTEL_CODE] ASC,
	[FAC_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HTL_INFO_MAST_FAC] ADD  CONSTRAINT [DF_HTL_INFO_MAST_FAC_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO
