USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_DOM_INFO_CXL_SUB](
	[CX_SEQ] [int] NOT NULL,
	[CX_DAY] [smallint] NOT NULL,
	[NET_RATE] [int] NULL,
	[SALE_RATE] [int] NULL,
	[CREATE_USER] [varchar](30) NULL,
	[CREATE_DATE] [datetime] NULL,
	[UPDATE_USER] [varchar](30) NULL,
	[UPDATE_DATE] [datetime] NULL
) ON [PRIMARY]
GO
