USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_LOCAL_ROOM](
	[ROOM_SEQ] [int] IDENTITY(1,1) NOT NULL,
	[HOTEL_CODE] [int] NOT NULL,
	[ROOM_TYPE_NAME] [varchar](500) NULL,
	[ROOM_TYPE_EN_NAME] [varchar](500) NULL,
	[ROOM_DESC] [varchar](2000) NULL,
	[PROMO_DESC] [varchar](500) NULL,
	[ADULT_CNT] [int] NULL,
	[CHILD_CNT] [int] NULL,
	[BED_CNT] [int] NOT NULL,
	[EXTRA_BED_CNT] [int] NULL,
	[MEAL_TYPE] [varchar](2) NULL,
	[USE_YN] [varchar](1) NULL,
	[SORT_ORDER] [int] NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER] [varchar](30) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER] [varchar](30) NULL,
 CONSTRAINT [PK_HTL_LOCAL_ROOM] PRIMARY KEY CLUSTERED 
(
	[ROOM_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
