USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_CODE_SUPPLIER](
	[SUPP_CODE] [varchar](2) NOT NULL,
	[SUPP_NAME] [varchar](200) NULL,
	[SUPP_KOR_NAME] [varchar](200) NULL,
	[STATIC_YN] [varchar](1) NULL,
	[USER_ID] [varchar](50) NULL,
	[USER_ID2] [varchar](50) NULL,
	[PASSWORD] [varchar](50) NULL,
	[ADM_URL] [varchar](200) NULL,
	[SORT_SPEED] [int] NULL,
	[USE_YN] [varchar](1) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER] [varchar](30) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER] [varchar](30) NULL,
	[ACC_ID] [varchar](30) NULL,
	[ACC_BANK] [varchar](10) NULL,
	[ACC_NAME] [varchar](100) NULL,
	[ACC_NO] [varchar](100) NULL,
	[ACC_CODE] [varchar](100) NULL,
 CONSTRAINT [PK_HTL_CODE_SUPPLIER] PRIMARY KEY CLUSTERED 
(
	[SUPP_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
