USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_CODE_RATE](
	[SUPP_CODE] [varchar](4) NOT NULL,
	[NATION_CODE] [varchar](50) NOT NULL,
	[CITY_CODE] [varchar](50) NOT NULL,
	[HOTEL_CODE] [int] NOT NULL,
	[GROSS_YN] [char](1) NULL,
	[GROSS_RATE] [decimal](18, 2) NULL,
	[FIX_RATE] [decimal](18, 2) NULL,
	[CLASS_A] [decimal](18, 2) NULL,
	[CLASS_B] [decimal](18, 2) NULL,
	[CLASS_C] [decimal](18, 2) NULL,
	[CLASS_D] [decimal](18, 2) NULL,
	[CLASS_E] [decimal](18, 2) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER] [varchar](50) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER] [varchar](50) NULL,
 CONSTRAINT [PK_HTL_CODE_RATE] PRIMARY KEY CLUSTERED 
(
	[SUPP_CODE] ASC,
	[NATION_CODE] ASC,
	[CITY_CODE] ASC,
	[HOTEL_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
