USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_CODE_MAST](
	[M_CODE] [varchar](4) NOT NULL,
	[S_CODE] [varchar](20) NOT NULL,
	[CODE_NAME] [varchar](300) NULL,
	[CODE_NAME2] [varchar](300) NULL,
	[CODE_DESC] [varchar](500) NULL,
 CONSTRAINT [PK_HTL_CODE_MAST] PRIMARY KEY CLUSTERED 
(
	[M_CODE] ASC,
	[S_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
