USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_CODE_MARK](
	[MARK_CODE] [int] NOT NULL,
	[MARK_NAME] [varchar](200) NULL,
	[MARK_ENAME] [varchar](200) NULL,
	[LATITUDE] [varchar](20) NULL,
	[LONGITUDE] [varchar](20) NULL,
	[CITY_CODE] [bigint] NOT NULL,
	[ZOOM_LEVEL] [int] NULL,
	[USE_YN] [varchar](1) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER] [varchar](30) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER] [varchar](30) NULL,
 CONSTRAINT [PK_HTL_CODE_MARK] PRIMARY KEY CLUSTERED 
(
	[MARK_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
