USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PREFERRED_HOTEL](
	[hotel_id] [int] NOT NULL,
	[country_id] [int] NULL,
	[city_id] [int] NULL,
	[create_date] [datetime] NULL,
 CONSTRAINT [PK_PREFERRED_HOTEL] PRIMARY KEY CLUSTERED 
(
	[hotel_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PREFERRED_HOTEL] ADD  CONSTRAINT [DF_PREFERRED_HOTEL_create_date]  DEFAULT (getdate()) FOR [create_date]
GO
