USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_INFO_MAST_ROOM](
	[HOTEL_CODE] [int] NOT NULL,
	[ROOM_CODE] [varchar](100) NOT NULL,
	[ROOM_CAPTION] [varchar](1000) NULL,
	[ROOM_CAPTION_TRANSLATED] [varchar](1000) NULL,
	[ROOM_MAX_OCCUPY] [varchar](100) NULL,
	[ROOM_TOTAL] [varchar](100) NULL,
	[ROOM_SIZE] [varchar](100) NULL,
	[ROOM_TERRACE] [varchar](100) NULL,
	[ROOM_VIEW] [varchar](100) NULL,
	[ROOM_EXTRABEDS] [varchar](100) NULL,
	[ROOM_MAX_INFANT] [varchar](100) NULL,
	[ROOM_PICTURE] [varchar](500) NULL,
	[BED_TYPE] [varchar](1000) NULL,
	[ROOM_TYPE_ID] [varchar](100) NULL,
	[ROOM_ALTER_NAME] [varchar](1000) NULL,
	[SHARE_BATH] [varchar](100) NULL,
	[SMOKING] [varchar](100) NULL,
	[GENDER] [varchar](100) NULL,
 CONSTRAINT [PK_HTL_INFO_MAST_ROOM_NEW] PRIMARY KEY CLUSTERED 
(
	[HOTEL_CODE] ASC,
	[ROOM_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
