USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_DOM_INFO_BLOCK_HISTORY](
	[HISTORY_NO] [bigint] IDENTITY(1,1) NOT NULL,
	[PRICE_SEQ] [bigint] NULL,
	[HOTEL_CODE] [varchar](10) NULL,
	[ROOM_CODE] [varchar](10) NULL,
	[CHECK_IN_DATE] [varchar](10) NULL,
	[AVAIL_TYPE] [varchar](2) NULL,
	[HARD_TOTAL] [int] NULL,
	[SOFT_TOTAL] [int] NULL,
	[REQ_TOTAL] [int] NULL,
	[HARD_USED] [int] NULL,
	[SOFT_USED] [int] NULL,
	[REQ_USED] [int] NULL,
	[HARD_REMAIN] [int] NULL,
	[SOFT_REMAIN] [int] NULL,
	[REQ_REMAIN] [int] NULL,
	[ORG_HARD_TOTAL] [int] NULL,
	[ORG_SOFT_TOTAL] [int] NULL,
	[ORG_REQ_TOTAL] [int] NULL,
	[ORG_HARD_USED] [int] NULL,
	[ORG_SOFT_USED] [int] NULL,
	[ORG_REQ_USED] [int] NULL,
	[ORG_HARD_REMAIN] [int] NULL,
	[ORG_SOFT_REMAIN] [int] NULL,
	[ORG_REQ_REMAIN] [int] NULL,
	[RESV_NO] [int] NULL,
	[CREATE_USER] [varchar](30) NULL,
	[CREATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_HTL_DOM_INFO_BLOCK_HISTORY] PRIMARY KEY CLUSTERED 
(
	[HISTORY_NO] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
