USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_RESV_MAST](
	[RESV_NO] [int] IDENTITY(1,1) NOT NULL,
	[SUPP_NO] [varchar](50) NULL,
	[SUPP_CFM_NO] [varchar](300) NULL,
	[SUPP_CODE] [varchar](2) NULL,
	[SUPP_STATUS] [varchar](4) NULL,
	[MCPN_CODE] [varchar](20) NULL,
	[RESV_ID] [varchar](50) NULL,
	[RESV_NAME] [varchar](50) NULL,
	[RESV_PASSWORD] [varchar](50) NULL,
	[RESV_PHONE_MOBILE] [varchar](20) NULL,
	[RESV_PHONE_HOME] [varchar](20) NULL,
	[RESV_EMAIL] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[HOTEL_CODE] [varchar](50) NULL,
	[HOTEL_NAME] [varchar](300) NULL,
	[S_HOTEL_CODE] [varchar](50) NULL,
	[S_HOTEL_NAME] [varchar](300) NULL,
	[CHECK_IN_DATE] [datetime] NULL,
	[CHECK_OUT_DATE] [datetime] NULL,
	[ROOM_CNT] [smallint] NULL,
	[ADULT_CNT] [smallint] NULL,
	[CHILD_CNT] [smallint] NULL,
	[MEAL_YN] [varchar](1) NULL,
	[MEAL_DESC] [varchar](200) NULL,
	[DEAD_LINE] [datetime] NULL,
	[SUPP_DEAD_LINE] [datetime] NULL,
	[NON_REFUND_YN] [varchar](1) NULL,
	[REQ_TEXT] [varchar](4000) NULL,
	[REQ_TEXT_YN] [varchar](1) NULL,
	[LAST_STATUS] [varchar](4) NULL,
	[LAST_UPDATE_USER] [varchar](30) NULL,
	[LAST_UPDATE_DATE] [datetime] NULL,
	[PAY_REQ_DATE] [datetime] NULL,
	[CANCEL_REQ_DATE] [datetime] NULL,
	[CANCEL_DATE] [datetime] NULL,
	[CANCEL_TEXT] [varchar](1000) NULL,
	[CANCEL_USER] [varchar](30) NULL,
	[REF_BANK_CODE] [varchar](5) NULL,
	[REF_BANK_NAME] [varchar](100) NULL,
	[REF_BANK_OWN] [varchar](100) NULL,
	[REF_BANK_ACC] [varchar](100) NULL,
	[ORG_CURRENCY] [varchar](3) NULL,
	[ORG_SUPP_NET] [decimal](13, 5) NULL,
	[ORG_TOTAL_AMT] [decimal](13, 5) NULL,
	[ORG_DSC_RATE] [decimal](13, 5) NULL,
	[ORG_DSC_AMT] [decimal](13, 5) NULL,
	[EX_RATE] [decimal](13, 5) NULL,
	[SUPP_NET] [decimal](18, 0) NULL,
	[TOTAL_AMT] [decimal](18, 0) NULL,
	[ORG_CANCEL_NET] [decimal](18, 5) NULL,
	[CANCEL_NET] [decimal](18, 0) NULL,
	[CANCEL_AMT] [decimal](18, 0) NULL,
	[COM_AMT] [decimal](18, 0) NULL,
	[DSC_COST] [decimal](18, 0) NULL,
	[AFF_COST] [decimal](18, 0) NULL,
	[CARD_COST] [decimal](18, 0) NULL,
	[VAT_COST] [decimal](18, 0) NULL,
	[COUP_COST] [decimal](18, 0) NULL,
	[AIR_COST] [decimal](18, 0) NULL,
	[AVAIL_PARAM] [varchar](4000) NULL,
	[AUTO_VOUCHER] [char](1) NULL,
	[VGT_CODE] [varchar](20) NULL,
	[VGT_NO] [varchar](20) NULL,
	[VGT_USER] [int] NULL,
	[VGT_REMARKS] [varchar](2000) NULL,
	[AUTO_CANCEL] [varchar](1) NULL,
	[MOBILE_YN] [varchar](1) NULL,
	[AFF_NO] [varchar](100) NULL,
	[AFF_ORD_NO] [varchar](100) NULL,
	[CX_CHARGE_YN] [varchar](1) NULL,
	[RESV_RANK] [varchar](10) NULL,
	[CHANNEL] [varchar](10) NULL,
	[CHRG_USER] [varchar](30) NULL,
	[CLOSE_DATE] [datetime] NULL,
	[CLOSE_YN] [varchar](1) NULL,
	[CLOSE_USER] [varchar](20) NULL,
	[CANCEL_CLOSE_DATE] [datetime] NULL,
	[CANCEL_CLOSE_YN] [varchar](1) NULL,
	[CANCEL_CLOSE_USER] [varchar](20) NULL,
	[EXPECT_PAYDATE] [datetime] NULL,
	[UNPAID_REASON] [varchar](100) NULL,
 CONSTRAINT [PK_HTL_RESV_MAST] PRIMARY KEY CLUSTERED 
(
	[RESV_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
