USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_INFO_MAST_ROOM_OLD](
	[HOTEL_CODE] [int] NOT NULL,
	[ROOM_CODE] [varchar](50) NOT NULL,
	[ROOM_NAME] [varchar](400) NULL,
	[ROOM_DESC] [varchar](8000) NULL,
	[USE_YN] [varchar](1) NULL,
	[CREATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_HTL_INFO_MAST_ROOM] PRIMARY KEY CLUSTERED 
(
	[HOTEL_CODE] ASC,
	[ROOM_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
