USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_RESV_VACCOUNT](
	[RESV_NO] [int] NOT NULL,
	[ACC_NO] [int] NOT NULL,
	[BANK_AMOUNT] [decimal](18, 0) NULL,
	[BANK_NAME] [varchar](100) NULL,
	[BANK_ACCOUNT] [varchar](50) NULL,
	[BANK_DEPOSITOR] [varchar](100) NULL,
	[EXPIRE_DATE] [datetime] NULL,
	[TRAN_NO] [varchar](50) NULL,
	[PAYMENT_ID] [varchar](50) NULL,
	[PAY_YN] [varchar](1) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER] [varchar](50) NULL,
	[BANK_ACCOUNT_OLD] [varchar](50) NULL,
 CONSTRAINT [PK_HTL_RESV_VACCOUNT] PRIMARY KEY CLUSTERED 
(
	[RESV_NO] ASC,
	[ACC_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
