USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_COMPANY](
	[COMPANY_ID] [varchar](20) NOT NULL,
	[COMPANY_NAME] [varchar](100) NULL,
	[COMPANY_CEO] [varchar](20) NULL,
	[BUSINESS_STATUS] [varchar](100) NULL,
	[BUSINESS_TYPES] [varchar](100) NULL,
	[REGIST_NUMBER] [varchar](20) NULL,
	[COMPANY_ZIPCODE] [varchar](10) NULL,
	[COMPANY_ADDRESS] [varchar](100) NULL,
	[COMPANY_ADDRESS_DETAIL] [varchar](100) NULL,
	[COMPANY_TEL] [varchar](20) NULL,
	[COMPANY_FAX] [varchar](20) NULL,
	[REG_DATE] [datetime] NULL,
	[REG_USER] [varchar](50) NULL,
	[USE_YN] [varchar](1) NULL,
	[UPD_DATE] [datetime] NULL,
	[UPD_USER] [varchar](50) NULL,
	[REG_YN] [varchar](1) NULL,
 CONSTRAINT [PK_TBL_COMPANY] PRIMARY KEY CLUSTERED 
(
	[COMPANY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
