USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_CODE_LANDMARK](
	[MARK_CODE] [int] NOT NULL,
	[MARK_NAME] [varchar](255) NULL,
	[P_REGION_ID] [bigint] NULL,
	[SUB_CLASS] [varchar](50) NULL,
 CONSTRAINT [PK_HTL_CODE_LANDMARK] PRIMARY KEY CLUSTERED 
(
	[MARK_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
