USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_RESV_PAX](
	[RESV_NO] [int] NOT NULL,
	[PAX_NO] [smallint] NOT NULL,
	[PAX_TYPE] [varchar](3) NULL,
	[SUR_NAME] [varchar](100) NULL,
	[GIVEN_NAME] [varchar](200) NULL,
	[KOR_NAME] [varchar](200) NULL,
	[GENDER] [varchar](1) NULL,
	[AGE] [varchar](10) NULL,
	[BIRTH] [varchar](10) NULL,
	[ROOM_NO] [int] NULL,
	[USE_YN] [varchar](1) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER] [varchar](30) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER] [varchar](30) NULL,
 CONSTRAINT [PK_HTL_RESV_PAX] PRIMARY KEY CLUSTERED 
(
	[RESV_NO] ASC,
	[PAX_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
