USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_INFO_MAST_IMAGE_OLD](
	[IMG_NO] [int] IDENTITY(1,1) NOT NULL,
	[HOTEL_CODE] [int] NULL,
	[CAPTION] [varchar](200) NULL,
	[IMG_THUMB] [varchar](200) NULL,
	[IMG_URL] [varchar](200) NULL,
	[MAIN_YN] [varchar](1) NULL,
	[USE_YN] [varchar](1) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER] [varchar](30) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER] [varchar](30) NULL,
	[IMG_Y] [varchar](200) NULL,
	[IMG_Z] [varchar](200) NULL,
 CONSTRAINT [PK_HTL_INFO_MAST_IMAGE] PRIMARY KEY CLUSTERED 
(
	[IMG_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
