USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_PAY_COM_RATE](
	[PAY_TYPE] [varchar](4) NOT NULL,
	[PAY_NAME] [varchar](50) NULL,
	[COM_RATE] [decimal](16, 2) NULL,
	[COM_PRICE] [decimal](16, 2) NULL,
 CONSTRAINT [PK_TBL_PAY_COM_RATE] PRIMARY KEY CLUSTERED 
(
	[PAY_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
