USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_INFO_MAST_ROOM_FAC](
	[HOTEL_CODE] [int] NOT NULL,
	[ROOM_CODE] [int] NOT NULL,
	[PROPERTY_CODE] [int] NOT NULL,
	[PROPERTY_NAME] [varchar](200) NULL,
	[TRANSLATED_NAME] [varchar](200) NULL,
 CONSTRAINT [PK_HTL_INFO_MAST_ROOM_FAC_2] PRIMARY KEY CLUSTERED 
(
	[HOTEL_CODE] ASC,
	[ROOM_CODE] ASC,
	[PROPERTY_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
