USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_CODE_MAST_AREA](
	[AREA_CODE] [bigint] NOT NULL,
	[CITY_CODE] [bigint] NOT NULL,
	[AREA_NAME] [nvarchar](400) NULL,
	[AREA_ENAME] [nvarchar](400) NULL,
	[CITY_NAME] [varchar](100) NULL,
	[SORT_ORDER] [int] NULL,
	[HOTEL_CNT] [int] NULL,
	[USE_YN] [varchar](1) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER] [varchar](30) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER] [varchar](30) NULL,
 CONSTRAINT [PK_HTL_CODE_MAST_AREA] PRIMARY KEY CLUSTERED 
(
	[AREA_CODE] ASC,
	[CITY_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
