USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_INFO_MAST_FAC_IDX](
	[HOTEL_CODE] [int] NOT NULL,
	[S_CODE] [varchar](20) NULL,
	[CODE_NAME] [varchar](300) NULL
) ON [PRIMARY]
GO
