USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_RESV_ARS](
	[RESV_NO] [int] NOT NULL,
	[ARS_NO] [int] NOT NULL,
	[ARS_NAME] [varchar](100) NULL,
	[ARS_AMT] [decimal](18, 0) NULL,
	[ARS_AUTO_NO] [varchar](50) NULL,
	[EXPIRE_DATE] [datetime] NULL,
	[TRAN_NO] [varchar](50) NULL,
	[PAYMENT_ID] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER] [varchar](50) NULL,
 CONSTRAINT [PK_HTL_RESV_ARS] PRIMARY KEY CLUSTERED 
(
	[RESV_NO] ASC,
	[ARS_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
