USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_RESV_REMARK](
	[RESV_NO] [int] NOT NULL,
	[REQ_NO] [int] NOT NULL,
	[REQ_CODE] [varchar](30) NULL,
	[REQ_DESC] [varchar](100) NULL,
 CONSTRAINT [PK_HTL_RESV_REMARK] PRIMARY KEY CLUSTERED 
(
	[RESV_NO] ASC,
	[REQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
