USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_INFO_RECOM](
	[RECOM_SEQ] [int] IDENTITY(1,1) NOT NULL,
	[CITY_CODE] [varchar](20) NULL,
	[HOTEL_CODE] [int] NULL,
	[RECOM_DESC] [varchar](3000) NULL,
	[RECOM_TYPE] [varchar](1) NULL,
	[RECOM_URL] [varchar](300) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER] [varchar](30) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER] [varchar](30) NULL,
 CONSTRAINT [PK_HTL_INFO_RECOM] PRIMARY KEY CLUSTERED 
(
	[RECOM_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
