USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_LOCAL_PRICE](
	[PRICE_SEQ] [int] IDENTITY(1,1) NOT NULL,
	[HOTEL_CODE] [int] NOT NULL,
	[ROOM_SEQ] [int] NOT NULL,
	[CHECK_IN_DATE] [varchar](10) NOT NULL,
	[STATUS] [varchar](2) NULL,
	[ROOM_CNT] [int] NULL,
	[NET_PRICE] [decimal](18, 0) NULL,
	[SALE_PRICE] [decimal](18, 0) NULL,
	[NET_MEAL_PRICE] [decimal](18, 0) NULL,
	[SALE_MEAL_PRICE] [decimal](18, 0) NULL,
	[CANCEL_DAY] [int] NULL,
	[USE_YN] [varchar](1) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER] [varchar](30) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER] [varchar](30) NULL,
 CONSTRAINT [PK_HTL_LOCAL_PRICE] PRIMARY KEY CLUSTERED 
(
	[PRICE_SEQ] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HTL_LOCAL_PRICE] ADD  CONSTRAINT [DF_HTL_LOCAL_PRICE_ROOM_CNT]  DEFAULT ((0)) FOR [ROOM_CNT]
GO
