USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_INFO_BLOG](
	[HOTEL_CODE] [int] NOT NULL,
	[BLOG_TYPE] [varchar](2) NOT NULL,
	[BLOG_ID] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL
) ON [PRIMARY]
GO
