USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_INFO_MAST_ROOM_BED](
	[HOTEL_CODE] [int] NOT NULL,
	[ROOM_CODE] [int] NOT NULL,
	[BED_CODE] [int] NOT NULL,
	[BED_NAME] [varchar](300) NULL,
	[BED_QUANTITY] [int] NULL,
	[BED_SIZE] [varchar](100) NULL,
	[BED_TYPE] [varchar](100) NULL,
 CONSTRAINT [PK_HTL_INFO_MAST_ROOM_BED] PRIMARY KEY CLUSTERED 
(
	[HOTEL_CODE] ASC,
	[ROOM_CODE] ASC,
	[BED_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
