USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AGODA_TEST_HOTEL](
	[HOTEL_CODE] [int] NOT NULL,
	[USE_YN] [varchar](1) NULL,
	[CITY_CODE] [int] NULL
) ON [PRIMARY]
GO
