USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_POSITION](
	[POSITION_CODE] [varchar](20) NOT NULL,
	[POSITION_NAME] [varchar](50) NULL,
	[USE_YN] [varchar](1) NULL,
	[ACC_ID] [varchar](30) NULL,
 CONSTRAINT [PK_TBL_POSITION] PRIMARY KEY CLUSTERED 
(
	[POSITION_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
