USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_INFO_LOCAL](
	[HOTEL_CODE] [int] NOT NULL,
	[INFO_TYPE] [varchar](30) NULL,
	[CATEGORY_NAME] [varchar](100) NULL,
	[IATA_CODE] [varchar](10) NULL,
	[LOCAL_NAME] [varchar](200) NULL,
	[DISTANCE] [decimal](18, 2) NULL,
	[DISTANCE_UNIT] [varchar](20) NULL
) ON [PRIMARY]
GO
