USE [JGHotel]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_CODE_MAIN_CITY](
	[REGION_CODE] [varchar](3) NOT NULL,
	[CITY_CODE] [int] NOT NULL,
	[SORT_ORDER] [int] NULL,
 CONSTRAINT [PK_HTL_CODE_MAIN_CITY] PRIMARY KEY CLUSTERED 
(
	[REGION_CODE] ASC,
	[CITY_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
