USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVSEGMENT](
	[SEGMENT_NO] [numeric](15, 0) NOT NULL,
	[USER_ID] [varchar](15) NULL,
	[GRP_CD] [varchar](12) NULL,
	[SEGMENT_NM] [varchar](100) NULL,
	[DBINFO_SEQ] [numeric](2, 0) NULL,
	[SEGMENT_DESC] [varchar](250) NULL,
	[SQLHEAD] [varchar](4000) NULL,
	[SQLTAIL] [varchar](4000) NULL,
	[SQLBODY] [varchar](4000) NULL,
	[SQLFILTER] [varchar](4000) NULL,
	[LASTUPDATE_DT] [char](8) NULL,
	[SEGMENT_SIZE] [numeric](10, 0) NULL,
	[CRTGRP_CD] [varchar](12) NULL,
	[SEGMENT_TYPE] [char](1) NULL,
	[FILETODB_YN] [char](1) NULL,
	[EDITOR_ID] [varchar](15) NULL,
	[SHARE_YN] [char](1) NULL,
	[ACTIVE_YN] [char](1) NULL,
	[CATEGORY_CD] [varchar](12) NULL,
	[SEGMENT_STS] [char](1) NULL,
	[TAG_NO] [numeric](10, 0) NULL,
	[PSEGMENT_NO] [numeric](15, 0) NULL,
	[PLINK_SEQ] [varchar](250) NULL,
	[SEG_TYPE] [char](1) NULL,
	[TESTQUERY] [varchar](4000) NULL,
	[UPDATEQUERY] [varchar](4000) NULL,
 CONSTRAINT [PK_NVSEGMENT] PRIMARY KEY CLUSTERED 
(
	[SEGMENT_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVSEGMENT]  WITH CHECK ADD  CONSTRAINT [FK_DBINFO_SEGMENT] FOREIGN KEY([DBINFO_SEQ])
REFERENCES [dbo].[NVDBINFO] ([DBINFO_SEQ])
GO
ALTER TABLE [dbo].[NVSEGMENT] CHECK CONSTRAINT [FK_DBINFO_SEGMENT]
GO
ALTER TABLE [dbo].[NVSEGMENT]  WITH CHECK ADD  CONSTRAINT [FK_USER_SEGMENT] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[NVUSER] ([USER_ID])
GO
ALTER TABLE [dbo].[NVSEGMENT] CHECK CONSTRAINT [FK_USER_SEGMENT]
GO
ALTER TABLE [dbo].[NVSEGMENT]  WITH CHECK ADD  CONSTRAINT [FK_USERGRP_SEGMENT] FOREIGN KEY([GRP_CD])
REFERENCES [dbo].[NVUSERGRP] ([GRP_CD])
GO
ALTER TABLE [dbo].[NVSEGMENT] CHECK CONSTRAINT [FK_USERGRP_SEGMENT]
GO
