USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVLINKRESULT](
	[CAMPAIGN_NO] [numeric](15, 0) NOT NULL,
	[RESULT_SEQ] [numeric](16, 0) NOT NULL,
	[LIST_SEQ] [varchar](10) NOT NULL,
	[LINK_DT] [char](8) NOT NULL,
	[LINK_TM] [char](6) NOT NULL,
	[RECORD_SEQ] [varchar](10) NULL,
	[LINK_SEQ] [numeric](3, 0) NOT NULL,
	[CUSTOMER_ID] [varchar](50) NOT NULL,
	[CUSTOMER_NM] [varchar](100) NOT NULL,
	[CUSTOMER_EMAIL] [varchar](100) NOT NULL,
	[CLICK_CNT] [numeric](10, 0) NULL,
	[AB_TYPE] [varchar](4) NULL,
 CONSTRAINT [PK_NVLINKRESULT] PRIMARY KEY CLUSTERED 
(
	[CAMPAIGN_NO] ASC,
	[RESULT_SEQ] ASC,
	[LIST_SEQ] ASC,
	[LINK_DT] ASC,
	[LINK_TM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVLINKRESULT] ADD  DEFAULT ('0') FOR [RECORD_SEQ]
GO
ALTER TABLE [dbo].[NVLINKRESULT]  WITH CHECK ADD  CONSTRAINT [FK_LINKTRACE_LINKRESULT] FOREIGN KEY([CAMPAIGN_NO], [LINK_SEQ])
REFERENCES [dbo].[NVLINKTRACE] ([CAMPAIGN_NO], [LINK_SEQ])
GO
ALTER TABLE [dbo].[NVLINKRESULT] CHECK CONSTRAINT [FK_LINKTRACE_LINKRESULT]
GO
