USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NV_SVC_DIVIDE](
	[TASK_ID] [varchar](31) NOT NULL,
	[SERVER_ID] [varchar](10) NOT NULL,
	[DIVIDE_SEQ] [numeric](2, 0) NOT NULL,
	[CLIENT] [varchar](2) NULL,
	[SERVICE_NO] [numeric](15, 0) NULL,
	[TARGET_CNT] [numeric](10, 0) NULL,
	[SEND_CNT] [numeric](10, 0) NULL,
	[START_DT] [varchar](14) NULL,
	[END_DT] [varchar](14) NULL,
	[STATUS] [char](1) NULL,
 CONSTRAINT [PK_NV_SVC_DIVIDE] PRIMARY KEY CLUSTERED 
(
	[TASK_ID] ASC,
	[SERVER_ID] ASC,
	[DIVIDE_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
