USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NV_SVC_TRANS](
	[T_ID] [varchar](31) NOT NULL,
	[SERVER_ID] [varchar](10) NOT NULL,
	[CREATE_TM] [varchar](17) NULL,
	[PRC_FLAG] [char](1) NULL,
 CONSTRAINT [PK_NV_SVC_TRANS] PRIMARY KEY CLUSTERED 
(
	[T_ID] ASC,
	[SERVER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
