USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVTEMPLATE](
	[CAMPAIGN_NO] [numeric](15, 0) NOT NULL,
	[SEG] [varchar](20) NOT NULL,
	[TEMPLATE] [text] NULL,
 CONSTRAINT [PK_NVTEMPLATE] PRIMARY KEY CLUSTERED 
(
	[CAMPAIGN_NO] ASC,
	[SEG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVTEMPLATE]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAIGN_TEMPLATE] FOREIGN KEY([CAMPAIGN_NO])
REFERENCES [dbo].[NVCAMPAIGN] ([CAMPAIGN_NO])
GO
ALTER TABLE [dbo].[NVTEMPLATE] CHECK CONSTRAINT [FK_CAMPAIGN_TEMPLATE]
GO
