USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVSESSIONLOG](
	[SESSION_TIME] [varchar](14) NOT NULL,
	[SOEID] [varchar](7) NULL,
	[USER_NM] [varchar](50) NULL,
 CONSTRAINT [PK_NVSESSIONLOG] PRIMARY KEY CLUSTERED 
(
	[SESSION_TIME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
