USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVLINKCONDITION](
	[SCENARIO_NO] [numeric](15, 0) NOT NULL,
	[SCHEDULE_SEQ] [numeric](15, 0) NOT NULL,
	[LINK_SEQ] [numeric](3, 0) NOT NULL,
	[TRACKING_YN] [char](1) NULL,
 CONSTRAINT [PK_NVLINKCONDITION] PRIMARY KEY CLUSTERED 
(
	[SCENARIO_NO] ASC,
	[SCHEDULE_SEQ] ASC,
	[LINK_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVLINKCONDITION]  WITH CHECK ADD  CONSTRAINT [FK_SCHEDULE_LINKCONDITION] FOREIGN KEY([SCENARIO_NO], [SCHEDULE_SEQ])
REFERENCES [dbo].[NVSCHEDULE] ([SCENARIO_NO], [SCHEDULE_SEQ])
GO
ALTER TABLE [dbo].[NVLINKCONDITION] CHECK CONSTRAINT [FK_SCHEDULE_LINKCONDITION]
GO
