USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVSENDERR](
	[ERROR_CD] [varchar](4) NOT NULL,
	[ERROR_NM] [varchar](100) NULL,
	[ERROR_DESC] [varchar](250) NULL,
	[ERROR_SMS_DESC] [varchar](250) NULL,
	[CATEGORY_CD] [varchar](12) NULL,
	[CHANNEL_TYPE] [char](1) NULL,
	[SPAM_YN] [char](1) NULL,
 CONSTRAINT [PK_NVSENDERR] PRIMARY KEY CLUSTERED 
(
	[ERROR_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVSENDERR] ADD  DEFAULT ('N') FOR [SPAM_YN]
GO
ALTER TABLE [dbo].[NVSENDERR]  WITH CHECK ADD  CONSTRAINT [FK_SMTPCATEGORY_SENDERR] FOREIGN KEY([CATEGORY_CD])
REFERENCES [dbo].[NVSMTPCATEGORY] ([CATEGORY_CD])
GO
ALTER TABLE [dbo].[NVSENDERR] CHECK CONSTRAINT [FK_SMTPCATEGORY_SENDERR]
GO
