USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVSEGGENEALOGY](
	[SEGMENT_NO] [numeric](15, 0) NOT NULL,
	[GENEALOGY_SEQ] [numeric](3, 0) NOT NULL,
	[SUPRASEGMENT_NO] [numeric](15, 0) NULL,
 CONSTRAINT [PK_NVSEGGENEALOGY] PRIMARY KEY CLUSTERED 
(
	[SEGMENT_NO] ASC,
	[GENEALOGY_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVSEGGENEALOGY]  WITH CHECK ADD  CONSTRAINT [FK_SEGMENT_SEGGENEALOGY] FOREIGN KEY([SEGMENT_NO])
REFERENCES [dbo].[NVSEGMENT] ([SEGMENT_NO])
GO
ALTER TABLE [dbo].[NVSEGGENEALOGY] CHECK CONSTRAINT [FK_SEGMENT_SEGGENEALOGY]
GO
