USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVECARETRACEINFO](
	[ECARE_NO] [numeric](15, 0) NOT NULL,
	[TRACE_TYPE] [varchar](10) NOT NULL,
	[START_DT] [char](8) NULL,
	[START_TM] [char](6) NULL,
	[END_DT] [char](8) NULL,
	[END_TM] [char](6) NULL,
	[TERM_TYPE] [char](1) NULL,
 CONSTRAINT [PK_NVECARETRACEINFO] PRIMARY KEY CLUSTERED 
(
	[ECARE_NO] ASC,
	[TRACE_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVECARETRACEINFO]  WITH CHECK ADD  CONSTRAINT [FK_ECAREMSG_ECARETRACEINFO] FOREIGN KEY([ECARE_NO])
REFERENCES [dbo].[NVECAREMSG] ([ECARE_NO])
GO
ALTER TABLE [dbo].[NVECARETRACEINFO] CHECK CONSTRAINT [FK_ECAREMSG_ECARETRACEINFO]
GO
