USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVRPTDURATION](
	[CAMPAIGN_NO] [numeric](15, 0) NOT NULL,
	[REPORT_DT] [char](8) NOT NULL,
	[REPORT_TM] [char](2) NOT NULL,
	[DURATIONINFO_CD] [char](2) NULL,
	[VALIDOPEN_CNT] [numeric](10, 0) NULL,
	[VALIDOPEN_OCNT] [numeric](10, 0) NULL,
	[RESULT_SEQ] [numeric](16, 0) NOT NULL,
 CONSTRAINT [PK_NVRPTDURATION] PRIMARY KEY CLUSTERED 
(
	[CAMPAIGN_NO] ASC,
	[RESULT_SEQ] ASC,
	[REPORT_DT] ASC,
	[REPORT_TM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVRPTDURATION]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAIGN_RPTDURATION] FOREIGN KEY([CAMPAIGN_NO])
REFERENCES [dbo].[NVCAMPAIGN] ([CAMPAIGN_NO])
GO
ALTER TABLE [dbo].[NVRPTDURATION] CHECK CONSTRAINT [FK_CAMPAIGN_RPTDURATION]
GO
