USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NV_SVR_INFO](
	[SERVER_ID] [varchar](10) NOT NULL,
	[LAST_UPDATE_TM] [varchar](14) NULL,
	[START_TM] [varchar](14) NULL,
	[JOB_CNT] [numeric](10, 0) NULL,
	[PROCESS_THREAD_CNT] [numeric](5, 0) NULL,
	[WORK_THREAD_CNT] [numeric](5, 0) NULL,
	[OPENFILE_DESC_CNT] [numeric](5, 0) NULL,
	[MAX_MEMORY] [numeric](10, 0) NULL,
	[USED_MEMORY] [numeric](10, 0) NULL,
	[CPU_RATE] [numeric](10, 2) NULL,
	[MAX_QUEUE_SIZE] [numeric](5, 0) NULL,
	[USED_QUEUE_SIZE] [numeric](5, 0) NULL,
	[STATUS] [numeric](1, 0) NULL,
	[POLLING_ACT_STATUS] [char](1) NULL,
	[POLLING_ACT_STATUS_UPDATE_TM] [varchar](14) NULL,
	[DISP_NO] [numeric](2, 0) NULL,
	[EXEC_INFO] [varchar](500) NULL,
	[CONFIG_CONT] [text] NULL,
 CONSTRAINT [PK_NV_SVR_INFO] PRIMARY KEY CLUSTERED 
(
	[SERVER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
