USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVMPSSCHEDULERINFO](
	[SCHEDULER_ID] [char](6) NOT NULL,
	[SCHEDULER_NAME] [varchar](100) NULL,
	[SCHEDULER_WORKER] [varchar](250) NULL,
	[SCHEDULER_TYPE] [char](1) NULL,
	[SCHEDULER_TERM] [numeric](10, 0) NULL,
	[SCHEDULER_RUNTIME] [varchar](6) NULL,
	[SCHEDULER_FILEPATH] [varchar](100) NULL,
	[SCHEDULER_FILEPATTERN] [varchar](250) NULL,
	[SCHEDULER_QUERY] [text] NULL,
 CONSTRAINT [PK_NVMPSSCHEDULERINFO] PRIMARY KEY CLUSTERED 
(
	[SCHEDULER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVMPSSCHEDULERINFO] ADD  DEFAULT ((60)) FOR [SCHEDULER_TERM]
GO
