USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVSCHEDULE](
	[SCENARIO_NO] [numeric](15, 0) NOT NULL,
	[SCHEDULE_SEQ] [numeric](15, 0) NOT NULL,
	[CAMPAIGN_NO] [numeric](15, 0) NULL,
	[SUPRACAMPAIGN_NO] [numeric](15, 0) NULL,
	[CAMPAIGN_DT] [char](8) NULL,
	[POSITION_X] [numeric](5, 0) NULL,
	[POSITION_Y] [numeric](5, 0) NULL,
	[SIZEWIDTH] [numeric](10, 0) NULL,
	[SIZEHEIGHT] [numeric](10, 0) NULL,
	[DURATION_TM] [numeric](5, 0) NULL,
	[RECEIPT_YN] [char](1) NULL,
	[FROMSQL] [varchar](1000) NULL,
	[WHERESQL] [varchar](1000) NULL,
 CONSTRAINT [PK_NVSCHEDULE] PRIMARY KEY CLUSTERED 
(
	[SCENARIO_NO] ASC,
	[SCHEDULE_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVSCHEDULE]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAIGN_SCHEDULE] FOREIGN KEY([CAMPAIGN_NO])
REFERENCES [dbo].[NVCAMPAIGN] ([CAMPAIGN_NO])
GO
ALTER TABLE [dbo].[NVSCHEDULE] CHECK CONSTRAINT [FK_CAMPAIGN_SCHEDULE]
GO
ALTER TABLE [dbo].[NVSCHEDULE]  WITH CHECK ADD  CONSTRAINT [FK_SCENARIO_SCHEDULE] FOREIGN KEY([SCENARIO_NO])
REFERENCES [dbo].[NVSCENARIO] ([SCENARIO_NO])
GO
ALTER TABLE [dbo].[NVSCHEDULE] CHECK CONSTRAINT [FK_SCENARIO_SCHEDULE]
GO
