USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NV_PERMISSION_MENUROLE](
	[PERMISSION_MENUROLE_NO] [numeric](8, 0) NOT NULL,
	[MENU_CD] [varchar](10) NOT NULL,
	[READ_AUTH] [char](1) NULL,
	[WRITE_AUTH] [char](1) NULL,
	[EXECUTE_AUTH] [char](1) NULL,
 CONSTRAINT [PK_NV_PERMISSION_MENUROLE] PRIMARY KEY CLUSTERED 
(
	[PERMISSION_MENUROLE_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
