USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVEVENTLOG](
	[EVENT_DATE] [varchar](19) NOT NULL,
	[USER_ID] [varchar](50) NULL,
	[EVENT_ACTION_DESC] [varchar](250) NULL
) ON [PRIMARY]
GO
