USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVSCENARIO](
	[SCENARIO_NO] [numeric](15, 0) NOT NULL,
	[USER_ID] [varchar](15) NULL,
	[GRP_CD] [varchar](12) NULL,
	[SCENARIO_NM] [varchar](100) NULL,
	[SCENARIO_DESC] [varchar](250) NULL,
	[SCENARIO_TYPE] [char](1) NULL,
	[CREATE_DT] [char](8) NULL,
	[LASTUPDATE_DT] [char](8) NULL,
	[FINISH_YN] [char](1) NULL,
	[FINISH_DT] [char](8) NULL,
	[TAG_NO] [numeric](10, 0) NULL,
	[CREATE_TM] [char](6) NULL,
	[LASTUPDATE_TM] [char](6) NULL,
	[HANDLER_TYPE] [char](1) NULL,
 CONSTRAINT [PK_NVSCENARIO] PRIMARY KEY CLUSTERED 
(
	[SCENARIO_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVSCENARIO] ADD  DEFAULT ('G') FOR [HANDLER_TYPE]
GO
ALTER TABLE [dbo].[NVSCENARIO]  WITH CHECK ADD  CONSTRAINT [FK_USER_SCENARIO] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[NVUSER] ([USER_ID])
GO
ALTER TABLE [dbo].[NVSCENARIO] CHECK CONSTRAINT [FK_USER_SCENARIO]
GO
ALTER TABLE [dbo].[NVSCENARIO]  WITH CHECK ADD  CONSTRAINT [FK_USERGRP_SCENARIO] FOREIGN KEY([GRP_CD])
REFERENCES [dbo].[NVUSERGRP] ([GRP_CD])
GO
ALTER TABLE [dbo].[NVSCENARIO] CHECK CONSTRAINT [FK_USERGRP_SCENARIO]
GO
