USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVLINKTRACE](
	[CAMPAIGN_NO] [numeric](15, 0) NOT NULL,
	[LINK_SEQ] [numeric](3, 0) NOT NULL,
	[LINK_URL] [varchar](2000) NULL,
	[LINK_DESC] [varchar](2000) NULL,
	[LINK_TITLE] [varchar](2000) NULL,
 CONSTRAINT [PK_NVLINKTRACE] PRIMARY KEY CLUSTERED 
(
	[CAMPAIGN_NO] ASC,
	[LINK_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVLINKTRACE]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAIGN_LINKTRACE] FOREIGN KEY([CAMPAIGN_NO])
REFERENCES [dbo].[NVCAMPAIGN] ([CAMPAIGN_NO])
GO
ALTER TABLE [dbo].[NVLINKTRACE] CHECK CONSTRAINT [FK_CAMPAIGN_LINKTRACE]
GO
