USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVECAREKMMAP](
	[ECARE_NO] [numeric](15, 0) NOT NULL,
	[ITEMFIELD_NM] [varchar](50) NOT NULL,
	[KNOWLEDGEMAP_ID] [varchar](12) NOT NULL,
	[GRP_CD] [varchar](12) NULL,
	[USER_ID] [varchar](15) NULL,
	[ITEM_CD] [char](2) NULL,
	[ITEM_NM] [varchar](50) NULL,
	[ITEMINDENT] [numeric](2, 0) NULL,
	[ITEM_LENGTH] [numeric](5, 0) NULL,
	[ITEM_TYPE] [varchar](50) NULL,
	[ITEM_FORMAT] [varchar](50) NULL,
	[QUERY_SEQ] [numeric](2, 0) NULL,
	[ITEM_PRAM_VALUE] [varchar](100) NULL,
 CONSTRAINT [PK_NVECAREKMMAP] PRIMARY KEY CLUSTERED 
(
	[ECARE_NO] ASC,
	[ITEMFIELD_NM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVECAREKMMAP]  WITH CHECK ADD  CONSTRAINT [FK_USER_ECAREKMMAP] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[NVUSER] ([USER_ID])
GO
ALTER TABLE [dbo].[NVECAREKMMAP] CHECK CONSTRAINT [FK_USER_ECAREKMMAP]
GO
ALTER TABLE [dbo].[NVECAREKMMAP]  WITH CHECK ADD  CONSTRAINT [FK_USERGRP_ECAREKMMAP] FOREIGN KEY([GRP_CD])
REFERENCES [dbo].[NVUSERGRP] ([GRP_CD])
GO
ALTER TABLE [dbo].[NVECAREKMMAP] CHECK CONSTRAINT [FK_USERGRP_ECAREKMMAP]
GO
