USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVECARESENDLOG](
	[ECARE_NO] [numeric](15, 0) NOT NULL,
	[RESULT_SEQ] [numeric](16, 0) NOT NULL,
	[LIST_SEQ] [varchar](10) NOT NULL,
	[CUSTOMER_KEY] [varchar](50) NOT NULL,
	[RECORD_SEQ] [varchar](10) NOT NULL,
	[SID] [varchar](5) NOT NULL,
	[CUSTOMER_NM] [varchar](100) NULL,
	[CUSTOMER_EMAIL] [varchar](100) NOT NULL,
	[SEND_DT] [char](8) NULL,
	[SEND_TM] [char](6) NULL,
	[END_DT] [char](8) NULL,
	[END_TM] [char](6) NULL,
	[ERROR_CD] [varchar](4) NULL,
	[SEND_DOMAIN] [varchar](50) NULL,
	[ERR_MSG] [varchar](250) NULL,
	[SLOT1] [varchar](100) NULL,
	[SLOT2] [varchar](100) NULL,
	[RESEND_YN] [char](1) NULL,
	[REQ_DEPT_ID] [varchar](50) NULL,
	[REQ_USER_ID] [varchar](50) NULL,
	[MESSAGE_KEY] [varchar](20) NULL,
	[SEQ] [varchar](100) NULL,
	[SRFIDD] [varchar](50) NULL,
 CONSTRAINT [PK_NVECARESENDLOG] PRIMARY KEY CLUSTERED 
(
	[ECARE_NO] ASC,
	[RESULT_SEQ] ASC,
	[LIST_SEQ] ASC,
	[CUSTOMER_KEY] ASC,
	[RECORD_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVECARESENDLOG] ADD  DEFAULT ('0') FOR [RECORD_SEQ]
GO
