USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVSEGMENTCHECK](
	[SEGMENT_NO] [numeric](15, 0) NOT NULL,
	[USER_ID] [varchar](15) NOT NULL,
 CONSTRAINT [PK_NVSEGMENTCHECK] PRIMARY KEY CLUSTERED 
(
	[SEGMENT_NO] ASC,
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
