USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVECARELINKTRACE](
	[ECARE_NO] [numeric](15, 0) NOT NULL,
	[LINK_SEQ] [numeric](2, 0) NOT NULL,
	[LINK_DESC] [varchar](2000) NULL,
	[LINK_URL] [varchar](2000) NULL,
	[LINK_TITLE] [varchar](2000) NULL,
 CONSTRAINT [PK_NVECARELINKTRACE] PRIMARY KEY CLUSTERED 
(
	[ECARE_NO] ASC,
	[LINK_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVECARELINKTRACE]  WITH CHECK ADD  CONSTRAINT [FK_ECAREMSG_ECARELINKTRACE] FOREIGN KEY([ECARE_NO])
REFERENCES [dbo].[NVECAREMSG] ([ECARE_NO])
GO
ALTER TABLE [dbo].[NVECARELINKTRACE] CHECK CONSTRAINT [FK_ECAREMSG_ECARELINKTRACE]
GO
