USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVTESTUSERPOOL](
	[USER_ID] [varchar](15) NOT NULL,
	[SEQ_NO] [numeric](5, 0) NOT NULL,
	[TESTRECEIVER_EMAIL] [varchar](100) NOT NULL,
	[TESTRECEIVER_TEL] [varchar](50) NULL,
	[TESTRECEIVER_NM] [varchar](50) NOT NULL,
	[TESTRECEIVER_FAX] [varchar](50) NULL,
	[TEST_GRP_CD] [numeric](5, 0) NULL,
 CONSTRAINT [PK_NVTESTUSERPOOL] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC,
	[SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVTESTUSERPOOL]  WITH CHECK ADD  CONSTRAINT [FK_USER_TESTUSERPOOL] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[NVUSER] ([USER_ID])
GO
ALTER TABLE [dbo].[NVTESTUSERPOOL] CHECK CONSTRAINT [FK_USER_TESTUSERPOOL]
GO
