USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVUSER](
	[USER_ID] [varchar](15) NOT NULL,
	[PASS_WD] [varchar](128) NULL,
	[PASS_SALT] [varchar](50) NULL,
	[GRP_CD] [varchar](12) NULL,
	[NAME_KOR] [varchar](50) NULL,
	[NAME_ENG] [varchar](50) NULL,
	[TEL_NO] [varchar](20) NULL,
	[EMAIL] [varchar](100) NULL,
	[USER_CLASS] [varchar](50) NULL,
	[USERTYPE_CD] [char](1) NOT NULL,
	[LASTUPDATE_DT] [char](8) NULL,
	[ACTIVE_YN] [char](1) NULL,
	[ACCEPT_YN] [char](1) NULL,
	[LIST_COUNT_PER_PAGE] [varchar](3) NULL,
	[SOEID] [char](7) NULL,
	[GEID] [char](10) NULL,
	[ISA_ROLE] [char](1) NULL,
	[WORK_DOC] [varchar](100) NULL,
	[USER_ROLE] [char](1) NULL,
	[CREATE_USER] [varchar](15) NULL,
	[PERMIT_STS] [char](1) NULL,
	[PERMIT_DT] [varchar](8) NULL,
	[LOGIN_CNT] [numeric](1, 0) NULL,
	[LASTLOGIN_DT] [varchar](14) NULL,
 CONSTRAINT [PK_NVUSER] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVUSER] ADD  DEFAULT ((10)) FOR [LIST_COUNT_PER_PAGE]
GO
ALTER TABLE [dbo].[NVUSER] ADD  DEFAULT ((0)) FOR [LOGIN_CNT]
GO
ALTER TABLE [dbo].[NVUSER]  WITH CHECK ADD  CONSTRAINT [FK_USERGRP_USER] FOREIGN KEY([GRP_CD])
REFERENCES [dbo].[NVUSERGRP] ([GRP_CD])
GO
ALTER TABLE [dbo].[NVUSER] CHECK CONSTRAINT [FK_USERGRP_USER]
GO
