USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVMAILBLOCK](
	[SERVICE_NO] [numeric](15, 0) NOT NULL,
	[SERVICE_TYPE] [char](2) NOT NULL,
	[BLOCK_YN] [char](1) NOT NULL,
 CONSTRAINT [PK_NVMAILBLOCK] PRIMARY KEY CLUSTERED 
(
	[SERVICE_NO] ASC,
	[SERVICE_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVMAILBLOCK] ADD  DEFAULT ('EC') FOR [SERVICE_TYPE]
GO
ALTER TABLE [dbo].[NVMAILBLOCK] ADD  DEFAULT ('N') FOR [BLOCK_YN]
GO
