USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVUSERGRP](
	[GRP_CD] [varchar](12) NOT NULL,
	[GRP_NM] [varchar](100) NULL,
	[SUPRAGRP_CD] [varchar](12) NULL,
	[GRP_DESC] [varchar](250) NULL,
	[GRP_LEVEL] [numeric](2, 0) NULL,
	[PERMISSION] [char](1) NULL,
	[EDITOR_ID] [varchar](15) NULL,
	[LASTUPDATE_DT] [char](8) NULL,
	[MANAGER_ID] [varchar](13) NULL,
	[ACTIVE_YN] [char](1) NULL,
	[ETC_INFO1] [varchar](250) NULL,
	[MANAGER_NM] [varchar](50) NULL,
	[SERVER_IP] [varchar](20) NULL,
	[SERVER_PORT] [varchar](5) NULL,
	[FUNC_CODE] [varchar](50) NULL,
	[FUNC_DESC] [varchar](50) NULL,
	[WORK_DOC] [varchar](100) NULL,
	[ACCEPT_YN] [char](1) NULL,
	[PERMIT_DT] [varchar](8) NULL,
	[PERMIT_STS] [char](1) NULL,
	[REQ_DEPT_ID] [varchar](50) NULL,
 CONSTRAINT [PK_NVUSERGRP] PRIMARY KEY CLUSTERED 
(
	[GRP_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVUSERGRP] ADD  DEFAULT ('Y') FOR [ACCEPT_YN]
GO
