USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVSENDRESULT](
	[CAMPAIGN_NO] [numeric](15, 0) NOT NULL,
	[RESULT_SEQ] [numeric](16, 0) NOT NULL,
	[RESULT_DESC] [varchar](250) NULL,
	[RESULT_STS] [char](2) NULL,
	[START_DT] [char](8) NULL,
	[START_TM] [char](6) NULL,
	[END_DT] [char](8) NULL,
	[END_TM] [char](6) NULL,
	[TARGET_CNT] [numeric](10, 0) NULL,
	[SEND_CNT] [numeric](10, 0) NULL,
	[SUCCESS_CNT] [numeric](10, 0) NULL,
	[FAIL_CNT] [numeric](10, 0) NULL,
	[UNKNOWN_USER_CNT] [numeric](10, 0) NULL,
	[UNKNOWN_HOST_CNT] [numeric](10, 0) NULL,
	[SMTP_EXCEPT_CNT] [numeric](10, 0) NULL,
	[NO_ROUTE_CNT] [numeric](10, 0) NULL,
	[REFUSED_CNT] [numeric](10, 0) NULL,
	[ETC_EXCEPT_CNT] [numeric](10, 0) NULL,
	[INVALID_ADDRESS_CNT] [numeric](10, 0) NULL,
	[LOG_STS] [char](2) NULL,
	[DOMAIN_STS] [char](2) NULL,
	[RETURNMAIL_CNT] [numeric](10, 0) NULL,
	[OPEN_CNT] [numeric](10, 0) NULL,
	[DURATION_CNT] [numeric](10, 0) NULL,
	[LINK_CNT] [numeric](10, 0) NULL,
	[MANUALBATCH_STS] [char](1) NULL,
	[RESEND_STS] [char](1) NULL,
	[SUPER_SEQ] [numeric](16, 0) NULL,
 CONSTRAINT [PK_NVSENDRESULT] PRIMARY KEY CLUSTERED 
(
	[CAMPAIGN_NO] ASC,
	[RESULT_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVSENDRESULT] ADD  DEFAULT ((0)) FOR [RETURNMAIL_CNT]
GO
ALTER TABLE [dbo].[NVSENDRESULT] ADD  DEFAULT ((0)) FOR [OPEN_CNT]
GO
ALTER TABLE [dbo].[NVSENDRESULT] ADD  DEFAULT ((0)) FOR [DURATION_CNT]
GO
ALTER TABLE [dbo].[NVSENDRESULT] ADD  DEFAULT ((0)) FOR [LINK_CNT]
GO
ALTER TABLE [dbo].[NVSENDRESULT] ADD  DEFAULT (NULL) FOR [RESEND_STS]
GO
ALTER TABLE [dbo].[NVSENDRESULT]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAIGN_SENDRESULT] FOREIGN KEY([CAMPAIGN_NO])
REFERENCES [dbo].[NVCAMPAIGN] ([CAMPAIGN_NO])
GO
ALTER TABLE [dbo].[NVSENDRESULT] CHECK CONSTRAINT [FK_CAMPAIGN_SENDRESULT]
GO
