USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVSMSRPTSENDRESULT](
	[REPORT_DT] [char](8) NOT NULL,
	[SERVICE_NO] [numeric](15, 0) NOT NULL,
	[RESULT_SEQ] [numeric](16, 0) NOT NULL,
	[SERVICE_TYPE] [char](2) NOT NULL,
	[TARGET_CNT] [numeric](10, 0) NULL,
	[SEND_CNT] [numeric](10, 0) NULL,
	[SUCCESS_CNT] [numeric](10, 0) NULL,
	[FAIL_CNT] [numeric](10, 0) NULL,
	[SEND_GBN] [varchar](3) NOT NULL,
	[SEND_TM] [char](6) NOT NULL,
 CONSTRAINT [PK_NVSMSRPTSENDRESULT] PRIMARY KEY CLUSTERED 
(
	[REPORT_DT] ASC,
	[SERVICE_NO] ASC,
	[RESULT_SEQ] ASC,
	[SERVICE_TYPE] ASC,
	[SEND_GBN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
