USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVUSERPWHISTORY](
	[USER_ID] [varchar](15) NOT NULL,
	[CREATE_DT] [varchar](14) NOT NULL,
	[PASS_WD] [varchar](128) NULL,
	[PASS_SALT] [varchar](50) NULL,
	[DEFAULT_PASSYN] [char](1) NULL,
 CONSTRAINT [PK_NVUSERPWHISTORY] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC,
	[CREATE_DT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVUSERPWHISTORY] ADD  DEFAULT ('N') FOR [DEFAULT_PASSYN]
GO
