USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVECAREREJECT](
	[ECARE_NO] [numeric](15, 0) NOT NULL,
	[RESULT_SEQ] [numeric](16, 0) NOT NULL,
	[LIST_SEQ] [varchar](10) NOT NULL,
	[CUSTOMER_ID] [varchar](50) NOT NULL,
	[RECORD_SEQ] [varchar](10) NOT NULL,
	[CUSTOMER_EMAIL] [varchar](100) NOT NULL,
	[CUSTOMER_NM] [varchar](100) NOT NULL,
	[REJECT_DT] [char](8) NOT NULL,
	[REJECT_TM] [char](6) NOT NULL,
 CONSTRAINT [PK_NVECAREREJECT] PRIMARY KEY CLUSTERED 
(
	[ECARE_NO] ASC,
	[RESULT_SEQ] ASC,
	[LIST_SEQ] ASC,
	[CUSTOMER_ID] ASC,
	[RECORD_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVECAREREJECT] ADD  DEFAULT ('0') FOR [RECORD_SEQ]
GO
