USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVSCHEDULEACCEPTDATA](
	[SEQ] [varchar](100) NOT NULL,
	[DATA_SEQ] [numeric](3, 0) NOT NULL,
	[ATTACH_YN] [char](1) NULL,
	[ATTACH_NAME] [varchar](100) NULL,
	[SECU_KEY] [varchar](13) NULL,
	[DATA] [text] NULL,
 CONSTRAINT [PK_NVSCHEDULEACCEPTDATA] PRIMARY KEY CLUSTERED 
(
	[SEQ] ASC,
	[DATA_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
