USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NV_STATUS_REQ](
	[REQ_KIND] [varchar](10) NOT NULL,
	[CREATE_TM] [varchar](14) NOT NULL,
	[TASK_ID] [varchar](31) NOT NULL,
	[REQ] [varchar](20) NULL,
	[RESULT] [numeric](1, 0) NULL,
	[UPDATE_TM] [varchar](14) NULL,
	[USER_ID] [varchar](20) NULL,
 CONSTRAINT [PK_NV_STATUS_REQ] PRIMARY KEY CLUSTERED 
(
	[REQ_KIND] ASC,
	[CREATE_TM] ASC,
	[TASK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
