USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVDOMAINLOG](
	[CAMPAIGN_NO] [numeric](15, 0) NOT NULL,
	[RESULT_SEQ] [numeric](16, 0) NOT NULL,
	[DOMAIN_NM] [varchar](50) NOT NULL,
	[ERROR_CD] [varchar](4) NOT NULL,
	[SEND_CNT] [numeric](10, 0) NULL,
 CONSTRAINT [PK_NVDOMAINLOG] PRIMARY KEY CLUSTERED 
(
	[CAMPAIGN_NO] ASC,
	[RESULT_SEQ] ASC,
	[DOMAIN_NM] ASC,
	[ERROR_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVDOMAINLOG]  WITH CHECK ADD  CONSTRAINT [FK_SENDERR_DOMAINLOG] FOREIGN KEY([ERROR_CD])
REFERENCES [dbo].[NVSENDERR] ([ERROR_CD])
GO
ALTER TABLE [dbo].[NVDOMAINLOG] CHECK CONSTRAINT [FK_SENDERR_DOMAINLOG]
GO
ALTER TABLE [dbo].[NVDOMAINLOG]  WITH CHECK ADD  CONSTRAINT [FK_SENDRESULT_DOMAINLOG] FOREIGN KEY([CAMPAIGN_NO], [RESULT_SEQ])
REFERENCES [dbo].[NVSENDRESULT] ([CAMPAIGN_NO], [RESULT_SEQ])
GO
ALTER TABLE [dbo].[NVDOMAINLOG] CHECK CONSTRAINT [FK_SENDRESULT_DOMAINLOG]
GO
