USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVECMSCHEDULE](
	[ECMSCHEDULE_NO] [numeric](5, 0) NOT NULL,
	[ECMSCHEDULE_NM] [varchar](50) NULL,
	[CYCLE_CD] [char](1) NULL,
	[SENDSTART_DT] [char](8) NULL,
	[SENDEND_DT] [char](8) NULL,
	[INVOKE_TM] [char](6) NULL,
	[INVOKE_EVERY_MIN] [char](1) NULL,
	[DAY] [numeric](2, 0) NULL,
	[SCHE_WEEKNUMBER] [numeric](1, 0) NULL,
	[WEEKDAY] [varchar](10) NULL,
	[START_TM] [char](6) NULL,
	[END_TM] [char](6) NULL,
	[TERM_MIN] [char](2) NULL,
 CONSTRAINT [PK_NVECMSCHEDULE] PRIMARY KEY CLUSTERED 
(
	[ECMSCHEDULE_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVECMSCHEDULE]  WITH CHECK ADD  CONSTRAINT [FK_SENDCYCLE_ECMSCHEDULE] FOREIGN KEY([CYCLE_CD])
REFERENCES [dbo].[NVSENDCYCLE] ([CYCLE_CD])
GO
ALTER TABLE [dbo].[NVECMSCHEDULE] CHECK CONSTRAINT [FK_SENDCYCLE_ECMSCHEDULE]
GO
