USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVECARESENDRESULT](
	[ECARE_NO] [numeric](15, 0) NOT NULL,
	[RESULT_SEQ] [numeric](16, 0) NOT NULL,
	[RESULT_DESC] [varchar](250) NULL,
	[RESULT_STS] [char](2) NULL,
	[START_DT] [char](8) NULL,
	[START_TM] [char](6) NULL,
	[END_DT] [char](8) NULL,
	[END_TM] [char](6) NULL,
	[TARGET_CNT] [numeric](10, 0) NULL,
	[SEND_CNT] [numeric](10, 0) NULL,
	[SUCCESS_CNT] [numeric](10, 0) NULL,
	[FAIL_CNT] [numeric](10, 0) NULL,
	[UNKNOWN_USER_CNT] [numeric](10, 0) NULL,
	[UNKNOWN_HOST_CNT] [numeric](10, 0) NULL,
	[SMTP_EXCEPT_CNT] [numeric](10, 0) NULL,
	[NO_ROUTE_CNT] [numeric](10, 0) NULL,
	[REFUSED_CNT] [numeric](10, 0) NULL,
	[ETC_EXCEPT_CNT] [numeric](10, 0) NULL,
	[INVALID_ADDRESS_CNT] [numeric](10, 0) NULL,
	[CRTGRP_CD] [varchar](12) NULL,
	[EDITOR_ID] [varchar](15) NULL,
	[LOG_STS] [char](2) NULL,
	[SUPER_SEQ] [numeric](16, 0) NULL,
	[RESEND_RETRY_CNT] [numeric](2, 0) NULL,
	[RESEND_STS] [char](1) NULL,
	[RETURNMAIL_CNT] [numeric](10, 0) NULL,
	[MANUALBATCH_STS] [char](1) NULL,
	[TMPL_VER] [numeric](5, 0) NOT NULL,
	[COVER_VER] [numeric](5, 0) NOT NULL,
	[PREFACE_VER] [numeric](5, 0) NOT NULL,
	[HANDLER_VER] [numeric](5, 0) NOT NULL,
	[CHANNEL] [varchar](1) NOT NULL,
 CONSTRAINT [PK_NVECARESENDRESULT] PRIMARY KEY CLUSTERED 
(
	[ECARE_NO] ASC,
	[RESULT_SEQ] ASC,
	[CHANNEL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVECARESENDRESULT] ADD  DEFAULT ((0)) FOR [RETURNMAIL_CNT]
GO
ALTER TABLE [dbo].[NVECARESENDRESULT] ADD  DEFAULT ((0)) FOR [TMPL_VER]
GO
ALTER TABLE [dbo].[NVECARESENDRESULT] ADD  DEFAULT ((0)) FOR [COVER_VER]
GO
ALTER TABLE [dbo].[NVECARESENDRESULT] ADD  DEFAULT ((0)) FOR [PREFACE_VER]
GO
ALTER TABLE [dbo].[NVECARESENDRESULT] ADD  DEFAULT ((0)) FOR [HANDLER_VER]
GO
ALTER TABLE [dbo].[NVECARESENDRESULT] ADD  DEFAULT ('A') FOR [CHANNEL]
GO
ALTER TABLE [dbo].[NVECARESENDRESULT]  WITH CHECK ADD  CONSTRAINT [FK_ECAREMSG_ECARESENDRESULT] FOREIGN KEY([ECARE_NO])
REFERENCES [dbo].[NVECAREMSG] ([ECARE_NO])
GO
ALTER TABLE [dbo].[NVECARESENDRESULT] CHECK CONSTRAINT [FK_ECAREMSG_ECARESENDRESULT]
GO
