USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVCAMPAIGN](
	[CAMPAIGN_NO] [numeric](15, 0) NOT NULL,
	[GRP_CD] [varchar](12) NULL,
	[USER_ID] [varchar](15) NULL,
	[SEGMENT_NO] [numeric](15, 0) NULL,
	[CAMPAIGN_NM] [varchar](100) NULL,
	[CAMPAIGN_DESC] [varchar](250) NULL,
	[CAMPAIGN_PREFACE] [varchar](250) NULL,
	[CAMPAIGN_STS] [char](1) NULL,
	[CREATE_DT] [char](8) NULL,
	[CREATE_TM] [char](6) NULL,
	[LASTUPDATE_DT] [char](8) NULL,
	[LASTUPDATE_TM] [char](6) NULL,
	[CAMPAIGN_TYPE] [char](1) NULL,
	[TEMPLATE_TYPE] [numeric](2, 0) NULL,
	[SENDING_STS] [char](1) NULL,
	[SENDING_CYCLE] [char](20) NULL,
	[SENDSTART_DT] [char](8) NULL,
	[SENDSTART_TM] [char](6) NULL,
	[SENDFINISH_DT] [char](8) NULL,
	[SENDFINISH_TM] [char](6) NULL,
	[TARGET_CNT] [numeric](10, 0) NULL,
	[SURVEY_END_YN] [char](1) NULL,
	[SENDING_MODE] [char](1) NULL,
	[SURVEY_RESPONSE_CNT] [numeric](10, 0) NULL,
	[SURVEY_NO] [numeric](15, 0) NULL,
	[LOG_YN] [char](1) NULL,
	[KEEPDAY] [numeric](4, 0) NULL,
	[SHARE_YN] [char](1) NULL,
	[SURVEY_START_DT] [char](8) NULL,
	[SURVEY_START_TM] [char](6) NULL,
	[SURVEY_END_DT] [char](8) NULL,
	[SURVEY_END_TM] [char](6) NULL,
	[RETRY_CNT] [numeric](2, 0) NULL,
	[RPTCREATE_DT] [char](8) NULL,
	[SENDER_NM] [varchar](50) NULL,
	[SENDER_EMAIL] [varchar](100) NULL,
	[RECEIVER_NM] [varchar](50) NULL,
	[SENDER_TEL] [varchar](50) NULL,
	[RETMAIL_RECEIVER] [varchar](100) NULL,
	[HTMLUPDATE_YN] [char](1) NULL,
	[REPORT_STS] [char](1) NULL,
	[CAMPAIGN_CLASS] [char](1) NULL,
	[CHANNEL_TYPE] [char](1) NULL,
	[RELATION_TYPE] [char](1) NULL,
	[RETMAIL_SEND_YN] [char](1) NULL,
	[ETC_INFO1] [varchar](250) NULL,
	[ETC_INFO2] [varchar](250) NULL,
	[PROMOTION_TYPE] [char](1) NULL,
	[CAMPAIGN_LEVEL] [char](1) NULL,
	[CATEGORY_CD] [varchar](12) NULL,
	[SCENARIO_NO] [numeric](15, 0) NULL,
	[DEPTH_NO] [numeric](2, 0) NULL,
	[EDITOR_ID] [varchar](15) NULL,
	[SEND_SERVER] [numeric](1, 0) NULL,
	[APPROVAL_STS] [char](1) NULL,
	[REQ_DEPT_ID] [varchar](50) NULL,
	[REQ_USER_ID] [varchar](15) NULL,
	[DIVIDE_YN] [char](1) NULL,
	[DIVIDE_INTERVAL] [numeric](8, 0) NULL,
	[DIVIDE_CNT] [numeric](10, 0) NULL,
	[AB_TEST_TYPE] [char](1) NULL,
	[AB_TEST_COND] [char](1) NULL,
	[AB_TEST_RATE] [numeric](3, 0) NULL,
	[CAMPAIGN_PREFACE_AB] [varchar](250) NULL,
 CONSTRAINT [PK_NVCAMPAIGN] PRIMARY KEY CLUSTERED 
(
	[CAMPAIGN_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVCAMPAIGN] ADD  DEFAULT ((0)) FOR [CAMPAIGN_LEVEL]
GO
ALTER TABLE [dbo].[NVCAMPAIGN] ADD  DEFAULT ((1)) FOR [DEPTH_NO]
GO
ALTER TABLE [dbo].[NVCAMPAIGN] ADD  DEFAULT ('N') FOR [DIVIDE_YN]
GO
ALTER TABLE [dbo].[NVCAMPAIGN]  WITH CHECK ADD  CONSTRAINT [FK_SEGMENT_CAMPAIGN] FOREIGN KEY([SEGMENT_NO])
REFERENCES [dbo].[NVSEGMENT] ([SEGMENT_NO])
GO
ALTER TABLE [dbo].[NVCAMPAIGN] CHECK CONSTRAINT [FK_SEGMENT_CAMPAIGN]
GO
ALTER TABLE [dbo].[NVCAMPAIGN]  WITH CHECK ADD  CONSTRAINT [FK_USER_CAMPAIGN] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[NVUSER] ([USER_ID])
GO
ALTER TABLE [dbo].[NVCAMPAIGN] CHECK CONSTRAINT [FK_USER_CAMPAIGN]
GO
ALTER TABLE [dbo].[NVCAMPAIGN]  WITH CHECK ADD  CONSTRAINT [FK_USERGRP_CAMPAIGN] FOREIGN KEY([GRP_CD])
REFERENCES [dbo].[NVUSERGRP] ([GRP_CD])
GO
ALTER TABLE [dbo].[NVCAMPAIGN] CHECK CONSTRAINT [FK_USERGRP_CAMPAIGN]
GO
