USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVUSERMAILINFO](
	[USER_ID] [varchar](15) NOT NULL,
	[SEQ_NO] [numeric](5, 0) NOT NULL,
	[SENDER_NM] [varchar](50) NULL,
	[SENDER_EMAIL] [varchar](100) NULL,
	[RECEIVER_NM] [varchar](50) NULL,
	[SENDER_TEL] [varchar](50) NULL,
	[SENDER_FAX] [varchar](50) NULL,
	[RECEIVER_FAX] [varchar](50) NULL,
	[RETMAIL_RECEIVER] [varchar](100) NULL,
 CONSTRAINT [PK_NVUSERMAILINFO] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC,
	[SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVUSERMAILINFO]  WITH CHECK ADD  CONSTRAINT [FK_USER_USERMAILINFO] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[NVUSER] ([USER_ID])
GO
ALTER TABLE [dbo].[NVUSERMAILINFO] CHECK CONSTRAINT [FK_USER_USERMAILINFO]
GO
