USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVCYCLEITEM](
	[ECMSCHEDULE_NO] [numeric](5, 0) NOT NULL,
	[CYCLEITEM] [varchar](10) NOT NULL,
	[CHECK_YN] [char](1) NULL,
 CONSTRAINT [PK_NVCYCLEITEM] PRIMARY KEY CLUSTERED 
(
	[ECMSCHEDULE_NO] ASC,
	[CYCLEITEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVCYCLEITEM]  WITH CHECK ADD  CONSTRAINT [FK_ECMSCHEDULE_CYCLEITEM] FOREIGN KEY([ECMSCHEDULE_NO])
REFERENCES [dbo].[NVECMSCHEDULE] ([ECMSCHEDULE_NO])
GO
ALTER TABLE [dbo].[NVCYCLEITEM] CHECK CONSTRAINT [FK_ECMSCHEDULE_CYCLEITEM]
GO
