USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVKAKAOPROFILE](
	[USER_ID] [varchar](15) NOT NULL,
	[KAKAO_SENDER_KEY] [varchar](40) NOT NULL,
	[KAKAO_YELLOW_ID] [varchar](50) NOT NULL,
	[LAST_SYNC_DTM] [varchar](14) NULL,
 CONSTRAINT [PK_NVKAKAOPROFILE] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC,
	[KAKAO_SENDER_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
