USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVRESENDTARGET](
	[SERVICE_NO] [numeric](15, 0) NOT NULL,
	[RESULT_SEQ] [numeric](16, 0) NOT NULL,
	[LIST_SEQ] [varchar](10) NOT NULL,
	[CLIENT] [varchar](2) NOT NULL,
	[TARGET_KEY] [varchar](100) NOT NULL,
	[TARGET_NM] [varchar](100) NULL,
	[TARGET_CONTACT] [varchar](100) NULL,
	[SEND_DT] [varchar](14) NOT NULL,
	[TARGET_LST1] [varchar](4000) NOT NULL,
	[TARGET_LST2] [varchar](4000) NULL,
 CONSTRAINT [PK_NVRESENDTARGET] PRIMARY KEY CLUSTERED 
(
	[SERVICE_NO] ASC,
	[RESULT_SEQ] ASC,
	[LIST_SEQ] ASC,
	[CLIENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
