USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVDBINFO](
	[DBINFO_SEQ] [numeric](2, 0) NOT NULL,
	[DRIVER_NM] [varchar](250) NULL,
	[SERVER_NM] [varchar](100) NULL,
	[DRIVER_DSN] [varchar](250) NULL,
	[DBUSER_ID] [varchar](30) NULL,
	[DBPASSWORD] [varchar](50) NULL,
	[ENCODING] [varchar](20) NULL,
	[DECODING] [varchar](20) NULL,
	[DBKIND] [varchar](20) NULL,
	[TESTQUERY] [varchar](250) NULL,
 CONSTRAINT [PK_NVDBINFO] PRIMARY KEY CLUSTERED 
(
	[DBINFO_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
