USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NV_TEST_GRP](
	[TEST_GRP_CD] [numeric](5, 0) NOT NULL,
	[TEST_GRP_NM] [varchar](100) NULL,
	[TEST_SUPRAGRP_CD] [numeric](5, 0) NULL,
	[USER_ID] [varchar](15) NULL,
	[ACTIVE_YN] [char](1) NULL,
 CONSTRAINT [PK_NV_TEST_GRP] PRIMARY KEY CLUSTERED 
(
	[TEST_GRP_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
