USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVMPSSENTENCEFORMAT](
	[SENTENCE_CD] [char](6) NOT NULL,
	[SENTENCE_PART] [char](1) NOT NULL,
	[FIELD_SEQ] [numeric](3, 0) NOT NULL,
	[FIELD_ID] [varchar](20) NULL,
	[FIELD_NAME] [varchar](50) NULL,
	[FIELD_DESC] [varchar](250) NULL,
	[FIELD_START] [numeric](10, 0) NULL,
	[FIELD_LENGTH] [numeric](10, 0) NULL,
	[FIELD_LOGICAL_LENGTH] [numeric](10, 0) NULL,
	[FIELD_TYPE] [char](1) NULL,
	[FIELD_PATTERN] [varchar](50) NULL,
	[ARRAY_YN] [char](1) NOT NULL,
	[ARRAY_SENTENCE_CD] [char](5) NULL,
 CONSTRAINT [PK_NVMPSSENTENCEFORMAT] PRIMARY KEY CLUSTERED 
(
	[SENTENCE_CD] ASC,
	[SENTENCE_PART] ASC,
	[FIELD_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVMPSSENTENCEFORMAT] ADD  DEFAULT ('X') FOR [FIELD_TYPE]
GO
ALTER TABLE [dbo].[NVMPSSENTENCEFORMAT] ADD  DEFAULT ('N') FOR [ARRAY_YN]
GO
