USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVECARERPTSENDRESULT](
	[ECARE_NO] [numeric](15, 0) NOT NULL,
	[RESULT_SEQ] [numeric](16, 0) NOT NULL,
	[REPORT_DT] [char](8) NOT NULL,
	[RESULT_DESC] [varchar](250) NULL,
	[RESULT_STS] [char](2) NULL,
	[TARGET_CNT] [numeric](10, 0) NULL,
	[SEND_CNT] [numeric](10, 0) NULL,
	[SUCCESS_CNT] [numeric](10, 0) NULL,
	[FAIL_CNT] [numeric](10, 0) NULL,
	[UNKNOWN_USER_CNT] [numeric](10, 0) NULL,
	[UNKNOWN_HOST_CNT] [numeric](10, 0) NULL,
	[SMTP_EXCEPT_CNT] [numeric](10, 0) NULL,
	[NO_ROUTE_CNT] [numeric](10, 0) NULL,
	[REFUSED_CNT] [numeric](10, 0) NULL,
	[ETC_EXCEPT_CNT] [numeric](10, 0) NULL,
	[INVALID_ADDRESS_CNT] [numeric](10, 0) NULL,
	[LOG_STS] [char](2) NULL,
	[RETURNMAIL_CNT] [numeric](10, 0) NULL,
	[OPEN_CNT] [numeric](10, 0) NULL,
	[DURATION_CNT] [numeric](10, 0) NULL,
	[LINK_CNT] [numeric](10, 0) NULL,
	[START_DT] [varchar](8) NULL,
	[START_TM] [varchar](6) NULL,
	[END_DT] [varchar](8) NULL,
	[END_TM] [varchar](6) NULL,
	[RESEND_STS] [char](1) NULL,
 CONSTRAINT [PK_NVECARERPTSENDRESULT] PRIMARY KEY CLUSTERED 
(
	[ECARE_NO] ASC,
	[RESULT_SEQ] ASC,
	[REPORT_DT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NVECARERPTSENDRESULT] ADD  DEFAULT ((0)) FOR [RETURNMAIL_CNT]
GO
ALTER TABLE [dbo].[NVECARERPTSENDRESULT] ADD  DEFAULT ((0)) FOR [OPEN_CNT]
GO
ALTER TABLE [dbo].[NVECARERPTSENDRESULT] ADD  DEFAULT ((0)) FOR [DURATION_CNT]
GO
ALTER TABLE [dbo].[NVECARERPTSENDRESULT] ADD  DEFAULT ((0)) FOR [LINK_CNT]
GO
