USE [SEND]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVSENTENCE](
	[CAMPAIGN_NO] [numeric](15, 0) NOT NULL,
	[SEQ] [numeric](10, 0) NOT NULL,
	[DATA_FIELD] [varchar](50) NOT NULL,
	[DATA_NAME] [varchar](50) NULL,
	[OFFSET] [numeric](5, 0) NULL,
	[LENGTH] [numeric](5, 0) NULL,
	[DATA_DESC] [varchar](100) NULL,
 CONSTRAINT [PK_NVSENTENCE] PRIMARY KEY CLUSTERED 
(
	[CAMPAIGN_NO] ASC,
	[SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
