USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COM_BBS_NOTICE](
	[MASTER_SEQ] [int] NOT NULL,
	[BOARD_SEQ] [int] NOT NULL,
	[SEQNO] [int] NOT NULL,
	[AGT_CODE] [varchar](10) NOT NULL,
	[AGT_NAME] [varchar](50) NULL,
	[EMP_CODE] [int] NULL,
 CONSTRAINT [PK_COM_BBS_NOTICE] PRIMARY KEY CLUSTERED 
(
	[AGT_CODE] ASC,
	[MASTER_SEQ] ASC,
	[BOARD_SEQ] ASC,
	[SEQNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
