USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MNU_MNG_GRP_TEMPLATE](
	[TYPE_SEQ] [int] IDENTITY(1,1) NOT NULL,
	[TYPE_NAME] [varchar](30) NULL,
	[COLS_USE_NAME] [varchar](300) NULL,
	[COLS_TITLE] [varchar](300) NULL,
	[COLS_ATTR] [varchar](300) NULL,
	[COLS_WIDTH] [varchar](300) NULL,
	[COLS_ORDER] [varchar](100) NULL,
	[TYPE_REMARK] [varchar](200) NULL,
	[NEW_CODE] [dbo].[NEW_CODE] NOT NULL,
	[NEW_DATE] [dbo].[NEW_DATE] NULL,
	[EDT_CODE] [dbo].[EDT_CODE] NULL,
	[EDT_DATE] [dbo].[EDT_DATE] NULL,
 CONSTRAINT [PK_MNU_MNG_GRP_TEMPLATE] PRIMARY KEY CLUSTERED 
(
	[TYPE_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
