USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EVT_OKCASHBAG](
	[CUS_NO] [int] NOT NULL,
	[CONSENT_YN] [varchar](1) NOT NULL,
	[CONSENT_DATE] [datetime] NOT NULL,
	[RES_CODE] [dbo].[RES_CODE] NULL,
	[OCB_CARD_NUM] [char](16) NULL,
	[CUS_CNT] [int] NULL,
	[BASE_PRICE] [int] NULL,
	[BASE_POINT] [int] NULL,
	[TOTAL_POINT] [int] NULL,
	[IS_CXL] [int] NULL,
	[NEW_CODE] [dbo].[NEW_CODE] NULL,
	[NEW_DATE] [datetime] NULL,
	[EDT_CODE] [dbo].[EDT_CODE] NULL,
	[EDT_DATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EVT_OKCASHBAG] ADD  DEFAULT ((0)) FOR [IS_CXL]
GO
