USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SMS_MASTER](
	[SEQ] [int] IDENTITY(1,1) NOT NULL,
	[CODE1] [varchar](20) NULL,
	[CODE2] [varchar](20) NULL,
	[CODE3] [varchar](20) NULL,
	[CALL_STATUS] [varchar](20) NULL,
	[CALL_MESSAGE] [varchar](100) NULL,
	[CALL_DATE] [datetime] NULL,
	[SEND_DATE] [datetime] NULL,
	[SEND_NUMBER] [varchar](13) NULL,
	[SEND_TYPE] [tinyint] NOT NULL,
	[CONTENTS] [varchar](1000) NULL,
	[HP_NUMBER1] [varchar](4) NULL,
	[HP_NUMBER2] [varchar](4) NULL,
	[HP_NUMBER3] [varchar](4) NULL,
	[NEW_CODE] [dbo].[NEW_CODE] NOT NULL,
	[NEW_DATE] [dbo].[NEW_DATE] NULL,
 CONSTRAINT [PK_SMS_MASTER] PRIMARY KEY CLUSTERED 
(
	[SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SMS_MASTER] ADD  CONSTRAINT [DF_SMS_MASTER_SEND_TYPE]  DEFAULT ((1)) FOR [SEND_TYPE]
GO
