USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMP_EMP_PASS](
	[EMP_CODE] [dbo].[EMP_CODE] NULL,
	[ORG_PASSWORD] [varchar](20) NULL,
	[ENC_PASSWORD] [varchar](100) NULL
) ON [PRIMARY]
GO
