USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMP_POINT_SUMMER_EVENT](
	[CUS_NO] [int] NULL,
	[SLEEP_YN] [char](1) NULL,
	[CUS_NAME] [varchar](20) NULL,
	[RES_STATUS] [char](1) NULL,
	[TOTAL_POINT] [decimal](18, 0) NULL,
	[SAVE_POINT] [decimal](18, 0) NULL,
	[NOR_TEL1] [varchar](5) NULL,
	[NOR_TEL2] [varchar](5) NULL,
	[NOR_TEL3] [varchar](5) NULL,
	[JOIN_DATE] [date] NULL,
	[SEND_YN] [char](1) NULL,
	[SEND_DATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TMP_POINT_SUMMER_EVENT] ADD  CONSTRAINT [DEF_TMP_POINT_SUMMER_EVENT_SLEEP_YN]  DEFAULT ('N') FOR [SLEEP_YN]
GO
ALTER TABLE [dbo].[TMP_POINT_SUMMER_EVENT] ADD  CONSTRAINT [DEF_TMP_POINT_SUMMER_EVENT_RES_STATUS]  DEFAULT ('N') FOR [RES_STATUS]
GO
ALTER TABLE [dbo].[TMP_POINT_SUMMER_EVENT] ADD  CONSTRAINT [DEF_TMP_POINT_SUMMER_EVENT_SEND_YN]  DEFAULT ('N') FOR [SEND_YN]
GO
