USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMP_MASTER_CODE_MAIN_CITY](
	[MASTER_CODE] [dbo].[MASTER_CODE] NOT NULL,
	[CITY_CODE] [char](3) NULL
) ON [PRIMARY]
GO
