USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RES_EVENT](
	[PRO_CODE] [dbo].[PRO_CODE] NULL,
	[RES_CODE] [dbo].[RES_CODE] NULL,
	[EVT_SEQ] [int] NULL,
	[EVT_ADT_PRICE] [int] NULL,
	[NEW_CODE] [char](7) NULL,
	[NEW_DATE] [datetime] NULL
) ON [PRIMARY]
GO
