USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EVT_FAMILYTOUR](
	[MASTER_CODE] [varchar](10) NOT NULL,
	[REGION_CODE] [varchar](1) NULL,
	[REGION_NAME] [varchar](200) NULL,
	[CATEGORY] [varchar](1) NULL,
	[PRICE] [varchar](100) NULL,
	[SPECIAL_POINT] [varchar](200) NULL,
	[SELL_POINT] [varchar](200) NULL,
 CONSTRAINT [PK_EVT_FAMILYTOUR] PRIMARY KEY CLUSTERED 
(
	[MASTER_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
