USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI_NOTE_RECEIPT](
	[NOTE_SEQ_NO] [dbo].[SEQ_NO] NOT NULL,
	[RCV_TYPE] [char](1) NULL,
	[EMP_CODE] [dbo].[EMP_CODE] NULL,
	[CONFIRM_DATE] [datetime] NULL,
	[SEND_DEL_YN] [char](1) NULL,
	[TEAM_NAME] [varchar](50) NULL,
	[RCV_CAT_SEQ_NO] [int] NULL,
	[CONFIRM_YN] [char](1) NULL,
	[RCV_SEQ_NO] [int] NOT NULL,
	[RCV_DEL_YN] [char](1) NULL,
	[SEND_CAT_SEQ_NO] [int] NULL,
 CONSTRAINT [PK_PRI_NOTE_RECEIPT] PRIMARY KEY CLUSTERED 
(
	[NOTE_SEQ_NO] DESC,
	[RCV_SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRI_NOTE_RECEIPT]  WITH CHECK ADD  CONSTRAINT [R_61] FOREIGN KEY([NOTE_SEQ_NO])
REFERENCES [dbo].[PRI_NOTE] ([NOTE_SEQ_NO])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRI_NOTE_RECEIPT] CHECK CONSTRAINT [R_61]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'1 : Receipt, 2 : Reference, 3 : ReSend ' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRI_NOTE_RECEIPT', @level2type=N'COLUMN',@level2name=N'RCV_TYPE'
GO
