USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_LOGIN_INFO](
	[SEQ_NO] [int] IDENTITY(1,1) NOT NULL,
	[EMP_CODE] [dbo].[EMP_CODE] NOT NULL,
	[CLIENT_IP] [varchar](20) NULL,
	[LOGIN_DATE] [datetime] NULL,
	[SERVER_IP] [varchar](20) NULL,
	[USER_AGENT] [varchar](1000) NULL,
 CONSTRAINT [PK_SYS_LOGIN_INFO] PRIMARY KEY CLUSTERED 
(
	[SEQ_NO] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
