USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IP_BAN_LIST](
	[SEQ_NO] [int] IDENTITY(1,1) NOT NULL,
	[IPADDRESS] [varchar](50) NULL,
	[NATION_CODE] [char](2) NULL,
	[BAN_COUNT] [int] NOT NULL,
	[BAN_YN] [char](1) NOT NULL,
	[CONNECT_DATE] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IP_BAN_LIST] ADD  DEFAULT ((0)) FOR [BAN_COUNT]
GO
ALTER TABLE [dbo].[IP_BAN_LIST] ADD  DEFAULT ('N') FOR [BAN_YN]
GO
