USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PUB_BANNER_CATEGORY](
	[BNR_TYPE] [int] NOT NULL,
	[BNR_PAGE] [varchar](50) NOT NULL,
	[BNR_PAGE_NAME] [varchar](100) NULL,
	[BNR_CATEGORY] [varchar](50) NOT NULL,
	[BNR_CATEGORY_NAME] [varchar](100) NULL,
	[LEVEL] [int] NULL,
	[ORDER_NO] [int] NULL,
	[NEW_DATE] [dbo].[NEW_DATE] NULL,
	[NEW_CODE] [dbo].[NEW_CODE] NOT NULL,
	[EDT_DATE] [dbo].[EDT_DATE] NULL,
	[EDT_CODE] [dbo].[EDT_CODE] NULL
) ON [PRIMARY]
GO
