USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EVT_PROMOTION_DETAIL_RECOMMENDED](
	[SEC_SEQ] [int] NOT NULL,
	[SEQ_NO] [int] NOT NULL,
	[CUS_NO] [int] NULL,
	[IPADDRESS] [varchar](50) NULL,
	[NEW_DATE] [datetime] NOT NULL
) ON [PRIMARY]
GO
