USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PKG_TMP_SCH_DAY](
	[PRO_CODE] [varchar](13) NOT NULL,
	[SCH_SEQ] [int] NOT NULL,
	[DAY_SEQ] [int] NOT NULL,
	[DAY_NUMBER] [int] NULL
) ON [PRIMARY]
GO
