USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SECURITY_VIEW](
	[EMP_CODE] [dbo].[EMP_CODE] NOT NULL,
	[EDI_CODE] [dbo].[EDI_CODE] NOT NULL,
	[SEQ] [varchar](10) NOT NULL,
	[NEW_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_SECURITY_VIEW] PRIMARY KEY CLUSTERED 
(
	[EMP_CODE] ASC,
	[EDI_CODE] ASC,
	[SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
