USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMP_ST_AIRLINE](
	[AIRLINE_NAME] [varchar](40) NULL,
	[AIRLINE_CODE] [varchar](40) NULL
) ON [PRIMARY]
GO
