USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACC_JUNL](
	[JUNL_FG] [varchar](2) NOT NULL,
	[JUNL_CD] [varchar](10) NOT NULL,
	[JUNL_CD_NM] [varchar](40) NULL,
	[USE_ACC_CD1] [varchar](10) NULL,
	[USE_ACC_CD2] [varchar](10) NULL,
	[REMARK] [varchar](100) NULL,
	[DEL_YN] [char](1) NULL,
 CONSTRAINT [PK_ACC_JUNL] PRIMARY KEY CLUSTERED 
(
	[JUNL_FG] ASC,
	[JUNL_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_JUNL] ADD  DEFAULT ('N') FOR [DEL_YN]
GO
