USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROAD_ADDR_JIBUN](
	[관리번호] [varchar](25) NOT NULL,
	[일련번호] [int] NOT NULL,
	[법정동코드] [varchar](10) NULL,
	[시도명] [varchar](20) NULL,
	[시군구명] [varchar](20) NULL,
	[법정읍면동명] [varchar](20) NULL,
	[법정리명] [varchar](20) NULL,
	[산여부] [char](1) NULL,
	[지번본번] [int] NULL,
	[지번부번] [int] NULL,
	[대표여부] [char](1) NULL,
 CONSTRAINT [ROAD_ADDR_JIBUN_PK1] PRIMARY KEY CLUSTERED 
(
	[관리번호] ASC,
	[일련번호] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ROAD_ADDR_JIBUN]  WITH CHECK ADD  CONSTRAINT [ROAD_ADDR_JIBUN_FK1] FOREIGN KEY([관리번호])
REFERENCES [dbo].[ROAD_ADDR] ([관리번호])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ROAD_ADDR_JIBUN] CHECK CONSTRAINT [ROAD_ADDR_JIBUN_FK1]
GO
