USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACC_CHECKCHA](
	[ACCT_CODE] [char](5) NOT NULL,
	[SERIAL_NO] [numeric](5, 0) NOT NULL,
	[CHECK_CODE] [char](3) NULL,
 CONSTRAINT [PK_ACC_CHECKCHA] PRIMARY KEY CLUSTERED 
(
	[ACCT_CODE] ASC,
	[SERIAL_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
