USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMP_OVER_IMAGE](
	[SEQ] [int] IDENTITY(1,1) NOT NULL,
	[CODE] [varchar](20) NULL,
	[IMG_URL] [varchar](500) NULL
) ON [PRIMARY]
GO
