USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VR_CONTENT](
	[CONTENT_NO] [int] IDENTITY(1,1) NOT NULL,
	[VR_NO] [int] NOT NULL,
	[MASTER_CODE] [varchar](10) NOT NULL,
	[CONTENT_ORDER] [int] NULL,
 CONSTRAINT [PK_VR_CONTENT] PRIMARY KEY CLUSTERED 
(
	[CONTENT_NO] ASC,
	[VR_NO] ASC,
	[MASTER_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VR_CONTENT]  WITH CHECK ADD  CONSTRAINT [R_VR_CONTENT1] FOREIGN KEY([MASTER_CODE])
REFERENCES [dbo].[PKG_MASTER] ([MASTER_CODE])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[VR_CONTENT] CHECK CONSTRAINT [R_VR_CONTENT1]
GO
ALTER TABLE [dbo].[VR_CONTENT]  WITH CHECK ADD  CONSTRAINT [R_VR_CONTENT2] FOREIGN KEY([VR_NO])
REFERENCES [dbo].[VR_MASTER] ([VR_NO])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[VR_CONTENT] CHECK CONSTRAINT [R_VR_CONTENT2]
GO
