USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUS_MEMBER_OPTION](
	[CUS_NO] [int] NOT NULL,
	[PUSH_YN] [char](1) NULL,
	[CUVE_YN] [char](1) NULL,
	[FONT_SIZE] [int] NULL,
	[NEW_CODE] [char](7) NOT NULL,
	[NEW_DATE] [datetime] NULL,
 CONSTRAINT [PK_CUS_MEMBER_OPTION] PRIMARY KEY CLUSTERED 
(
	[CUS_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUS_MEMBER_OPTION]  WITH CHECK ADD  CONSTRAINT [R_598] FOREIGN KEY([CUS_NO])
REFERENCES [dbo].[CUS_MEMBER] ([CUS_NO])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CUS_MEMBER_OPTION] CHECK CONSTRAINT [R_598]
GO
