USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACC_DSR_SLIP](
	[TICKET] [varchar](10) NOT NULL,
	[SLIP_MK_DAY] [char](8) NULL,
	[SLIP_MK_SEQ] [smallint] NULL,
	[INS_DT] [datetime] NULL,
 CONSTRAINT [PK_ACC_DSR_SLIP] PRIMARY KEY CLUSTERED 
(
	[TICKET] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_DSR_SLIP] ADD  DEFAULT (getdate()) FOR [INS_DT]
GO
