USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUS_CONSULT_PRODUCT](
	[PRO_CODE] [varchar](20) NOT NULL,
	[CON_NO] [int] NOT NULL,
 CONSTRAINT [PK_CUS_CONSULT_PRODUCT] PRIMARY KEY CLUSTERED 
(
	[PRO_CODE] ASC,
	[CON_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUS_CONSULT_PRODUCT]  WITH CHECK ADD  CONSTRAINT [R_154] FOREIGN KEY([CON_NO])
REFERENCES [dbo].[CUS_CONSULT] ([CON_NO])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CUS_CONSULT_PRODUCT] CHECK CONSTRAINT [R_154]
GO
