USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MNU_MNG_ITEM_SCH](
	[SITE_CODE] [varchar](3) NOT NULL,
	[MENU_CODE] [varchar](20) NOT NULL,
	[SEC_CODE] [varchar](4) NOT NULL,
	[GRP_SEQ] [int] NOT NULL,
	[ITEM_SEQ] [int] NOT NULL,
	[START_DATE] [datetime] NULL,
	[END_DATE] [datetime] NULL,
	[DAY_START_TIME] [char](8) NULL,
	[DAY_END_TIME] [char](8) NULL,
	[SHOW_DAY] [char](7) NULL,
	[NEW_CODE] [dbo].[NEW_CODE] NOT NULL,
	[NEW_DATE] [dbo].[NEW_DATE] NULL,
	[EDT_CODE] [dbo].[EDT_CODE] NULL,
	[EDT_DATE] [dbo].[EDT_DATE] NULL,
 CONSTRAINT [PK_MNU_MNG_ITEM_SCH] PRIMARY KEY CLUSTERED 
(
	[SITE_CODE] ASC,
	[MENU_CODE] ASC,
	[SEC_CODE] ASC,
	[GRP_SEQ] ASC,
	[ITEM_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MNU_MNG_ITEM_SCH] ADD  CONSTRAINT [DEF_MNU_MNG_ITEM_SCH_START_DATE]  DEFAULT ('1900-01-01') FOR [START_DATE]
GO
ALTER TABLE [dbo].[MNU_MNG_ITEM_SCH] ADD  CONSTRAINT [DEF_MNU_MNG_ITEM_SCH_END_DATE]  DEFAULT ('2999-01-01') FOR [END_DATE]
GO
ALTER TABLE [dbo].[MNU_MNG_ITEM_SCH] ADD  CONSTRAINT [DEF_MNU_MNG_ITEM_SCH_DAY_START_TIME]  DEFAULT ('00:00:00') FOR [DAY_START_TIME]
GO
ALTER TABLE [dbo].[MNU_MNG_ITEM_SCH] ADD  CONSTRAINT [DEF_MNU_MNG_ITEM_SCH_DAY_END_TIME]  DEFAULT ('23:59:59') FOR [DAY_END_TIME]
GO
