USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DBChange_Log](
	[Idx] [int] IDENTITY(1,1) NOT NULL,
	[Obj_Name] [varchar](100) NULL,
	[Gubun] [varchar](20) NULL,
	[SQLCMD] [nvarchar](max) NULL,
	[Writer] [varchar](20) NULL,
	[WDate] [datetime] NULL,
 CONSTRAINT [PK_DBChange_Log] PRIMARY KEY CLUSTERED 
(
	[Idx] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
