USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI_NOTE_ATTACH](
	[NOTE_SEQ_NO] [dbo].[SEQ_NO] NOT NULL,
	[FILE_NAME] [varchar](100) NULL,
	[FILE_URL] [varchar](200) NULL,
	[FILE_SEQ_NO] [int] NOT NULL,
 CONSTRAINT [PK_PRI_NOTE_ATTACH] PRIMARY KEY CLUSTERED 
(
	[NOTE_SEQ_NO] ASC,
	[FILE_SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRI_NOTE_ATTACH]  WITH CHECK ADD  CONSTRAINT [R_65] FOREIGN KEY([NOTE_SEQ_NO])
REFERENCES [dbo].[PRI_NOTE] ([NOTE_SEQ_NO])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRI_NOTE_ATTACH] CHECK CONSTRAINT [R_65]
GO
