USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RES_CUSTOMER_damo_BACKUP](
	[RES_CODE] [char](12) NOT NULL,
	[SEQ_NO] [int] NOT NULL,
	[RES_STATE] [int] NULL,
	[SEAT_YN] [char](1) NULL,
	[CUS_TYPE] [int] NULL,
	[CUS_GRADE] [int] NULL,
	[CUS_NO] [int] NULL,
	[CUS_NAME] [varchar](40) NULL,
	[LAST_NAME] [varchar](20) NULL,
	[FIRST_NAME] [varchar](20) NULL,
	[AGE_TYPE] [int] NULL,
	[GENDER] [char](1) NULL,
	[SOC_NUM1] [varchar](6) NULL,
	[NOR_TEL1] [varchar](6) NULL,
	[NOR_TEL2] [varchar](5) NULL,
	[NOR_TEL3] [varchar](4) NULL,
	[EMAIL] [varchar](40) NULL,
	[NATIONAL] [char](2) NULL,
	[APIS_YN] [char](1) NOT NULL,
	[VISA_YN] [char](1) NULL,
	[PASS_YN] [char](1) NULL,
	[PASS_EXPIRE] [datetime] NULL,
	[PASS_ISSUE] [datetime] NULL,
	[SALE_PRICE] [int] NULL,
	[CHG_PRICE] [int] NULL,
	[DC_PRICE] [int] NULL,
	[TAX_PRICE] [int] NULL,
	[PENALTY_PRICE] [int] NULL,
	[PENALTY_YN] [char](1) NULL,
	[CHG_REMARK] [nvarchar](max) NULL,
	[SENDING_REMARK] [nvarchar](1000) NULL,
	[ROOMING_REMARK] [nvarchar](1000) NULL,
	[ETC_REMARK] [nvarchar](1000) NULL,
	[RETURN_YN] [char](1) NULL,
	[ROOMING] [varchar](2) NULL,
	[POINT_PRICE] [int] NULL,
	[POINT_YN] [char](1) NULL,
	[POINT_REF] [int] NULL,
	[CUS_INS_YN] [char](1) NULL,
	[INS_CODE] [varchar](10) NULL,
	[INS_SEQ] [int] NULL,
	[INS_PRICE] [int] NULL,
	[INS_DAY] [int] NULL,
	[COMM_YN] [char](1) NULL,
	[NEW_CODE] [dbo].[NEW_CODE] NOT NULL,
	[NEW_DATE] [datetime] NULL,
	[EDT_CODE] [dbo].[EDT_CODE] NULL,
	[EDT_DATE] [datetime] NULL,
	[CXL_DATE] [datetime] NULL,
	[CXL_CODE] [char](7) NULL,
	[MOV_RES_CODE] [char](12) NULL,
	[COMM_RATE] [decimal](13, 1) NULL,
	[COMM_AMT] [decimal](13, 0) NULL,
	[POINT_RATE] [decimal](4, 2) NULL,
	[row_id] [uniqueidentifier] NULL,
	[sec_SOC_NUM2] [varbinary](16) NULL,
	[sec1_SOC_NUM2] [varchar](28) NULL,
	[sec_PASS_NUM] [varbinary](32) NULL,
	[IPIN_DUP_INFO] [char](64) NULL,
	[IPIN_CONN_INFO] [char](88) NULL,
	[CALL_CODE] [char](7) NULL,
	[CALL_DATE] [datetime] NULL,
	[VIEW_YN] [char](1) NULL,
	[FIRST_QCHARGE] [int] NULL,
	[FIRST_QCHARGE_DATE] [datetime] NULL,
	[BIRTH_DATE] [datetime] NULL,
	[PPT_NO] [int] NULL,
	[FILE_NO] [int] NULL,
	[FAX_SEQ] [char](17) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
