USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IPADDRESS_COUNTRY_IP](
	[SEQ_NO] [int] NOT NULL,
	[START_NUM] [bigint] NOT NULL,
	[END_NUM] [bigint] NOT NULL
) ON [PRIMARY]
GO
