USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BBS_MASTER_AGT_LINK](
	[MASTER_SEQ] [dbo].[SEQ_NO] NOT NULL,
	[AGT_CODE] [varchar](10) NULL,
	[USE_YN] [char](18) NULL,
 CONSTRAINT [PK_BBS_MASTER_AGT_LINK] PRIMARY KEY CLUSTERED 
(
	[MASTER_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BBS_MASTER_AGT_LINK]  WITH CHECK ADD  CONSTRAINT [R_390] FOREIGN KEY([MASTER_SEQ])
REFERENCES [dbo].[BBS_MASTER] ([MASTER_SEQ])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[BBS_MASTER_AGT_LINK] CHECK CONSTRAINT [R_390]
GO
ALTER TABLE [dbo].[BBS_MASTER_AGT_LINK]  WITH CHECK ADD  CONSTRAINT [R_391] FOREIGN KEY([AGT_CODE])
REFERENCES [dbo].[AGT_MASTER] ([AGT_CODE])
GO
ALTER TABLE [dbo].[BBS_MASTER_AGT_LINK] CHECK CONSTRAINT [R_391]
GO
