USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[POPULAR_KEYWORD](
	[KEYWORD_NO] [int] IDENTITY(1,1) NOT NULL,
	[AGE] [int] NULL,
	[KEYWORD] [varchar](50) NULL,
	[KEYWORD_ORDER] [int] NULL,
	[NEW_CODE] [char](7) NOT NULL,
	[NEW_DATE] [datetime] NULL,
 CONSTRAINT [PK_POPULAR_KEYWORD] PRIMARY KEY CLUSTERED 
(
	[KEYWORD_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
