USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEVICE_MASTER](
	[DEVICE_SEQ_NO] [int] IDENTITY(1,1) NOT NULL,
	[APP_CODE] [int] NOT NULL,
	[CUS_NO] [int] NULL,
	[DEVICE_NO] [varchar](512) NOT NULL,
	[CUS_DEVICE_ID] [varchar](4000) NULL,
	[SEND_DATE] [datetime] NULL,
	[SEND_RESULT] [varchar](20) NULL,
	[REMARK] [varchar](2000) NULL,
	[NEW_CODE] [char](7) NOT NULL,
	[NEW_DATE] [datetime] NULL,
 CONSTRAINT [PK_DEVICE_MASTER] PRIMARY KEY CLUSTERED 
(
	[DEVICE_SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEVICE_MASTER]  WITH CHECK ADD  CONSTRAINT [R_APP_MASTER_TO_DEVICE_MASTER] FOREIGN KEY([APP_CODE])
REFERENCES [dbo].[APP_MASTER] ([APP_CODE])
GO
ALTER TABLE [dbo].[DEVICE_MASTER] CHECK CONSTRAINT [R_APP_MASTER_TO_DEVICE_MASTER]
GO
ALTER TABLE [dbo].[DEVICE_MASTER]  WITH CHECK ADD  CONSTRAINT [R_CUS_CUSTOMER_TO_DEVICE_MASTER] FOREIGN KEY([CUS_NO])
REFERENCES [dbo].[CUS_CUSTOMER_damo] ([CUS_NO])
GO
ALTER TABLE [dbo].[DEVICE_MASTER] CHECK CONSTRAINT [R_CUS_CUSTOMER_TO_DEVICE_MASTER]
GO
