USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EVT_EMAIL_PROMOTION](
	[SEQ_NO] [int] IDENTITY(1,1) NOT NULL,
	[CUS_NO] [int] NULL,
	[EMAIL] [varchar](300) NULL,
	[NEW_DATE] [dbo].[NEW_DATE] NULL,
	[CUS_NAME] [varchar](20) NULL,
	[NOR_TEL1] [varchar](6) NULL,
	[NOR_TEL2] [varchar](5) NULL,
	[NOR_TEL3] [varchar](4) NULL,
	[SITE_URL] [varchar](50) NULL,
	[AFF_TYPE] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EVT_EMAIL_PROMOTION] ADD  CONSTRAINT [DEF_EVT_EMAIL_PROMOTION_CUS_NO]  DEFAULT ((0)) FOR [CUS_NO]
GO
