USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AIRLINE_QCHARGE_220519_BAK](
	[AIRLINE_CODE] [dbo].[AIRLINE_CODE] NOT NULL,
	[GROUP_SEQ] [int] NOT NULL,
	[REGION_SEQ] [int] NOT NULL,
	[QCHARGE_SEQ] [int] NOT NULL,
	[START_DATE] [datetime] NULL,
	[END_DATE] [datetime] NULL,
	[QCHARGE_PRICE] [decimal](10, 0) NULL,
	[NEW_CODE] [dbo].[NEW_CODE] NOT NULL,
	[NEW_DATE] [dbo].[NEW_DATE] NULL,
	[ADT_QCHARGE] [int] NULL,
	[CHD_QCHARGE] [int] NULL,
	[INF_QCHARGE] [int] NULL,
	[EDT_DATE] [datetime] NULL,
	[EDT_CODE] [dbo].[EMP_CODE] NULL
) ON [PRIMARY]
GO
