USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_CITY_CONNECT](
	[CITY_CODE] [char](3) NOT NULL,
	[SUP_CODE] [varchar](10) NOT NULL,
	[PROVIDER_CITY_CODE] [varchar](5) NOT NULL,
 CONSTRAINT [PK_HTL_CITY_CONNECT] PRIMARY KEY CLUSTERED 
(
	[CITY_CODE] ASC,
	[SUP_CODE] ASC,
	[PROVIDER_CITY_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
