USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COM_CURRENCY_CODE](
	[SEQ_NO] [int] IDENTITY(1,1) NOT NULL,
	[CURRENCY_CODE] [varchar](3) NULL,
	[CURRENCY_KOR] [varchar](10) NULL,
	[CODE_KOR] [varchar](30) NULL,
	[USE_YN] [varchar](1) NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_COM_CURRENCY_CODE] PRIMARY KEY CLUSTERED 
(
	[SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
