USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TEMP_CUSTOMER_BIRTH](
	[ROWNUMBER] [int] NULL,
	[CUS_NAME] [varchar](20) NULL,
	[BIRTH_DATE] [date] NULL,
	[BIRTH_COUNT] [int] NULL
) ON [PRIMARY]
GO
