USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EVT_EMAIL_PROMOTION_TVCF](
	[SEQ_NO] [int] NOT NULL,
	[CF_SEQ] [int] NOT NULL,
	[CONTENTS] [nvarchar](50) NULL,
	[EMAIL] [varchar](50) NULL,
	[NEW_DATE] [datetime] NULL,
 CONSTRAINT [PK_EVT_EMAIL_PROMOTION_TVCF] PRIMARY KEY CLUSTERED 
(
	[SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EVT_EMAIL_PROMOTION_TVCF] ADD  CONSTRAINT [DEF_EVT_EMAIL_PROMOTION_TVCF_NEW_DATE]  DEFAULT (getdate()) FOR [NEW_DATE]
GO
