USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUS_VIP_BENEFIT](
	[VIP_YEAR] [int] NOT NULL,
	[CUS_GRADE] [int] NOT NULL,
	[BEN_TYPE] [int] NOT NULL,
	[BEN_NAME] [nvarchar](20) NULL,
	[BEN_VALUE] [decimal](5, 2) NULL,
	[BEN_REMARK] [nvarchar](50) NULL,
 CONSTRAINT [PK_CUS_VIP_BENEFIT] PRIMARY KEY CLUSTERED 
(
	[VIP_YEAR] ASC,
	[CUS_GRADE] ASC,
	[BEN_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
