USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AIRLINE_TEMP](
	[TEAM_NAME] [varchar](28) NOT NULL,
	[TEAM_CODE] [int] NOT NULL,
	[AIRLINE_CODE] [varchar](2) NOT NULL,
	[COUNTER] [varchar](1) NOT NULL,
	[COUNTER_CODE] [int] NOT NULL
) ON [PRIMARY]
GO
