USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FIT_SCH_CONTENT](
	[CUS_NO] [dbo].[CUS_NO] NOT NULL,
	[SCH_SEQ] [int] NOT NULL,
	[DAY_SEQ] [int] NOT NULL,
	[CITY_SEQ] [int] NOT NULL,
	[CNT_SEQ] [int] NOT NULL,
	[CNT_CODE] [int] NULL,
	[CNT_INFO] [nvarchar](max) NULL,
	[CNT_NAME] [nvarchar](100) NULL,
	[USER_YN] [varchar](20) NULL,
 CONSTRAINT [PK_FIT_SCH_CONTENT] PRIMARY KEY CLUSTERED 
(
	[CITY_SEQ] ASC,
	[DAY_SEQ] ASC,
	[SCH_SEQ] ASC,
	[CUS_NO] ASC,
	[CNT_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[FIT_SCH_CONTENT]  WITH CHECK ADD  CONSTRAINT [FK__FIT_SCH_CONTENT__75785BC3] FOREIGN KEY([CUS_NO], [SCH_SEQ], [DAY_SEQ], [CITY_SEQ])
REFERENCES [dbo].[FIT_SCH_CITY] ([CUS_NO], [SCH_SEQ], [DAY_SEQ], [CITY_SEQ])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[FIT_SCH_CONTENT] CHECK CONSTRAINT [FK__FIT_SCH_CONTENT__75785BC3]
GO
