USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_MASTER_MAP_NAVER](
	[HTL_MASTER_CODE] [varchar](20) NULL,
	[N_HOTEL_ID] [int] NULL,
	[SHOW_ORDER] [int] NULL,
	[NEW_DATE] [dbo].[NEW_DATE] NULL
) ON [PRIMARY]
GO
