USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMP_CHECK_PROCODE](
	[PRO_CODE] [varchar](20) NULL,
	[TOTAL_PRICE] [int] NULL,
	[TOTAL_PRICE_TOP] [int] NULL,
	[DIFF_PRICE] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TMP_CHECK_PROCODE] ADD  DEFAULT ((0)) FOR [TOTAL_PRICE]
GO
ALTER TABLE [dbo].[TMP_CHECK_PROCODE] ADD  DEFAULT ((0)) FOR [TOTAL_PRICE_TOP]
GO
ALTER TABLE [dbo].[TMP_CHECK_PROCODE] ADD  DEFAULT ((0)) FOR [DIFF_PRICE]
GO
