USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUS_VIP_HISTORY](
	[SEQ_NO] [int] IDENTITY(1,1) NOT NULL,
	[VIP_YEAR] [int] NOT NULL,
	[CUS_NO] [int] NOT NULL,
	[CUS_GRADE] [int] NOT NULL,
	[CUS_GRADE_NAME] [varchar](20) NOT NULL,
	[NEW_DATE] [datetime] NOT NULL,
	[EDT_DATE] [datetime] NULL,
	[EDT_CODE] [char](7) NULL,
	[REMARK] [varchar](100) NULL,
 CONSTRAINT [PK_CUS_VIP_HISTORY] PRIMARY KEY CLUSTERED 
(
	[SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUS_VIP_HISTORY] ADD  DEFAULT (getdate()) FOR [NEW_DATE]
GO
