USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMP_RTS_CITY](
	[CITY_CODE] [nvarchar](255) NULL,
	[CITY_NAME] [nvarchar](255) NULL,
	[NATION_CODE] [nvarchar](255) NULL,
	[MAPPING_CITY_CODE] [nvarchar](255) NULL
) ON [PRIMARY]
GO
