USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EST_PRO_CATEGORY_MAP](
	[MASTER_CODE] [dbo].[MASTER_CODE] NULL,
	[EST_CATE_SCODE] [varchar](10) NULL
) ON [PRIMARY]
GO
