USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COM_BBS_DETAIL](
	[AGT_CODE] [varchar](10) NULL,
	[MASTER_SEQ] [int] NOT NULL,
	[BOARD_SEQ] [int] NOT NULL,
	[CATEGORY_SEQ] [int] NOT NULL,
	[REQUEST_SEQ] [int] NULL,
	[PARENT_SEQ] [int] NOT NULL,
	[BT_CODE] [varchar](20) NULL,
	[SUBJECT] [nvarchar](200) NULL,
	[CONTENTS] [text] NULL,
	[SHOW_COUNT] [int] NULL,
	[NOTICE_YN] [char](1) NULL,
	[DEL_YN] [char](1) NULL,
	[IP_ADDRESS] [varchar](15) NULL,
	[MASTER_CODE] [int] NULL,
	[REGION_CODE] [varchar](20) NULL,
	[NATION_CODE] [varchar](20) NULL,
	[STATUS] [varchar](1) NULL,
	[NEW_DATE] [datetime] NOT NULL,
	[NEW_SEQ] [int] NULL,
	[EDT_DATE] [datetime] NULL,
	[EDT_SEQ] [int] NULL,
	[EMP_CODE] [int] NULL,
	[SEARCH_PK] [int] IDENTITY(1,1) NOT NULL,
	[ALL_NOTICE_YN] [char](1) NULL,
 CONSTRAINT [PK_COM_BBS_DETAIL] PRIMARY KEY CLUSTERED 
(
	[MASTER_SEQ] ASC,
	[BOARD_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[COM_BBS_DETAIL] ADD  CONSTRAINT [DF_COM_BBS_DETAIL_SHOW_COUNT]  DEFAULT ((0)) FOR [SHOW_COUNT]
GO
ALTER TABLE [dbo].[COM_BBS_DETAIL] ADD  CONSTRAINT [DF_COM_BBS_DETAIL_DEL_YN]  DEFAULT ('N') FOR [DEL_YN]
GO
ALTER TABLE [dbo].[COM_BBS_DETAIL] ADD  CONSTRAINT [DF_COM_BBS_DETAIL_NEW_DATE]  DEFAULT (getdate()) FOR [NEW_DATE]
GO
