USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PUB_NOTE](
	[EMP_CODE] [dbo].[EMP_CODE] NOT NULL,
	[SEQ_NO] [dbo].[SEQ_NO] NOT NULL,
	[CAT_SEQ_NO] [int] NULL,
	[SEND_CAT_SEQ_NO] [int] NULL,
	[SUBJECT] [varchar](100) NULL,
	[CONTENTS] [nvarchar](max) NULL,
	[FILENAME] [varchar](100) NULL,
	[SEND_DEL_YN] [char](1) NULL,
	[RECEIVE_DATE] [datetime] NULL,
	[DEL_YN] [char](1) NULL,
	[FILEURL] [varchar](200) NULL,
	[NEW_CODE] [dbo].[NEW_CODE] NOT NULL,
	[NEW_DATE] [dbo].[NEW_DATE] NULL,
 CONSTRAINT [PK_PUB_NOTE] PRIMARY KEY CLUSTERED 
(
	[EMP_CODE] ASC,
	[SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
