USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMP_GTA_CITY](
	[CITY_CODE] [varchar](5) NOT NULL,
	[CITY_NAME] [varchar](100) NULL,
	[NATION_CODE] [char](2) NULL,
	[MAPPING_CITY_CODE] [varchar](5) NULL
) ON [PRIMARY]
GO
