USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PKG_BEST_SECTION](
	[SEC_SEQ] [int] IDENTITY(1,1) NOT NULL,
	[TYPE_SEQ] [int] NULL,
	[SEC_NAME] [varchar](300) NULL,
	[SEC_TITLE] [varchar](300) NULL,
	[SEC_REMARK] [varchar](300) NULL,
	[DIV_CODE] [varchar](10) NULL,
	[MAX_CNT] [int] NULL,
	[USE_YN] [char](1) NULL,
	[ORDER_NO] [int] NULL,
	[NEW_CODE] [dbo].[NEW_CODE] NOT NULL,
	[NEW_DATE] [dbo].[NEW_DATE] NULL,
	[EDT_CODE] [dbo].[EDT_CODE] NULL,
	[EDT_DATE] [dbo].[EDT_DATE] NULL,
 CONSTRAINT [PK_PKG_BEST_SECTION] PRIMARY KEY CLUSTERED 
(
	[SEC_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
