USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PKG_DETAIL_PRICE_INOUT](
	[PRO_CODE] [varchar](20) NOT NULL,
	[PRICE_SEQ] [int] NOT NULL,
	[INOUT_CODE] [varchar](3) NULL,
	[IN_YN] [char](1) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PKG_DETAIL_PRICE_INOUT]  WITH CHECK ADD  CONSTRAINT [R_64] FOREIGN KEY([PRO_CODE])
REFERENCES [dbo].[PKG_DETAIL] ([PRO_CODE])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PKG_DETAIL_PRICE_INOUT] CHECK CONSTRAINT [R_64]
GO
