USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PUB_CITY_MAP_NAVER](
	[CITY_CODE] [varchar](3) NULL,
	[N_CITY_CODE] [varchar](3) NULL,
	[SHOW_ORDER] [int] NULL,
	[NEW_DATE] [dbo].[NEW_DATE] NULL
) ON [PRIMARY]
GO
