USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LATEST_KEYWORD](
	[CUS_NO] [int] NOT NULL,
	[KEYWORD_NO] [int] IDENTITY(1,1) NOT NULL,
	[KEYWORD] [varchar](50) NULL,
	[NEW_DATE] [datetime] NULL,
 CONSTRAINT [PK_LATEST_KEYWORD] PRIMARY KEY CLUSTERED 
(
	[CUS_NO] ASC,
	[KEYWORD_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
