USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RES_HTL_DETAIL](
	[CONTRACT_DATE] [datetime] NULL,
	[CONTRACT_YN] [char](1) NULL,
	[RES_CODE] [dbo].[RES_CODE] NOT NULL,
	[SUP_RES_CODE] [varchar](20) NULL,
	[SUP_CODE] [varchar](10) NULL,
	[CITY_CODE] [dbo].[CITY_CODE] NULL,
 CONSTRAINT [PK_RES_HTL_DETAIL] PRIMARY KEY CLUSTERED 
(
	[RES_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RES_HTL_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK__RES_HTL_D__RES_C__609D3A6E] FOREIGN KEY([RES_CODE])
REFERENCES [dbo].[RES_MASTER_damo] ([RES_CODE])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RES_HTL_DETAIL] CHECK CONSTRAINT [FK__RES_HTL_D__RES_C__609D3A6E]
GO
