USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI_NOTE](
	[NOTE_SEQ_NO] [dbo].[SEQ_NO] IDENTITY(1,1) NOT NULL,
	[SUBJECT] [varchar](300) NULL,
	[CONTENTS] [nvarchar](max) NULL,
	[NEW_CODE] [dbo].[NEW_CODE] NOT NULL,
	[NEW_DATE] [dbo].[NEW_DATE] NULL,
	[DEL_YN] [char](1) NULL,
 CONSTRAINT [PK_PRI_NOTE] PRIMARY KEY CLUSTERED 
(
	[NOTE_SEQ_NO] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRI_NOTE] ADD  CONSTRAINT [DF_PRI_NOTE_DEL_YN]  DEFAULT ('N') FOR [DEL_YN]
GO
