USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KICC_PAY_REQUEST](
	[SEQ_NO] [int] IDENTITY(1,1) NOT NULL,
	[REQ_CTR_NO] [varchar](30) NULL,
	[RES_CODE] [dbo].[RES_CODE] NULL,
	[KICC_ID] [varchar](15) NULL,
	[PAY_REQ_TYPE] [varchar](10) NULL,
	[BANK_CODE] [varchar](10) NULL,
	[ACCT_NUM] [varchar](20) NULL,
	[REQ_EXP_DATE] [datetime] NULL,
	[CUS_TEL] [varchar](20) NULL,
	[REQ_AMOUNT] [int] NULL,
	[COMP_YN] [char](1) NULL,
	[REQ_REMARK] [varchar](max) NULL,
	[NEW_CODE] [dbo].[NEW_CODE] NOT NULL,
	[NEW_DATE] [dbo].[NEW_DATE] NULL,
	[EDT_CODE] [dbo].[EDT_CODE] NULL,
	[EDT_DATE] [dbo].[EDT_DATE] NULL,
	[CUS_NAME] [varchar](20) NULL,
	[CUS_EMAIL] [varchar](40) NULL,
	[SMS_YN] [char](1) NULL,
	[RES_REMARK] [varchar](max) NULL,
	[LAST_SEND_DATE] [datetime] NULL,
	[LAST_SEND_EMP] [dbo].[EMP_CODE] NULL,
	[RES_SEQ_NO] [int] NULL,
	[DEL_YN] [char](1) NULL,
	[RES_MCH_SEQ] [int] NULL,
	[ORG_RES_CODE] [dbo].[RES_CODE] NULL,
 CONSTRAINT [PK_KICC_PAY_REQUEST] PRIMARY KEY CLUSTERED 
(
	[SEQ_NO] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
