USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APP_PUSH_MSG_ALARM_BACKUP](
	[MSG_SEQ] [int] IDENTITY(1,1) NOT NULL,
	[MSG_NO] [int] NOT NULL,
	[CUS_NO] [int] NOT NULL,
	[READ_DATE] [datetime] NULL,
	[TRAN_STATE] [varchar](1) NULL,
	[TRAN_RESULT] [varchar](500) NULL
) ON [PRIMARY]
GO
