USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WOE_PRODUCT_MASTER](
	[SEQ_NO] [int] IDENTITY(1,1) NOT NULL,
	[NATION_CODE] [char](2) NULL,
	[CITY_CODE] [char](3) NULL,
	[PRO_NAME] [varchar](200) NULL,
	[PRO_CODE] [varchar](20) NULL,
	[CONTENTS] [varchar](200) NULL,
	[PRICE] [int] NULL,
	[IMG_URL] [varchar](200) NULL,
	[URL] [varchar](400) NULL,
	[NEW_CODE] [char](7) NULL,
	[NEW_DATE] [datetime] NULL,
	[EDT_CODE] [char](7) NULL,
	[EDT_DATE] [datetime] NULL,
	[PRO_TYPE] [char](1) NULL,
	[AIRLINE_CODE] [char](2) NULL,
 CONSTRAINT [PK__WOE_PRODUCT_MAST__4A6ECD84] PRIMARY KEY CLUSTERED 
(
	[SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
