USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EST_CITY_ATTR_MAP](
	[EST_ATTR_CODE] [varchar](10) NOT NULL,
	[EST_REGION_NAME] [varchar](20) NOT NULL,
	[EST_CITY_NAME] [varchar](100) NOT NULL,
	[CITY_CODE] [char](3) NULL,
	[CITY_NAME] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[EST_ATTR_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
