USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PKG_TMP_UPDATE](
	[PRO_CODE] [varchar](13) NOT NULL,
	[SCH_SEQ] [int] NOT NULL,
	[SCH_NAME] [nvarchar](50) NULL
) ON [PRIMARY]
GO
