USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EVT_LOTTE_COUPON_damo](
	[REQ_NO] [int] IDENTITY(1,1) NOT NULL,
	[RES_CODE] [dbo].[RES_CODE] NULL,
	[SEQ_NO] [int] NULL,
	[CUS_NO] [int] NULL,
	[ISSUE_YN] [char](1) NULL,
	[ISSUE_PRICE] [int] NULL,
	[ACC_PRICE] [int] NULL,
	[ISSUE_TYPE] [int] NULL,
	[ISSUER_CODE] [char](7) NULL,
	[ISSUE_DATE] [datetime] NULL,
	[NEW_CODE] [dbo].[NEW_CODE] NOT NULL,
	[NEW_DATE] [datetime] NULL,
	[EDT_CODE] [dbo].[EDT_CODE] NULL,
	[EDT_DATE] [datetime] NULL,
	[REMARK] [varchar](200) NULL,
	[sec_PASS_NUM] [varbinary](32) NULL,
	[sec1_PASS_NUM] [varchar](80) NULL,
PRIMARY KEY CLUSTERED 
(
	[REQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
