USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUS_POINT_REFUND](
	[POINT_NO] [int] NOT NULL,
	[SEQ_NO] [int] NOT NULL,
	[RFD_SEQ_NO] [int] NOT NULL,
	[ACC_POINT_NO] [int] NULL,
	[RFD_POINT_PRICE] [money] NOT NULL,
	[NEW_CODE] [dbo].[NEW_CODE] NOT NULL,
	[NEW_DATE] [dbo].[NEW_DATE] NOT NULL,
 CONSTRAINT [PK_CUS_POINT_REFUND] PRIMARY KEY CLUSTERED 
(
	[POINT_NO] ASC,
	[SEQ_NO] ASC,
	[RFD_SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
