USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PKG_MASTER_SCH_CONTENT_TEMP](
	[MASTER_CODE] [dbo].[MASTER_CODE] NOT NULL,
	[DAY_SEQ] [int] NOT NULL,
	[CITY_SEQ] [int] NOT NULL,
	[CNT_SEQ] [int] NOT NULL,
	[CNT_CODE] [int] NULL,
	[CNT_INFO] [nvarchar](max) NULL,
	[CNT_SHOW_ORDER] [int] NULL,
 CONSTRAINT [PK_PKG_MATER_SCH_CONTENT_TEMP] PRIMARY KEY CLUSTERED 
(
	[MASTER_CODE] ASC,
	[DAY_SEQ] ASC,
	[CITY_SEQ] ASC,
	[CNT_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
