USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUVE_HISTORY](
	[HIS_NO] [int] IDENTITY(1,1) NOT NULL,
	[CUR_NO] [int] NULL,
	[HIS_TYPE] [int] NULL,
	[HIS_TITLE] [varchar](100) NULL,
	[HIS_MESSAGE] [varchar](200) NULL,
	[NEW_DATE] [datetime] NULL,
 CONSTRAINT [PK_CUVE_HISTORY] PRIMARY KEY CLUSTERED 
(
	[HIS_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUVE_HISTORY]  WITH CHECK ADD  CONSTRAINT [R_CUVE_HISTORY] FOREIGN KEY([CUR_NO])
REFERENCES [dbo].[CUR_INFO] ([CUR_NO])
GO
ALTER TABLE [dbo].[CUVE_HISTORY] CHECK CONSTRAINT [R_CUVE_HISTORY]
GO
