USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GMARKET_CITY_MAP](
	[G_CITY_CODE] [varchar](3) NOT NULL,
	[G_NATION_CODE] [varchar](2) NULL,
	[G_STATE_CODE] [varchar](3) NULL,
	[G_STATE_NAME] [varchar](100) NULL,
	[G_STATE_ENG_NAME] [varchar](100) NULL,
	[CITY_CODE] [varchar](3) NULL,
	[NATION_CODE] [varchar](2) NULL,
	[REMARK] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[G_CITY_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
