USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACC_RE_SLIP](
	[PAY_SEQ] [int] NOT NULL,
	[MCH_SEQ] [int] NOT NULL,
	[SLIP_PROC_YN] [char](1) NULL,
	[SLIP_MK_DAY] [char](8) NULL,
	[SLIP_MK_SEQ] [smallint] NULL,
	[INS_DT] [datetime] NULL,
 CONSTRAINT [PK_ACC_RE_SLIP] PRIMARY KEY CLUSTERED 
(
	[PAY_SEQ] ASC,
	[MCH_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_RE_SLIP] ADD  DEFAULT ('N') FOR [SLIP_PROC_YN]
GO
ALTER TABLE [dbo].[ACC_RE_SLIP] ADD  DEFAULT (getdate()) FOR [INS_DT]
GO
