USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROAD_ADDR_INFO](
	[관리번호] [varchar](25) NOT NULL,
	[행정동코드] [varchar](10) NULL,
	[행정동명] [varchar](20) NULL,
	[우편번호] [varchar](5) NULL,
	[우편번호일련번호] [varchar](3) NULL,
	[다량배달처명] [varchar](40) NULL,
	[건축물대장건물명] [varchar](40) NULL,
	[시군구건물명] [varchar](200) NULL,
	[공동주택여부] [char](1) NULL,
 CONSTRAINT [ROAD_ADDR_INFO_PK1] PRIMARY KEY CLUSTERED 
(
	[관리번호] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ROAD_ADDR_INFO]  WITH CHECK ADD  CONSTRAINT [ROAD_ADDR_INFO_FK1] FOREIGN KEY([관리번호])
REFERENCES [dbo].[ROAD_ADDR] ([관리번호])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ROAD_ADDR_INFO] CHECK CONSTRAINT [ROAD_ADDR_INFO_FK1]
GO
