USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PKG_MASTER_PRICE_INOUT](
	[MASTER_CODE] [varchar](10) NOT NULL,
	[PRICE_SEQ] [int] NOT NULL,
	[INOUT_CODE] [varchar](3) NULL,
	[IN_YN] [char](1) NULL
) ON [PRIMARY]
GO
