USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BACK_CHECK](
	[PRO_CODE] [dbo].[PRO_CODE] NOT NULL,
	[PRO_NAME] [dbo].[PRO_NAME] NULL,
	[MASTER_CODE] [dbo].[MASTER_CODE] NOT NULL,
	[TRANSFER_TYPE] [int] NULL,
	[SEAT_CODE] [int] NULL,
	[DEP_DATE] [datetime] NULL,
	[ARR_DATE] [datetime] NULL,
	[TOUR_NIGHT] [int] NULL,
	[TOUR_DAY] [int] NULL,
	[TOUR_JOURNEY] [nvarchar](400) NULL,
	[SEAT_STATUS] [char](2) NULL,
	[FAKE_COUNT] [int] NULL,
	[MAX_COUNT] [int] NULL,
	[MIN_COUNT] [int] NULL,
	[LAST_PAY_DATE] [datetime] NULL,
	[SENDING_YN] [char](1) NULL,
	[SENDING_DATE] [datetime] NULL,
	[TC_YN] [char](1) NULL,
	[TC_CODE] [varchar](20) NULL,
	[TC_NAME] [varchar](20) NULL,
	[RES_ADD_YN] [char](1) NULL,
	[RES_EDT_YN] [char](1) NULL,
	[DEP_CFM_YN] [char](1) NULL,
	[CONFIRM_YN] [char](1) NULL,
	[INS_CODE] [varchar](10) NULL,
	[INS_YN] [char](1) NULL,
	[VISA_YN] [char](1) NULL,
	[PASS_INFO] [varchar](200) NULL,
	[FIRST_MEET] [varchar](200) NULL,
	[SALE_TYPE] [int] NULL,
	[PRICE_TYPE] [int] NULL,
	[AIR_GDS] [int] NULL,
	[HOTEL_GDS] [int] NULL,
	[AIRLINE] [varchar](20) NULL,
	[PKG_SUMMARY] [varchar](max) NULL,
	[PKG_INC_SPECIAL] [varchar](max) NULL,
	[PKG_REVIEW] [varchar](max) NULL,
	[PKG_CONTRACT] [nvarchar](max) NULL,
	[PKG_REMARK] [nvarchar](max) NULL,
	[RES_REMARK] [nvarchar](max) NULL,
	[PKG_SHOPPING_REMARK] [nvarchar](max) NULL,
	[HOTEL_REMARK] [nvarchar](max) NULL,
	[OPTION_REMARK] [nvarchar](max) NULL,
	[SHOW_YN] [char](1) NULL,
	[NEW_CODE] [dbo].[NEW_CODE] NOT NULL,
	[NEW_DATE] [datetime] NULL,
	[EDT_CODE] [dbo].[EDT_CODE] NULL,
	[EDT_DATE] [datetime] NULL,
	[PKG_TOUR_REMARK] [varchar](8000) NULL,
	[PKG_PASSPORT_REMARK] [varchar](8000) NULL,
	[INS_DAY] [int] NULL,
	[PKG_INSIDE_REMARK] [nvarchar](1000) NULL,
	[MONITORING_YN] [char](1) NULL,
	[MONITORING_WRITE_YN] [char](1) NULL,
	[PRO_TYPE] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
