USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HBS_EMPLOYEE](
	[SEQ_NO] [int] NOT NULL,
	[EMP_CODE] [dbo].[EMP_CODE] NOT NULL,
	[USE_YN] [dbo].[USE_YN] NULL,
	[NEW_CODE] [dbo].[EMP_CODE] NULL,
	[NEW_DATE] [datetime] NULL,
	[REGION] [varchar](100) NULL,
	[CITY] [varchar](100) NULL,
	[ORDER_NUM] [int] NULL,
 CONSTRAINT [PK_HBS_EMPLOYEE] PRIMARY KEY CLUSTERED 
(
	[SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
