USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMP_ST_CITY](
	[REGION_NAME] [varchar](30) NULL,
	[CITY_NAME] [varchar](50) NULL,
	[CITY_CODE] [varchar](50) NULL
) ON [PRIMARY]
GO
