USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INF_MASTER_MAP_NAVER](
	[CNT_CODE] [int] NULL,
	[N_CNT_CODE] [varchar](30) NULL,
	[SHOW_ORDER] [int] NULL,
	[NEW_DATE] [dbo].[NEW_DATE] NULL
) ON [PRIMARY]
GO
