USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NAVER_CITY_CODE](
	[N_CITY_CODE] [varchar](3) NULL,
	[NAME_KR] [varchar](500) NULL,
	[NAME_EN] [varchar](500) NULL,
	[N_NATION_CODE] [varchar](2) NULL
) ON [PRIMARY]
GO
