USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TMP_RTS_HOTEL_XML](
	[HOTEL_CODE] [varchar](10) NOT NULL,
	[RESPONSE] [varchar](max) NULL,
	[NEW_DATE] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
