USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ARG_INVOICE_ITEM2](
	[INV_SEQ_NO] [int] IDENTITY(1,1) NOT NULL,
	[TITLE] [varchar](50) NULL,
	[SHOW_YN] [char](1) NULL
) ON [PRIMARY]
GO
