USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI_NOTE_CATEGORY](
	[CAT_SEQ_NO] [int] NOT NULL,
	[NAME] [varchar](50) NULL,
	[DEL_YN] [char](1) NULL,
	[EMP_CODE] [char](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[CAT_SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
