USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VR_MASTER](
	[VR_NO] [int] IDENTITY(1,1) NOT NULL,
	[VR_NAME] [varchar](50) NULL,
	[VR_DESC] [varchar](200) NULL,
	[REGION_CODE] [char](3) NULL,
	[VR_CREATOR] [varchar](20) NULL,
	[VR_LINK] [varchar](200) NULL,
	[VR_THUMBNAIL] [varchar](200) NULL,
	[VR_TYPE] [int] NULL,
	[NEW_CODE] [char](7) NOT NULL,
	[NEW_DATE] [datetime] NULL,
 CONSTRAINT [PK_VR_MASTER] PRIMARY KEY CLUSTERED 
(
	[VR_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
