USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EVT_LOTTE_damo](
	[EVT_NO] [int] IDENTITY(1,1) NOT NULL,
	[CUS_NAME] [varchar](20) NOT NULL,
	[SOC_NUM1] [char](6) NOT NULL,
	[NOR_TEL1] [varchar](6) NOT NULL,
	[NOR_TEL2] [varchar](5) NOT NULL,
	[NOR_TEL3] [varchar](4) NOT NULL,
	[PASS_NUM] [varchar](20) NOT NULL,
	[EMAIL] [varchar](40) NOT NULL,
	[ZIP_CODE] [varchar](7) NOT NULL,
	[ADDRESS1] [varchar](100) NOT NULL,
	[ADDRESS2] [varchar](100) NOT NULL,
	[NEW_CODE] [int] NOT NULL,
	[NEW_DATE] [datetime] NOT NULL,
	[sec_SOC_NUM2] [varbinary](16) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[EVT_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
