USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAY_COUPON](
	[RES_CODE] [dbo].[RES_CODE] NOT NULL,
	[AGT_CODE] [varchar](10) NOT NULL,
	[CPN_NO] [varchar](200) NULL,
	[DEVICE_TYPE] [char](1) NULL,
	[CPN_TITLE] [varchar](200) NULL,
	[CPN_TYPE] [char](1) NULL,
	[DC_USE_PRICE] [int] NULL,
	[DC_MAX_PRICE] [int] NULL,
	[DC_DUP_YN] [char](1) NULL,
	[DC_MAIN_COM] [char](1) NULL,
	[DC_START_DATE] [datetime] NULL,
	[DC_START_END] [datetime] NULL,
	[PAY_TARGET_PRICE] [int] NULL,
	[DC_RATE] [decimal](4, 2) NULL,
	[DC_PRICE] [decimal](12, 2) NULL,
	[COMM_RATE] [decimal](4, 2) NULL,
	[COMM_PRICE] [decimal](12, 2) NULL,
	[NEW_DATE] [datetime] NULL,
	[NEW_CODE] [dbo].[EMP_CODE] NULL,
	[PAY_SEQ] [int] NULL,
	[USE_DATE] [datetime] NULL,
	[CXL_YN] [char](1) NULL,
	[CXL_DATE] [datetime] NULL,
	[CPN_SEQ] [int] NOT NULL,
	[MCH_SEQ] [int] NULL,
 CONSTRAINT [PK_PAY_COUPON] PRIMARY KEY CLUSTERED 
(
	[RES_CODE] ASC,
	[CPN_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
