USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PKG_HOTEL_MASTER](
	[SEQ_NO] [int] IDENTITY(1,1) NOT NULL,
	[PRO_CODE] [dbo].[PRO_CODE] NULL,
	[CNT_CODE] [int] NULL,
	[MASTER_CODE_H] [dbo].[MASTER_CODE] NULL,
	[MASTER_CODE_A] [dbo].[MASTER_CODE] NULL,
	[REMARK] [varchar](200) NULL,
	[NEW_DATE] [dbo].[NEW_DATE] NULL,
	[NEW_CODE] [dbo].[EMP_CODE] NULL,
	[EDT_DATE] [datetime] NULL,
	[EDT_CODE] [dbo].[EMP_CODE] NULL
) ON [PRIMARY]
GO
