USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EVT_PROMOTION_PRODUCT](
	[SEC_SEQ] [int] NOT NULL,
	[GROUP_SEQ] [int] NOT NULL,
	[MASTER_CODE] [char](10) NOT NULL,
	[PRODUCT_FEATURES] [varchar](300) NULL,
	[REGION_NAME] [varchar](30) NULL,
	[NEW_DATE] [datetime] NOT NULL,
	[NEW_CODE] [char](7) NOT NULL,
	[EDT_DATE] [datetime] NULL,
	[EDT_CODE] [char](7) NULL,
	[VIEW_CNT] [int] NULL
) ON [PRIMARY]
GO
