USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUS_AUTH](
	[CUS_NO] [int] NOT NULL,
	[PASS_NUM] [varchar](20) NULL,
	[PASS_EXPIRE] [datetime] NULL,
	[PASS_ISSUE] [datetime] NULL,
	[SEQ_NO] [int] NOT NULL,
	[NEW_DATE] [datetime] NULL,
	[FAX_NO] [int] NULL,
	[AUTH_YN] [char](1) NULL,
	[NEW_CODE] [char](7) NOT NULL,
 CONSTRAINT [PK_CUS_AUTH] PRIMARY KEY CLUSTERED 
(
	[CUS_NO] ASC,
	[SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
