USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUS_LOGIN_INFO](
	[TOKEN] [varchar](20) NOT NULL,
	[CUS_NO] [int] NOT NULL,
	[ISVALID] [char](1) NOT NULL,
	[NEW_DATE] [datetime] NULL,
	[EDT_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[TOKEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUS_LOGIN_INFO] ADD  DEFAULT ('N') FOR [ISVALID]
GO
ALTER TABLE [dbo].[CUS_LOGIN_INFO] ADD  DEFAULT (getdate()) FOR [NEW_DATE]
GO
ALTER TABLE [dbo].[CUS_LOGIN_INFO] ADD  DEFAULT (getdate()) FOR [EDT_DATE]
GO
