USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACC_PUM_SLIP](
	[EDI_CODE] [char](10) NOT NULL,
	[SLIP_MK_DAY] [char](8) NOT NULL,
	[SLIP_MK_SEQ] [smallint] NOT NULL,
	[INS_DT] [datetime] NULL,
 CONSTRAINT [PK_ACC_PUM_SLIP] PRIMARY KEY CLUSTERED 
(
	[EDI_CODE] ASC,
	[SLIP_MK_DAY] ASC,
	[SLIP_MK_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACC_PUM_SLIP] ADD  DEFAULT (getdate()) FOR [INS_DT]
GO
