USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAY_CASH_RECEIPT_OLD_damo](
	[RECEIPT_NO] [int] IDENTITY(1,1) NOT NULL,
	[GROUP_NO] [int] NULL,
	[REQ_NO] [int] NULL,
	[REQ_VER] [int] NULL,
	[PAY_SEQ] [int] NULL,
	[MCH_SEQ] [int] NULL,
	[RES_CODE] [dbo].[RES_CODE] NULL,
	[SOC_NUM1] [varchar](6) NULL,
	[NOR_TEL1] [varchar](3) NULL,
	[NOR_TEL2] [varchar](4) NULL,
	[NOR_TEL3] [varchar](4) NULL,
	[TARGET_PRICE] [money] NULL,
	[STATUS_TYPE] [int] NULL,
	[NEW_CODE] [dbo].[EMP_CODE] NULL,
	[REQ_COMMENT] [varchar](200) NULL,
	[MNG_CODE] [dbo].[EMP_CODE] NULL,
	[MNG_COMMENT] [varchar](200) NULL,
	[NEW_DATE] [datetime] NULL,
	[EDT_DATE] [datetime] NULL,
	[REMARK] [varchar](500) NULL,
	[sec_SOC_NUM2] [varbinary](16) NULL,
	[sec1_SOC_NUM2] [varchar](28) NULL,
PRIMARY KEY CLUSTERED 
(
	[RECEIPT_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
