USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [onetime].[LOTTE_INFO_LOG](
	[IDX] [int] IDENTITY(1,1) NOT NULL,
	[RES_CODE] [char](12) NULL,
	[TEL] [varchar](15) NULL,
	[TMPL_CD] [varchar](30) NULL,
	[NEW_DATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [onetime].[LOTTE_INFO_LOG] ADD  CONSTRAINT [DF_LOTTE_INFO_LOG_NEW_DATE]  DEFAULT (getdate()) FOR [NEW_DATE]
GO
