USE [ADCGuardian_20220617]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RequestFlag](
	[ServerID] [smallint] NOT NULL,
	[SQLServerID] [smallint] NOT NULL,
	[DataListCode] [char](17) NOT NULL,
	[RequestYN] [char](1) NULL,
 CONSTRAINT [PK_RequestFlag] PRIMARY KEY CLUSTERED 
(
	[ServerID] ASC,
	[SQLServerID] ASC,
	[DataListCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RequestFlag] ADD  DEFAULT ((0)) FOR [ServerID]
GO
ALTER TABLE [dbo].[RequestFlag] ADD  DEFAULT ((0)) FOR [SQLServerID]
GO
