USE [ADCGuardian_20220617]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ServerAdminList](
	[ServerID] [smallint] NOT NULL,
	[USER_ID] [varchar](30) NOT NULL,
 CONSTRAINT [PK_ServerAdminList] PRIMARY KEY CLUSTERED 
(
	[ServerID] ASC,
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ServerAdminList]  WITH CHECK ADD  CONSTRAINT [FK_ServerAdminList_ServerList] FOREIGN KEY([ServerID])
REFERENCES [dbo].[ServerList] ([ServerID])
GO
ALTER TABLE [dbo].[ServerAdminList] CHECK CONSTRAINT [FK_ServerAdminList_ServerList]
GO
ALTER TABLE [dbo].[ServerAdminList]  WITH CHECK ADD  CONSTRAINT [FK_ServerAdminList_USER_INFO] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USER_INFO] ([USER_ID])
GO
ALTER TABLE [dbo].[ServerAdminList] CHECK CONSTRAINT [FK_ServerAdminList_USER_INFO]
GO
