USE [ADCGuardian_20220617]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DASHBOARD_ITEM](
	[ITEM_ID] [smallint] IDENTITY(1,1) NOT NULL,
	[ITEM_ALIAS_NAME] [char](30) NOT NULL,
	[ITEM_NAME] [varchar](200) NULL,
	[MIN_VALUE] [float] NOT NULL,
	[MAX_VALUE] [float] NOT NULL,
	[UNIT] [varchar](30) NOT NULL,
	[REF_TABLE] [nvarchar](128) NULL,
	[INS_DATE] [smalldatetime] NULL,
	[UPD_DATE] [smalldatetime] NULL,
 CONSTRAINT [PK_DASHBOARD_ITEM] PRIMARY KEY NONCLUSTERED 
(
	[ITEM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DASHBOARD_ITEM] ADD  DEFAULT (CONVERT([smalldatetime],getdate())) FOR [INS_DATE]
GO
