USE [ADCGuardian_20220617]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SQLConfig](
	[SQLServerID] [smallint] NOT NULL,
	[Name] [nvarchar](35) NOT NULL,
	[Minimum] [int] NOT NULL,
	[Maximum] [int] NOT NULL,
	[ConfigValue] [int] NOT NULL,
	[RunValue] [int] NOT NULL,
	[ModDate] [datetime] NULL,
 CONSTRAINT [PK_SQLConfig] PRIMARY KEY CLUSTERED 
(
	[SQLServerID] ASC,
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SQLConfig]  WITH CHECK ADD  CONSTRAINT [FK_SQLConfig_SQLServerID_for_SQLServerList] FOREIGN KEY([SQLServerID])
REFERENCES [dbo].[SQLServerList] ([SQLServerID])
GO
ALTER TABLE [dbo].[SQLConfig] CHECK CONSTRAINT [FK_SQLConfig_SQLServerID_for_SQLServerList]
GO
