USE [VGLog]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ERP_ERR_LOG](
	[SEQ_NO] [int] IDENTITY(1,1) NOT NULL,
	[CATEGORY] [varchar](20) NULL,
	[ROUTE_INFO] [varchar](200) NULL,
	[ACTION_NAME] [varchar](200) NULL,
	[SERVER_IP] [varchar](50) NULL,
	[CLIENT_IP] [varchar](50) NULL,
	[URL] [varchar](1000) NULL,
	[REF_URL] [varchar](1000) NULL,
	[USER_AGENT] [varchar](1000) NULL,
	[EMP_CODE] [char](7) NULL,
	[PARAM_DATA] [varchar](max) NULL,
	[POST_DATA] [varchar](max) NULL,
	[COOKIE_DATA] [varchar](max) NULL,
	[SESSION_DATA] [varchar](max) NULL,
	[LOG_MSG] [varchar](max) NULL,
	[TRACE] [varchar](max) NULL,
	[NEW_DATE] [datetime] NOT NULL,
	[ERR_CODE] [varchar](100) NULL,
	[SYS_NAME] [varchar](30) NULL,
	[COM_CODE] [varchar](20) NULL,
 CONSTRAINT [PK_ERP_ERR_LOG] PRIMARY KEY CLUSTERED 
(
	[SEQ_NO] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[ERP_ERR_LOG] ADD  DEFAULT (getdate()) FOR [NEW_DATE]
GO
