USE [VGLog]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HTL_TMP_PRICE_MASTER](
	[SEQ_NO] [int] IDENTITY(100000,1) NOT NULL,
	[CITY_CODE] [char](3) NOT NULL,
	[CHECK_IN] [datetime] NOT NULL,
	[CHECK_OUT] [datetime] NOT NULL,
	[NEW_DATE] [datetime] NULL,
	[ROOM_TYPE] [varchar](10) NULL,
	[SEARCH_COUNT] [int] NULL,
	[USE_YN] [char](1) NULL,
 CONSTRAINT [PK_HTL_TMP_PRICE_MASTER] PRIMARY KEY NONCLUSTERED 
(
	[SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HTL_TMP_PRICE_MASTER] ADD  CONSTRAINT [DF_HTL_TMP_PRICE_MASTER_NEW_DATE]  DEFAULT (getdate()) FOR [NEW_DATE]
GO
ALTER TABLE [dbo].[HTL_TMP_PRICE_MASTER] ADD  CONSTRAINT [DF_HTL_TMP_PRICE_MASTER_SEARCH_COUNT]  DEFAULT ((1)) FOR [SEARCH_COUNT]
GO
