USE [VGLog]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SCH_ERROR_LOG](
	[SCH_SEQ] [int] NOT NULL,
	[SCH_NAME] [nchar](50) NOT NULL,
	[SCH_DATE] [int] NOT NULL,
	[DATA_SEQ] [int] NOT NULL,
	[MESSAGE] [nchar](100) NULL,
	[ERROR_MESSAGE] [nchar](100) NULL,
	[NEW_DATE] [datetime] NOT NULL
) ON [PRIMARY]
GO
