USE [VGLog]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PUB_EVENT_READ_COUNT_TEST](
	[EVT_SEQ] [int] NOT NULL,
	[READ_DATE] [date] NOT NULL,
	[TOTAL_COUNT] [int] NULL,
	[WEEK_COUNT] [int] NULL,
	[NEW_DATE] [datetime] NULL
) ON [PRIMARY]
GO
