USE [VGLog]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MKT_CATEGORY](
	[CATE_CODE] [varchar](20) NOT NULL,
	[PRO_TYPE] [varchar](4) NOT NULL,
	[CATE_TYPE] [varchar](1) NULL,
	[CODE_B] [varchar](10) NULL,
	[CODE_M] [varchar](10) NULL,
	[CODE_S] [varchar](10) NULL,
	[NEW_DATE] [datetime] NULL,
	[NEW_CODE] [varchar](7) NULL,
	[EDT_DATE] [datetime] NULL,
	[EDT_CODE] [varchar](7) NULL,
 CONSTRAINT [PK_MK_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[CATE_CODE] ASC,
	[PRO_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
