USE [VGLog]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MKT_AFF_CODE](
	[AFF_CODE] [varchar](2) NOT NULL,
	[AFF_NAME] [varchar](100) NULL,
	[NV_ID] [varchar](50) NULL,
	[NV_PASS] [varchar](50) NULL,
	[HOST] [varchar](30) NULL,
	[AFF_DESC] [varchar](500) NULL,
	[SORT_NUM] [smallint] NULL,
	[USE_YN] [varchar](1) NULL,
	[NEW_DATE] [datetime] NULL,
	[EDT_DATE] [datetime] NULL,
 CONSTRAINT [PK_MKT_AFF_CODE] PRIMARY KEY CLUSTERED 
(
	[AFF_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MKT_AFF_CODE] ADD  CONSTRAINT [DF_MKT_AFF_CODE_SORT_NUM]  DEFAULT ((99)) FOR [SORT_NUM]
GO
