USE [VGLog]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SCH_LOG](
	[SCH_SEQ] [int] NOT NULL,
	[SCH_NAME] [nchar](50) NOT NULL,
	[SCH_DATE] [int] NOT NULL,
	[MESSAGE] [nchar](100) NULL,
	[WORK_COUNT] [int] NULL,
	[ERROR_COUNT] [int] NULL,
	[SUCCESS_RUN_COUNT] [int] NULL,
	[AVG_RUN_TIME] [time](7) NULL,
	[NEW_DATE] [datetime] NOT NULL,
	[LAST_RUN_DATE] [datetime] NULL
) ON [PRIMARY]
GO
