USE [VGLog]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MKT_STATS_DAY](
	[APP_DATE] [datetime] NOT NULL,
	[PRO_TYPE] [varchar](4) NOT NULL,
	[AFF_CODE] [varchar](2) NOT NULL,
	[VIEW_CNT] [int] NULL,
	[CLICK_CNT] [int] NULL,
	[TOTAL_PRICE] [decimal](18, 0) NULL,
	[AVG_PRICE] [decimal](18, 0) NULL,
	[CREATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_MKT_STATS_DAY] PRIMARY KEY CLUSTERED 
(
	[APP_DATE] ASC,
	[PRO_TYPE] ASC,
	[AFF_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
