USE [VGLog]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APP_SCH_MASTER](
	[SCH_SEQ] [int] IDENTITY(1,1) NOT NULL,
	[SCH_NAME] [nchar](50) NOT NULL,
	[SCH_TYPE] [int] NOT NULL,
	[HOST_NAME] [nchar](20) NOT NULL,
	[LAST_RUN_DATE] [datetime] NULL,
	[LAST_RUN_TIME] [time](7) NULL,
	[LAST_RUN_REMARK] [nchar](100) NULL,
	[NEW_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_APP_SCH_MASTER] PRIMARY KEY CLUSTERED 
(
	[SCH_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
