USE [VGLog]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_SCH_MASTER](
	[SCH_SEQ] [int] IDENTITY(1,1) NOT NULL,
	[SCH_NAME] [varchar](100) NULL,
	[SCH_TYPE] [int] NULL,
	[HOST_NAME] [varchar](30) NULL,
	[LAST_RUN_DATE] [datetime] NULL,
	[LAST_RUN_REMARK] [varchar](50) NULL,
	[NEW_DATE] [datetime] NULL,
	[EDT_DATE] [datetime] NULL,
 CONSTRAINT [PK_SYS_SCH_MASTER] PRIMARY KEY CLUSTERED 
(
	[SCH_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
