USE [VGLog]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KEYWORD_LOG](
	[SEQ_NO] [int] IDENTITY(1,1) NOT NULL,
	[KEYWORD] [varchar](200) NULL,
	[CUS_NO] [int] NULL,
	[NEW_DATE] [datetime] NULL,
 CONSTRAINT [PK_KEYWORD_LOG] PRIMARY KEY CLUSTERED 
(
	[SEQ_NO] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KEYWORD_LOG] ADD  DEFAULT (getdate()) FOR [NEW_DATE]
GO
