USE [VGLog]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MKT_HOTEL_PRICE](
	[MASTER_CODE] [varchar](10) NOT NULL,
	[SUP_CODE] [varchar](10) NULL,
	[CHECK_IN_DATE] [datetime] NULL,
	[SALE_PRICE] [decimal](18, 0) NULL,
	[NEW_DATE] [datetime] NULL,
	[EDT_DATE] [datetime] NULL,
 CONSTRAINT [PK_MK_HOTEL_PRICE] PRIMARY KEY CLUSTERED 
(
	[MASTER_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
