USE [Sirens]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [cti].[CTI_SEQ_NUMBER](
	[CTI_SEQ_TYPE] [tinyint] NOT NULL,
	[CTI_SEQ_YMD] [varchar](8) NOT NULL,
	[CTI_SEQ] [int] NULL,
 CONSTRAINT [PK_CTI_SEQ_NUMBER] PRIMARY KEY CLUSTERED 
(
	[CTI_SEQ_TYPE] ASC,
	[CTI_SEQ_YMD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
