USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*-----------------------------------------------------------------------------------

2012-01-09 매일매일의 시간 추가  POPDAYSTARTTIME , POPDAYENDTIME , 
			수평정렬 추가 HORIZONALIGN  1:left ,2:center , 3:right  
2012-03-02 WITH(NOLOCK)  추가 
-----------------------------------------------------------------------------------*/
CREATE PROC [dbo].[SP_WEB_POPUP_OPEN]
AS      
SELECT * FROM PUB_POPUP WITH(NOLOCK)
WHERE GETDATE()
	BETWEEN CONVERT(DATETIME,ISNULL(POPSTARTDATE, '1900-01-01') +' '+ ISNULL(POPSTARTTIME, '00:00:00') )
		AND CONVERT(DATETIME,ISNULL(POPENDDATE, '2999-12-31')  +' '+ ISNULL(POPENDTIME, '23:59:59')  )
AND SUBSTRING(CONVERT(VARCHAR(20), GETDATE(), 120), 12, 8) 
	BETWEEN ISNULL(POPDAYSTARTTIME, '00:00:00')
		AND ISNULL(POPDAYENDTIME, '23:59:59')  
AND SUBSTRING(ISNULL(POPDAY, '1111111'), DATEPART(DW, GETDATE()), 1) = 1  
AND POPISPAUSE = 'N' 
--and POPOPTION  = '/common/main.aspx'
---- 날짜 시간 무제한 팝업 = 모두 NULL      
--SELECT * FROM PUB_POPUP       
--WHERE POPSTARTDATE IS NULL       
--AND POPSTARTTIME IS NULL       
--AND POPENDDATE IS NULL      
--AND POPENDTIME IS NULL      
--AND POPISPAUSE = 'N'      
    
--UNION ALL       
      
---- 시간 제한      
--SELECT * FROM PUB_POPUP       
--WHERE CONVERT(VARCHAR(8), GETDATE(), 108) BETWEEN POPSTARTTIME AND POPENDTIME      
--AND POPSTARTDATE IS NULL       
--AND POPENDDATE IS NULL      
--AND POPISPAUSE = 'N'     
    
--UNION ALL       
      
---- 날짜 시간 제한      
--SELECT * FROM PUB_POPUP       
--WHERE GETDATE() BETWEEN CAST(POPSTARTDATE + ' ' + POPSTARTTIME AS DATETIME) AND CAST(POPENDDATE + ' ' + POPENDTIME AS DATETIME)    
--AND POPISPAUSE = 'N' 
GO
