USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
	전자결제 팩스문서 추가시 조회 

	2012-03-02 READ UNCOMMITTED 설정
	2014-04-23	박형만	팀팩스 조회에서 개인조회 팩스로 수정 

EX)
SP_DOC_FAX_LIST 'C', 10 , 0 , '2009068','2014-04-01', '', ''
SP_DOC_FAX_LIST 'L', 10 , 0 , '2009068','2014-04-01', '', ''

*/
CREATE PROCEDURE [dbo].[SP_DOC_FAX_LIST]
	@FLAG			CHAR(1),
	@PAGESIZE		INT,
	@IPAGE			INT,
	@EMP_CODE		CHAR(7),
	@START_DATE		VARCHAR(10),
	@END_DATE		VARCHAR(10),
	@SUBJECT		VARCHAR(100)
AS
BEGIN

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	DECLARE @FROM INT, @TO INT, @SQLSTRING NVARCHAR(1000), @PARMDEFINITION NVARCHAR(1000)

	SET @FROM = @IPAGE * @PAGESIZE + 1;
	SET @TO = @IPAGE * @PAGESIZE + @PAGESIZE;
	
--SELECT @FROM , @TO 
	-- WHERE 조건 만들기
	SET @SQLSTRING = '';
	
		-- 수신일자
	IF ISNULL(@START_DATE, '') <> '' AND ISNULL(@END_DATE, '') <> ''
	BEGIN
		SET @SQLSTRING = @SQLSTRING + ' AND A.NEW_DATE BETWEEN CONVERT(DATETIME,@START_DATE) AND CONVERT(DATETIME,@END_DATE)'
	END
	ELSE IF ISNULL(@START_DATE, '') <> '' AND ISNULL(@END_DATE, '') = ''
	BEGIN
		SET @SQLSTRING = @SQLSTRING + ' AND A.NEW_DATE >= CONVERT(DATETIME,@START_DATE)'
	END
	ELSE IF ISNULL(@START_DATE, '') = '' AND ISNULL(@END_DATE, '') <> ''
	BEGIN
		SET @SQLSTRING = @SQLSTRING + ' AND A.NEW_DATE =< CONVERT(DATETIME,@END_DATE)'
	END

	ELSE IF ISNULL(@START_DATE, '') = '' AND ISNULL(@END_DATE, '') <> ''
	BEGIN
		SET @SQLSTRING = @SQLSTRING + ' AND A.NEW_DATE =< CONVERT(DATETIME,@END_DATE)'
	END
		
		-- 검색어
	IF ISNULL(LTRIM(RTRIM(@SUBJECT)), '') <> ''
	BEGIN
		SET @SQLSTRING = @SQLSTRING + ' AND A.SUBJECT LIKE (''%'' + @SUBJECT + ''%'')'
	END
	
	IF @FLAG = 'C'					-- 전체 글수
	BEGIN
		--SET @SQLSTRING = N'
		--SELECT COUNT(*) FROM FAX_MASTER WHERE FAX_GROUP IN (
		--	SELECT PUB_VALUE2 FROM COD_PUBLIC WHERE PUB_TYPE = ''FAX.TEAM'' AND PUB_CODE IN (
		--		SELECT TEAM_CODE FROM EMP_MASTER_damo WHERE EMP_CODE = @EMP_CODE
		--	)
		--) AND FAX_TYPE = ''2''' + @SQLSTRING;

		SET @SQLSTRING = N'
		SELECT COUNT(*)
		FROM FAX_MASTER  A WITH(NOLOCK) 
			INNER JOIN FAX_RECEIVE B WITH(NOLOCK)
				ON A.FAX_SEQ = B.FAX_SEQ 
			INNER JOIN 
			( 
				SELECT FAX_NUMBER1 ,FAX_NUMBER2 ,FAX_NUMBER3 
				FROM EMP_MASTER_damo WITH(NOLOCK)
				WHERE TEAM_CODE = (SELECT TEAM_CODE FROM EMP_MASTER_damo WITH(NOLOCK) WHERE EMP_CODE = @EMP_CODE )
				--WHERE EMP_CODE = @EMP_CODE
				GROUP BY FAX_NUMBER1 ,FAX_NUMBER2 ,FAX_NUMBER3 
			) C 
				ON B.RCV_NUMBER1 = C.FAX_NUMBER1
				AND B.RCV_NUMBER2 = C.FAX_NUMBER2
				AND B.RCV_NUMBER3 = C.FAX_NUMBER3
		WHERE 1=1
		AND A.FAX_TYPE = 2 AND A.DEL_YN=''N''
		' 
		+ @SQLSTRING 

	END
	ELSE IF @FLAG = 'L'				-- 검색
	BEGIN
		SET @SQLSTRING = N'
		WITH LIST AS
		(
			SELECT A.FAX_SEQ, ROW_NUMBER() OVER (ORDER BY A.FAX_SEQ DESC) AS [ROWNUMBER]
			FROM FAX_MASTER  A WITH(NOLOCK) 
				INNER JOIN FAX_RECEIVE B WITH(NOLOCK)
					ON A.FAX_SEQ = B.FAX_SEQ 
				INNER JOIN 
				( 
					SELECT FAX_NUMBER1 ,FAX_NUMBER2 ,FAX_NUMBER3 
					FROM EMP_MASTER_damo WITH(NOLOCK)
					WHERE TEAM_CODE = (SELECT TEAM_CODE FROM EMP_MASTER_damo WITH(NOLOCK) WHERE EMP_CODE = @EMP_CODE )
					--WHERE EMP_CODE = @EMP_CODE
					GROUP BY FAX_NUMBER1 ,FAX_NUMBER2 ,FAX_NUMBER3 
				) C 
					ON B.RCV_NUMBER1 = C.FAX_NUMBER1
					AND B.RCV_NUMBER2 = C.FAX_NUMBER2
					AND B.RCV_NUMBER3 = C.FAX_NUMBER3

			WHERE 1=1
			AND A.FAX_TYPE = 2 AND A.DEL_YN=''N''
			' 
			+ @SQLSTRING + ' 
		)
		SELECT A.ROWNUMBER, B.* FROM LIST A
		INNER JOIN FAX_MASTER B ON A.FAX_SEQ = B.FAX_SEQ
		WHERE ROWNUMBER BETWEEN @FROM AND @TO;';
	END
	
	SET @PARMDEFINITION = N'@FROM INT, @TO INT, @EMP_CODE VARCHAR(7), @START_DATE DATETIME, @END_DATE DATETIME, @SUBJECT VARCHAR(100)'
	
	--PRINT @SQLSTRING
	EXEC SP_EXECUTESQL @SQLSTRING, @PARMDEFINITION, @FROM, @TO, @EMP_CODE, @START_DATE, @END_DATE, @SUBJECT;
END
GO
