USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_BBS_COMMENT_INSERT]
(
@BBS_SEQ INT,
@MASTER_SEQ INT,
@CONTENTS nVARCHAR(1000),
@PASSWORD VARCHAR(20),
@STATUS VARCHAR(1),
@STATUS_EMP_CODE VARCHAR(20),
@FINISH_DATE SMALLDATETIME,
@FINISH_EMP_CODE VARCHAR(20),
@TEAM_CODE VARCHAR(3),
@TEAM_NAME VARCHAR(50),
@NEW_CODE VARCHAR(7),
@NEW_NAME VARCHAR(20)
)
AS

BEGIN
	SET NOCOUNT OFF;
	DECLARE @SEQ INT;
	
	SELECT TOP 1 @SEQ  = ISNULL(MAX(COMMENT_SEQ),0) + 1 FROM BBS_COMMENT   WITH (UPDLOCK)  WHERE BBS_SEQ=@BBS_SEQ 	AND MASTER_SEQ=@MASTER_SEQ
 
	
	INSERT INTO BBS_COMMENT
	(COMMENT_SEQ,BBS_SEQ,MASTER_SEQ,CONTENTS,[PASSWORD],[STATUS],FINISH_DATE,TEAM_CODE,TEAM_NAME,NEW_CODE,NEW_NAME,NEW_DATE)
		VALUES
	(@SEQ,@BBS_SEQ,@MASTER_SEQ,@CONTENTS,@PASSWORD,@STATUS,@FINISH_DATE,@TEAM_CODE,@TEAM_NAME,@NEW_CODE,@NEW_NAME,GETDATE())
	
	UPDATE BBS_DETAIL SET COMMENT_COUNT = COMMENT_COUNT + 1 WHERE BBS_SEQ=@BBS_SEQ AND MASTER_SEQ=@MASTER_SEQ

	IF(@STATUS <> '')

		BEGIN
			UPDATE BBS_DETAIL 
			SET [STATUS]=@STATUS ,
			--FINISH_DATE=@FINISH_DATE, 
			--FINISH_EMP_CODE=@FINISH_EMP_CODE ,
			STATUS_EMP_CODE=@STATUS_EMP_CODE
			WHERE BBS_SEQ=@BBS_SEQ AND MASTER_SEQ=@MASTER_SEQ

		END


	IF(@FINISH_DATE <> '')

		BEGIN
			UPDATE BBS_DETAIL 
			SET 
			FINISH_DATE=@FINISH_DATE, 
			FINISH_EMP_CODE=@FINISH_EMP_CODE 
			
			WHERE BBS_SEQ=@BBS_SEQ AND MASTER_SEQ=@MASTER_SEQ

		END

	
END




GO
