USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_DSR_UPDATE_MULTI_PRODUCT_TICKET]  
 @PRO_CODE VARCHAR(50),     
 @TICKET VARCHAR(20),   
 @ISSUE_CODE CHAR(7),  
 @CITY_CODE CHAR(3),
 @NEW_CODE CHAR(7)    
AS    
BEGIN    
 DECLARE @SALE_CODE VARCHAR(20)    
 DECLARE @RES_CODE VARCHAR(20)
 DECLARE @SEQ_NO VARCHAR(20)
 DECLARE @FIRST_NAME VARCHAR(50)  
 DECLARE @LAST_NAME VARCHAR(50)
 DECLARE @PAX_NAME VARCHAR(100)

 
SET NOCOUNT ON;    
SELECT @PAX_NAME = PAX_NAME FROM DSR_TICKET WITH(NOLOCK) WHERE TICKET = @TICKET

IF(ISNULL(@PAX_NAME,'') <> '')
BEGIN
	 --PAX에서 LAST_NAME하구 FIRST_NAME을 분리
	SELECT @LAST_NAME = SUBSTRING(@PAX_NAME  ,1,CHARINDEX('/', @PAX_NAME,1 ) - 1)
	SELECT @FIRST_NAME = SUBSTRING(@PAX_NAME  ,CHARINDEX('/', @PAX_NAME,1 ) + 1,50)

	--MISS랑 MSTR에서를 두글자로 변경.. MR MS MI MS가 되니 2글자로 자름
	SELECT @FIRST_NAME = REPLACE(REPLACE(@FIRST_NAME,'MISS','MI'),'MSTR','MS')
	
	SELECT @FIRST_NAME = LEFT(@FIRST_NAME, LEN(@FIRST_NAME)-2)
END

 SELECT TOP 1 @RES_CODE = RC.RES_CODE, @SALE_CODE = RC.NEW_CODE, @SEQ_NO = RC.SEQ_NO FROM RES_CUSTOMER_damo RC WITH(NOLOCK)
	INNER JOIN RES_MASTER_DAMO RM WITH(NOLOCK)
 ON RC.RES_CODE = RM.RES_CODE
 WHERE LAST_NAME = @LAST_NAME 
 AND FIRST_NAME = @FIRST_NAME
 AND RM.PRO_CODE = @PRO_CODE
 
 -- 예약코드 없는 경우 매칭 금지    
 IF (@RES_CODE = '') RETURN   
     
 UPDATE DSR_TICKET SET     
  PRO_CODE = @PRO_CODE,    
  RES_CODE = @RES_CODE,    
  RES_SEQ_NO = @SEQ_NO,    
  SALE_CODE = @SALE_CODE,    
  ISSUE_CODE = @ISSUE_CODE,    
  CITY_CODE = @CITY_CODE,  
  NEW_CODE = @NEW_CODE    
 WHERE TICKET = @TICKET;    
    
 -- 기존에 입금이 물려있을 경우에는 입금을 이동해준다.    
IF EXISTS (SELECT * FROM PAY_MASTER_damo WHERE SEC1_PAY_NUM = damo.dbo.pred_meta_plain_v (@TICKET,'DIABLO','dbo.PAY_MASTER','PAY_NUM') )    
 BEGIN    
  UPDATE PAY_MATCHING     
  SET PRO_CODE = @PRO_CODE, RES_CODE = @RES_CODE     
  WHERE PAY_SEQ IN (SELECT PAY_SEQ FROM PAY_MASTER_damo WHERE SEC1_PAY_NUM = damo.dbo.pred_meta_plain_v (@TICKET,'DIABLO','dbo.PAY_MASTER','PAY_NUM') AND (PAY_TYPE = 10 OR PAY_TYPE = 12))    
 END        
END 



GO
