USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*================================================================================================================
■ USP_NAME					: XP_ARG_LAND_LIST_SELECT
■ DESCRIPTION				: 랜드사 리스트 검색
■ INPUT PARAMETER			: 
	@KOR_NAME   VARCHAR(50)	: 랜드사명
■ OUTPUT PARAMETER			: 
   
■ EXEC						: 

	exec XP_ARG_LAND_LIST_SELECT '참'

■ MEMO						: 
------------------------------------------------------------------------------------------------------------------
■ CHANGE HISTORY                   
------------------------------------------------------------------------------------------------------------------
   DATE				AUTHOR			DESCRIPTION           
------------------------------------------------------------------------------------------------------------------
   2013-06-21		김완기			최초생성    
   2019-03-18		이명훈			속도 개선
================================================================================================================*/ 

 CREATE  PROCEDURE [dbo].[XP_ARG_LAND_LIST_SELECT]
(
	@KOR_NAME		VARCHAR(50)
)

AS  
BEGIN

	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	
   -- 2013-06-21		김완기			최초생성
   --  SELECT A.AGT_CODE,
   --         A.KOR_NAME,
			--MAX(A.SHOW_YN) AS SHOW_YN,
   --         (SELECT COUNT(DISTINCT(G.PRO_CODE))
   --         FROM OTR_POL_MASTER F WITH(NOLOCK) 
   --         INNER JOIN OTR_MASTER G WITH(NOLOCK) ON (F.OTR_SEQ = G.OTR_SEQ AND G.OTR_STATE = '3')
   --         WHERE F.AGT_CODE = A.AGT_CODE) AS G_COUNT,
   --         ISNULL((SELECT ROUND((SUM(CONVERT(INT,L.EXAMPLE_DESC)) / CONVERT(FLOAT,COUNT(K.OTR_POL_EXAMPLE_SEQ))),1)
			--		FROM OTR_MASTER H WITH(NOLOCK)
			--		INNER JOIN dbo.OTR_POL_MASTER I WITH(NOLOCK) ON H.OTR_SEQ = I.OTR_SEQ AND I.POL_TYPE ='2'
			--		INNER JOIN dbo.OTR_POL_QUESTION J WITH(NOLOCK) ON I.OTR_POL_MASTER_SEQ = J.OTR_POL_MASTER_SEQ AND J.QUS_TYPE='1'
			--		INNER JOIN dbo.OTR_POL_ANSWER K WITH(NOLOCK) ON J.OTR_POL_MASTER_SEQ = K.OTR_POL_MASTER_SEQ AND J.OTR_POL_QUESTION_SEQ = K.OTR_POL_QUESTION_SEQ
			--		INNER JOIN dbo.OTR_POL_DETAIL L WITH(NOLOCK) ON K.OTR_POL_MASTER_SEQ = L.OTR_POL_MASTER_SEQ AND K.OTR_POL_QUESTION_SEQ = L.OTR_POL_QUESTION_SEQ AND K.OTR_POL_EXAMPLE_SEQ =L.OTR_POL_EXAMPLE_SEQ 
			--		WHERE H.OTR_STATE = '3' AND I.AGT_CODE = A.AGT_CODE), 0) AS AVG_NUM ,
   --         ISNULL((SELECT ROUND((SUM(CONVERT(INT,L.EXAMPLE_DESC)) / CONVERT(FLOAT,COUNT(K.OTR_POL_EXAMPLE_SEQ))),1)
			--		FROM OTR_MASTER H WITH(NOLOCK)
			--		INNER JOIN dbo.OTR_POL_MASTER I WITH(NOLOCK) ON H.OTR_SEQ = I.OTR_SEQ AND I.POL_TYPE ='2'
			--		INNER JOIN dbo.OTR_POL_QUESTION J WITH(NOLOCK) ON I.OTR_POL_MASTER_SEQ = J.OTR_POL_MASTER_SEQ AND J.QUS_TYPE='1'
			--		INNER JOIN dbo.OTR_POL_ANSWER K WITH(NOLOCK) ON J.OTR_POL_MASTER_SEQ = K.OTR_POL_MASTER_SEQ AND J.OTR_POL_QUESTION_SEQ = K.OTR_POL_QUESTION_SEQ
			--		INNER JOIN dbo.OTR_POL_DETAIL L WITH(NOLOCK) ON K.OTR_POL_MASTER_SEQ = L.OTR_POL_MASTER_SEQ AND K.OTR_POL_QUESTION_SEQ = L.OTR_POL_QUESTION_SEQ AND K.OTR_POL_EXAMPLE_SEQ =L.OTR_POL_EXAMPLE_SEQ 
			--		WHERE H.OTR_STATE = '3' AND H.PRO_CODE = MAX(D.PRO_CODE) AND I.AGT_CODE = A.AGT_CODE), 0) AS AVG_NUM_LAST ,
   --         (SELECT DEP_DATE FROM PKG_DETAIL WITH(NOLOCK) WHERE PRO_CODE = MAX(D.PRO_CODE)) AS LAST_DEP_DATE
   -- FROM AGT_MASTER A WITH(NOLOCK)
   -- LEFT OUTER JOIN AGT_MEMBER B WITH(NOLOCK) ON (A.AGT_CODE = B.AGT_CODE AND B.MEM_TYPE ='1' AND B.WORK_TYPE != '5')
   -- LEFT OUTER JOIN OTR_POL_MASTER C WITH(NOLOCK) ON (B.AGT_CODE = C.AGT_CODE AND B.MEM_CODE = C.MEM_CODE)
   -- LEFT OUTER JOIN OTR_MASTER D WITH(NOLOCK) ON (C.OTR_SEQ = D.OTR_SEQ AND D.OTR_STATE = '3')
   -- WHERE A.AGT_TYPE_CODE = '12' AND A.SHOW_YN = 'Y' AND A.KOR_NAME LIKE '%' + @KOR_NAME + '%'
   -- GROUP BY A.AGT_CODE, A.KOR_NAME 
   -- ORDER BY A.AGT_CODE DESC


    SELECT A.AGT_CODE,
            A.KOR_NAME,
			MAX(A.SHOW_YN) AS SHOW_YN,
            0 AS G_COUNT,
            0 AS AVG_NUM ,
            0 AS AVG_NUM_LAST ,
            (SELECT DEP_DATE FROM PKG_DETAIL WITH(NOLOCK) WHERE PRO_CODE = MAX(D.PRO_CODE)) AS LAST_DEP_DATE
    FROM AGT_MASTER A WITH(NOLOCK)
    LEFT OUTER JOIN AGT_MEMBER B WITH(NOLOCK) ON (A.AGT_CODE = B.AGT_CODE AND B.MEM_TYPE ='1' AND B.WORK_TYPE != '5')
    LEFT OUTER JOIN OTR_POL_MASTER C WITH(NOLOCK) ON (B.AGT_CODE = C.AGT_CODE AND B.MEM_CODE = C.MEM_CODE)
    LEFT OUTER JOIN OTR_MASTER D WITH(NOLOCK) ON (C.OTR_SEQ = D.OTR_SEQ AND D.OTR_STATE = '3')
    WHERE A.AGT_TYPE_CODE = '12' AND A.SHOW_YN = 'Y' AND A.KOR_NAME LIKE '%' + @KOR_NAME + '%'
    GROUP BY A.AGT_CODE, A.KOR_NAME 
    ORDER BY A.AGT_CODE DESC
END



GO
