USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
	PUB_VGT_MENU 배포
	-- ERP에서 작업한 내용을 웹페이지로 배포한다.
*/
CREATE PROC [dbo].[SP_PUB_VGT_MENU_RELEASE] (
	@MENU_CODE VARCHAR(3)
) AS

-- 해당 대분류 그룹 항목 삭제
DELETE FROM PUB_VGT_MENU_REL WHERE MENU_CODE LIKE @MENU_CODE + '%'

-- 관리 테이블에서 홈페이지 메뉴 테이블로 이관
-- 홈페이지에서는 USE_YN이 N인건 사용하지 않으므로 Y인것만 복사
INSERT INTO PUB_VGT_MENU_REL (
	MENU_CODE,PARENT_CODE,MENU_NAME,REGION_CODE,CITY_CODE,NATION_CODE,ATT_CODE,GROUP_CODE,BASIC_CODE,CATEGORY_TYPE,VIEW_TYPE,LINK_URL,
	IMAGE_URL,ORDER_TYPE,BEST_CODE,FONT_STYLE,FONT_COLOR,ORDER_NUM,OLD_MENU_CODE,USE_YN,NEW_CODE,NEW_DATE,EDT_CODE,EDT_DATE
)
	SELECT 
		MENU_CODE,PARENT_CODE,MENU_NAME,REGION_CODE,CITY_CODE,NATION_CODE,ATT_CODE,GROUP_CODE,BASIC_CODE,CATEGORY_TYPE,VIEW_TYPE,LINK_URL,
		IMAGE_URL,ORDER_TYPE,BEST_CODE,FONT_STYLE,FONT_COLOR,ORDER_NUM,OLD_MENU_CODE,USE_YN,NEW_CODE,GETDATE(),NULL,NULL
	FROM PUB_VGT_MENU WHERE MENU_CODE LIKE @MENU_CODE + '%' AND USE_YN = 'Y'
GO
