USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
행사검색 인쇄 sp 
2014-06-25 박형만 상품가총액계산 으로 변경
*/
CREATE PROCEDURE [dbo].[SP_PKG_DETAIL_SELECT_LIST_PRINT]    
	@FLAG   CHAR(1),    
	@PAGE_SIZE  INT,    
	@PAGE_INDEX  INT,    

	@EMP_CODE  VARCHAR(7),    
	@TEAM_CODE  VARCHAR(3),    
	@PRO_CODE  VARCHAR(20),    
	@PRO_NAME  NVARCHAR(100),    
	@START_DATE  VARCHAR(10),    
	@END_DATE  VARCHAR(10),    
	@WEEK_DAY_TYPE VARCHAR(7),    
	@CITY_CODE  CHAR(3),    
	@AIRLINE_CODE VARCHAR(2),   
	@AIRLINE_NUMBER VARCHAR(2), 
	@RES_YN   INT    
AS    
BEGIN    
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	DECLARE @SQLSTRING NVARCHAR(4000), @PARMDEFINITION NVARCHAR(1000), @FROM INT, @TO INT;  

	SET @FROM = @PAGE_INDEX * @PAGE_SIZE + 1;    
	SET @TO = @PAGE_INDEX * @PAGE_SIZE + @PAGE_SIZE;    
  
	-- WHERE 조건 만들기    
	SET @SQLSTRING = ' WHERE 1 = 1 AND A.SHOW_YN = ''Y'' ';
  
	-- 담당자코드( 없으면 팀 전체, 팀 코드가 없으면 전체)
	IF LTRIM(ISNULL(@EMP_CODE, '')) <> ''
		SET @SQLSTRING = @SQLSTRING + ' AND A.NEW_CODE = @EMP_CODE'
	ELSE IF LTRIM(ISNULL(@TEAM_CODE, '')) <> ''
		SET @SQLSTRING = @SQLSTRING + ' AND A.NEW_CODE IN (SELECT EMP_CODE FROM EMP_MASTER WITH(NOLOCK) WHERE TEAM_CODE = @TEAM_CODE)'
  
	IF @FLAG = 'C'     -- 전체 글수    
	BEGIN    
		SET @SQLSTRING = N'SELECT COUNT(*) FROM PKG_DETAIL A  WITH(NOLOCK) ' + @SQLSTRING;  
	END    
	ELSE IF @FLAG = 'L'    -- 검색    
	BEGIN    
		SET @SQLSTRING = N'
		WITH LIST AS        
		(         
			SELECT   ROW_NUMBER() OVER (ORDER BY A.DEP_DATE) AS [ROWNUMBER]
				, A.PRO_CODE
				, A.PRO_NAME
				, A.DEP_DATE
				, A.SALE_TYPE
				, ISNULL(A.FAKE_COUNT, 0) AS [FAKE_COUNT]
				, ISNULL(A.MIN_COUNT, 0) AS [MIN_COUNT]
				, ISNULL((SELECT TOP 1 ADT_PRICE FROM PKG_DETAIL_PRICE WHERE PRO_CODE = A.PRO_CODE ORDER BY ADT_PRICE), 0) AS [PRO_PRICE]
				, ISNULL(dbo.XN_PRO_DETAIL_SALE_PRICE_CUTTING(A.PRO_CODE,0) , 0) AS [PRO_SALE_PRICE] --추가  
				, DBO.FN_PRO_GET_RES_COUNT(A.PRO_CODE) AS [RES_COUNT]
				, (SELECT KOR_NAME FROM EMP_MASTER WHERE EMP_CODE = A.NEW_CODE) AS [NEW_NAME]
				, A.DEP_CFM_YN
				, A.CONFIRM_YN
				, A.RES_ADD_YN
				, DBO.FN_PRO_GET_ACCOUNT_STATE(A.PRO_CODE) AS [ACCOUNT_TYPE] 
				, A.PKG_INSIDE_REMARK 
				, A.SHOW_YN
				, A.SEAT_CODE
			FROM PKG_DETAIL A WITH(NOLOCK)
			INNER JOIN (
				SELECT MASTER_CODE, 
				(SELECT TOP 1 DEP_DATE FROM PKG_DETAIL Z  WHERE Z.MASTER_CODE = A.MASTER_CODE AND Z.DEP_DATE >= @START_DATE AND Z.SHOW_YN = ''Y'' ORDER BY Z.DEP_DATE) AS DEP_DATE
				FROM PKG_MASTER A
				' + @SQLSTRING + '
			)B ON B.MASTER_CODE = A.MASTER_CODE AND A.DEP_DATE = B.DEP_DATE
			WHERE A.SHOW_YN = ''Y''
		 )        
		SELECT    A.ROWNUMBER
				, A.PRO_CODE
				, A.PRO_NAME
				, A.DEP_DATE
				, A.SALE_TYPE
				, A.FAKE_COUNT
				, A.MIN_COUNT
				, A.PRO_SALE_PRICE 
				, A.PRO_PRICE
				, A.RES_COUNT
				, A.NEW_NAME
				, A.NEW_NAME
				, A.DEP_CFM_YN
				, A.CONFIRM_YN
				, A.RES_ADD_YN
				, A.ACCOUNT_TYPE 
				, A.PKG_INSIDE_REMARK 
				, A.SHOW_YN
				, NULL AS DEP_TRANS_CODE
				, NULL AS DEP_TRANS_NUMBER    
		FROM LIST A        
		-- INNER JOIN PKG_DETAIL B  WITH(NOLOCK) ON A.PRO_CODE = B.PRO_CODE               ------------------조인제거
		WHERE A.ROWNUMBER BETWEEN @FROM AND @TO        
		ORDER BY A.PRO_CODE;';    
	END    
  
	SET @PARMDEFINITION = N'@FROM INT, @TO INT, @EMP_CODE VARCHAR(7), @TEAM_CODE VARCHAR(3), @PRO_CODE VARCHAR(20), @PRO_NAME NVARCHAR(100), 
	@START_DATE VARCHAR(10), @END_DATE VARCHAR(10), @WEEK_DAY_TYPE VARCHAR(7), @CITY_CODE CHAR(3), @AIRLINE_CODE VARCHAR(2), @AIRLINE_NUMBER VARCHAR(2), @RES_YN INT';  
  
	PRINT @SQLSTRING
	EXEC SP_EXECUTESQL @SQLSTRING, @PARMDEFINITION, @FROM, @TO, @EMP_CODE, @TEAM_CODE, @PRO_CODE, @PRO_NAME, @START_DATE, @END_DATE, @WEEK_DAY_TYPE, @CITY_CODE, @AIRLINE_CODE, @AIRLINE_NUMBER, @RES_YN;    
END    
    
-- @FLAG, @PAGE_SIZE, @PAGE_INDEX, @EMP_CODE, @TEAM_CODE, @PRO_CODE, @PRO_NAME, @START_DATE, @END_DATE, @WEEK_DAY_TYPE, @CITY_CODE, @RES_YN INT    
-- SP_PKG_DETAIL_SELECT_LIST 'L', 10, 0, '', '529', 'CPW100', '상품명', '2008-12-20', '2008-12-31', '1111101', 'TYO', 0    
-- SP_PKG_DETAIL_SELECT_LIST 'L', 10, 0, '', '529', '', '', '', '', '1011111', '', 0    
-- SP_PKG_DETAIL_SELECT_LIST 'L', 10, 0, '', '', 'jpo', '', '2009-03-01', '', '1111111', '', 2    
-- EXEC SP_PKG_DETAIL_SELECT_LIST @PAGE_INDEX=0,@PAGE_SIZE=1000,@EMP_CODE=N' ',@TEAM_CODE=N'511',@PRO_CODE=NULL,@PRO_NAME=NULL,
-- @START_DATE=N'2009-11-09',@END_DATE=N'2009-11-15',@WEEK_DAY_TYPE=N'1111111',@CITY_CODE=N'000',@RES_YN=0,@AIRLINE_CODE=N'KE',@FLAG=N'C'  
  
  

GO
