USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO




-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_RES_TOURSOFT_MIGRANTION]
	-- Add the parameters for the stored procedure here
	@RES_DAY CHAR(8),
	@RES_SEQ INT,
	@PRO_CODE VARCHAR(20),
	@PRICE_SEQ INT
AS
BEGIN
	DECLARE @RESULT CHAR(1)
	DECLARE @RES_CODE CHAR(12)
	DECLARE @TMP_CUS_NO INT
	DECLARE @CU_YY CHAR(4)
	DECLARE @CU_SEQ INT
	DECLARE @SOC1 VARCHAR(20)
	DECLARE @SOC2 VARCHAR(20)
	DECLARE @MEMBER_YN CHAR(1)
	DECLARE @GENDER CHAR(1)
	-- 출발고객
	DECLARE @RES_NO INT
	DECLARE @SALE_AMT MONEY
	DECLARE @RES_AMT MONEY
	DECLARE @RES_DC_AMT MONEY
	DECLARE @RES_ADD_AMT MONEY
	DECLARE @AGE_CD CHAR(1)
	DECLARE @DC_REMARK VARCHAR(40)
	DECLARE @ADD_REMARK VARCHAR(50)
	DECLARE @REMARK VARCHAR(200)
	DECLARE @INS_EMP_NO VARCHAR(10)
	DECLARE @INS_DT VARCHAR(8)
	DECLARE @SEX CHAR(1)
	DECLARE @SEQ_NO INT

	DECLARE @EV_YM CHAR(6)
	DECLARE @EV_SEQ INT
	DECLARE @EV_NM VARCHAR(100)


	
	-- 투어소프트에 해당 예약이 있는지를 체크
	IF NOT EXISTS (SELECT 1 FROM toursoft.toursoft2005.dbo.re001  WITH(NOLOCK) WHERE RES_DAY = @RES_DAY AND RES_SEQ = @RES_SEQ)
	BEGIN
		SELECT '1'
		RETURN
	END

	-- 신규 erp에 해당 상품이 있는지를 체크
	IF NOT EXISTS (SELECT 1 FROM PKG_DETAIL  WITH(NOLOCK) WHERE PRO_CODE = @PRO_CODE)
	BEGIN
		SELECT '2'
		RETURN
	END

	-- 예약자 고객 정보를 가져온다.
	SELECT @CU_YY = CU_YY, @CU_SEQ = CU_SEQ, @EV_YM = EV_YM, @EV_SEQ = EV_SEQ FROM toursoft.toursoft2005.dbo.re001  WITH(NOLOCK) WHERE RES_DAY = @RES_DAY AND RES_SEQ = @RES_SEQ
	SELECT @SOC1 = CU_JMNO FROM toursoft.toursoft2005.dbo.CU001  WITH(NOLOCK) WHERE CU_YY = @CU_YY AND CU_SEQ = @CU_SEQ
	IF @SOC1 IS NOT NULL
	BEGIN
		IF LEN(@SOC1) = 13 
		BEGIN
			SET @SOC2 = SUBSTRING(@SOC1, 7, 7)
			SET @SOC1 = SUBSTRING(@SOC1, 1, 6)
			IF SUBSTRING(@SOC2, 1, 1) IN ('2', '4') SET @GENDER  = 'F'
			ELSE SET @GENDER  = 'M'
		END
		ELSE
		BEGIN
			SET @SOC1 = NULL
			SET @SOC2 = NULL
		END
	END
	ELSE
	BEGIN
		SET @SOC1 = NULL
		SET @SOC2 = NULL
	END

	SET @TMP_CUS_NO = 0

	IF @SOC2 IS NOT NULL
	BEGIN
		SELECT 
			@TMP_CUS_NO = CUS_NO ,
			@MEMBER_YN = CASE WHEN CUS_ID IS NOT NULL THEN 'Y' ELSE 'N' END
		FROM CUS_CUSTOMER  WITH(NOLOCK) WHERE SOC_NUM1 = @SOC1 AND SOC_NUM2 = @SOC2
	END

	BEGIN TRY
	--BEGIN TRAN

		SELECT @EV_NM = EV_NM FROM TOURSOFT.TOURSOFT2005.DBO.EV001 WITH(NOLOCK)  WHERE EV_YM = @EV_YM AND EV_SEQ = @EV_SEQ

		INSERT INTO RES_TOURSOFT(EV_YM, EV_SEQ, EV_NM, RES_DAY, RES_SEQ, PRO_CODE)
		VALUES (@EV_YM, @EV_SEQ, @EV_NM, @RES_DAY, @RES_SEQ, @PRO_CODE)

		IF @TMP_CUS_NO = 0
		-- 예약자 정보가 없을 경우
		BEGIN

			INSERT INTO CUS_CUSTOMER(CUS_NAME, SOC_NUM1, SOC_NUM2, NOR_TEL1, NOR_TEL2, NOR_TEL3, GENDER, NEW_CODE)
			SELECT 
				ISNULL(A.RES_NM, 'AAA'), @SOC1, @SOC2, A.HANDPHONE1, A.HANDPHONE2, A.HANDPHONE3, 
				@GENDER, A.INS_EMP_NO
			FROM toursoft.toursoft2005.dbo.re001  A  WITH(NOLOCK) 
			--INNER JOIN toursoft.toursoft2005.dbo.CU001 B ON CU_YY = A.CU_YY AND CU_SEQ = A.CU_SEQ
			WHERE A.RES_DAY = @RES_DAY AND A.RES_SEQ = @RES_SEQ

			SET @TMP_CUS_NO = @@IDENTITY
			SET @MEMBER_YN = 'N'
		END
		

		-- 예약코드를 발급 받는다.
		EXEC dbo.SP_RES_GET_RES_CODE 'P', @RES_CODE OUTPUT

		IF @RES_CODE IS NULL
		BEGIN
			SELECT '3'
			RETURN
		END

		-- 예약 마스터 입력
		INSERT INTO 
			RES_MASTER(RES_CODE, PRICE_SEQ, SYSTEM_TYPE, 
				PROVIDER, 
				MEDIUM_TYPE, 
				AD_CODE, 
				PRO_CODE, PRO_NAME, MASTER_CODE, PRO_TYPE, RES_STATE, RES_TYPE, DEP_DATE,
				ARR_DATE, CUS_NO, RES_NAME, SOC_NUM1, SOC_NUM2, RES_EMAIL,
				NOR_TEL1, NOR_TEL2, NOR_TEL3, ETC_TEL1, ETC_TEL2, ETC_TEL3,
				RES_ADDRESS1, RES_ADDRESS2, ZIP_CODE, MEMBER_YN,
				CUS_REQUEST, ETC, TAX_YN, COMM_RATE, LAST_PAY_DATE,
				SALE_EMP_CODE, SALE_COM_CODE, NEW_DATE, NEW_CODE, NEW_TEAM_NAME)
		SELECT	
				@RES_CODE, @PRICE_SEQ, 2, 
				-- 예약형태구분
				CASE B.RES_CHK 
					WHEN '10' THEN 1
					WHEN '20' THEN 2
					WHEN '21' THEN 3
					WHEN '30' THEN 4
					WHEN '40' THEN 5
					WHEN '50' THEN 6
					WHEN '51' THEN 7
					WHEN '60' THEN 8
					WHEN '70' THEN 9
					ELSE 1
				END AS PROVIDER,
				-- 광고매체구분
				CASE WHEN B.MASS_CD IS NULL THEN NULL
					ELSE B.MASS_CD
				END AS MEDIUM_TYPE, 
				-- 매체구분
				MASS_SITE_CD, 
				@PRO_CODE, A.PRO_NAME, A.MASTER_CODE, 1, 2, 0, A.DEP_DATE,
				A.ARR_DATE, @TMP_CUS_NO, B.RES_NM, @SOC1, @SOC2, B.EMAIL,
				B.HANDPHONE1, B.HANDPHONE2, B.HANDPHONE3, B.TEL1, B.TEL2, B.TEL3,
				NULL, NULL, NULL, @MEMBER_YN,
				NULL, ADD_REMARK + ' ' + RES_REMARK2 + ' ' + RES_REMARK3 + ' ' + RES_REMARK4, C.TAX_YN, C.SITE_COMM_RATE, A.LAST_PAY_DATE,
				B.INS_EMP_NO, B.AGEN_CD, B.INS_DT, ISNULL(B.CHA_EMP_NO, B.INS_EMP_NO), NULL
		FROM PKG_DETAIL A WITH(NOLOCK) 
		INNER JOIN toursoft.toursoft2005.dbo.re001 B  WITH(NOLOCK) ON B.RES_DAY = @RES_DAY AND B.RES_SEQ = @RES_SEQ
		LEFT OUTER JOIN toursoft.toursoft2005.dbo.re003 C  WITH(NOLOCK) ON C.RES_DAY = B.RES_DAY AND C.RES_SEQ = B.RES_SEQ
		WHERE A.PRO_CODE = @PRO_CODE
	
		-- 예약디테일 입력
		INSERT INTO RES_PKG_DETAIL(RES_CODE)VALUES(@RES_CODE)		


		-- 출발자 정보 입력
		DECLARE CUSTOMER_CURSOR CURSOR FOR 
			SELECT 
				CU_YY, CU_SEQ, RES_NO, SALE_AMT, RES_AMT, RES_DC_AMT, RES_ADD_AMT,
				AGE_CD, DC_REMARK, ADD_REMARK, REMARK, INS_EMP_NO, INS_DT, SEX
			FROM toursoft.toursoft2005.dbo.RE002 WITH(NOLOCK) 
			WHERE RES_DAY = @RES_DAY AND RES_SEQ = @RES_SEQ AND CANC_CD IS NULL
		
		OPEN CUSTOMER_CURSOR
		FETCH NEXT FROM CUSTOMER_CURSOR INTO 
				@CU_YY, @CU_SEQ, @RES_NO, @SALE_AMT, @RES_AMT, @RES_DC_AMT, @RES_ADD_AMT,
				@AGE_CD, @DC_REMARK, @ADD_REMARK, @REMARK, @INS_EMP_NO, @INS_DT, @SEX

		SET @SEQ_NO = 0
		WHILE @@FETCH_STATUS = 0
		BEGIN
			SET @SEQ_NO = @SEQ_NO + 1

			IF @CU_YY IS NOT NULL
			BEGIN

				-- 출발자 정보 등록
				INSERT INTO CUS_CUSTOMER(CUS_NAME, last_name, first_name, SOC_NUM1, SOC_NUM2, NOR_TEL1, NOR_TEL2, NOR_TEL3, GENDER, NEW_CODE)
				SELECT 
					ISNULL(CU_NM_KOR, 'AAA'), 					
					CASE 
						WHEN CHARINDEX('/', CU_NM_ENG) IS NULL THEN NULL
						WHEN CHARINDEX('/', CU_NM_ENG) = 0 THEN CU_NM_ENG
						ELSE SUBSTRING(ISNULL(CU_NM_ENG, ''), 1,CHARINDEX('/', CU_NM_ENG)-1)
					END AS LAST_NAME, 
					CASE 
						WHEN CHARINDEX('/', CU_NM_ENG) IS NULL THEN NULL
						WHEN CHARINDEX('/', CU_NM_ENG) = 0 THEN NULL
						ELSE SUBSTRING(ISNULL(CU_NM_ENG, ''), CHARINDEX('/', CU_NM_ENG)+1, LEN(CU_NM_ENG) - CHARINDEX('/', CU_NM_ENG))
					END AS FIRST_NAME, 
					CASE 
						WHEN LEN(CU_JMNO) = 13 THEN SUBSTRING(CU_JMNO, 1, 6)
						ELSE NULL
					END AS SOC_NUM1, 
					CASE 
						WHEN LEN(CU_JMNO) = 13 THEN SUBSTRING(CU_JMNO, 7, 7)
						ELSE NULL
					END AS SOC_NUM2, 
					HANDPHONE1, HANDPHONE2, HANDPHONE3, 
					CASE @SEX 
						WHEN 'M' THEN 'M'
						WHEN 'F' THEN 'F'
						ELSE NULL
					END AS GENDER, 
					@INS_EMP_NO
				FROM toursoft.toursoft2005.dbo.CU001
				WHERE CU_YY = @CU_YY AND CU_SEQ = @CU_SEQ

				SET @TMP_CUS_NO = @@IDENTITY

				INSERT INTO RES_CUSTOMER(RES_CODE, SEQ_NO, RES_STATE, CUS_NO, CUS_NAME, LAST_NAME, 
					FIRST_NAME, AGE_TYPE, GENDER, SOC_NUM1, SOC_NUM2, NOR_TEL1, NOR_TEL2, NOR_TEL3, EMAIL,
					PASS_NUM, PASS_EXPIRE, 
					SALE_PRICE, CHG_PRICE, DC_PRICE,TAX_PRICE, CHG_REMARK, ETC_REMARK, NEW_CODE)
				SELECT @RES_CODE, @SEQ_NO, 0, @TMP_CUS_NO, ISNULL(CU_NM_KOR, 'AAA'), 
					CASE 
						WHEN CHARINDEX('/', CU_NM_ENG) IS NULL THEN NULL
						WHEN CHARINDEX('/', CU_NM_ENG) = 0 THEN CU_NM_ENG
						ELSE SUBSTRING(ISNULL(CU_NM_ENG, ''), 1,CHARINDEX('/', CU_NM_ENG)-1)
					END AS LAST_NAME, 
					CASE 
						WHEN CHARINDEX('/', CU_NM_ENG) IS NULL THEN NULL
						WHEN CHARINDEX('/', CU_NM_ENG) = 0 THEN NULL
						ELSE SUBSTRING(ISNULL(CU_NM_ENG, ''), CHARINDEX('/', CU_NM_ENG)+1, LEN(CU_NM_ENG) - CHARINDEX('/', CU_NM_ENG))
					END AS FIRST_NAME, 
					CASE @AGE_CD 
						WHEN 'A' THEN 0
						WHEN 'C' THEN 1
						WHEN 'I' THEN 2
						ELSE 0
					END AS AGE_TYPE, 
					CASE @SEX 
						WHEN 'M' THEN 'M'
						WHEN 'F' THEN 'F'
						ELSE NULL
					END AS GENDER, 
					CASE 
						WHEN LEN(CU_JMNO) = 13 THEN SUBSTRING(CU_JMNO, 1, 6)
						ELSE NULL
					END AS SOC_NUM1, 
					CASE 
						WHEN LEN(CU_JMNO) = 13 THEN SUBSTRING(CU_JMNO, 7, 7)
						ELSE NULL
					END AS SOC_NUM2, 
					HANDPHONE1, HANDPHONE2, HANDPHONE3, EMAIL,
					PP_NO, CAST(PP_TERMINATION_DAY AS DATETIME) AS PASS_EXPIRE, 
					@SALE_AMT, @RES_ADD_AMT, @RES_DC_AMT, 0,
					@ADD_REMARK, @REMARK, @INS_EMP_NO
				FROM toursoft.toursoft2005.dbo.CU001 WITH(NOLOCK) 
				WHERE CU_YY = @CU_YY AND CU_SEQ = @CU_SEQ
			END
			ELSE
			BEGIN

				-- 출발자 정보 등록
				INSERT INTO CUS_CUSTOMER(CUS_NAME, SOC_NUM1, SOC_NUM2, NOR_TEL1, NOR_TEL2, NOR_TEL3, GENDER, NEW_CODE)
				VALUES('고객',NULL, NULL, NULL, NULL, NULL, 
						CASE @SEX 
						WHEN 'M' THEN 'M'
						WHEN 'F' THEN 'F'
						ELSE NULL
					END , @INS_EMP_NO)

				SET @TMP_CUS_NO = @@IDENTITY


				INSERT INTO RES_CUSTOMER(RES_CODE, SEQ_NO, RES_STATE, CUS_NO, CUS_NAME, LAST_NAME, 
					FIRST_NAME, AGE_TYPE, GENDER, SOC_NUM1, SOC_NUM2, NOR_TEL1, NOR_TEL2, NOR_TEL3, EMAIL,
					PASS_NUM, PASS_EXPIRE, 
					SALE_PRICE, CHG_PRICE, DC_PRICE,TAX_PRICE, CHG_REMARK, ETC_REMARK, NEW_CODE)
				VALUES(@RES_CODE, @SEQ_NO, 0, @TMP_CUS_NO, '고객', NULL, NULL,0, NULL, NULL, NULL,
					NULL, NULL, NULL, NULL, NULL, NULL,
					@SALE_AMT, @RES_ADD_AMT, @RES_DC_AMT, 0,
					@ADD_REMARK, @REMARK, @INS_EMP_NO)
			END

			FETCH NEXT FROM CUSTOMER_CURSOR INTO 
					@CU_YY, @CU_SEQ, @RES_NO, @SALE_AMT, @RES_AMT, @RES_DC_AMT, @RES_ADD_AMT,
					@AGE_CD, @DC_REMARK, @ADD_REMARK, @REMARK, @INS_EMP_NO, @INS_DT, @SEX
		END

		CLOSE CUSTOMER_CURSOR
		DEALLOCATE CUSTOMER_CURSOR

		--COMMIT TRAN

		SELECT @RES_CODE
	END TRY
	BEGIN CATCH
		--ROLLBACK TRAN;
		--PRINT ERROR_MESSAGE()
		--SELECT '0'
		SELECT ERROR_MESSAGE()
	END CATCH
END

--exec SP_RES_TOURSOFT_MIGRANTION '20090807', 55, 'ipt001-090901', 1



GO
