USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
	2012-03-02 READ UNCOMMITTED 설정
*/
CREATE PROCEDURE [dbo].[SP_DOC_RECEIPT_COUNT_SELECT]
	@EMP_CODE		CHAR(7)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	DECLARE @QUERY VARCHAR(8000), @GROUP_CODES VARCHAR(1000);
	--SET @EMP_CODE = '2006008';

	IF ((SELECT ISNULL(GROUP_CODE, '') FROM EMP_MASTER_damo WHERE EMP_CODE = @EMP_CODE) = '')
	BEGIN
		SET @QUERY = '
		SELECT COUNT(*) FROM EDI_MASTER_DAMO
		WHERE EDI_STATUS = ''3'' AND RCV_TEAM_CODE IN (
		SELECT TEAM_CODE FROM EMP_MASTER_damo WHERE EMP_CODE = ''' + @EMP_CODE + ''')
		AND ISNULL(RCV_CODE, '''') = '''''
	END
	ELSE
	BEGIN
		WITH GROUP_LIST AS
		(
			SELECT GROUP_CODE, PARENT_CODE, 0 AS [DEPTH] FROM EMP_GROUP_MASTER
			WHERE GROUP_CODE LIKE
			(
				SELECT (GROUP_CODE + '_') FROM EMP_MASTER
				WHERE EMP_CODE = @EMP_CODE
			)
			UNION ALL
			SELECT A.GROUP_CODE, A.PARENT_CODE, B.DEPTH + 1
			FROM EMP_GROUP_MASTER A
			INNER JOIN GROUP_LIST B ON A.PARENT_CODE = B.GROUP_CODE
		)
		SELECT
			@GROUP_CODES = (STUFF ((SELECT (', ''' + GROUP_CODE + '''') AS [text()] FROM GROUP_LIST FOR XML PATH('')), 1, 2, ''))

		SET @QUERY = 
		'SELECT COUNT(*) FROM EDI_MASTER_DAMO
		WHERE RCV_TEAM_CODE IN 
		(
			SELECT TEAM_CODE FROM EMP_GROUP_DETAIL
			WHERE GROUP_CODE IN (' + @GROUP_CODES + ')
		) AND EDI_STATUS = ''3''
		AND ISNULL(RCV_CODE, '''') = '''''
	END

	EXEC (@QUERY)
	--PRINT (@QUERY)
END

--SP_DOC_RECEIPT_COUNT_SELECT '2007044'

--SELECT * FROM EMP_MASTER_damo WHERE KOR_NAME = '백종구'


GO
