USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_COD_GETSEQ2]
(
@COD_TYPE VARCHAR(7),
@RETURN_CODE VARCHAR(10) OUTPUT,
@FLAG CHAR(1)
)
 AS
BEGIN 
	SET NOCOUNT OFF;
	BEGIN TRAN

	DECLARE @SEQ INT;
	DECLARE @VARSEQ VARCHAR(3);

	SELECT TOP 1 @SEQ  = ISNULL(MAX(COD_SQ),0) FROM COD_SEQ  WITH (UPDLOCK) WHERE COD_TYPE =@COD_TYPE

	 IF (@SEQ = 0) 
		BEGIN
			INSERT INTO COD_SEQ (COD_SQ,COD_TYPE, FLAG) VALUES ('0',@COD_TYPE, @FLAG)
			SET @SEQ = 0
		END 

	-- Flag 1: 9999 최대, 2: 제한없이 계속증가
	SET @SEQ = (@SEQ + 1)

	IF @SEQ > 999 AND EXISTS(SELECT * FROM COD_SEQ WHERE COD_TYPE = @COD_TYPE AND FLAG = '1')
		SET @SEQ = 1
	
--	IF @SEQ < 9999
--		SET @SEQ = (@SEQ + 1)
--	ELSE IF EXISTS(SELECT * FROM COD_SEQ WHERE COD_TYPE = @COD_TYPE AND FLAG = '1')
--		SET @SEQ = 1

	UPDATE COD_SEQ SET COD_SQ  = @SEQ WHERE COD_TYPE= @COD_TYPE

	IF(@COD_TYPE='EMP' )		--사원등록만 예외로 000을 채워준다
		BEGIN
			IF (LEN(@SEQ) < 3)
				BEGIN
					SET @VARSEQ='000'
				
					SET @VARSEQ = SUBSTRING(@VARSEQ,1,3-len(@seq)) + CAST( @SEQ AS VARCHAR)
					SET @RETURN_CODE = CAST(Year(GETDATE()) AS VARCHAR) +    @VARSEQ
				END
			ELSE
				BEGIN
					SET @RETURN_CODE = CAST(Year(GETDATE()) AS VARCHAR) +    @SEQ
				END

		END
	ELSE
		SET @RETURN_CODE = @SEQ
	
	COMMIT TRAN
END
GO
