USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- AUTHOR:		<김성호>
-- CREATE DATE: 2008-12-31
-- EDIT DATE: 2009-07-21 [MASTER 일정 멀티로 인해 수정]
-- DESCRIPTION:	<행사 상세일정 마스터 입력>
-- 2019-03-15 네이버 관련 컬럼추가 
-- =============================================
CREATE PROCEDURE [dbo].[SP_PKG_DETAIL_INSERT_NEW_SCHEDULE]
	@PRO_CODE		VARCHAR(20)
AS
BEGIN
	-- 행사일정 마스터 저장
	INSERT INTO PKG_DETAIL_SCH_MASTER 
	SELECT @PRO_CODE, SCH_SEQ, SCH_NAME FROM PKG_MASTER_SCH_MASTER  
	WHERE MASTER_CODE IN (SELECT MASTER_CODE FROM PKG_DETAIL   WHERE PRO_CODE = @PRO_CODE)
	
	-- 행사일정 일자 저장
	INSERT INTO PKG_DETAIL_SCH_DAY
	SELECT @PRO_CODE, SCH_SEQ, DAY_SEQ, DAY_NUMBER,FREE_SCH_YN FROM PKG_MASTER_SCH_DAY    --19.03 자유일정유무추가
	WHERE MASTER_CODE IN (SELECT MASTER_CODE FROM PKG_DETAIL   WHERE PRO_CODE = @PRO_CODE)

	-- 행사일정 도시 저장
	INSERT INTO PKG_DETAIL_SCH_CITY
	SELECT @PRO_CODE, SCH_SEQ, DAY_SEQ, CITY_SEQ, CITY_CODE, MAINCITY_YN, CITY_SHOW_ORDER FROM PKG_MASTER_SCH_CITY  
	WHERE MASTER_CODE IN (SELECT MASTER_CODE FROM PKG_DETAIL   WHERE PRO_CODE = @PRO_CODE)

	-- 행사일정 컨텐츠 저장
	INSERT INTO PKG_DETAIL_SCH_CONTENT
	SELECT @PRO_CODE, SCH_SEQ, DAY_SEQ, CITY_SEQ, CNT_SEQ, CNT_CODE, CNT_INFO, CNT_SHOW_ORDER FROM PKG_MASTER_SCH_CONTENT  
	WHERE MASTER_CODE IN (SELECT MASTER_CODE FROM PKG_DETAIL WHERE PRO_CODE = @PRO_CODE)

	-- 마스터 상세와 관광일수 차이가 있을때 실행
	DECLARE @MASTER_CODE VARCHAR(10), @TOURDAY INT, @MASTER_SCH_SEQ INT, @SCHEDULEDAY INT, @SCHEDULESEQ INT , @FREE_SCH_YN CHAR(1)  --19.03 자유일정유무추가
	SELECT @MASTER_CODE = MASTER_CODE, @TOURDAY = ISNULL(TOUR_DAY, 0) FROM PKG_DETAIL   WHERE PRO_CODE = @PRO_CODE
	
	-- 멀티 스케줄 관련 커서
	DECLARE SCH_CURSOR CURSOR FOR
	SELECT SCH_SEQ FROM PKG_MASTER_SCH_MASTER  
	WHERE MASTER_CODE = @MASTER_CODE
	
	OPEN SCH_CURSOR
	
	FETCH NEXT FROM SCH_CURSOR
	INTO @MASTER_SCH_SEQ
	
	WHILE @@FETCH_STATUS = 0
	BEGIN
		SELECT @SCHEDULESEQ = ISNULL(MAX(DAY_SEQ), 0), @SCHEDULEDAY = ISNULL(MAX(DAY_NUMBER), 0)  
			, @FREE_SCH_YN = MAX(FREE_SCH_YN)  --19.03 자유일정유무추가
		FROM PKG_MASTER_SCH_DAY	  WHERE MASTER_CODE = @MASTER_CODE AND SCH_SEQ = @MASTER_SCH_SEQ
		
		IF (@SCHEDULEDAY < @TOURDAY)
		BEGIN
			WHILE (@SCHEDULEDAY < @TOURDAY)
			BEGIN
				SET @SCHEDULESEQ = @SCHEDULESEQ + 1
				SET @SCHEDULEDAY = @SCHEDULEDAY + 1
				INSERT INTO PKG_DETAIL_SCH_DAY VALUES (@PRO_CODE, @MASTER_SCH_SEQ, @SCHEDULESEQ, @SCHEDULEDAY,@FREE_SCH_YN);
			END
		END
		ELSE IF (@SCHEDULEDAY > @TOURDAY)
		BEGIN
			DELETE FROM PKG_DETAIL_SCH_DAY WHERE PRO_CODE = @PRO_CODE AND SCH_SEQ = @MASTER_SCH_SEQ AND DAY_NUMBER > @TOURDAY
		END
	
		--PRINT @MASTER_SCH_SEQ
		
		FETCH NEXT FROM SCH_CURSOR
		INTO @MASTER_SCH_SEQ
	END
	CLOSE SCH_CURSOR
	DEALLOCATE SCH_CURSOR
END




GO
