USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_ACC_GET_DUZ_CODE]
(
	@RES_CODE	VARCHAR(20)
)
 AS
BEGIN
	BEGIN TRAN
	
	DECLARE @DUZ_CODE VARCHAR(20), @PRO_CODE VARCHAR(20), @DEP_STR VARCHAR(6), @TMP_DUZ_CODE VARCHAR(20)
	
	IF NOT EXISTS(SELECT 1 FROM ACC_MATCHING WITH(NOLOCK) WHERE PRO_CODE IN (SELECT PRO_CODE FROM RES_MASTER_damo WITH(NOLOCK) WHERE RES_CODE = @RES_CODE))
	BEGIN
		SELECT @PRO_CODE = PRO_CODE, @DEP_STR = (
			CASE WHEN DEP_DATE IS NULL THEN SUBSTRING(PRO_CODE, (CHARINDEX('-', PRO_CODE) + 1), 6)
			ELSE CONVERT(VARCHAR(10), DEP_DATE, 12) END
		)
		FROM RES_MASTER_damo WITH(NOLOCK)
		WHERE RES_CODE = @RES_CODE
		
		SET @TMP_DUZ_CODE = ISNULL((SELECT TOP 1 DUZ_CODE FROM ACC_MATCHING WITH(NOLOCK) WHERE DUZ_CODE LIKE (@DEP_STR + '%') ORDER BY DUZ_CODE DESC), '')
		
		-- 더존코드 EX)FORM : YYMMDD(출발일)-0001
		IF @TMP_DUZ_CODE = ''
		BEGIN
			SET @DUZ_CODE = (@DEP_STR + '-0001')
		END
		ELSE
		BEGIN
			SET @DUZ_CODE = (@DEP_STR + '-' + RIGHT(('0000' + CONVERT(VARCHAR(4), (CONVERT(INT, SUBSTRING(@TMP_DUZ_CODE, 8, 10)) + 1))), 4))
		END
		
		INSERT INTO ACC_MATCHING (DUZ_CODE, PRO_CODE) VALUES (@DUZ_CODE, @PRO_CODE)
	END
	
	COMMIT TRAN
END
GO
