USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*==================================================================================
	기본내용
====================================================================================
- SP 명 : SP_PKG_EVENT_GROUP_SELECT_LIST
- 기 능 : 그룹코드 상품 조회 - 날짜별 
====================================================================================
	참고내용
====================================================================================
- 예제

EXEC SP_PKG_EVENT_GROUP_SELECT_LIST  'CPP0006,CPS-009,CCPP111,CCPP002,cpp137,cpp365' , '2013-02-01'

====================================================================================
	변경내역
====================================================================================
- 2013-01-31 박형만 신규 작성 
===================================================================================*/
CREATE PROC [dbo].[SP_PKG_EVENT_GROUP_SELECT_LIST]
	@GROUP_CODES VARCHAR(1000),
	@DEP_DATE DATETIME
AS 
SET NOCOUNT ON 
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--DECLARE @GROUP_CODES VARCHAR(1000),
--	@DEP_DATE DATETIME
--SELECT @GROUP_CODES = 'CPP0006,CPS-009,CCPP111,CCPP002,cpp137,cpp365' , @DEP_DATE = '2013-02-01'

	SELECT
		PG.GROUP_CODE ,
		(SELECT GROUP_NAME FROM GRP_MASTER WHERE GROUP_CODE = PG.GROUP_CODE) AS  GROUP_NAME , 
		PM.MASTER_CODE , PD.PRO_CODE ,  PDP.PRICE_SEQ , 
		PD.DEP_DATE, 
		PD.TOUR_NIGHT, PD.TOUR_DAY, PDP.ADT_PRICE ,  PDP.PRICE_SEQ , 
		
		DBO.FN_PRO_GET_RES_COUNT(PD.PRO_CODE) AS RES_COUNT,
		--PD.FAKE_COUNT,
		--CASE WHEN PD.MAX_COUNT > 40 OR  PD.MAX_COUNT = 0  THEN 40 ELSE PD.MAX_COUNT END AS MAX_COUNT  ,
		PD.PRO_NAME , 
		PD.PKG_SUMMARY ,
		PM.PKG_COMMENT,
		IFM.FILE_CODE ,IFM.REGION_CODE,IFM.NATION_CODE,IFM.STATE_CODE,IFM.CITY_CODE,
		(SELECT KOR_NAME FROM PUB_REGION B WHERE B.REGION_CODE = IFM.REGION_CODE) AS REGION_NAME,
		(SELECT KOR_NAME FROM PUB_CITY B WHERE B.CITY_CODE = IFM.CITY_CODE) AS CITY_NAME,
		IFM.KOR_NAME,IFM.ENG_NAME,
		IFM.FILE_TYPE,IFM.FILE_NAME,IFM.EXTENSION_NAME,IFM.FILE_SIZE,
		IFM.FILE_NAME_S,IFM.FILE_NAME_M,IFM.FILE_NAME_L,
		IFM.FILE_REMARK,IFM.FILE_TAG,IFM.RESOLUTION,
		IFM.COPYRIGHT,
		IFM.COPYRIGHT_REMARK,
		IFM.SHOW_YN
		
	FROM PKG_GROUP AS PG WITH(NOLOCK)
		INNER JOIN PKG_MASTER AS PM WITH(NOLOCK)
			ON	PG.MASTER_CODE = PM.MASTER_CODE  
		INNER JOIN PKG_DETAIL AS PD WITH(NOLOCK)
			ON	PM.MASTER_CODE = PD.MASTER_CODE  
			AND PD.DEP_DATE = @DEP_DATE
		INNER JOIN PKG_DETAIL_PRICE AS PDP WITH(NOLOCK)
			ON	PD.PRO_CODE = PDP.PRO_CODE  
			AND PDP.PRICE_SEQ  = 
			( 
				SELECT TOP 1 PRICE_SEQ FROM PKG_DETAIL_PRICE AS SUB1
					INNER JOIN PKG_DETAIL_SCH_MASTER AS SUB2
						ON SUB1.PRO_CODE = SUB2.PRO_CODE 
						AND SUB1.SCH_SEQ = SUB2.SCH_SEQ
				WHERE PDP.PRO_CODE = SUB1.PRO_CODE
				ORDER BY SUB1.ADT_PRICE ASC 
			)
		INNER JOIN PKG_DETAIL_FILE AS PDF WITH(NOLOCK) 
			ON PD.PRO_CODE = PDF.PRO_CODE  
			AND PDF.FILE_CODE = (  SELECT TOP 1 FILE_CODE FROM PKG_DETAIL_FILE S1
					WHERE S1.PRO_CODE = PDF.PRO_CODE 
					ORDER  BY SHOW_ORDER , FILE_CODE ) 
			
		LEFT OUTER JOIN INF_FILE_MASTER AS IFM WITH(NOLOCK) 
			ON PDF.FILE_CODE = IFM.FILE_CODE
			--ON PM.MAIN_FILE_CODE = IFM.FILE_CODE  
		
	WHERE PG.GROUP_CODE IN (SELECT DATA FROM DBO.FN_SPLIT(@GROUP_CODES,','))
	ORDER BY PG.GROUP_CODE ASC, PD.PRO_CODE , PDP.ADT_PRICE,  PM.GROUP_ORDER 

END 

GO
