USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*================================================================================================================
■ USP_NAME					: [XP_COM_AGENT_DEFAULT_INSERT]
■ DESCRIPTION				: 거래처등록 초기데이터생성
■ INPUT PARAMETER			: 
■ OUTPUT PARAMETER			: 

■ EXEC						: 
	EXEC XP_COM_AGENT_DEFAULT_INSERT '93832', 'JUSTGOTEST', '0AA10C4B57356216B4E6B0AEB998372643354D96', '9910001'

■ MEMO						: 
------------------------------------------------------------------------------------------------------------------
■ CHANGE HISTORY                   
------------------------------------------------------------------------------------------------------------------
   DATE				AUTHOR			DESCRIPTION           
------------------------------------------------------------------------------------------------------------------
   2016-04-29		저스트고-이유라		최초생성
================================================================================================================*/ 
CREATE PROCEDURE [dbo].[XP_COM_AGENT_DEFAULT_INSERT]
(
	@AGT_CODE		VARCHAR(10),
	@AGT_DOMAIN		VARCHAR(20),
	@AGT_PASSWORD	VARCHAR(MAX)
)
AS

BEGIN

    DECLARE @DECEMP_SEQ INT, @POS_SEQ INT, @ORDER_NUM INT
	
		SET @DECEMP_SEQ = (ISNULL((SELECT MAX(EMP_SEQ) FROM COM_EMPLOYEE A WITH(NOLOCK) WHERE A.AGT_CODE = @AGT_CODE ), 100) + 1)

		--1) 공지사항
		INSERT INTO COM_BBS_MASTER
		(	AGT_CODE,MASTER_SEQ, [SUBJECT],	[DESC],	BOARD_TYPE,	REPLY_YN, REGION_YN, NOTICE_YN, CATEGORY_YN, USE_YN, NEW_DATE, NEW_SEQ,	EDT_DATE, EDT_SEQ, LIST_TOP, VIEW_TOP)
		VALUES
		(	@AGT_CODE,	1,	'공지사항',	'공지사항',	1, 'N',	'N', 'Y', 'N', 'Y',	GETDATE(),	@DECEMP_SEQ,	NULL,	NULL,	1,	1)

		--2) 출장후기
		INSERT INTO COM_BBS_MASTER
		(	AGT_CODE,MASTER_SEQ, [SUBJECT],	[DESC],	BOARD_TYPE,	REPLY_YN, REGION_YN, NOTICE_YN, CATEGORY_YN, USE_YN, NEW_DATE, NEW_SEQ,	EDT_DATE, EDT_SEQ, LIST_TOP, VIEW_TOP)
		VALUES
		(	@AGT_CODE,	2,	'출장후기',	'출장후기',	1, 'N',	'Y', 'N', 'N', 'Y',	GETDATE(),	@DECEMP_SEQ,	NULL,	NULL,	1,	1)

		--3) 비자정보
		INSERT INTO COM_BBS_MASTER
		(	AGT_CODE,MASTER_SEQ, [SUBJECT],	[DESC],	BOARD_TYPE,	REPLY_YN, REGION_YN, NOTICE_YN, CATEGORY_YN, USE_YN, NEW_DATE, NEW_SEQ,	EDT_DATE, EDT_SEQ, LIST_TOP, VIEW_TOP)
		VALUES
		(	@AGT_CODE,	3,	'비자정보',	'비자정보',	1, 'N',	'Y', 'Y', 'N', 'Y',	GETDATE(),	@DECEMP_SEQ,	NULL,	NULL,	0,	1)

		--4) 온라인상담
		INSERT INTO COM_BBS_MASTER
		(	AGT_CODE,MASTER_SEQ, [SUBJECT],	[DESC],	BOARD_TYPE,	REPLY_YN, REGION_YN, NOTICE_YN, CATEGORY_YN, USE_YN, NEW_DATE, NEW_SEQ,	EDT_DATE, EDT_SEQ, LIST_TOP, VIEW_TOP)
		VALUES
		(	@AGT_CODE,	4,	'온라인상담',	'온라인상담',	1, 'N',	'N', 'N', 'Y', 'Y',	GETDATE(),	@DECEMP_SEQ,	NULL,	NULL,	0,	1)


		--5) 사원 직급 추가

		INSERT INTO COM_POSITION
		(	
			AGT_CODE,	POS_SEQ,	POS_NAME,	ORDER_NUM,	NEW_DATE,	NEW_SEQ
		)
		VALUES
		(
			@AGT_CODE,	1,	'사원',	1, GETDATE(), @DECEMP_SEQ
		)

		--5) 관리자 아이디 
		INSERT INTO COM_EMPLOYEE
		(
			AGT_CODE,	EMP_SEQ,	TEAM_SEQ,	EMP_ID,	KOR_NAME,	LAST_NAME,	FIRST_NAME,	BIRTH_DATE,	GENDER,	PASS_WORD,	POS_SEQ,	WORK_TYPE,	JOIN_DATE,	OUT_DATE,	EMAIL,
			COM_NUMBER,	HP_NUMBER,	FAX_NUMBER,	SEAT_REMARK,	AIR_REMARK,	HOTEL_REMARK,	FAIL_COUNT,	MANAGER_YN,	NEW_DATE,	NEW_SEQ,	EDT_DATE,	EDT_SEQ,	MAIL_RECEIVE_YN
		)
		VALUES
		(
			@AGT_CODE,	@DECEMP_SEQ,	NULL,	@AGT_DOMAIN, '관리자',	'',	'',	NULL,	'M',	
			@AGT_PASSWORD,	'1',	'1',	NULL,	NULL,	(SELECT AGT_MGR_NAME FROM AGT_MASTER  WHERE AGT_CODE = @AGT_CODE), 	'--',	'--',   '--',
			NULL, NULL, NULL, 0,	'Y',	GETDATE(),	@DECEMP_SEQ,	NULL,	NULL,	'Y'
		)

		--6) 관리자 권한

		DECLARE @CNT INT, @MENU_SEQ INT;
		SET @CNT = 0;
	    WHILE @CNT < (SELECT COUNT(*) FROM COM_MENU)
		BEGIN
			IF(@CNT = 0)
			BEGIN 
				SET @MENU_SEQ = 100
			END
			ELSE
			BEGIN
				SET @MENU_SEQ = (SELECT TOP 1 A.MENU_SEQ FROM COM_MENU A WHERE A.MENU_SEQ > ISNULL((SELECT TOP 1 MENU_SEQ FROM COM_AUTH_MENU WHERE AGT_CODE = @AGT_CODE AND EMP_SEQ = @DECEMP_SEQ ORDER BY MENU_SEQ DESC),100) ORDER BY A.MENU_SEQ )
			END
			INSERT INTO COM_AUTH_MENU
			(AGT_CODE,EMP_SEQ,MENU_SEQ)
			VALUES
			(@AGT_CODE,	@DECEMP_SEQ,	@MENU_SEQ)

			SET @CNT = @CNT + 1;
		END;

		--7) 기본규정 그룹
		 INSERT INTO COM_BIZTRIP_GROUP
		(
			AGT_CODE, BT_SEQ, BTG_NAME, ALL_YN,	REPORT_YN, EMAIL_SEND_YN, CONFIRM_YN, AIR_SAME_YN, AIR_LIKE_YN, HOTEL_LIKE_YN, USE_YN, NEW_DATE, NEW_SEQ, EDT_DATE, EDT_SEQ, ORDER_NUM
		)
		VALUES
		(
			@AGT_CODE, 1, '기본그룹', 'Y', 'N', 'N', 'N', 'N', 'N','N',	'Y', GETDATE(),@DECEMP_SEQ, NULL, NULL, 1
		)

		--9) 항공규정 등록
		INSERT INTO COM_AIR_RULE
		(
			AGT_CODE, BT_SEQ, AIR_RULE_SEQ, START_HOUR,	END_HOUR, CLASS, USE_YN, NEW_DATE, NEW_SEQ
		)
		VALUES
		(
			@AGT_CODE,	1, 1,	'0', '0',	'E',	'N', GETDATE(),	@DECEMP_SEQ
		)

		INSERT INTO COM_AIR_RULE
		(
			AGT_CODE, BT_SEQ, AIR_RULE_SEQ, START_HOUR,	END_HOUR, CLASS, USE_YN, NEW_DATE, NEW_SEQ
		)
		VALUES
		(
			@AGT_CODE,	1, 2,	'0', '0',	'B',	'N', GETDATE(),	@DECEMP_SEQ
		)

		INSERT INTO COM_AIR_RULE
		(
			AGT_CODE, BT_SEQ, AIR_RULE_SEQ, START_HOUR,	END_HOUR, CLASS, USE_YN, NEW_DATE, NEW_SEQ
		)
		VALUES
		(
			@AGT_CODE,	1, 3,	'0', '0',	'F',	'N', GETDATE(),@DECEMP_SEQ
		)

		--10) 거래처이메일주소 없을시 @로 업데이트 / 에러처리
		IF((SELECT AGT_MGR_EMAIL FROM AGT_MASTER WHERE AGT_CODE = @AGT_CODE) IS NULL)
		BEGIN 
			UPDATE AGT_MASTER SET AGT_MGR_EMAIL = '@' WHERE AGT_CODE = @AGT_CODE
		END

		--11) 거래처우편번호 없을시 -로 업데이트 / 에러처리
		IF((SELECT AGT_MGR_EMAIL FROM AGT_MASTER WHERE AGT_CODE = @AGT_CODE) IS NULL)
		BEGIN 
			UPDATE AGT_MASTER SET ZIP_CODE = '-' WHERE AGT_CODE = @AGT_CODE
		END

END
GO
