USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*================================================================================================================
■ USP_NAME					: XP_WEB_RES_HOTEL_INFO_SELECT
■ DESCRIPTION				: 호텔 예약 등록 정보 
■ INPUT PARAMETER			: 

	exec XP_WEB_RES_HOTEL_INFO_SELECT @RES_CODE=N'RH1603152693'
	XP_WEB_RES_HOTEL_INFO_SELECT '92756',1

■ OUTPUT PARAMETER			: 
■ EXEC						: 
	
■ MEMO						: 
------------------------------------------------------------------------------------------------------------------
■ CHANGE HISTORY                   
------------------------------------------------------------------------------------------------------------------
   DATE				AUTHOR			DESCRIPTION           
------------------------------------------------------------------------------------------------------------------
   2016-03-15		박형만			최초생성 
   2016-04-05		박형만			나이 추가 
================================================================================================================*/ 
CREATE PROC [dbo].[XP_WEB_RES_HOTEL_INFO_SELECT]
	@RES_CODE RES_CODE 
AS
BEGIN

-- 호텔 기본 예약 정보 
SELECT 
A.RES_CODE, A.RES_NAME, A.RES_STATE, 
A.MASTER_CODE, A.PRO_NAME, A.RES_STATE, 
A.CUS_REQUEST , A.CUS_RESPONSE , A.SALE_COM_CODE,
A.LAST_PAY_DATE , dbo.FN_RES_GET_PAY_PRICE(A.RES_CODE) AS PAY_PRICE  
FROM RES_MASTER_DAMO A WITH(NOLOCK) 
WHERE RES_CODE = @RES_CODE

-- 호텔룸 마스터 정보
SELECT
A.MASTER_CODE AS HOTEL_CODE ,
A.HOTEL_NAME  ,
A.CHECK_IN, A.CHECK_OUT, A.CITY_CODE, A.LAST_CXL_DATE, A.ROOM_YN, A.SALE_PRICE, A.POINT_RATE, A.CXL_REMARK, 
A.SUP_CODE, A.SUP_RES_CODE ,
C.KOR_NAME AS CITY_NAME, 
D.KOR_NAME AS NATION_NAME ,
A.NON_REFUND_YN 
FROM RES_HTL_ROOM_MASTER A WITH(NOLOCK)
	--LEFT JOIN HTL_MASTER B WITH(NOLOCK) ON A.MASTER_CODE = B.MASTER_CODE
	LEFT JOIN PUB_CITY C WITH(NOLOCK) ON A.CITY_CODE = C.CITY_CODE
	LEFT JOIN PUB_NATION D WITH(NOLOCK) ON C.NATION_CODE = D.NATION_CODE
	--LEFT JOIN INF_HOTEL E WITH(NOLOCK) ON C.CNT_CODE = E.CNT_CODE
WHERE A.RES_CODE = @RES_CODE;

-- 호텔 룸 정보
SELECT RES_CODE,ROOM_NO,ROOM_TYPE,ROOM_NAME,ROOM_COUNT,BREAKFAST_YN,PRICE_SEQ ,  
(SELECT COUNT(*) FROM RES_HTL_CUSTOMER_DETAIL AA INNER JOIN RES_CUSTOMER_damo BB ON AA.RES_CODE = BB.RES_CODE AND AA.SEQ_NO = BB.SEQ_NO  WHERE AA.RES_CODE = A.RES_CODE AND AA.ROOM_NO = A.ROOM_NO AND BB.AGE_TYPE = 0 )  AS ADT_CNT ,
(SELECT COUNT(*) FROM RES_HTL_CUSTOMER_DETAIL AA INNER JOIN RES_CUSTOMER_damo BB ON AA.RES_CODE = BB.RES_CODE AND AA.SEQ_NO = BB.SEQ_NO  WHERE AA.RES_CODE = A.RES_CODE AND AA.ROOM_NO = A.ROOM_NO AND BB.AGE_TYPE IN(1,2) )  AS CHD_CNT 
FROM RES_HTL_ROOM_DETAIL A WITH(NOLOCK) 
WHERE RES_CODE = @RES_CODE
GROUP BY RES_CODE,ROOM_NO,ROOM_TYPE,ROOM_NAME,ROOM_COUNT,BREAKFAST_YN,PRICE_SEQ

--예약마스터정보
SELECT A.* , B.GENDER, B.BIRTH_DATE , DBO.FN_RES_GET_PAY_PRICE(A.RES_CODE) AS [PAY_PRICE]
FROM RES_MASTER_DAMO A WITH(NOLOCK)
	LEFT JOIN CUS_CUSTOMER_DAMO B WITH(NOLOCK)
		ON A.CUS_NO = B.CUS_NO
WHERE A.RES_CODE = @RES_CODE;

--출발자정보
SELECT
	A.RES_CODE, A.SEQ_NO, A.CUS_NAME, A.GENDER, A.LAST_NAME, A.FIRST_NAME
	, C.BIRTH_DATE--, A.SOC_NUM1
	--, DAMO.DBO.DEC_VARCHAR('DIABLO', 'DBO.RES_CUSTOMER', 'SOC_NUM2', A.SEC_SOC_NUM2) AS SOC_NUM2
	, A.AGE_TYPE , B.AGE 
	, A.VISA_YN  , A.PASS_EXPIRE , A.PASS_ISSUE
	, DAMO.DBO.DEC_VARCHAR('DIABLO', 'DBO.RES_CUSTOMER', 'PASS_NUM', A.SEC_PASS_NUM) AS PASS_NUM
	, B.ROOM_NO 
	, D.AGT_CODE , D.EMP_SEQ , ISNULL(E.KOR_NAME,A.CUS_NAME) AS CUS_NAME  ,  F.TEAM_NAME
	, A.ETC_REMARK 
FROM RES_CUSTOMER_DAMO A WITH(NOLOCK)
	LEFT JOIN RES_HTL_CUSTOMER_DETAIL B WITH(NOLOCK)
		ON A.RES_CODE = B.RES_CODE 
		AND A.SEQ_NO = B.SEQ_NO 
	LEFT JOIN CUS_CUSTOMER_DAMO C WITH(NOLOCK)
		ON A.CUS_NO = C.CUS_NO
	--LEFT JOIN PUB_AIRLINE E1 WITH(NOLOCK)
	--	ON E1.AIRLINE_CODE = B.DEP_AIRLINE_CODE
	--LEFT JOIN PUB_AIRLINE E2 WITH(NOLOCK)
	--	ON E2.AIRLINE_CODE = B.ARR_AIRLINE_CODE

	LEFT JOIN COM_EMPLOYEE_MATCHING D WITH(NOLOCK)
		ON A.CUS_NO = D.CUS_NO 
	LEFT JOIN COM_EMPLOYEE E WITH(NOLOCK)
		ON D.AGT_CODE = E.AGT_CODE
		AND D.EMP_SEQ = E.EMP_SEQ 
	LEFT JOIN COM_TEAM F WITH(NOLOCK)
		ON E.AGT_CODE = F.AGT_CODE
		AND E.TEAM_SEQ = F.TEAM_SEQ 

WHERE A.RES_CODE =  @RES_CODE
ORDER BY A.SEQ_NO ASC 

--담당자정보
DECLARE @EMP_CODE CHAR(7)
SELECT @EMP_CODE = NEW_CODE FROM RES_MASTER_damo WITH(NOLOCK) WHERE RES_CODE = @RES_CODE

SELECT 
	EMP_CODE, KOR_NAME, INNER_NUMBER1, INNER_NUMBER2, INNER_NUMBER3, 
	FAX_NUMBER1, FAX_NUMBER2, FAX_NUMBER3, EMAIL, GREETING , 
	A.TEAM_CODE , (SELECT TEAM_NAME FROM EMP_TEAM WITH(NOLOCK) WHERE TEAM_CODE = A.TEAM_CODE) AS [TEAM_NAME] 
FROM EMP_MASTER A WITH(NOLOCK)
WHERE EMP_CODE = @EMP_CODE

END 
GO
