USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_COLUMNS_SEARCH]
(
	@COLUMN_NAME VARCHAR(50)
)
 AS
BEGIN 
	SET NOCOUNT OFF;

	SELECT A.NAME AS TABLE_NAME,B.NAME AS COLUMN_NAME 
	FROM SYSOBJECTS A , SYSCOLUMNS B 
	WHERE A.ID = B.ID 
	AND B.NAME = @COLUMN_NAME
	ORDER BY A.NAME
END
GO
