USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		 
-- Create date:  2011-11-28
-- Description:	<팩스 수신함 조회 - 번호로 조회 >
-- SP_FAX_MASTER_SEARCH_BY_FAX_NUMBER_LIST '02','6944','9107',15,1
-- 2012-03-02 박형만 WITH(NOLOCK) 추가 	
-- =============================================
CREATE PROCEDURE [dbo].[SP_FAX_MASTER_SEARCH_BY_FAX_NUMBER_LIST]
	
	@RCV_NUMBER1 VARCHAR(4),
	@RCV_NUMBER2 VARCHAR(4),
	@RCV_NUMBER3 VARCHAR(4),
	
	@PAGE_SIZE INT ,
	@PAGE_INDEX INT
AS
BEGIN	
	DECLARE @FROM INT 
	DECLARE @TO INT
	SET @FROM = @PAGE_INDEX * @PAGE_SIZE + 1;
	SET @TO = @PAGE_INDEX * @PAGE_SIZE + @PAGE_SIZE;
	
	WITH DOCUMENTLIST AS ( 
		SELECT 
			ROW_NUMBER() OVER (ORDER BY A.NEW_DATE DESC )  AS ROW_NUM ,
			A.*,
			B.RCV_NUMBER1 , B.RCV_NUMBER2 , B.RCV_NUMBER3 , B.RCV_EMP_CODE
		FROM FAX_MASTER  A WITH(NOLOCK) 
			INNER JOIN FAX_RECEIVE B WITH(NOLOCK)
				ON A.FAX_SEQ = B.FAX_SEQ 
		WHERE A.FAX_TYPE = 2 AND A.DEL_YN='N' 
		
		AND B.RCV_NUMBER1 = @RCV_NUMBER1
		AND B.RCV_NUMBER2 = @RCV_NUMBER2
		AND B.RCV_NUMBER3 = @RCV_NUMBER3
	)
	SELECT 
		(SELECT [SUBJECT] FROM FAX_CATEGORY WITH(NOLOCK) WHERE FAX_CAT_SEQ =A.FAX_CAT_SEQ  AND FAX_GROUP = A.FAX_GROUP AND DEL_YN='N') AS CAT_NAME , 
		(SELECT KOR_NAME FROM EMP_MASTER WITH(NOLOCK) WHERE EMP_CODE =A.RCV_EMP_CODE) AS RCV_EMP_NAME , 
		* 
	FROM  DOCUMENTLIST AS A 
	WHERE ROW_NUM BETWEEN @FROM AND @TO;
END 
GO
