USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*==================================================================================
	기본내용
====================================================================================
- SP 명 : SP_HBS_DETAIL_MOVE_COPY
- 기 능 : HBS 게시물 이동  . 파일이동 기능 보류 
고객이 남긴글만 처리 가능 ( 답글 LEVEL 1 만 처리 가능 ) 
원글은 복사 하고 이동메시지를 남겨 주며
나머지 답글 및 답글의 댓글은 모두 이동한다.
====================================================================================
	참고내용
====================================================================================
- 예제 EXEC SP_HBS_DETAIL_MOVE_COPY @MASTER_SEQ=1, @BOARD_SEQ= 9130,@NEW_MASTER_SEQ=19,@NEW_CATEGORY_SEQ = 1,@MOVE_MESSAGE = '해당 글은 게시판 성격과 맞지 않아 고객의 소리로 이동 되었습니다'
====================================================================================
	변경내역
====================================================================================
- 2011-08-22 신규 작성 
- 2011-09-01 게시물 이동시 현재글 삭제(DEL_YN=Y)상태로 변경 
- 2011-09-16 게시물 이동 사번 입력 
===================================================================================*/
CREATE PROC [dbo].[SP_HBS_DETAIL_MOVE_COPY]
	@MASTER_SEQ INT ,
	@BOARD_SEQ INT ,
	@NEW_MASTER_SEQ INT ,
	@NEW_CATEGORY_SEQ INT ,
	@MOVE_MESSAGE VARCHAR(1000),
	@NEW_CODE EMP_CODE
AS

--DECLARE  @MASTER_SEQ INT ,
--	@BOARD_SEQ INT ,
--	@NEW_MASTER_SEQ INT ,
--	@NEW_CATEGORY_SEQ INT ,
--	@MOVE_MESSAGE VARCHAR(1000)
	
BEGIN TRY

--DECLARE @MASTER_SEQ INT ,@NEW_MASTER_SEQ INT ,@NEW_CATEGORY_SEQ INT, , @BOARD_SEQ INT 
--SELECT @MASTER_SEQ = 1 ,@NEW_MASTER_SEQ = 19   ,NEW_CATEGORY_SEQ = 1 , @BOARD_SEQ= 9130   --여행후기를 고객의 소리로 

BEGIN TRAN 

	DECLARE @NEW_BOARD_SEQ INT 
	--현재글 복사
	--복사글 번호 
	SELECT @NEW_BOARD_SEQ = ISNULL(MAX(BOARD_SEQ), 0) + 1 FROM HBS_DETAIL WHERE MASTER_SEQ = @NEW_MASTER_SEQ;
	INSERT INTO HBS_DETAIL
	(MASTER_SEQ, BOARD_SEQ, CATEGORY_SEQ, 
		PARENT_SEQ, LEVEL, STEP, SUBJECT, 
		CONTENTS, SHOW_COUNT, NOTICE_YN, DEL_YN, IP_ADDRESS, 
		COMPLETE_YN, FILE_PATH, EDIT_PASS, LOCK_YN, MASTER_CODE, CNT_CODE, REGION_NAME, 
		NICKNAME, PHONE_NUM, EMAIL, NEW_DATE, NEW_CODE, EDT_DATE, EDT_CODE, EMP_CODE, GOOD_TYPE_CD, 
		AREA_CD, GOOD_YY, GOOD_SEQ)
	SELECT TOP 1 
		@NEW_MASTER_SEQ, @NEW_BOARD_SEQ, @NEW_CATEGORY_SEQ AS CATEGORY_SEQ, 
		@NEW_BOARD_SEQ AS PARENT_SEQ, LEVEL, STEP, SUBJECT, 
		 CONTENTS, SHOW_COUNT, NOTICE_YN, DEL_YN, IP_ADDRESS, 
		COMPLETE_YN, FILE_PATH, EDIT_PASS, LOCK_YN, MASTER_CODE, CNT_CODE, REGION_NAME, 
		NICKNAME, PHONE_NUM, EMAIL, GETDATE() NEW_DATE , NEW_CODE, EDT_DATE, EDT_CODE, EMP_CODE, GOOD_TYPE_CD, 
		AREA_CD, GOOD_YY, GOOD_SEQ
	FROM HBS_DETAIL WITH(NOLOCK)
	WHERE MASTER_SEQ = @MASTER_SEQ
	AND BOARD_SEQ = @BOARD_SEQ
	
	--복사된글 컨텐츠 텍스트 APPEND 
	--UPDATE HBS_DETAIL
	--SET CONTENTS.WRITE(N'*관리자에 의해 게시물이 이동되었습니다<BR>', 0, 0)
	--WHERE MASTER_SEQ = @NEW_MASTER_SEQ
	--AND BOARD_SEQ = @NEW_BOARD_SEQ 
	
	--현재글 내용 변경 
	UPDATE HBS_DETAIL
	SET SUBJECT ='해당 글은 게시판 성격과 맞지 않아 고객의 소리로 이동 되었습니다'
		, CONTENTS = '해당 글은 게시판 성격과 맞지 않아 고객의 소리로 이동 되었습니다' + '이동글번호:' + CONVERT(VARCHAR,@NEW_BOARD_SEQ )
		,EDT_DATE = GETDATE() , EDT_CODE = @NEW_CODE
		, DEL_YN = 'Y'
	WHERE MASTER_SEQ = @MASTER_SEQ
	AND BOARD_SEQ = @BOARD_SEQ 
	
	--현재글의 댓글 이동 
	INSERT INTO HBS_COMMENT
	(MASTER_SEQ, BOARD_SEQ, COMMENT_SEQ, CONTENTS, DEL_YN, NICKNAME, NEW_DATE, NEW_CODE, DEL_DATE, DEL_CODE)
	SELECT 
	@NEW_MASTER_SEQ, @NEW_BOARD_SEQ, COMMENT_SEQ, CONTENTS, DEL_YN, NICKNAME, NEW_DATE, NEW_CODE, DEL_DATE, DEL_CODE
	FROM  HBS_COMMENT WITH(NOLOCK)
	WHERE MASTER_SEQ = @MASTER_SEQ
	AND BOARD_SEQ = @BOARD_SEQ 
	
	--현재글의 댓글 삭제 
	DELETE HBS_COMMENT 
	WHERE MASTER_SEQ = @MASTER_SEQ
	AND BOARD_SEQ = @BOARD_SEQ 
	
	--게시판 답글 임시 데이터 테이블 
	DECLARE @REPLY_BOARD TABLE ( NUM INT , BOARD_SEQ INT )
	INSERT INTO  @REPLY_BOARD
	SELECT ROW_NUMBER() OVER(ORDER  BY MASTER_SEQ , BOARD_SEQ) AS NUM, BOARD_SEQ 
	FROM HBS_DETAIL WITH(NOLOCK)
	WHERE MASTER_SEQ = @MASTER_SEQ
	AND PARENT_SEQ = @BOARD_SEQ 
	AND BOARD_SEQ <> @BOARD_SEQ
	
	--루프준비
	DECLARE @LOOP_CNT INT 
	DECLARE @MAX_CNT INT 
	SET @LOOP_CNT = 1 
	SET @MAX_CNT = ISNULL((SELECT COUNT(*) FROM @REPLY_BOARD),0) 

--SELECT * FROM @REPLY_BOARD 
	-- 현재글 답글 이동 (이동후삭제) LEVEL 1 만 가능 . 
	IF( @MAX_CNT > 0 ) 
	BEGIN 
		WHILE ( @LOOP_CNT <= @MAX_CNT )
		BEGIN
			--이전 답글 번호 
			DECLARE @OLD_REPLY_BOARD_SEQ INT 
			SELECT @OLD_REPLY_BOARD_SEQ = BOARD_SEQ FROM @REPLY_BOARD WHERE NUM = @LOOP_CNT 
			
			--신규 답글 번호 
			DECLARE @NEW_REPLY_BOARD_SEQ INT 
			SELECT @NEW_REPLY_BOARD_SEQ = ISNULL(MAX(BOARD_SEQ), 0) + 1 FROM HBS_DETAIL WHERE MASTER_SEQ = @NEW_MASTER_SEQ;
			
			--답글 복사 
			INSERT INTO HBS_DETAIL
			(MASTER_SEQ, BOARD_SEQ, CATEGORY_SEQ, 
				PARENT_SEQ, LEVEL, STEP, SUBJECT, CONTENTS, SHOW_COUNT, NOTICE_YN, DEL_YN, IP_ADDRESS, 
				COMPLETE_YN, FILE_PATH, EDIT_PASS, LOCK_YN, MASTER_CODE, CNT_CODE, REGION_NAME, 
				NICKNAME, PHONE_NUM, EMAIL, NEW_DATE, NEW_CODE, EDT_DATE, EDT_CODE, EMP_CODE, GOOD_TYPE_CD, 
				AREA_CD, GOOD_YY, GOOD_SEQ)
			SELECT TOP 1 
				@NEW_MASTER_SEQ, @NEW_REPLY_BOARD_SEQ, @NEW_CATEGORY_SEQ AS CATEGORY_SEQ, 
				@NEW_BOARD_SEQ AS PARENT_SEQ, LEVEL, STEP, SUBJECT, CONTENTS, SHOW_COUNT, NOTICE_YN, DEL_YN, IP_ADDRESS, 
				COMPLETE_YN, FILE_PATH, EDIT_PASS, LOCK_YN, MASTER_CODE, CNT_CODE, REGION_NAME, 
				NICKNAME, PHONE_NUM, EMAIL, GETDATE() NEW_DATE , NEW_CODE, EDT_DATE, EDT_CODE, EMP_CODE, GOOD_TYPE_CD, 
				AREA_CD, GOOD_YY, GOOD_SEQ
			FROM HBS_DETAIL WITH(NOLOCK)
			WHERE MASTER_SEQ = @MASTER_SEQ
			AND BOARD_SEQ = @OLD_REPLY_BOARD_SEQ 
			
			--현재답글의 댓글 이동 
			INSERT INTO HBS_COMMENT
			(MASTER_SEQ, BOARD_SEQ, COMMENT_SEQ, CONTENTS, DEL_YN, NICKNAME, NEW_DATE, NEW_CODE, DEL_DATE, DEL_CODE)
			SELECT 
			@NEW_MASTER_SEQ, @NEW_REPLY_BOARD_SEQ, COMMENT_SEQ, CONTENTS, DEL_YN, NICKNAME, NEW_DATE, NEW_CODE, DEL_DATE, DEL_CODE
			FROM  HBS_COMMENT WITH(NOLOCK)
			WHERE MASTER_SEQ = @MASTER_SEQ
			AND BOARD_SEQ = @OLD_REPLY_BOARD_SEQ 
			
			--PRINT ( '답글이동'  + CONVERT(VARCHAR,@LOOP_CNT) ) 
			
			--현재답글의 댓글 삭제 
			DELETE HBS_COMMENT 
			WHERE MASTER_SEQ = @MASTER_SEQ
			AND BOARD_SEQ = @OLD_REPLY_BOARD_SEQ 
			
			--답글 삭제 
			DELETE HBS_DETAIL 
			WHERE MASTER_SEQ = @MASTER_SEQ
			AND BOARD_SEQ = @OLD_REPLY_BOARD_SEQ 
			
			--ROW_NUM  증가
			SET @LOOP_CNT = @LOOP_CNT + 1 
			
			--첨부파일 이동??
			--(고객게시판 이동이므로 차후 다른게시판 이동 필요시 추가 ) 
		END 
		
	END 
	
COMMIT TRAN --정상 게시물 이동시 TRAN COMMIT 

END TRY 
BEGIN CATCH 
-- 에러 처리 
DECLARE @ErrorMessage NVARCHAR(4000);
DECLARE @ErrorSeverity INT;
DECLARE @ErrorState INT;
SELECT 
    @ErrorMessage = '게시물 이동시 에러가 발생하였습니다' +ERROR_MESSAGE()  ,
    @ErrorSeverity = ERROR_SEVERITY(),
    @ErrorState = ERROR_STATE();

-- Use RAISERROR inside the CATCH block to return error
-- information about the original error that caused
-- execution to jump to the CATCH block.
RAISERROR (@ErrorMessage, -- Message text.
           @ErrorSeverity, -- Severity.
           @ErrorState -- State.
           );
ROLLBACK TRAN  --에러시 롤백 
END CATCH

GO
