USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


/*================================================================================================================
■ USP_NAME					: XP_ARG_DETAIL_LIST_BY_PROCODE_SELECT
■ DESCRIPTION				: 수배현황상세 리스트(by procode)
■ INPUT PARAMETER			: 
■ OUTPUT PARAMETER			: 
■ EXEC						: 
	
	EXEC DBO.XP_ARG_DETAIL_LIST_BY_PROCODE_SELECT 'CPP317-131206', 'RP1311069795', 0
■ MEMO						: 
------------------------------------------------------------------------------------------------------------------
■ CHANGE HISTORY                   
------------------------------------------------------------------------------------------------------------------
   DATE				AUTHOR			DESCRIPTION           
------------------------------------------------------------------------------------------------------------------
   2013-11-12		김완기			최초생성
================================================================================================================*/ 
CREATE PROC [dbo].[XP_ARG_DETAIL_LIST_BY_PROCODE_SELECT]
 	@PRO_CODE VARCHAR(20),
	@RES_CODE VARCHAR(12),
	@ARG_DETAIL_GROUP INT
AS 
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED	
	
	DECLARE @SQLSTRING NVARCHAR(4000), @WHERE NVARCHAR(4000), @PARMDEFINITION NVARCHAR(1000)
	
	SET @WHERE = ''

	
	IF ISNULL(@RES_CODE, '') <> ''
		SET @WHERE = @WHERE + ' AND B.RES_CODE = ''' + @RES_CODE + ''' '

	-- 수배상세
	IF @ARG_DETAIL_GROUP = 0
		BEGIN		
			SET @SQLSTRING = N'
				SELECT 
				C.*,
				B.PRO_CODE,
				(SELECT PRO_NAME FROM dbo.PKG_DETAIL WHERE PRO_CODE = B.PRO_CODE) AS PRO_NAME,
				ADT_COUNT +CHD_COUNT+INF_COUNT+FOC_COUNT  AS TOT_COUNT,
				DBO.XN_COM_GET_EMP_NAME(C.NEW_CODE) AS NEW_NAME,
				DBO.XN_COM_GET_TEAM_NAME(C.NEW_CODE) AS NEW_TEAM_NAME,
				DBO.XN_COM_GET_EMP_NAME(C.CFM_CODE) AS CFM_NAME,
				DBO.XN_COM_GET_TEAM_NAME(C.CFM_CODE) AS CFM_TEAM_NAME
				FROM (SELECT A.ARG_SEQ_NO
							,A.AGT_CODE
							,(SELECT TOP 1 GRP_SEQ_NO FROM ARG_DETAIL WHERE ARG_SEQ_NO = A.ARG_SEQ_NO AND ARG_DETAIL_GROUP = B.ARG_DETAIL_GROUP ORDER BY NEW_DATE DESC) AS GRP_SEQ_NO
							,ARG_DETAIL_GROUP
					   FROM ARG_MASTER A WITH(NOLOCK)
					  INNER JOIN ARG_DETAIL B WITH(NOLOCK) ON A.ARG_SEQ_NO = B.ARG_SEQ_NO
					  WHERE A.PRO_CODE = @PRO_CODE ' + @WHERE + '
					  GROUP BY A.ARG_SEQ_NO, A.AGT_CODE, B.ARG_DETAIL_GROUP) A
				INNER JOIN ARG_MASTER B WITH(NOLOCK) ON A.ARG_SEQ_NO = B.ARG_SEQ_NO
				 LEFT OUTER JOIN ARG_DETAIL C WITH(NOLOCK) ON (A.ARG_SEQ_NO = C.ARG_SEQ_NO AND A.GRP_SEQ_NO = C.GRP_SEQ_NO)
			';
		END
	ELSE
		BEGIN
			SET @SQLSTRING = N'
				SELECT 
				A.*,
				B.PRO_CODE,
				--(SELECT PRO_CODE FROM ARG_MASTER WHERE ARG_SEQ_NO = A.ARG_SEQ_NO) AS PRO_CODE,
				(SELECT PRO_NAME FROM dbo.PKG_DETAIL WHERE PRO_CODE = B.PRO_CODE) AS PRO_NAME,
				ADT_COUNT +CHD_COUNT+INF_COUNT+FOC_COUNT  AS TOT_COUNT,
				DBO.XN_COM_GET_EMP_NAME(A.NEW_CODE) AS NEW_NAME,
				DBO.XN_COM_GET_TEAM_NAME(A.NEW_CODE) AS NEW_TEAM_NAME,
				DBO.XN_COM_GET_EMP_NAME(A.CFM_CODE) AS CFM_NAME,
				DBO.XN_COM_GET_TEAM_NAME(A.CFM_CODE) AS CFM_TEAM_NAME
				FROM ARG_DETAIL A WITH(NOLOCK)
				INNER JOIN ARG_MASTER B WITH(NOLOCK) ON A.ARG_SEQ_NO = B.ARG_SEQ_NO
				WHERE A.ARG_SEQ_NO = @ARG_SEQ_NO AND A.ARG_DETAIL_GROUP = @ARG_DETAIL_GROUP  ' + @WHERE + ' 
			';
		END


	SET @PARMDEFINITION = N'
		@PRO_CODE VARCHAR(20),
		@ARG_DETAIL_GROUP INT';

	EXEC SP_EXECUTESQL @SQLSTRING, @PARMDEFINITION, 
		@PRO_CODE,
		@ARG_DETAIL_GROUP;


	-- 인보이스
	SELECT
	       A.ARG_SEQ_NO
		  ,A.AGT_CODE
		  ,(SELECT KOR_NAME FROM AGT_MASTER WHERE AGT_CODE = A.AGT_CODE) AS AGT_NAME
		  ,A.PRO_CODE
		  ,A.DEP_DATE
		  ,A.ARR_DATE
		  ,B.GRP_SEQ_NO
		  ,B.ARG_DETAIL_STATUS
		  ,B.ADT_COUNT
		  ,B.FOC_COUNT
		  ,(ISNULL(B.ADT_COUNT, 0) + ISNULL(B.CHD_COUNT, 0) + ISNULL(B.INF_COUNT, 0)) AS PERSON_COUNT
		  ,B.CFM_CODE
		  ,B.CFM_DATE
		  ,C.NEW_DATE
		  ,C.CURRENCY
		  ,C.EXH_RATE
		  ,C.AIRLINE
		  ,C.HOTEL
		  ,C.CONTENT
		  ,C.ACC_NAME
		  ,C.REG_NAME
		  ,C.REG_NUMBER
	      ,DBO.XN_COM_GET_EMP_NAME(C.NEW_CODE) AS NEW_NAME
	      ,DBO.XN_COM_GET_TEAM_NAME(C.NEW_CODE) AS NEW_TEAM_NAME
		  ,(SELECT CASE WHEN ISNULL(B.ADT_COUNT, 0) > 0 THEN ISNULL(SUM(D.ADT_PRICE), 0) / B.ADT_COUNT ELSE ISNULL(SUM(D.ADT_PRICE), 0) END FROM ARG_INVOICE_DETAIL D WHERE A.ARG_SEQ_NO = D.ARG_SEQ_NO AND B.GRP_SEQ_NO = D.GRP_SEQ_NO) AS PRICE_PER_ADT
		  ,(SELECT ISNULL(SUM(D.ADT_PRICE), 0) + ISNULL(SUM(D.CHD_PRICE), 0) + ISNULL(SUM(D.INF_PRICE), 0) FROM ARG_INVOICE_DETAIL D WHERE A.ARG_SEQ_NO = D.ARG_SEQ_NO AND B.GRP_SEQ_NO = D.GRP_SEQ_NO) AS PRICE_TOTAL
	FROM ARG_MASTER A WITH(NOLOCK)
	INNER JOIN ARG_DETAIL B WITH(NOLOCK) ON A.ARG_SEQ_NO = B.ARG_SEQ_NO 
	INNER JOIN ARG_INVOICE C WITH(NOLOCK) ON (A.ARG_SEQ_NO = C.ARG_SEQ_NO AND B.GRP_SEQ_NO = C.GRP_SEQ_NO)
 	WHERE A.PRO_CODE = @PRO_CODE

END 

GO
