USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*================================================================================================================
■ USP_NAME					: XP_COM_STS_DSR_SALE_LIST_BY_AGENT_SELECT
■ DESCRIPTION				: BTMS 거래처별 매출현황 리스트 검색
■ INPUT PARAMETER			: 
	@START_DATE		DATE	: 결제 시작일
	@END_DATE		DATE	: 결제 종료일
■ OUTPUT PARAMETER			: 
■ EXEC						: 
   DBO.XP_COM_STS_DSR_SALE_LIST_BY_AGENT_SELECT  '2017-01-01', '2017-05-20', '', '', '', 1, 2, 'EX'
■ MEMO						: 
------------------------------------------------------------------------------------------------------------------
■ Change History                   
------------------------------------------------------------------------------------------------------------------
   Date				Author			Description           
------------------------------------------------------------------------------------------------------------------   
	2016-06-16		이유라			최초생성
	2016-09-07		이유라			판매금액 -> 입금금액으로 변경
	2016-12-01		이유라			거래처코드유무에 따른 GROUPBY 추가
	2016-12-07		이유라			건수 -> 인원수, 점유율 변경
	2016-12-13		이유라			DateType = 0 : 결제일기준 / 1 : 출발일 기준 검색 추가
	2016-12-15		이유라			변동금액(서비스수수료)추가 
	2016-12-23		이유라			결제일 기준 삭제 도착일 기준 추가, 입금금액 주석처리
	2016-12-28		이유라			SUP_CODE 유입처 구분 추가
================================================================================================================*/ 
CREATE PROC [dbo].[XP_COM_STS_DSR_SALE_LIST_BY_AGENT_SELECT]
(
	@START_DATE		VARCHAR(10),		
	@END_DATE		VARCHAR(10),
	@AGT_CODE		VARCHAR(10),
	@TEAM_SEQ		INT,
	@EMP_SEQ		INT,
	@DATE_TYPE		INT = 1,
	@RES_STATE		INT = 10,
	@SUP_CODE		VARCHAR(10) = 'EX'
)
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	DECLARE @SQLSTRING NVARCHAR(MAX), @PARMDEFINITION NVARCHAR(1000);
	DECLARE @WHERE NVARCHAR(MAX) = '', @GROUPBY1 NVARCHAR(50) = '', @GROUPBY2 NVARCHAR(50) = '', @GROUP3 NVARCHAR(50) = '';
	DECLARE @WHERE2 NVARCHAR(MAX) = '';

	-- 검색 조건 만들기
	IF LEN(@AGT_CODE) > 0
	BEGIN
		SET @WHERE = @WHERE + ' AND B.AGT_CODE = @AGT_CODE'
		SET @GROUPBY1 = 'B.KOR_NAME, B.TEAM_NAME,'
		SET @GROUPBY2 = 'B.KOR_NAME, B.TEAM_NAME '
	END
	ELSE
	BEGIN
		SET @GROUPBY1 = 'B.KOR_NAME,'
		SET @GROUPBY2 = 'B.KOR_NAME '
	END

	IF @EMP_SEQ > 0
	BEGIN
		SET @WHERE = @WHERE + ' AND C.NEW_SEQ = @EMP_SEQ'
	END
	ELSE IF @TEAM_SEQ > 0
	BEGIN
		SET @WHERE = @WHERE + ' AND D.TEAM_SEQ = @TEAM_SEQ'
	END
	
	IF @START_DATE IS NOT NULL AND @END_DATE IS NOT NULL
	BEGIN 
		IF @DATE_TYPE = 1
		BEGIN
			SET @WHERE = @WHERE + ' AND  CONVERT(DATETIME, A.DEP_DATE, 121) >= CONVERT(DATETIME,@START_DATE , 121) AND CONVERT(DATETIME,  A.DEP_DATE, 121) < DATEADD(DAY, 1, CONVERT(DATETIME, @END_DATE, 121)) ';
		END
		ELSE IF @DATE_TYPE = 2
		BEGIN
			SET @WHERE = @WHERE + ' AND  CONVERT(DATETIME, A.ARR_DATE, 121) >= CONVERT(DATETIME,@START_DATE , 121) AND CONVERT(DATETIME,  A.ARR_DATE, 121) < DATEADD(DAY, 1, CONVERT(DATETIME, @END_DATE, 121)) ';
		END
	END
	
	IF @DATE_TYPE = 1
	BEGIN
		SET @GROUP3 = 'A.DEP_DATE'
	END
	ELSE IF @DATE_TYPE = 2
	BEGIN
		SET @GROUP3 = 'A.ARR_DATE'
	END
	
	IF @RES_STATE IS NOT NULL AND @RES_STATE <> 10 
	BEGIN
		SET @WHERE = @WHERE + ' AND A.RES_STATE = @RES_STATE'
	END

	IF @SUP_CODE IS NOT NULL AND @SUP_CODE != ''
	BEGIN
		SET @WHERE2 = ' AND H.SUP_CODE = @SUP_CODE ';
	END

	SET @SQLSTRING = N'
	WITH LIST AS (
			SELECT DISTINCT
				CONVERT(VARCHAR(7),' + @GROUP3 + N',121) AS MONTH_DATE,
				A.RES_CODE,
				(SELECT dbo.FN_RES_GET_CHANGE_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND B.PRO_DETAIL_TYPE = 2))) AS PROFIT_PRICE, --변동금액(서비스수수료)
				--항공
				(SELECT COUNT(1) FROM RES_CUSTOMER_damo Z WHERE A.RES_CODE = Z.RES_CODE AND Z.RES_STATE IN (0,3,4) AND B.PRO_DETAIL_TYPE = 2 ) AS AIR_COUNT,
				--(SELECT DBO.FN_RES_GET_PAY_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 2 ))) AS AIR_PAY_PRICE,
				(SELECT DBO.FN_RES_GET_TOTAL_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 2))) AS AIR_SALE_PRICE, 
				--호텔
				(SELECT COUNT(1) FROM RES_CUSTOMER_damo Z WHERE A.RES_CODE = Z.RES_CODE AND Z.RES_STATE IN (0,3,4) AND B.PRO_DETAIL_TYPE = 3 '+ @WHERE2 + N' ) AS HTL_COUNT,
				--(SELECT DBO.FN_RES_GET_PAY_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 3 '+ @WHERE2 + N'))) AS HTL_PAY_PRICE,
				(SELECT DBO.FN_RES_GET_TOTAL_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 3 '+ @WHERE2 + N'))) AS HTL_SALE_PRICE, 
				--렌트카
				(SELECT COUNT(1) FROM RES_CUSTOMER_damo Z WHERE A.RES_CODE = Z.RES_CODE AND Z.RES_STATE IN (0,3,4) AND B.PRO_DETAIL_TYPE = 4 ) AS CAR_COUNT,
				--(SELECT DBO.FN_RES_GET_PAY_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 4 ))) AS CAR_PAY_PRICE,
				(SELECT DBO.FN_RES_GET_TOTAL_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 4))) AS CAR_SALE_PRICE, 
				--비자
				(SELECT COUNT(1) FROM RES_CUSTOMER_damo Z WHERE A.RES_CODE = Z.RES_CODE AND Z.RES_STATE IN (0,3,4) AND B.PRO_DETAIL_TYPE = 5 ) AS VISA_COUNT,
				--(SELECT DBO.FN_RES_GET_PAY_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 5 ))) AS VISA_PAY_PRICE,
				(SELECT DBO.FN_RES_GET_TOTAL_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 5))) AS VISA_SALE_PRICE, 
				--기타
				(SELECT COUNT(1) FROM RES_CUSTOMER_damo Z WHERE A.RES_CODE = Z.RES_CODE AND Z.RES_STATE IN (0,3,4) AND B.PRO_DETAIL_TYPE = 9 ) AS ETC_COUNT,
				--(SELECT DBO.FN_RES_GET_PAY_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 9 ))) AS ETC_PAY_PRICE,
				(SELECT DBO.FN_RES_GET_TOTAL_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 9))) AS ETC_SALE_PRICE, 
				--합계
				(SELECT COUNT(1) FROM RES_CUSTOMER_damo Z WHERE A.RES_CODE = Z.RES_CODE AND Z.RES_STATE IN (0,3,4) AND B.PRO_DETAIL_TYPE IN (2,3,4,5,9)) AS TOTAL_COUNT,
				--(SELECT DBO.FN_RES_GET_PAY_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE))) AS TOTAL_PAY_PRICE,
				(SELECT DBO.FN_RES_GET_TOTAL_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE))) AS TOTAL_SALE_PRICE
			FROM RES_MASTER_damo A WITH(NOLOCK)
			JOIN COM_BIZTRIP_DETAIL B WITH(NOLOCK) ON A.RES_CODE = B.RES_CODE 
			JOIN COM_BIZTRIP_MASTER C WITH(NOLOCK) ON B.AGT_CODE = C.AGT_CODE AND B.BT_CODE = C.BT_CODE
			LEFT JOIN COM_EMPLOYEE D WITH(NOLOCK) ON C.AGT_CODE = D.AGT_CODE AND C.NEW_SEQ = D.EMP_SEQ
			LEFT JOIN AGT_MASTER E WITH(NOLOCK) ON C.AGT_CODE = E.AGT_CODE
			LEFT JOIN COM_TEAM F WITH(NOLOCK) ON F.AGT_CODE = E.AGT_CODE AND F.TEAM_SEQ = D.TEAM_SEQ
			LEFT JOIN PAY_MATCHING G WITH(NOLOCK) ON G.RES_CODE = B.RES_CODE AND G.CXL_YN = ''N''
			LEFT JOIN RES_HTL_ROOM_MASTER H WITH(NOLOCK) ON H.RES_CODE = B.RES_CODE
			WHERE 1 = 1 ' + @WHERE + N'
		) 
		SELECT 
			B.MONTH_DATE, 
			ISNULL(SUM(B.PROFIT_PRICE),0) AS PROFIT_PRICE,
			ISNULL(SUM(B.AIR_COUNT),0) AS AIR_COUNT,
			--ISNULL(SUM(B.AIR_PAY_PRICE),0) AS AIR_PAY_PRICE,
			ISNULL(SUM(B.AIR_SALE_PRICE),0) AS AIR_SALE_PRICE,
			ISNULL(SUM(B.HTL_COUNT),0) AS HTL_COUNT,
			--ISNULL(SUM(B.HTL_PAY_PRICE),0) AS HTL_PAY_PRICE,
			ISNULL(SUM(B.HTL_SALE_PRICE),0) AS HTL_SALE_PRICE,
			ISNULL(SUM(B.CAR_COUNT),0) AS CAR_COUNT,
			--ISNULL(SUM(B.CAR_PAY_PRICE),0) AS CAR_PAY_PRICE,
			ISNULL(SUM(B.CAR_SALE_PRICE),0) AS CAR_SALE_PRICE,
			ISNULL(SUM(B.VISA_COUNT),0) AS VISA_COUNT,
			--ISNULL(SUM(B.VISA_PAY_PRICE),0) AS VISA_PAY_PRICE,
			ISNULL(SUM(B.VISA_SALE_PRICE),0) AS VISA_SALE_PRICE,
			ISNULL(SUM(B.ETC_COUNT),0) AS ETC_COUNT,
			--ISNULL(SUM(B.ETC_PAY_PRICE),0) AS ETC_PAY_PRICE,
			ISNULL(SUM(B.ETC_SALE_PRICE),0) AS ETC_SALE_PRICE,
			ISNULL(SUM(B.TOTAL_COUNT),0) AS TOTAL_COUNT,
			--ISNULL(SUM(B.TOTAL_PAY_PRICE),0) AS TOTAL_PAY_PRICE,
			ISNULL(SUM(B.TOTAL_SALE_PRICE),0) AS TOTAL_SALE_PRICE
		FROM LIST B
		GROUP BY B.MONTH_DATE
		ORDER BY B.MONTH_DATE DESC;'
		
	SET @SQLSTRING = @SQLSTRING + N'
		WITH LIST AS (
			SELECT DISTINCT
				E.KOR_NAME, F.TEAM_NAME, A.RES_CODE,
				(SELECT dbo.FN_RES_GET_CHANGE_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND B.PRO_DETAIL_TYPE = 2)))AS PROFIT_PRICE, --변동금액(서비스수수료)
				--항공
				(SELECT COUNT(1) FROM RES_CUSTOMER_damo Z WHERE A.RES_CODE = Z.RES_CODE AND Z.RES_STATE IN (0,3,4) AND B.PRO_DETAIL_TYPE = 2 ) AS AIR_COUNT,
				--(SELECT DBO.FN_RES_GET_PAY_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 2 ))) AS AIR_PAY_PRICE,
				(SELECT DBO.FN_RES_GET_TOTAL_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 2))) AS AIR_SALE_PRICE, 
				--호텔
				(SELECT COUNT(1) FROM RES_CUSTOMER_damo Z WHERE A.RES_CODE = Z.RES_CODE AND Z.RES_STATE IN (0,3,4) AND B.PRO_DETAIL_TYPE = 3 '+ @WHERE2 + N') AS HTL_COUNT,
				--(SELECT DBO.FN_RES_GET_PAY_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 3 '+ @WHERE2 + N'))) AS HTL_PAY_PRICE,
				(SELECT DBO.FN_RES_GET_TOTAL_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 3 '+ @WHERE2 + N'))) AS HTL_SALE_PRICE, 
				--렌트카
				(SELECT COUNT(1) FROM RES_CUSTOMER_damo Z WHERE A.RES_CODE = Z.RES_CODE AND Z.RES_STATE IN (0,3,4) AND B.PRO_DETAIL_TYPE = 4 ) AS CAR_COUNT,
				--(SELECT DBO.FN_RES_GET_PAY_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 4 ))) AS CAR_PAY_PRICE,
				(SELECT DBO.FN_RES_GET_TOTAL_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 4))) AS CAR_SALE_PRICE, 
				--비자
				(SELECT COUNT(1) FROM RES_CUSTOMER_damo Z WHERE A.RES_CODE = Z.RES_CODE AND Z.RES_STATE IN (0,3,4) AND B.PRO_DETAIL_TYPE = 5 ) AS VISA_COUNT,
				--(SELECT DBO.FN_RES_GET_PAY_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 5 ))) AS VISA_PAY_PRICE,
				(SELECT DBO.FN_RES_GET_TOTAL_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 5))) AS VISA_SALE_PRICE, 
				--기타
				(SELECT COUNT(1) FROM RES_CUSTOMER_damo Z WHERE A.RES_CODE = Z.RES_CODE AND Z.RES_STATE IN (0,3,4) AND B.PRO_DETAIL_TYPE = 9 ) AS ETC_COUNT,
				--(SELECT DBO.FN_RES_GET_PAY_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 9 ))) AS ETC_PAY_PRICE,
				(SELECT DBO.FN_RES_GET_TOTAL_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE AND Z.PRO_DETAIL_TYPE = 9))) AS ETC_SALE_PRICE, 
				--합계
				(SELECT COUNT(1) FROM RES_CUSTOMER_damo Z WHERE A.RES_CODE = Z.RES_CODE AND Z.RES_STATE IN (0,3,4) AND B.PRO_DETAIL_TYPE IN (2,3,4,5,9)) AS TOTAL_COUNT,
				--(SELECT DBO.FN_RES_GET_PAY_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE))) AS TOTAL_PAY_PRICE,
				(SELECT DBO.FN_RES_GET_TOTAL_PRICE((SELECT Z.RES_CODE FROM COM_BIZTRIP_DETAIL Z WHERE A.RES_CODE = Z.RES_CODE))) AS TOTAL_SALE_PRICE
			FROM RES_MASTER_damo A WITH(NOLOCK)
			JOIN COM_BIZTRIP_DETAIL B WITH(NOLOCK) ON A.RES_CODE = B.RES_CODE 
			JOIN COM_BIZTRIP_MASTER C WITH(NOLOCK) ON B.AGT_CODE = C.AGT_CODE AND B.BT_CODE = C.BT_CODE
			LEFT JOIN COM_EMPLOYEE D WITH(NOLOCK) ON C.AGT_CODE = D.AGT_CODE AND C.NEW_SEQ = D.EMP_SEQ
			LEFT JOIN AGT_MASTER E WITH(NOLOCK) ON C.AGT_CODE = E.AGT_CODE
			LEFT JOIN COM_TEAM F WITH(NOLOCK) ON F.AGT_CODE = E.AGT_CODE AND F.TEAM_SEQ = D.TEAM_SEQ
			LEFT JOIN PAY_MATCHING G WITH(NOLOCK) ON G.RES_CODE = B.RES_CODE AND G.CXL_YN = ''N''
			LEFT JOIN RES_HTL_ROOM_MASTER H WITH(NOLOCK) ON H.RES_CODE = B.RES_CODE
			WHERE 1 = 1 ' + @WHERE + N'
		) 
		SELECT 
			' + @GROUPBY1 + N' 
			ISNULL(SUM(B.PROFIT_PRICE),0) AS PROFIT_PRICE,
			ISNULL(SUM(B.AIR_COUNT),0) AS AIR_COUNT,
			--ISNULL(SUM(B.AIR_PAY_PRICE),0) AS AIR_PAY_PRICE,
			ISNULL(SUM(B.AIR_SALE_PRICE),0) AS AIR_SALE_PRICE,
			ISNULL(SUM(B.HTL_COUNT),0) AS HTL_COUNT,
			--ISNULL(SUM(B.HTL_PAY_PRICE),0) AS HTL_PAY_PRICE,
			ISNULL(SUM(B.HTL_SALE_PRICE),0) AS HTL_SALE_PRICE,
			ISNULL(SUM(B.CAR_COUNT),0) AS CAR_COUNT,
			--ISNULL(SUM(B.CAR_PAY_PRICE),0) AS CAR_PAY_PRICE,
			ISNULL(SUM(B.CAR_SALE_PRICE),0) AS CAR_SALE_PRICE,
			ISNULL(SUM(B.VISA_COUNT),0) AS VISA_COUNT,
			--ISNULL(SUM(B.VISA_PAY_PRICE),0) AS VISA_PAY_PRICE,
			ISNULL(SUM(B.VISA_SALE_PRICE),0) AS VISA_SALE_PRICE,
			ISNULL(SUM(B.ETC_COUNT),0) AS ETC_COUNT,
			--ISNULL(SUM(B.ETC_PAY_PRICE),0) AS ETC_PAY_PRICE,
			ISNULL(SUM(B.ETC_SALE_PRICE),0) AS ETC_SALE_PRICE,
			ISNULL(SUM(B.TOTAL_COUNT),0) AS TOTAL_COUNT,
			--ISNULL(SUM(B.TOTAL_PAY_PRICE),0) AS TOTAL_PAY_PRICE,
			ISNULL(SUM(B.TOTAL_SALE_PRICE),0) AS TOTAL_SALE_PRICE
		FROM LIST B
		GROUP BY ' + @GROUPBY2 + N'
		ORDER BY SUM(B.TOTAL_SALE_PRICE) DESC'

	SET @PARMDEFINITION = N'	
		@AGT_CODE			VARCHAR(10),
		@START_DATE			DATE,
		@END_DATE			DATE,
		@TEAM_SEQ			INT,
		@EMP_SEQ			INT,
		@DATE_TYPE			INT,
		@RES_STATE			INT,
		@SUP_CODE			VARCHAR(10)';

	PRINT @SQLSTRING

	EXEC SP_EXECUTESQL @SQLSTRING, @PARMDEFINITION, 		
		@AGT_CODE,
		@START_DATE,
		@END_DATE,
		@TEAM_SEQ,
		@EMP_SEQ,
		@DATE_TYPE,
		@RES_STATE,
		@SUP_CODE;
END
GO
