USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*================================================================================================================
■ USP_NAME					: XP_ARG_MASTER_SELECT
■ DESCRIPTION				: 수배현황 검색
■ INPUT PARAMETER			: 
■ OUTPUT PARAMETER			: 
■ EXEC						: 
	exec XP_ARG_MASTER_SEARCH_SELECT @KEY='3007',@TYPE=0
	EXEC DBO.XP_ARG_MASTER_SEARCH_SELECT '9039', 0
	EXEC DBO.XP_ARG_MASTER_SEARCH_SELECT 'MPP980-140129', 1
■ MEMO						: 
------------------------------------------------------------------------------------------------------------------
■ CHANGE HISTORY                   
------------------------------------------------------------------------------------------------------------------
   DATE				AUTHOR			DESCRIPTION           
------------------------------------------------------------------------------------------------------------------
   2013-05-22		이규식			최초생성
   2014-01-15		박형만			정산금액 수정
   2014-04-07		박형만			에러 안나게
================================================================================================================*/ 
CREATE PROC [dbo].[XP_ARG_MASTER_SEARCH_SELECT]
 	@KEY varchar(20),
	@TYPE int
AS 
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED	

	--정산합산금액 
	DECLARE @SUM_PRICE BIGINT 

	IF @TYPE = 0 
	BEGIN
		--정산합산금액
		SELECT @SUM_PRICE = SUM(SUB_SUM_PRICE)
		FROM ( 
			SELECT ISNULL(SUM(D.ADT_PRICE * E.EXH_RATE), 0) *  C.ADT_COUNT  + ISNULL(SUM(D.CHD_PRICE* E.EXH_RATE), 0) *  C.CHD_COUNT + ISNULL(SUM(D.INF_PRICE* E.EXH_RATE), 0) *  C.INF_COUNT AS SUB_SUM_PRICE 
			FROM  ARG_DETAIL C  WITH(NOLOCK)
			INNER  JOIN ARG_INVOICE_DETAIL D  WITH(NOLOCK)
				ON (C.ARG_CODE = D.ARG_CODE AND C.GRP_SEQ_NO = D.GRP_SEQ_NO)
			INNER  JOIN ARG_INVOICE E
				ON (D.ARG_CODE = E.ARG_CODE AND D.GRP_SEQ_NO = E.GRP_SEQ_NO)
			WHERE  C.ARG_CODE = @KEY AND C.ARG_TYPE = '2' 
			AND ARG_STATUS IN ( '3' ,'4','5','7','8' ) -- 인보이스 , 정산진행, 정산완료 , 지급완료 , 지급불가 
			GROUP BY C.ADT_COUNT , C.CHD_COUNT , C.INF_COUNT  
		) TBL  

		SELECT 
		A.ARG_CODE, A.AGT_CODE, /*A.RES_CODE,*/ A.PRO_CODE, B.DEP_DATE, B.ARR_DATE, B.DAY, B.NIGHTS, A.NEW_CODE, A.NEW_DATE,
		(SELECT TOP 1 ARG_STATUS FROM ARG_DETAIL WHERE ARG_CODE = A.ARG_CODE AND AGT_CODE = A.AGT_CODE ORDER BY NEW_DATE DESC) AS ARG_STATUS,
		(SELECT PRO_NAME FROM dbo.PKG_DETAIL WHERE PRO_CODE = A.PRO_CODE) AS PRO_NAME,
		DBO.XN_COM_GET_EMP_NAME(A.NEW_CODE) AS NEW_NAME,
		DBO.XN_COM_GET_TEAM_NAME(A.NEW_CODE) AS NEW_TEAM_NAME,
		(SELECT KOR_NAME FROM AGT_MASTER WHERE AGT_CODE = A.AGT_CODE) AS AGT_NAME,
		(SELECT COUNT(ARG_GUIDE_SEQ) FROM ARG_GUIDE WHERE ARG_CODE = A.ARG_CODE) AS COUNT_GUIDE,
		(SELECT COUNT(ACR_SEQ_NO) FROM ACR_MASTER WHERE PRO_CODE = A.PRO_CODE AND AGT_CODE = A.AGT_CODE) AS COUNT_REPORT_ACCIDENT,
		(SELECT COUNT(B.GRP_SEQ_NO) FROM ARG_DETAIL B WHERE B.ARG_CODE = A.ARG_CODE AND B.ARG_STATUS = 0) AS COUNT_R,
		(SELECT COUNT(B.GRP_SEQ_NO) FROM ARG_DETAIL B WHERE B.ARG_CODE = A.ARG_CODE AND B.ARG_STATUS = 2) AS COUNT_C,
		(SELECT COUNT(B.GRP_SEQ_NO) FROM ARG_DETAIL B WHERE B.ARG_CODE = A.ARG_CODE AND B.ARG_STATUS = 3) AS COUNT_I,		
		--(SELECT  ISNULL(SUM(D.ADT_PRICE), 0) + ISNULL(SUM(D.CHD_PRICE), 0) + ISNULL(SUM(D.INF_PRICE), 0)
		--   FROM  ARG_DETAIL C 
		--  INNER  JOIN ARG_INVOICE_DETAIL D 
		-- 	 ON (C.ARG_CODE = D.ARG_CODE AND C.GRP_SEQ_NO = D.GRP_SEQ_NO)
		--  WHERE  C.ARG_CODE = A.ARG_CODE AND C.ARG_TYPE = '2' AND ARG_STATUS <> '6') AS SUM_PRICE,
		@SUM_PRICE  AS SUM_PRICE,
		DBO.FN_PRO_GET_RES_COUNT(A.PRO_CODE) AS RES_COUNT
		FROM ARG_MASTER A 
			INNER JOIN ARG_DETAIL B 
				ON A.ARG_CODE = B.ARG_CODE 
		WHERE A.ARG_CODE = @KEY -- ARG_CODE 
	END
	ELSE IF @TYPE = 1
	BEGIN
		--정산합산금액
		SELECT @SUM_PRICE = SUM(SUB_SUM_PRICE)
		FROM ( 
			SELECT ISNULL(SUM(D.ADT_PRICE * E.EXH_RATE), 0) *  C.ADT_COUNT  + ISNULL(SUM(D.CHD_PRICE* E.EXH_RATE), 0) *  C.CHD_COUNT + ISNULL(SUM(D.INF_PRICE* E.EXH_RATE), 0) *  C.INF_COUNT AS SUB_SUM_PRICE 
			FROM  ARG_MASTER B
			INNER JOIN ARG_DETAIL C  WITH(NOLOCK)
				ON B.ARG_CODE = C.ARG_CODE 
			INNER  JOIN ARG_INVOICE_DETAIL D  WITH(NOLOCK)
				ON (C.ARG_CODE = D.ARG_CODE AND C.GRP_SEQ_NO = D.GRP_SEQ_NO)
			INNER  JOIN ARG_INVOICE E
				ON (D.ARG_CODE = E.ARG_CODE AND D.GRP_SEQ_NO = E.GRP_SEQ_NO)
			WHERE   B.PRO_CODE = @KEY AND C.ARG_TYPE = '2' 
			AND ARG_STATUS IN ( '3' ,'4','5','7','8' ) -- 인보이스 , 정산진행, 정산완료 , 지급완료 , 지급불가 
			GROUP BY C.ADT_COUNT , C.CHD_COUNT , C.INF_COUNT  
		) TBL  

		SELECT 
		A.ARG_CODE, A.AGT_CODE, /*B.RES_CODE,*/ A.PRO_CODE, B.DEP_DATE, B.ARR_DATE, B.DAY, B.NIGHTS, A.NEW_CODE, A.NEW_DATE,
		(SELECT TOP 1 ARG_STATUS FROM ARG_DETAIL WHERE ARG_CODE = A.ARG_CODE AND AGT_CODE = A.AGT_CODE ORDER BY NEW_DATE DESC) AS ARG_STATUS,
		(SELECT PRO_NAME FROM dbo.PKG_DETAIL WHERE PRO_CODE = A.PRO_CODE) AS PRO_NAME,
		DBO.XN_COM_GET_EMP_NAME(A.NEW_CODE) AS NEW_NAME,
		DBO.XN_COM_GET_TEAM_NAME(A.NEW_CODE) AS NEW_TEAM_NAME,
		(SELECT KOR_NAME FROM AGT_MASTER WHERE AGT_CODE = A.AGT_CODE) AS AGT_NAME,
		(SELECT COUNT(ARG_GUIDE_SEQ) FROM ARG_GUIDE WHERE ARG_CODE = A.ARG_CODE) AS COUNT_GUIDE,
		0 AS COUNT_REPORT_ACCIDENT,
		(SELECT COUNT(B.GRP_SEQ_NO) FROM ARG_DETAIL B WHERE B.ARG_CODE = A.ARG_CODE AND B.ARG_STATUS = 0) AS COUNT_R,
		(SELECT COUNT(B.GRP_SEQ_NO) FROM ARG_DETAIL B WHERE B.ARG_CODE = A.ARG_CODE AND B.ARG_STATUS = 2) AS COUNT_C,
		(SELECT COUNT(B.GRP_SEQ_NO) FROM ARG_DETAIL B WHERE B.ARG_CODE = A.ARG_CODE AND B.ARG_STATUS = 3) AS COUNT_I,		
		@SUM_PRICE  AS SUM_PRICE,
		DBO.FN_PRO_GET_RES_COUNT(A.PRO_CODE) AS RES_COUNT
		FROM ARG_MASTER A 
			INNER JOIN ARG_DETAIL B 
				ON A.ARG_CODE = B.ARG_CODE 
		WHERE PRO_CODE = @KEY
	END 
END 

GO
