USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*================================================================================================================
■ USP_NAME					: XP_WEB_PKG_DETAIL_SCHEDULE_SELECT
■ DESCRIPTION				: 행사 상세 일정표 검색
■ INPUT PARAMETER			: 
	@PRO_CODE VARCHAR(20)	: 행사코드
	@PRICE_SEQ INT			: 가격순번
■ OUTPUT PARAMETER			: 
■ EXEC						: 

	exec XP_WEB_PKG_DETAIL_SCHEDULE_SELECT 'CPP9050-140305A', 2

■ MEMO						: 
------------------------------------------------------------------------------------------------------------------
■ CHANGE HISTORY                   
------------------------------------------------------------------------------------------------------------------
   DATE				AUTHOR			DESCRIPTION           
------------------------------------------------------------------------------------------------------------------
   2013-04-03		김성호			최초생성
   2013-06-10		김성호			WITH(NOLOCK) 추가
   2019-03-12		김성호			쿼리 수정
   2019-03-14		박형만			식사코드 추가 
================================================================================================================*/ 
CREATE  PROCEDURE [dbo].[XP_WEB_PKG_DETAIL_SCHEDULE_SELECT]
(
	@PRO_CODE	VARCHAR(20),
	@PRICE_SEQ	INT
)
AS  
BEGIN

	-- 일자정보
	SELECT
		C.*, DATEADD(DAY, (C.DAY_NUMBER -1), A.DEP_DATE) AS [DAY],
		D.HTL_MASTER_CODE, D.STAY_INFO AS [HTL_MASTER_NAME], D.DINNER_1, D.DINNER_2, D.DINNER_3,
		D.DINNER_CODE_1,D.DINNER_CODE_2,D.DINNER_CODE_3,
		E.HTL_GRADE, F.TEL_NUMBER,
		STUFF((
			SELECT ('-' + BB.KOR_NAME) AS [text()] 
			FROM PKG_DETAIL_SCH_CITY AA WITH(NOLOCK) 
			INNER JOIN PUB_CITY BB WITH(NOLOCK) ON AA.CITY_CODE = BB.CITY_CODE 
			WHERE AA.PRO_CODE = C.PRO_CODE AND AA.SCH_SEQ = C.SCH_SEQ AND AA.DAY_SEQ = C.DAY_SEQ ORDER BY AA.CITY_SHOW_ORDER FOR XML PATH('')
		), 1, 1, '') AS [TOUR_JOURNEY]
	FROM PKG_DETAIL A WITH(NOLOCK)
	INNER JOIN PKG_DETAIL_PRICE B WITH(NOLOCK) ON A.PRO_CODE = B.PRO_CODE
	INNER JOIN PKG_DETAIL_SCH_DAY C WITH(NOLOCK) ON B.PRO_CODE = C.PRO_CODE AND B.SCH_SEQ = C.SCH_SEQ
	INNER JOIN PKG_DETAIL_PRICE_HOTEL D WITH(NOLOCK) ON B.PRO_CODE = D.PRO_CODE AND B.PRICE_SEQ = D.PRICE_SEQ AND C.DAY_NUMBER = D.DAY_NUMBER
	LEFT JOIN HTL_MASTER E WITH(NOLOCK) ON D.HTL_MASTER_CODE = E.MASTER_CODE
	LEFT JOIN INF_HOTEL F WITH(NOLOCK) ON E.CNT_CODE = F.CNT_CODE
	WHERE A.PRO_CODE = @PRO_CODE AND B.PRICE_SEQ = @PRICE_SEQ
	ORDER BY C.DAY_NUMBER;
	---- 도시
	SELECT B.*, C.KOR_NAME AS [CITY_NAME]
	FROM PKG_DETAIL_PRICE A WITH(NOLOCK)
	INNER JOIN PKG_DETAIL_SCH_CITY B WITH(NOLOCK) ON A.PRO_CODE = B.PRO_CODE AND A.SCH_SEQ = B.SCH_SEQ
	INNER JOIN PUB_CITY C WITH(NOLOCK) ON C.CITY_CODE = B.CITY_CODE
	WHERE A.PRO_CODE = @PRO_CODE AND A.PRICE_SEQ = @PRICE_SEQ
	ORDER BY B.DAY_SEQ, B.CITY_SHOW_ORDER;
	---- 컨텐츠
	SELECT B.*, C.KOR_TITLE, C.GPS_X, C.GPS_Y, C.SHORT_DESCRIPTION, C.DESCRIPTION, C.DISPLAY_TYPE, C.CNT_TYPE, C.SHOW_YN AS [CNTSHOW_YM],
		(CASE B.CNT_CODE WHEN 0 THEN NULL ELSE DBO.XN_CNT_GET_IMAGE_FILE_PATH_STRING(B.CNT_CODE, (CASE C.DISPLAY_TYPE WHEN 2 THEN 2 ELSE 1 END), '|') END) AS [FILE_PATH_STRING]
	FROM PKG_DETAIL_PRICE A WITH(NOLOCK)
	INNER JOIN PKG_DETAIL_SCH_CONTENT B WITH(NOLOCK) ON A.PRO_CODE = B.PRO_CODE AND A.SCH_SEQ = B.SCH_SEQ
	LEFT JOIN INF_MASTER C WITH(NOLOCK) ON B.CNT_CODE = C.CNT_CODE
	WHERE A.PRO_CODE = @PRO_CODE AND A.PRICE_SEQ = @PRICE_SEQ
	ORDER BY B.DAY_SEQ, B.CNT_SHOW_ORDER;



/*

	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	DECLARE @SQLSTRING NVARCHAR(4000), @PARMDEFINITION NVARCHAR(1000), @SCH_SEQ INT, @DEP_DATE DATETIME;

	SELECT @SCH_SEQ = PDP.SCH_SEQ, @DEP_DATE = PD.DEP_DATE FROM PKG_DETAIL_PRICE PDP WITH(NOLOCK)
	INNER JOIN PKG_DETAIL PD WITH(NOLOCK) ON PDP.PRO_CODE = PD.PRO_CODE
	WHERE PDP.PRO_CODE = @PRO_CODE AND PDP.PRICE_SEQ = @PRICE_SEQ
	
	SET @SQLSTRING = N'
	-- 일자정보
	SELECT PDSD.*, DATEADD(DAY, (PDSD.DAY_NUMBER - 1), @DEP_DATE) AS [DAY]
		, PDPH.HTL_MASTER_CODE, PDPH.STAY_INFO AS [HTL_MASTER_NAME], PDPH.DINNER_1, PDPH.DINNER_2, PDPH.DINNER_3
		, HM.HTL_GRADE, IH.TEL_NUMBER
		, STUFF((
			SELECT (''-'' + B.KOR_NAME) AS [text()] FROM PKG_DETAIL_SCH_CITY A WITH(NOLOCK) LEFT JOIN PUB_CITY B WITH(NOLOCK) ON A.CITY_CODE = B.CITY_CODE WHERE A.PRO_CODE = PDSD.PRO_CODE AND A.SCH_SEQ = PDSD.SCH_SEQ AND A.DAY_SEQ = PDSD.DAY_SEQ ORDER BY A.CITY_SH
OW_ORDER FOR XML PATH('''')
		), 1, 1, '''') AS [TOUR_JOURNEY]
	FROM PKG_DETAIL_SCH_DAY PDSD WITH(NOLOCK)
	INNER JOIN PKG_DETAIL_PRICE_HOTEL PDPH WITH(NOLOCK) ON PDSD.PRO_CODE = PDPH.PRO_CODE AND PDPH.PRICE_SEQ = @PRICE_SEQ AND PDSD.DAY_NUMBER = PDPH.DAY_NUMBER
	LEFT JOIN HTL_MASTER HM WITH(NOLOCK) ON PDPH.HTL_MASTER_CODE = HM.MASTER_CODE
	LEFT JOIN INF_HOTEL IH WITH(NOLOCK) ON HM.CNT_CODE = IH.CNT_CODE
	WHERE PDSD.PRO_CODE = @PRO_CODE AND PDSD.SCH_SEQ = @SCH_SEQ
	ORDER BY PDSD.DAY_NUMBER;
	---- 도시
	SELECT PDSC.*, PC.KOR_NAME AS [CITY_NAME]
	FROM PKG_DETAIL_SCH_CITY PDSC WITH(NOLOCK)
	LEFT JOIN PUB_CITY PC WITH(NOLOCK) ON PDSC.CITY_CODE = PC.CITY_CODE
	WHERE PDSC.PRO_CODE = @PRO_CODE AND PDSC.SCH_SEQ = @SCH_SEQ
	ORDER BY PDSC.CITY_SHOW_ORDER;
	---- 컨텐츠
	SELECT PDSC.*, IM.KOR_TITLE, IM.GPS_X, IM.GPS_Y, IM.SHORT_DESCRIPTION, IM.DESCRIPTION, IM.DISPLAY_TYPE, IM.CNT_TYPE, IM.SHOW_YN AS CNTSHOW_YN
		, (CASE PDSC.CNT_CODE WHEN 0 THEN NULL ELSE DBO.XN_CNT_GET_IMAGE_FILE_PATH_STRING(PDSC.CNT_CODE, (CASE IM.DISPLAY_TYPE WHEN 2 THEN 2 ELSE 1 END), ''|'') END) AS [FILE_PATH_STRING]
--		, (CASE PDSC.CNT_CODE WHEN 0 THEN NULL ELSE DBO.XN_CNT_GET_IMAGE_FILE_PATH_STRING(PDSC.CNT_CODE, 1, ''|'') END) AS [FILE_PATH_STRING]
	FROM PKG_DETAIL_SCH_CONTENT PDSC WITH(NOLOCK)
	LEFT JOIN INF_MASTER IM WITH(NOLOCK) ON PDSC.CNT_CODE = IM.CNT_CODE
	WHERE PDSC.PRO_CODE = @PRO_CODE AND PDSC.SCH_SEQ = @SCH_SEQ
	ORDER BY PDSC.CNT_SHOW_ORDER;

	--SELECT A.*
	--	, B.FILE_CODE, B.REGION_CODE, B.NATION_CODE, B.STATE_CODE, B.CITY_CODE, B.KOR_NAME, B.ENG_NAME, B.FILE_TYPE, B.FILE_NAME, B.EXTENSION_NAME
	--	, B.FILE_SIZE, B.FILE_NAME_S, B.FILE_NAME_M, B.FILE_NAME_L, B.FILE_REMARK
	--FROM (
	--	SELECT PDSC.*, IM.KOR_TITLE, IM.GPS_X, IM.GPS_Y, IM.SHORT_DESCRIPTION, IM.DESCRIPTION, IM.DISPLAY_TYPE, IM.CNT_TYPE, IM.SHOW_YN AS CNTSHOW_YN
	--		, (SELECT TOP 1 FILE_CODE FROM INF_FILE_MANAGER Z WHERE Z.CNT_CODE = PDSC.CNT_CODE ORDER BY Z.SHOW_ORDER) AS [FILE_CODE]
	--	FROM PKG_DETAIL_SCH_CONTENT PDSC
	--	LEFT JOIN INF_MASTER IM ON PDSC.CNT_CODE = IM.CNT_CODE
	--	WHERE PDSC.PRO_CODE = @PRO_CODE AND PDSC.SCH_SEQ = @SCH_SEQ
	--) A
	--LEFT JOIN INF_FILE_MASTER B ON A.FILE_CODE = B.FILE_CODE
	--ORDER BY CNT_SHOW_ORDER;
	'

	SET @PARMDEFINITION = N'
		@PRO_CODE VARCHAR(20),
		@PRICE_SEQ INT,
		@SCH_SEQ INT,
		@DEP_DATE DATETIME';

--	PRINT @SQLSTRING
		
	EXEC SP_EXECUTESQL @SQLSTRING, @PARMDEFINITION,
		@PRO_CODE,
		@PRICE_SEQ,
		@SCH_SEQ,
		@DEP_DATE;

*/

END


GO
