USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_LOG_INFLOW_INSERT]
	@IN_IP			VARCHAR(20),
	@IN_PATH		VARCHAR(500),
	@IN_URL			VARCHAR(1000),
	@IN_QUERY		VARCHAR(500),
	@INFLOW			VARCHAR(50),
	@IN_TYPE1		VARCHAR(50),
	@IN_TYPE2		VARCHAR(50),
	@IN_PRO_CODE	VARCHAR(100),
	@IN_MASTER_CODE	VARCHAR(100),
	@IN_USER_COOKIE VARCHAR(100) = NULL
AS
BEGIN
	INSERT INTO VGLog.dbo.SYS_INFLOW_LOG (
		IN_DATE,	IN_IP,		IN_PATH,		IN_URL,			IN_QUERY,
		INFLOW,		IN_TYPE1,	IN_TYPE2,		IN_PRO_CODE,	IN_MASTER_CODE
	) VALUES (
		GETDATE(),	@IN_IP,		@IN_PATH,		@IN_URL,		@IN_QUERY,
		@INFLOW,	@IN_TYPE1,	@IN_TYPE2,		@IN_PRO_CODE,	@IN_MASTER_CODE
	);
	
	/* 임시 주석 처리 (사용안함) : 2020-06-23
	
	-- 추천 관련 로그 쌓기
	DECLARE @LOG_SEQ_NO INT;
	SET @LOG_SEQ_NO = @@IDENTITY;
	INSERT INTO Cuve.dbo.TMP_1YEAR_LOG(
		SEQ_NO, IN_DATE, IN_IP, IN_PATH, IN_URL, IN_QUERY, INFLOW, IN_TYPE1, IN_TYPE2, IN_PRO_CODE, IN_MASTER_CODE, IN_USER_COOKIE
	) 
	SELECT 
		@LOG_SEQ_NO, IN_DATE, IN_IP, IN_PATH, IN_URL, IN_QUERY, INFLOW, IN_TYPE1, IN_TYPE2, IN_PRO_CODE, IN_MASTER_CODE, @IN_USER_COOKIE
	FROM VGLog.dbo.SYS_INFLOW_LOG WHERE SEQ_NO = @LOG_SEQ_NO;
	/*
	DELETE FROM Cuve..TMP_1YEAR_LOG WHERE SEQ_NO = ( SELECT TOP 1 SEQ_NO FROM Cuve..TMP_1YEAR_LOG WITH(NOLOCK) ORDER BY SEQ_NO ASC );
	*/
	
	*/
	
END
GO
