USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

 /*================================================================================================================
■ USP_NAME					: XP_ASG_EVT_REPORT_POLL_SELECT
■ DESCRIPTION				: 대외업무시스템 인솔자관리 출장보고서 POLL 리스트 검색
■ INPUT PARAMETER			: 
	@POL_TYPE CHAR(1)		:  전체평가 = 1, 가이드평가 = 2, 호텔평가 = 3, 식사평가 = 4, 고객평가 = 5, 이벤트 = 6
	@PRO_CODE	VARCHAR(20)
■ OUTPUT PARAMETER			: 

■ EXEC						: 
	DECLARE @POL_TYPE CHAR(1),@PRO_CODE	VARCHAR(20)
	SELECT @POL_TYPE='3', @PRO_CODE='EPP4056-181009KE'

	exec XP_ASG_EVT_REPORT_POLL_SELECT @POL_TYPE ,@PRO_CODE
	
■ MEMO						: 
------------------------------------------------------------------------------------------------------------------
■ CHANGE HISTORY                   
------------------------------------------------------------------------------------------------------------------
   DATE				AUTHOR			DESCRIPTION           
------------------------------------------------------------------------------------------------------------------
   2013-04-05		오인규			최초생성   
   2018-11-28		이명훈			가이드평가(POL_TYPE=3), 호텔평가(POL_TYPE=4) <가이드 평가/일정별 지역>부분 주석 제거   
================================================================================================================*/ 
CREATE  PROCEDURE [dbo].[XP_ASG_EVT_REPORT_POLL_SELECT]
(
	@POL_TYPE	CHAR(1),
	@PRO_CODE	VARCHAR(20)
)

AS  
BEGIN
   DECLARE @MASTER_SEQ INT


	IF @POL_TYPE = '1'
	BEGIN

		SELECT TOP 1 @MASTER_SEQ = MASTER_SEQ
		FROM	dbo.POL_MASTER A WITH(NOLOCK)
		WHERE	A.TARGET = 3
		AND		A.POL_TYPE = @POL_TYPE  --PollTypeEnum { 전체평가 = 1, 가이드평가 = 2, 호텔평가 = 3, 식사평가 = 4, 고객평가 = 5, 이벤트 = 6 };
		AND		A.POL_STATE = '1'  --진행중 = 1, 종료 = 2
		--AND     GETDATE() BETWEEN A.START_DATE AND A.END_DATE
		AND		A.DEL_FLAG ='N'
		ORDER BY NEW_DATE DESC

		SELECT    MASTER_SEQ                     --  
				, TARGET                         --  
				, POL_TYPE                       --  
				, POL_STATE                      --  
				, SUBJECT                        --  
				, POL_DESC                       --  
				, START_DATE                     --  
				, END_DATE                       --  
				, OPEN_DATE 
		FROM	dbo.POL_MASTER A WITH(NOLOCK)
		WHERE	A.TARGET = 3
		AND		A.POL_TYPE = @POL_TYPE  --PollTypeEnum { 전체평가 = 1, 가이드평가 = 2, 호텔평가 = 3, 식사평가 = 4, 고객평가 = 5, 이벤트 = 6 };
		AND		A.POL_STATE = '1'  --진행중 = 1, 종료 = 2
		--AND     GETDATE() BETWEEN A.START_DATE AND A.END_DATE
		AND		A.MASTER_SEQ = @MASTER_SEQ
			


		SELECT	A.MASTER_SEQ
				,B.QUESTION_SEQ
				,B.QUESTION_TITLE
				,B.QUS_TYPE
				,C.EXAMPLE_SEQ
				,C.EXAMPLE_DESC
		FROM	dbo.POL_MASTER A  WITH(NOLOCK)
		INNER JOIN dbo.POL_QUESTION B WITH(NOLOCK) ON A.MASTER_SEQ = B.MASTER_SEQ
		LEFT OUTER JOIN dbo.POL_DETAIL C WITH(NOLOCK) ON B.MASTER_SEQ = C.MASTER_SEQ AND B.QUESTION_SEQ = C.QUESTION_SEQ
		WHERE	A.TARGET = 3
		AND		A.POL_TYPE = @POL_TYPE  --PollTypeEnum { 전체평가 = 1, 가이드평가 = 2, 호텔평가 = 3, 식사평가 = 4, 고객평가 = 5, 이벤트 = 6 };
		AND		A.POL_STATE = '1'  --진행중 = 1, 종료 = 2
		--AND     GETDATE() BETWEEN A.START_DATE AND A.END_DATE
		AND		A.MASTER_SEQ = @MASTER_SEQ
		ORDER BY B.QUESTION_SEQ,C.EXAMPLE_SEQ

		SELECT '' AS NOTABLE
	END
	ELSE IF @POL_TYPE = '2'
	BEGIN

		SELECT TOP 1 @MASTER_SEQ = MASTER_SEQ
		FROM	dbo.POL_MASTER A WITH(NOLOCK)
		WHERE	A.TARGET = 3
		AND		A.POL_TYPE = @POL_TYPE  --PollTypeEnum { 전체평가 = 1, 가이드평가 = 2, 호텔평가 = 3, 식사평가 = 4, 고객평가 = 5, 이벤트 = 6 };
		AND		A.POL_STATE = '1'  --진행중 = 1, 종료 = 2
		--AND     GETDATE() BETWEEN A.START_DATE AND A.END_DATE
		AND		A.DEL_FLAG ='N'
		ORDER BY NEW_DATE DESC

		SELECT 
				MASTER_SEQ                     --  
				, TARGET                         --  
				, POL_TYPE                       --  
				, POL_STATE                      --  
				, SUBJECT                        --  
				, POL_DESC                       --  
				, START_DATE                     --  
				, END_DATE                       --  
				, OPEN_DATE 
		FROM	dbo.POL_MASTER A WITH(NOLOCK)
		WHERE	A.TARGET = 3
		AND		A.POL_TYPE = @POL_TYPE  --PollTypeEnum { 전체평가 = 1, 가이드평가 = 2, 호텔평가 = 3, 식사평가 = 4, 고객평가 = 5, 이벤트 = 6 };
		AND		A.POL_STATE = '1'  --진행중 = 1, 종료 = 2
		--AND     GETDATE() BETWEEN A.START_DATE AND A.END_DATE
		AND		A.MASTER_SEQ = @MASTER_SEQ

		SELECT	A.MASTER_SEQ
				,B.QUESTION_SEQ
				,B.QUESTION_TITLE
				,B.QUS_TYPE
				,C.EXAMPLE_SEQ
				,C.EXAMPLE_DESC
		FROM	dbo.POL_MASTER A WITH(NOLOCK)
		INNER JOIN dbo.POL_QUESTION B WITH(NOLOCK) ON A.MASTER_SEQ = B.MASTER_SEQ
		LEFT OUTER JOIN dbo.POL_DETAIL C WITH(NOLOCK) ON B.MASTER_SEQ = C.MASTER_SEQ AND B.QUESTION_SEQ = C.QUESTION_SEQ
		WHERE	A.TARGET = 3
		AND		A.POL_TYPE = @POL_TYPE  --PollTypeEnum { 전체평가 = 1, 가이드평가 = 2, 호텔평가 = 3, 식사평가 = 4, 고객평가 = 5, 이벤트 = 6 };
		AND		A.POL_STATE = '1'  --진행중 = 1, 종료 = 2
		--AND     GETDATE() BETWEEN A.START_DATE AND A.END_DATE
		AND		A.MASTER_SEQ = @MASTER_SEQ
		ORDER BY B.QUESTION_SEQ,C.EXAMPLE_SEQ
	
			-- 가이드 평가/일정별 지역
		SELECT TMP2.SEQ_DATE AS START_DATE ,TMP2.SEQ_DATE  AS END_DATE ,TMP2.DAY_SEQ,F.KOR_NAME AS CITY_NAME 
		FROM(
				SELECT SEQ_DATE, CASE WHEN TMP.TOUR_DAY = TMP.DAY_SEQ THEN MIN(TMP.CITY_SEQ) ELSE  MAX(TMP.CITY_SEQ)END AS CITY_SEQ,DAY_SEQ, SCH_SEQ,PRO_CODE 
				FROM 
					(SELECT	DATEADD(DAY,(E.DAY_SEQ-1), A.DEP_DATE) AS SEQ_DATE,E.DAY_SEQ,E.CITY_SEQ,A.TOUR_DAY ,F.KOR_NAME,E.CITY_CODE,B.SCH_SEQ ,A.PRO_CODE
						FROM	dbo.PKG_DETAIL A  WITH(NOLOCK)
							INNER JOIN (SELECT Z.PRO_CODE, ISNULL(MIN(Z.SCH_SEQ),1) AS SCH_SEQ FROM dbo.PKG_DETAIL_PRICE Z WITH(NOLOCK) WHERE Z.PRO_CODE =@PRO_CODE GROUP BY Z.PRO_CODE ,Z.SCH_SEQ) B ON A.PRO_CODE = B.PRO_CODE
							--dbo.PKG_DETAIL_PRICE B  WITH(NOLOCK) ON A.PRO_CODE = B.PRO_CODE
							INNER JOIN dbo.PKG_DETAIL_SCH_MASTER C  WITH(NOLOCK) ON  B.PRO_CODE = C.PRO_CODE AND B.SCH_SEQ = C.SCH_SEQ
							INNER JOIN dbo.PKG_DETAIL_SCH_DAY D  WITH(NOLOCK) ON  C.PRO_CODE = D.PRO_CODE AND C.SCH_SEQ = D.SCH_SEQ
							INNER JOIN dbo.PKG_DETAIL_SCH_CITY E  WITH(NOLOCK) ON  D.PRO_CODE = E.PRO_CODE AND D.SCH_SEQ = E.SCH_SEQ AND D.DAY_SEQ =E.DAY_SEQ
							INNER JOIN PUB_CITY F WITH(NOLOCK) ON F.CITY_CODE = E.CITY_CODE
					WHERE	A.PRO_CODE =@PRO_CODE
					--ORDER BY E.DAY_SEQ ,E.CITY_SEQ;
					) TMP
				GROUP BY TMP.SEQ_DATE,TMP.DAY_SEQ,TMP.TOUR_DAY,TMP.SCH_SEQ ,TMP.PRO_CODE
		) TMP2
		INNER JOIN dbo.PKG_DETAIL_SCH_CITY E  WITH(NOLOCK) ON  TMP2.PRO_CODE = E.PRO_CODE AND TMP2.SCH_SEQ = E.SCH_SEQ AND TMP2.DAY_SEQ =E.DAY_SEQ AND TMP2.CITY_SEQ = E.CITY_SEQ
		INNER JOIN PUB_CITY F WITH(NOLOCK) ON F.CITY_CODE = E.CITY_CODE


		
	END

	ELSE IF @POL_TYPE = '3'
	BEGIN
		SELECT TOP 1 @MASTER_SEQ = MASTER_SEQ
		FROM	dbo.POL_MASTER A WITH(NOLOCK)
		WHERE	A.TARGET = 3
		AND		A.POL_TYPE = @POL_TYPE  --PollTypeEnum { 전체평가 = 1, 가이드평가 = 2, 호텔평가 = 3, 식사평가 = 4, 고객평가 = 5, 이벤트 = 6 };
		AND		A.POL_STATE = '1'  --진행중 = 1, 종료 = 2
		--AND     GETDATE() BETWEEN A.START_DATE AND A.END_DATE
		AND		A.DEL_FLAG ='N'
		ORDER BY NEW_DATE DESC


		SELECT 
				MASTER_SEQ                     --  
				, TARGET                         --  
				, POL_TYPE                       --  
				, POL_STATE                      --  
				, SUBJECT                        --  
				, POL_DESC                       --  
				, START_DATE                     --  
				, END_DATE                       --  
				, OPEN_DATE 
		FROM	dbo.POL_MASTER A WITH(NOLOCK)
		WHERE	A.TARGET = 3
		AND		A.POL_TYPE = @POL_TYPE  --PollTypeEnum { 전체평가 = 1, 가이드평가 = 2, 호텔평가 = 3, 식사평가 = 4, 고객평가 = 5, 이벤트 = 6 };
		AND		A.POL_STATE = '1'  --진행중 = 1, 종료 = 2
		--AND     GETDATE() BETWEEN A.START_DATE AND A.END_DATE
		AND		A.MASTER_SEQ = @MASTER_SEQ

		SELECT	A.MASTER_SEQ
				,B.QUESTION_SEQ
				,B.QUESTION_TITLE
				,B.QUS_TYPE
				,C.EXAMPLE_SEQ
				,C.EXAMPLE_DESC
		FROM	dbo.POL_MASTER A WITH(NOLOCK) 
		INNER JOIN dbo.POL_QUESTION B WITH(NOLOCK) ON A.MASTER_SEQ = B.MASTER_SEQ
		LEFT OUTER JOIN dbo.POL_DETAIL C WITH(NOLOCK) ON B.MASTER_SEQ = C.MASTER_SEQ AND B.QUESTION_SEQ = C.QUESTION_SEQ
		WHERE	A.TARGET = 3
		AND		A.POL_TYPE = @POL_TYPE  --PollTypeEnum { 전체평가 = 1, 가이드평가 = 2, 호텔평가 = 3, 식사평가 = 4, 고객평가 = 5, 이벤트 = 6 };
		AND		A.POL_STATE = '1'  --진행중 = 1, 종료 = 2
		--AND     GETDATE() BETWEEN A.START_DATE AND A.END_DATE
			AND		A.MASTER_SEQ = @MASTER_SEQ
		ORDER BY B.QUESTION_SEQ,C.EXAMPLE_SEQ
	
		-- 가이드 평가/일정별 지역
		SELECT TMP2.SEQ_DATE AS START_DATE ,TMP2.SEQ_DATE  AS END_DATE ,TMP2.DAY_SEQ,F.KOR_NAME AS CITY_NAME ,G.MASTER_CODE, G.MASTER_NAME AS HOTEL_NAME --, G.DINNER_1,G.DINNER_2,G.DINNER_3 
		FROM(
				SELECT SEQ_DATE, CASE WHEN TMP.TOUR_DAY = TMP.DAY_SEQ THEN MIN(TMP.CITY_SEQ) ELSE  MAX(TMP.CITY_SEQ)END AS CITY_SEQ,DAY_SEQ, SCH_SEQ,PRO_CODE 
				FROM 
					(SELECT	DATEADD(DAY,(E.DAY_SEQ-1), A.DEP_DATE) AS SEQ_DATE,E.DAY_SEQ,E.CITY_SEQ,A.TOUR_DAY ,F.KOR_NAME,E.CITY_CODE,B.SCH_SEQ ,A.PRO_CODE
						FROM	dbo.PKG_DETAIL A  WITH(NOLOCK)
							INNER JOIN (SELECT Z.PRO_CODE, ISNULL(MIN(Z.SCH_SEQ),1) AS SCH_SEQ FROM dbo.PKG_DETAIL_PRICE Z WITH(NOLOCK) WHERE Z.PRO_CODE =@PRO_CODE GROUP BY Z.PRO_CODE ,Z.SCH_SEQ) B ON A.PRO_CODE = B.PRO_CODE
							--dbo.PKG_DETAIL_PRICE B  WITH(NOLOCK) ON A.PRO_CODE = B.PRO_CODE
							INNER JOIN dbo.PKG_DETAIL_SCH_MASTER C  WITH(NOLOCK) ON  B.PRO_CODE = C.PRO_CODE AND B.SCH_SEQ = C.SCH_SEQ
							INNER JOIN dbo.PKG_DETAIL_SCH_DAY D  WITH(NOLOCK) ON  C.PRO_CODE = D.PRO_CODE AND C.SCH_SEQ = D.SCH_SEQ
							INNER JOIN dbo.PKG_DETAIL_SCH_CITY E  WITH(NOLOCK) ON  D.PRO_CODE = E.PRO_CODE AND D.SCH_SEQ = E.SCH_SEQ AND D.DAY_SEQ =E.DAY_SEQ
							INNER JOIN PUB_CITY F WITH(NOLOCK) ON F.CITY_CODE = E.CITY_CODE
					WHERE	A.PRO_CODE =@PRO_CODE
					--ORDER BY E.DAY_SEQ ,E.CITY_SEQ;
					) TMP
				GROUP BY TMP.SEQ_DATE,TMP.DAY_SEQ,TMP.TOUR_DAY,TMP.SCH_SEQ ,TMP.PRO_CODE
		) TMP2
		INNER JOIN dbo.PKG_DETAIL_SCH_CITY E  WITH(NOLOCK) ON  TMP2.PRO_CODE = E.PRO_CODE AND TMP2.SCH_SEQ = E.SCH_SEQ AND TMP2.DAY_SEQ =E.DAY_SEQ AND TMP2.CITY_SEQ = E.CITY_SEQ
		INNER JOIN PUB_CITY F WITH(NOLOCK) ON F.CITY_CODE = E.CITY_CODE
		LEFT OUTER JOIN (
					SELECT A.PRO_CODE,A.DAY_NUMBER, B.MASTER_CODE, B.MASTER_NAME, A.DINNER_1,A.DINNER_2,A.DINNER_3
					FROM PKG_DETAIL_PRICE_HOTEL A WITH(NOLOCK) 
					LEFT OUTER JOIN HTL_MASTER B  WITH(NOLOCK) ON A.HTL_MASTER_CODE = B.MASTER_CODE
					WHERE A.PRO_CODE = @PRO_CODE AND A.PRICE_SEQ = (SELECT TOP 1 PRICE_SEQ FROM dbo.RES_MASTER_damo WITH(NOLOCK)   WHERE PRO_CODE = A.PRO_CODE ORDER BY PRICE_SEQ)
		) G ON G.PRO_CODE = TMP2.PRO_CODE  AND TMP2.DAY_SEQ= G.DAY_NUMBER

		
	END
	ELSE IF @POL_TYPE = '4'
	BEGIN
		SELECT TOP 1 @MASTER_SEQ = MASTER_SEQ
		FROM	dbo.POL_MASTER A WITH(NOLOCK)
		WHERE	A.TARGET = 3
		AND		A.POL_TYPE = @POL_TYPE  --PollTypeEnum { 전체평가 = 1, 가이드평가 = 2, 호텔평가 = 3, 식사평가 = 4, 고객평가 = 5, 이벤트 = 6 };
		AND		A.POL_STATE = '1'  --진행중 = 1, 종료 = 2
		--AND     GETDATE() BETWEEN A.START_DATE AND A.END_DATE
		AND		A.DEL_FLAG ='N'
		ORDER BY NEW_DATE DESC

		SELECT 
				MASTER_SEQ                     --  
				, TARGET                         --  
				, POL_TYPE                       --  
				, POL_STATE                      --  
				, SUBJECT                        --  
				, POL_DESC                       --  
				, START_DATE                     --  
				, END_DATE                       --  
				, OPEN_DATE 
		FROM	dbo.POL_MASTER A WITH(NOLOCK)
		WHERE	A.TARGET = 3
		AND		A.POL_TYPE = @POL_TYPE  --PollTypeEnum { 전체평가 = 1, 가이드평가 = 2, 호텔평가 = 3, 식사평가 = 4, 고객평가 = 5, 이벤트 = 6 };
		AND		A.POL_STATE = '1'  --진행중 = 1, 종료 = 2
		--AND     GETDATE() BETWEEN A.START_DATE AND A.END_DATE
		AND		A.MASTER_SEQ = @MASTER_SEQ
	    
		SELECT	A.MASTER_SEQ
				,B.QUESTION_SEQ
				,B.QUESTION_TITLE
				,B.QUS_TYPE
				,C.EXAMPLE_SEQ
				,C.EXAMPLE_DESC
		FROM	dbo.POL_MASTER A WITH(NOLOCK) 
		INNER JOIN dbo.POL_QUESTION B WITH(NOLOCK) ON A.MASTER_SEQ = B.MASTER_SEQ
		LEFT OUTER JOIN dbo.POL_DETAIL C WITH(NOLOCK) ON B.MASTER_SEQ = C.MASTER_SEQ AND B.QUESTION_SEQ = C.QUESTION_SEQ
		WHERE	A.TARGET = 3
		AND		A.POL_TYPE = @POL_TYPE  --PollTypeEnum { 전체평가 = 1, 가이드평가 = 2, 호텔평가 = 3, 식사평가 = 4, 고객평가 = 5, 이벤트 = 6 };
		AND		A.POL_STATE = '1'  --진행중 = 1, 종료 = 2
		--AND     GETDATE() BETWEEN A.START_DATE AND A.END_DATE
			AND		A.MASTER_SEQ = @MASTER_SEQ
		ORDER BY B.QUESTION_SEQ,C.EXAMPLE_SEQ

		-- 가이드 평가/일정별 지역
		SELECT TMP2.SEQ_DATE AS START_DATE ,TMP2.SEQ_DATE  AS END_DATE ,TMP2.DAY_SEQ,F.KOR_NAME  AS CITY_NAME , G.DINNER_1,G.DINNER_2,G.DINNER_3 
		FROM(
				SELECT SEQ_DATE, CASE WHEN TMP.TOUR_DAY = TMP.DAY_SEQ THEN MIN(TMP.CITY_SEQ) ELSE  MAX(TMP.CITY_SEQ)END AS CITY_SEQ,DAY_SEQ, SCH_SEQ,PRO_CODE 
				FROM 
					(SELECT	DATEADD(DAY,(E.DAY_SEQ-1), A.DEP_DATE) AS SEQ_DATE,E.DAY_SEQ,E.CITY_SEQ,A.TOUR_DAY ,F.KOR_NAME,E.CITY_CODE,B.SCH_SEQ ,A.PRO_CODE
						FROM	dbo.PKG_DETAIL A  WITH(NOLOCK)
							INNER JOIN (SELECT Z.PRO_CODE, ISNULL(MIN(Z.SCH_SEQ),1) AS SCH_SEQ FROM dbo.PKG_DETAIL_PRICE Z WITH(NOLOCK) WHERE Z.PRO_CODE =@PRO_CODE GROUP BY Z.PRO_CODE ,Z.SCH_SEQ) B ON A.PRO_CODE = B.PRO_CODE
							--dbo.PKG_DETAIL_PRICE B  WITH(NOLOCK) ON A.PRO_CODE = B.PRO_CODE
							INNER JOIN dbo.PKG_DETAIL_SCH_MASTER C  WITH(NOLOCK) ON  B.PRO_CODE = C.PRO_CODE AND B.SCH_SEQ = C.SCH_SEQ
							INNER JOIN dbo.PKG_DETAIL_SCH_DAY D  WITH(NOLOCK) ON  C.PRO_CODE = D.PRO_CODE AND C.SCH_SEQ = D.SCH_SEQ
							INNER JOIN dbo.PKG_DETAIL_SCH_CITY E  WITH(NOLOCK) ON  D.PRO_CODE = E.PRO_CODE AND D.SCH_SEQ = E.SCH_SEQ AND D.DAY_SEQ =E.DAY_SEQ
							INNER JOIN PUB_CITY F WITH(NOLOCK) ON F.CITY_CODE = E.CITY_CODE
					WHERE	A.PRO_CODE =@PRO_CODE
					--ORDER BY E.DAY_SEQ ,E.CITY_SEQ;
					) TMP
				GROUP BY TMP.SEQ_DATE,TMP.DAY_SEQ,TMP.TOUR_DAY,TMP.SCH_SEQ ,TMP.PRO_CODE
		) TMP2
		INNER JOIN dbo.PKG_DETAIL_SCH_CITY E  WITH(NOLOCK) ON  TMP2.PRO_CODE = E.PRO_CODE AND TMP2.SCH_SEQ = E.SCH_SEQ AND TMP2.DAY_SEQ =E.DAY_SEQ AND TMP2.CITY_SEQ = E.CITY_SEQ
		INNER JOIN PUB_CITY F WITH(NOLOCK) ON F.CITY_CODE = E.CITY_CODE
		LEFT OUTER JOIN (
					SELECT A.PRO_CODE,A.DAY_NUMBER, B.MASTER_CODE, B.MASTER_NAME, A.DINNER_1,A.DINNER_2,A.DINNER_3
					FROM PKG_DETAIL_PRICE_HOTEL A WITH(NOLOCK) 
					LEFT OUTER JOIN HTL_MASTER B  WITH(NOLOCK) ON A.HTL_MASTER_CODE = B.MASTER_CODE
					WHERE A.PRO_CODE = @PRO_CODE AND A.PRICE_SEQ = (SELECT TOP 1 PRICE_SEQ FROM dbo.RES_MASTER_damo   WHERE PRO_CODE = @PRO_CODE ORDER BY PRICE_SEQ)
		) G ON G.PRO_CODE = TMP2.PRO_CODE  AND TMP2.DAY_SEQ= G.DAY_NUMBER
		
			

	END
	ELSE IF @POL_TYPE = '5'
	BEGIN
		SELECT TOP 1 @MASTER_SEQ = MASTER_SEQ
		FROM	dbo.POL_MASTER A WITH(NOLOCK)
		WHERE	A.TARGET = 3
		AND		A.POL_TYPE = @POL_TYPE  --PollTypeEnum { 전체평가 = 1, 가이드평가 = 2, 호텔평가 = 3, 식사평가 = 4, 고객평가 = 5, 이벤트 = 6 };
		AND		A.POL_STATE = '1'  --진행중 = 1, 종료 = 2
		--AND     GETDATE() BETWEEN A.START_DATE AND A.END_DATE
		AND		A.DEL_FLAG ='N'
		ORDER BY NEW_DATE DESC

		SELECT 
				MASTER_SEQ                     --  
				, TARGET                         --  
				, POL_TYPE                       --  
				, POL_STATE                      --  
				, SUBJECT                        --  
				, POL_DESC                       --  
				, START_DATE                     --  
				, END_DATE                       --  
				, OPEN_DATE 
		FROM	dbo.POL_MASTER A WITH(NOLOCK)
		WHERE	A.TARGET = 3
		AND		A.POL_TYPE = @POL_TYPE  --PollTypeEnum { 전체평가 = 1, 가이드평가 = 2, 호텔평가 = 3, 식사평가 = 4, 고객평가 = 5, 이벤트 = 6 };
		AND		A.POL_STATE = '1'  --진행중 = 1, 종료 = 2
		--AND     GETDATE() BETWEEN A.START_DATE AND A.END_DATE
		AND		A.MASTER_SEQ = @MASTER_SEQ
	    
		SELECT	A.MASTER_SEQ
				,B.QUESTION_SEQ
				,B.QUESTION_TITLE
				,B.QUS_TYPE
				,C.EXAMPLE_SEQ
				,C.EXAMPLE_DESC
		FROM	dbo.POL_MASTER A WITH(NOLOCK) 
		INNER JOIN dbo.POL_QUESTION B WITH(NOLOCK) ON A.MASTER_SEQ = B.MASTER_SEQ
		LEFT OUTER JOIN dbo.POL_DETAIL C WITH(NOLOCK) ON B.MASTER_SEQ = C.MASTER_SEQ AND B.QUESTION_SEQ = C.QUESTION_SEQ
		WHERE	A.TARGET = 3
		AND		A.POL_TYPE = @POL_TYPE  --PollTypeEnum { 전체평가 = 1, 가이드평가 = 2, 호텔평가 = 3, 식사평가 = 4, 고객평가 = 5, 이벤트 = 6 };
		AND		A.POL_STATE = '1'  --진행중 = 1, 종료 = 2
		--AND     GETDATE() BETWEEN A.START_DATE AND A.END_DATE
			AND		A.MASTER_SEQ = @MASTER_SEQ
		ORDER BY B.QUESTION_SEQ,C.EXAMPLE_SEQ

			

	END

END

GO
