USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


/*================================================================================================================
■ USP_NAME					: XP_WEB_CUS_MEMBER_UPDATE
■ DESCRIPTION				: 회원가입 정보 수정
■ INPUT PARAMETER			:
■ OUTPUT PARAMETER			: 
■ EXEC						: 
	exec  XP_WEB_CUS_MEMBER_UPDATE 
■ MEMO						: 
------------------------------------------------------------------------------------------------------------------
■ CHANGE HISTORY                   
------------------------------------------------------------------------------------------------------------------
   DATE				AUTHOR			DESCRIPTION           
------------------------------------------------------------------------------------------------------------------
   2013-04-23		박형만			최초생성
   2013-07-05		박형만			수신동의 여부 수정시 Y 로 변경 되었을때만 수신동의날짜 수정
   2013-11-27		박형만			ok캐쉬백 인증으로 ok캐쉬백 카드번호 수정되도록
   2017-11-04		박형만			SNS 회원으로 인하여 생년월일, 성별이 있는경우 수정가능하도록 
   2018-03-21		박형만			모바일수정관련 여권수정안함,ocb 수정안함, 히스토리 남기기
   2019-12-23		오준혁			만14세 미만의 경우 생년월일 업데이트 안함
   2020-07-24		유민석			CUS_MEMBER 업데이트 시 마케팅수신동의여부도 수정되도록  
   2021-01-26		김영민			FORMEMBER_YN 평생회원추가
================================================================================================================*/ 
CREATE  PROC [dbo].[XP_WEB_CUS_MEMBER_UPDATE]
(
	@CUS_NO INT , 
	@LAST_NAME  VARCHAR(20),
	@FIRST_NAME VARCHAR(20),
	@NOR_TEL1 VARCHAR(6), 
	@NOR_TEL2 VARCHAR(5), 
	@NOR_TEL3 VARCHAR(4),
	@HOM_TEL1 VARCHAR(6), 
	@HOM_TEL2 VARCHAR(5), 
	@HOM_TEL3 VARCHAR(4), 
	@ZIP_CODE VARCHAR(7), 
	@ADDRESS1 VARCHAR(100), 
	@ADDRESS2 VARCHAR(100), 
	@EMAIL	VARCHAR(40),
	@RCV_EMAIL_YN CHAR(1),
	@RCV_SMS_YN CHAR(1), 

	@NEW_CODE NEW_CODE,

	@PASS_NUM VARCHAR(20) , 
	@PASS_EXPIRE datetime , 

	--@OCB_AGREE_YN CHAR(1),  --OK 캐쉬백 
	--@OCB_AGREE_DATE datetime , 
	--@OCB_AGREE_EMP_CODE EMP_CODE,
	--@OCB_CARD_NUM CHAR(16) ,

	@WEDDING_YN CHAR(1), 
	@WEDDING_DATE VARCHAR(10), 
	@MATE_BIRTHDAY VARCHAR(10), 
	@MATE_LUNAR_YN CHAR(1), 
	@HOPE_REGION VARCHAR(20), 
	@TRAVEL_TYPE VARCHAR(20), 
	@INFLOW_ROUTE VARCHAR(100),

	@ADDINFO_CHG_YN CHAR(1),  -- 추가정보 수정여부 
	@SYSTEM_TYPE	INT = NULL , 
	@BIRTH_DATE  datetime = NULL , 
	@GENDER char(1) = NULL  , 
	@CUS_NAME VARCHAr(20) = NULL, 
	@FORMEMBER_YN  CHAR(1) = NULL
)
AS 

BEGIN


	-- 만14세 미만의 경우 생년월일 업데이트 안함
	IF (ISNULL(@BIRTH_DATE ,'') <> '' AND DATEDIFF(YEAR ,@BIRTH_DATE ,GETDATE()) < 15)
	    SET @BIRTH_DATE = NULL



	-- 히스토리 남기기 
	EXEC XP_CUS_CUSTOMER_HISTORY_INSERT  
	@CUS_NO = @CUS_NO, 
	@BIRTH_DATE = @BIRTH_DATE, 
	@GENDER = @GENDER , 
	@CUS_NAME = @CUS_NAME ,

	@LAST_NAME  =@LAST_NAME,
	@FIRST_NAME = @FIRST_NAME ,
	@NOR_TEL1 = @NOR_TEL1,
	@NOR_TEL2 = @NOR_TEL2,
	@NOR_TEL3 = @NOR_TEL3,
	@HOM_TEL1 = @HOM_TEL1,
	@HOM_TEL2 = @HOM_TEL2,
	@HOM_TEL3 = @HOM_TEL3,
	@ZIP_CODE = @ZIP_CODE,
	@ADDRESS1 = @ADDRESS1,
	@ADDRESS2 = @ADDRESS2,
	@EMAIL	= @EMAIL,
	@RCV_EMAIL_YN = @RCV_EMAIL_YN,
	@RCV_SMS_YN = @RCV_SMS_YN,

	@EMP_CODE = '9999999' , 
	@EDT_REMARK = '고객수정' , 
	@SYSTEM_TYPE = @SYSTEM_TYPE ,
	@EDT_TYPE  = 1 


	/* 비회원 가입자의 경우 기록된 데이터가 있으므로 업데이트 */
	UPDATE CUS_CUSTOMER_DAMO
	SET 
		NOR_TEL1 = @NOR_TEL1,
		NOR_TEL2 = @NOR_TEL2,
		NOR_TEL3 = @NOR_TEL3,
		EMAIL = @EMAIL,
		--생년월일 성별은 값이 있는 경우만 수정 
		BIRTH_DATE = CASE WHEN @BIRTH_DATE IS NULL THEN BIRTH_DATE ELSE @BIRTH_DATE END ,
		GENDER = CASE WHEN ISNULL(@GENDER,'') = '' THEN GENDER ELSE @GENDER END ,
		RCV_EMAIL_YN = @RCV_EMAIL_YN,
		RCV_SMS_YN = @RCV_SMS_YN,
		EMAIL_AGREE_DATE = CASE WHEN @RCV_EMAIL_YN ='Y' AND RCV_EMAIL_YN <> 'Y' THEN  CONVERT(VARCHAR(10),GETDATE(),121)  ELSE EMAIL_AGREE_DATE END ,
		SMS_AGREE_DATE = CASE WHEN @RCV_SMS_YN ='Y' AND RCV_SMS_YN <> 'Y' THEN  CONVERT(VARCHAR(10),GETDATE(),121)  ELSE SMS_AGREE_DATE END ,
		EMAIL_INFLOW_TYPE = CASE WHEN @RCV_EMAIL_YN ='Y' AND RCV_EMAIL_YN <> 'Y' THEN  '99'  ELSE EMAIL_INFLOW_TYPE END ,
		SMS_INFLOW_TYPE = CASE WHEN @RCV_SMS_YN ='Y' AND RCV_SMS_YN <> 'Y' THEN  '99'  ELSE SMS_INFLOW_TYPE END ,

		-- 새로운 값이 있고 현재랑 틀릴때만 수정
		-- 모바일 수정 문제로 인하여 수정 
		CUS_NAME = CASE WHEN ISNULL(@CUS_NAME,'') <> '' AND ISNULL(CUS_NAME,'') <> ISNULL(@CUS_NAME,'')  THEN @CUS_NAME ELSE CUS_NAME END ,
		LAST_NAME = CASE WHEN ISNULL(@LAST_NAME,'') <> '' AND ISNULL(LAST_NAME,'') <> ISNULL(@LAST_NAME,'')  THEN @LAST_NAME ELSE LAST_NAME END ,
		FIRST_NAME = CASE WHEN ISNULL(@FIRST_NAME,'') <> '' AND ISNULL(FIRST_NAME,'') <> ISNULL(@FIRST_NAME,'') THEN @FIRST_NAME ELSE FIRST_NAME END ,
		HOM_TEL1 = CASE WHEN ISNULL(@HOM_TEL1,'') <> '' AND ISNULL(HOM_TEL1,'') <> ISNULL(@HOM_TEL1,'') THEN @HOM_TEL1 ELSE HOM_TEL1 END ,
		HOM_TEL2 = CASE WHEN ISNULL(@HOM_TEL2,'') <> '' AND ISNULL(HOM_TEL2,'') <> ISNULL(@HOM_TEL2,'') THEN @HOM_TEL2 ELSE HOM_TEL2 END ,
		HOM_TEL3 = CASE WHEN ISNULL(@HOM_TEL3,'') <> '' AND ISNULL(HOM_TEL3,'') <> ISNULL(@HOM_TEL3,'') THEN @HOM_TEL3 ELSE HOM_TEL3 END ,
		ADDRESS1 = CASE WHEN ISNULL(@ADDRESS1,'') <> '' AND ISNULL(ADDRESS1,'') <> ISNULL(@ADDRESS1,'') THEN @ADDRESS1 ELSE ADDRESS1 END ,
		ADDRESS2 = CASE WHEN ISNULL(@ADDRESS2,'') <> '' AND ISNULL(ADDRESS2,'') <> ISNULL(@ADDRESS2,'') THEN @ADDRESS2 ELSE ADDRESS2 END ,
		--CUS_ICON = @CUS_ICON,
		ZIP_CODE = CASE WHEN ISNULL(@ZIP_CODE,'') <> '' AND ISNULL(ZIP_CODE,'') <> ISNULL(@ZIP_CODE,'') THEN @ZIP_CODE ELSE ZIP_CODE END ,
		--LUNAR_YN = @LUNAR_YN,
		--BIRTHDAY = @BIRTHDAY,

		--SEC_PASS_NUM = damo.dbo.enc_varchar('DIABLO','dbo.CUS_CUSTOMER','PASS_NUM',@PASS_NUM),
		--SEC1_PASS_NUM = damo.dbo.pred_meta_plain_v( @PASS_NUM ,'DIABLO','dbo.CUS_CUSTOMER','PASS_NUM'),
		--PASS_EXPIRE = @PASS_EXPIRE ,

		EDT_CODE = @NEW_CODE,
		EDT_DATE = GETDATE(),
		EDT_MESSAGE = '고객수정' 

	WHERE 
		CUS_NO = @CUS_NO
		
	UPDATE CUS_MEMBER
	SET 
		NOR_TEL1 = @NOR_TEL1,
		NOR_TEL2 = @NOR_TEL2,
		NOR_TEL3 = @NOR_TEL3,
		EMAIL = @EMAIL,
		--생년월일 성별은 값이 있는 경우만 수정 
		BIRTH_DATE = CASE WHEN @BIRTH_DATE IS NULL THEN BIRTH_DATE ELSE @BIRTH_DATE END ,
		GENDER = CASE WHEN ISNULL(@GENDER,'') = '' THEN GENDER ELSE @GENDER END ,
		-- 수신동의여부 추가
		RCV_EMAIL_YN = @RCV_EMAIL_YN,
		RCV_SMS_YN = @RCV_SMS_YN,
		-- 새로운 값이 있고 현재랑 틀릴때만 수정
		-- 모바일 수정 문제로 인하여 수정 
		CUS_NAME = CASE WHEN ISNULL(@CUS_NAME,'') <> '' AND ISNULL(CUS_NAME,'') <> ISNULL(@CUS_NAME,'')  THEN @CUS_NAME ELSE CUS_NAME END ,
		LAST_NAME = CASE WHEN ISNULL(@LAST_NAME,'') <> '' AND ISNULL(LAST_NAME,'') <> ISNULL(@LAST_NAME,'')  THEN @LAST_NAME ELSE LAST_NAME END ,
		FIRST_NAME = CASE WHEN ISNULL(@FIRST_NAME,'') <> '' AND ISNULL(FIRST_NAME,'') <> ISNULL(@FIRST_NAME,'') THEN @FIRST_NAME ELSE FIRST_NAME END ,
		HOM_TEL1 = CASE WHEN ISNULL(@HOM_TEL1,'') <> '' AND ISNULL(HOM_TEL1,'') <> ISNULL(@HOM_TEL1,'') THEN @HOM_TEL1 ELSE HOM_TEL1 END ,
		HOM_TEL2 = CASE WHEN ISNULL(@HOM_TEL2,'') <> '' AND ISNULL(HOM_TEL2,'') <> ISNULL(@HOM_TEL2,'') THEN @HOM_TEL2 ELSE HOM_TEL2 END ,
		HOM_TEL3 = CASE WHEN ISNULL(@HOM_TEL3,'') <> '' AND ISNULL(HOM_TEL3,'') <> ISNULL(@HOM_TEL3,'') THEN @HOM_TEL3 ELSE HOM_TEL3 END ,
		ADDRESS1 = CASE WHEN ISNULL(@ADDRESS1,'') <> '' AND ISNULL(ADDRESS1,'') <> ISNULL(@ADDRESS1,'') THEN @ADDRESS1 ELSE ADDRESS1 END ,
		ADDRESS2 = CASE WHEN ISNULL(@ADDRESS2,'') <> '' AND ISNULL(ADDRESS2,'') <> ISNULL(@ADDRESS2,'') THEN @ADDRESS2 ELSE ADDRESS2 END ,
		FORMEMBER_YN = CASE WHEN ISNULL(@FORMEMBER_YN,'') <> '' THEN @FORMEMBER_YN  ELSE FORMEMBER_YN END  ,
		FORMEMBER_DATE = GETDATE(),
		--CUS_ICON = @CUS_ICON,
		ZIP_CODE = CASE WHEN ISNULL(@ZIP_CODE,'') <> '' AND ISNULL(ZIP_CODE,'') <> ISNULL(@ZIP_CODE,'') THEN @ZIP_CODE ELSE ZIP_CODE END ,
		
		--LUNAR_YN = @LUNAR_YN,
		--BIRTHDAY = @BIRTHDAY,
		
		--OCB_AGREE_YN = @OCB_AGREE_YN , 
		----기존 미동의 - 신규 동의시에만 갱신 
		--OCB_AGREE_DATE = CASE WHEN ISNULL(OCB_AGREE_YN,'N') ='N' AND @OCB_AGREE_YN ='Y' THEN @OCB_AGREE_DATE ELSE OCB_AGREE_DATE END , 
		--OCB_AGREE_EMP_CODE = CASE WHEN ISNULL(OCB_AGREE_YN,'N') ='N' AND @OCB_AGREE_YN ='Y' THEN @OCB_AGREE_EMP_CODE ELSE OCB_AGREE_EMP_CODE END , 
		--OCB_CARD_NUM = @OCB_CARD_NUM ,
		
		--SEC_PASS_NUM = damo.dbo.enc_varchar('DIABLO','dbo.CUS_CUSTOMER','PASS_NUM',@PASS_NUM),
		--SEC1_PASS_NUM = damo.dbo.pred_meta_plain_v( @PASS_NUM ,'DIABLO','dbo.CUS_CUSTOMER','PASS_NUM'),
		--PASS_EXPIRE = @PASS_EXPIRE ,

		EDT_CODE = @NEW_CODE,
		EDT_DATE = GETDATE(),
		EDT_MESSAGE = '고객수정' 
		
	WHERE 
		CUS_NO = @CUS_NO

	/* 부가정보 수정 */
	IF NOT EXISTS(SELECT 1 FROM CUS_ADDITION WITH(NOLOCK) WHERE CUS_NO=@CUS_NO)
	BEGIN
		INSERT INTO CUS_ADDITION(CUS_NO) VALUES(@CUS_NO)
	END
	
	-- 빈값이면 Y ,수정됨(기본
	IF ISNULL(@ADDINFO_CHG_YN,'Y') = 'Y' 
	BEGIN
		UPDATE CUS_ADDITION
		SET
			-- 새로운 값이 있고 현재랑 틀릴때만 수정
			WEDDING_YN = @WEDDING_YN,
			WEDDING_DATE = @WEDDING_DATE,
			MATE_BIRTHDAY = @MATE_BIRTHDAY,
			MATE_LUNAR_YN = @MATE_LUNAR_YN,
			HOPE_REGION = @HOPE_REGION,
			TRAVEL_TYPE = @TRAVEL_TYPE,
			INFLOW_ROUTE = @INFLOW_ROUTE 
		WHERE
			CUS_NO = @CUS_NO
	END 

	
END

GO
