USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/* ==========================================================================================
-- DESCRIPTION:	<G마켓 상품연동 XML 생성 GProductMakeXML.exe >
--		
-- CREATE DATE: <2010-09-15>
-- AUTHOR:		<박형만>
-- EXEC SP_PKG_MASTER_SELECT_PRODUCT_GMARKET 14
-- EDIT DATE:  

2010-11-22 국내 크루즈 상품 KPP120 G마켓 해외 크루즈 카테고리로(E-7) 넣기 추가 
2011-01-10 해외자유여행(E-1) 카테고리에 대표속성 항공+호텔,호텔팩,에어텔,티켓(B,H,I,T 추가 ) 
2011-03-09 AFF_TYPE  => PROVIDER 로변경 @PROVIDER 파라미터추가
2013-08-02 지마켓 국내 카테고리 다시 설정 , USE_YN  조건 추가 
2013-12-12 이미지업데이트 여부 IMAGE_UPDATE_STATUS 필드 추가 
2016-02-12 --사용안함
-- ==========================================================================================*/
CREATE PROC [dbo].[_SP_PKG_MASTER_SELECT_PRODUCT_GMARKET]
	@PROVIDER INT 
AS 
SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--DECLARE @AFF_TYPE INT 
--SET @AFF_TYPE = 1 

SELECT 
	GD_CD ,
	GD_NM ,
	DP_ST_DT , 
	DP_ED_DT ,
	DP_MIN_PRICE ,
	DP_MAX_PRICE ,
	REG_DT,
	CHG_DT,
	CONTENTS_PATH + BIG_IMG	 AS BIG_IMG ,
	CONTENTS_PATH + MIDDLE_IMG AS MIDDLE_IMG ,
	CONTENTS_PATH + SMALL_IMG AS SMALL_IMG,
	[STATUS],
	CASE WHEN SIGN_CODE <> 'K' THEN
		CASE WHEN ATT_CODE = 'P' THEN 'E-1' --해외패키지
			WHEN ATT_CODE IN('F','B','H','I','T')  THEN 'E-2' --해외자유여행
			WHEN ATT_CODE = 'V' THEN 'E-3' --해외패스/입장권
			
			WHEN ATT_CODE = 'W' THEN 'E-5'--해외허니문
			WHEN ATT_CODE = 'G' THEN 'E-6'--해외골프
			WHEN ATT_CODE = 'C' THEN 'E-7'--해외크루즈
			WHEN ATT_CODE = 'E' THEN 'E-8'--해외박람회
		ELSE 'E-1' END 
	ELSE 
		 CASE WHEN GD_CD = 'KPP120' THEN   'E-7' --국내 크루즈 상품 해외크루즈(E-7) 으로 예외처리
			WHEN PC.CITY_CODE = 'CJU' THEN 
				CASE  WHEN SUBSTRING(GD_CD ,3,1) = 'G' THEN 'G-2' 
					WHEN ATT_CODE = 'P' THEN 'J-1'
					WHEN ATT_CODE = 'F' THEN 'J-3'
				ELSE 'J-1' END 
		 END 
		--J-1: [제주도] 항공+숙박+버스관광
		--J-2: [제주도] 제주 골프/허니문여행
		--J-3: [제주도] 항공+숙박+렌터카
		--J-4: [제주도] 숙박/숙박+렌터카
		--J-5: [제주도] 지방출발 제주여행
	END AS GD_TYPE , 
	NATION ,
	PN.NATION_CODE AS COUNTRY_CD ,
	PN.KOR_NAME AS COUNTRY_NM ,
	PC.CITY_CODE AS CITY_CD ,
	PC.KOR_NAME AS CITY_NM ,
	'1' AS IMAGE_UPDATE_STATUS,
	'' CN_COMMS 

FROM 
( 
SELECT 
	UPPER(PM.MASTER_CODE)  AS GD_CD,
	PM.MASTER_NAME  AS GD_NM,
	--CONVERT(VARCHAR(10),PM.NEXT_DATE,121) AS DP_ST_DT,
	CASE WHEN PM.NEXT_DATE > DATEADD(DD,-1,GETDATE()) THEN CONVERT(VARCHAR(10),DATEADD(DD,-1,GETDATE()) ,121)
		ELSE CONVERT(VARCHAR(10),DATEADD(DD,-1,PM.NEXT_DATE) ,121)  END AS DP_ST_DT ,
	CONVERT(VARCHAR(10), DATEADD(DD, PM.TOUR_DAY ,PM.LAST_DATE) ,121) AS DP_ED_DT, --도착일까지는 전시
	PM.LOW_PRICE  AS DP_MIN_PRICE ,
	PM.HIGH_PRICE  AS DP_MAX_PRICE ,
	IFM.REGION_CODE +'/'+
	IFM.NATION_CODE +'/'+
	IFM.STATE_CODE +'/'+
	IFM.CITY_CODE +'/'+
	+ CASE WHEN IFM.FILE_TYPE = 1  THEN 'image'
		WHEN IFM.FILE_TYPE = 2  THEN 'movie'
		WHEN IFM.FILE_TYPE = 3 THEN 'document' 
	ELSE 'image' END  + '/'  AS CONTENTS_PATH ,
	IFM.[FILE_NAME] + '.' + IFM.EXTENSION_NAME AS [FILE_NAME] , 
	CASE WHEN ISNULL(IFM.[FILE_NAME_S],'') ='' THEN IFM.[FILE_NAME] + '.' + IFM.EXTENSION_NAME  ELSE IFM.[FILE_NAME_S] END AS SMALL_IMG,
	CASE WHEN ISNULL(IFM.[FILE_NAME_M],'') ='' THEN IFM.[FILE_NAME] + '.' + IFM.EXTENSION_NAME  ELSE IFM.[FILE_NAME_M] END AS MIDDLE_IMG,
	CASE WHEN ISNULL(IFM.[FILE_NAME_L],'') ='' THEN IFM.[FILE_NAME] + '.' + IFM.EXTENSION_NAME  ELSE IFM.[FILE_NAME_L] END AS BIG_IMG,
	
	CONVERT(VARCHAR(19),PM.NEW_DATE,121) AS REG_DT,
	CONVERT(VARCHAR(19),(CASE WHEN PMA.NEW_DATE > PM.EDT_DATE OR PM.EDT_DATE IS NULL THEN PMA.NEW_DATE ELSE PM.EDT_DATE  END) ,121) AS CHG_DT ,

	-- 제휴사 상품등록 제외 하거나 , 마스터 상품 보이지 않게 했을땐 판매중지
	CASE WHEN PM.SHOW_YN  = 'Y' AND PMA.USE_YN = 'Y' THEN '1' ELSE '2' END AS [STATUS] , 
	CASE WHEN PM.SIGN_CODE = 'K' THEN '1' ELSE '2' END AS NATION ,
	
	--PN.NATION_CODE AS COUNTRY_CD,
	--PN.KOR_NAME AS COUNTRY_NM,
	--PC.CITY_CODE AS CITY_CD,
	--PC.KOR_NAME AS CITY_NM
	
	DBO.XN_PRO_GET_PKG_MASTER_FIRST_MAIN_CITY(PM.MASTER_CODE) AS CITY_CODE,
	--(SELECT TOP 1 CITY_CODE FROM PKG_MASTER_SCH_CITY AS PMSC WITH(NOLOCK) 
	--WHERE PM.MASTER_CODE = PMSC.MASTER_CODE 
	--AND PMSC.MAINCITY_YN = 'Y' 
	--AND PMSC.CITY_CODE NOT IN('ICN','PUS','GMP')
	--ORDER BY CITY_SHOW_ORDER ASC ) AS CITY_CODE ,

	PM.SIGN_CODE , 
	PM.ATT_CODE
FROM PKG_MASTER AS PM WITH(NOLOCK)
	
		
	--G상품은 마스터 이미지정보 반드시 있어야함 - 사전공지 AND ERP 시스템 체크 
	INNER JOIN PKG_FILE_MANAGER AS PFM WITH(NOLOCK )
		ON PM.MASTER_CODE = PFM.MASTER_CODE
		AND PFM.FILE_CODE = ( SELECT TOP 1 S1.FILE_CODE FROM PKG_FILE_MANAGER AS S1 WITH(NOLOCK)
						INNER JOIN INF_FILE_MASTER AS S2 WITH(NOLOCK)
							ON S1.FILE_CODE = S2.FILE_CODE 
						WHERE S1.MASTER_CODE = PFM.MASTER_CODE 
						AND S2.SHOW_YN = 'Y'
						ORDER BY SHOW_ORDER ) 
	INNER JOIN INF_FILE_MASTER AS IFM WITH(NOLOCK)
		ON PFM.FILE_CODE = IFM.FILE_CODE
		
	INNER JOIN PKG_MASTER_AFFILIATE AS PMA WITH(NOLOCK)
		ON PM.MASTER_CODE = PMA.MASTER_CODE 
		--AND PMA.AFF_TYPE = 1 -- G마켓 
		AND PMA.PROVIDER = @PROVIDER -- G마켓 
		
	--G상품은 MAINCITY는 반드시 넣어주어야함! -사전공지 AND ERP 시스템 체크 
	--* 항상 스케쥴은 1번으로 
	--* MAINCITY 는 무조건 한개
	--LEFT JOIN PKG_MASTER_SCH_CITY AS PMSC WITH(NOLOCK)
	--	ON PM.MASTER_CODE = PMSC.MASTER_CODE 
	--	AND PMSC.CITY_CODE = ( SELECT TOP 1 S1.CITY_CODE FROM PKG_MASTER_SCH_CITY AS S1 WITH(NOLOCK)
	--							WHERE S1.MASTER_CODE = PMSC.MASTER_CODE 
	--							AND S1.SCH_SEQ = 1 
	--							AND S1.MAINCITY_YN = 'Y' 
	--							ORDER BY DAY_SEQ, CITY_SEQ , CITY_SHOW_ORDER )
	--	AND PMSC.SCH_SEQ = 1 	
	--	AND PMSC.MAINCITY_YN = 'Y' 			

--WHERE PMA.USE_YN = 'Y' 
	
) TBL 

LEFT JOIN PUB_CITY AS PC WITH(NOLOCK)
	ON TBL.CITY_CODE = PC.CITY_CODE
LEFT JOIN PUB_NATION AS PN WITH(NOLOCK)
	ON PC.NATION_CODE = PN.NATION_CODE
GO
