USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*================================================================================================================
■ USP_NAME					: XP_COM_RES_HOTEL_INFO_SELECT
■ DESCRIPTION				: 예약된 상품 정보 OR 상품정보 보기 
■ INPUT PARAMETER			:
■ OUTPUT PARAMETER			: 
■ EXEC						: 
	EXEC XP_COM_RES_ETC_SELECT '92756 ','RP1601047819',100

■ MEMO						: 
------------------------------------------------------------------------------------------------------------------
■ CHANGE HISTORY                   
------------------------------------------------------------------------------------------------------------------
   DATE					AUTHOR				DESCRIPTION           
------------------------------------------------------------------------------------------------------------------
   2016-03-08		저스트고 - 백경훈		최초생성
   2016-05-26		김성호					김성호
================================================================================================================*/ 
CREATE PROC [dbo].[XP_COM_RES_ETC_SELECT]
	@AGT_CODE VARCHAR(10),
	@RES_CODE VARCHAR(20),
	@NEW_SEQ INT
AS 
BEGIN
	WITH AGT_BIZTRIP_LIST AS 
	(
		SELECT top 1 A.AGT_CODE,A.BT_CODE, A.BT_START_DATE, A.BT_END_DATE, A.BT_REASON,  B.RES_CODE, 
		A.BT_TIME_LIMIT, A.NEW_DATE, A.NEW_SEQ, C.KOR_NAME AS EMP_NAME,
		D.HOTEL_LIKE_YN, D.HOTEL_DISLIKE_YN,  D.HOTEL_PRICE_LIMIT, D.REASON_SEQ, D.REASON_REMARK
		FROM 
		COM_BIZTRIP_MASTER A
		JOIN COM_BIZTRIP_DETAIL B
		ON A.BT_CODE = B.BT_CODE
		AND A.AGT_CODE = @AGT_CODE
		AND A.NEW_SEQ = @NEW_SEQ
		AND B.RES_CODE = @RES_CODE
		JOIN COM_EMPLOYEE C
		ON A.NEW_SEQ = C.EMP_SEQ
		LEFT JOIN COM_BIZTRIP_RULE_REMARK D
		ON B.RES_CODE = D.RES_CODE
	)
	--예약 정보
	SELECT  ABL.AGT_CODE,ABL.BT_CODE, ABL.BT_START_DATE, ABL.BT_END_DATE, ABL.BT_REASON,ABL.RES_CODE,
        ABL.BT_TIME_LIMIT, ABL.NEW_DATE, ABL.NEW_SEQ, ABL.EMP_NAME,
		ABL.HOTEL_LIKE_YN, ABL.HOTEL_DISLIKE_YN,  ABL.HOTEL_PRICE_LIMIT, ABL.REASON_SEQ, ABL.REASON_REMARK,
	CASE WHEN A.PRO_TYPE = 2 THEN 1 WHEN A.PRO_TYPE = 3 THEN 2 
		WHEN A.PRO_NAME LIKE '%비자%' THEN 3 
		WHEN A.PRO_tYPE LIKE '%렌터카%' THEN 4
		WHEN A.PRO_TYPE LIKE '%기타예약%' THEN 5
		ELSE 6 END AS PRO_TYPE,		
		A.RES_STATE , 
		A.RES_CODE, A.PRO_NAME, A.PRO_CODE,A.PRICE_SEQ , A.NEW_DATE , 
		A.CUS_NO , A.RES_NAME, A.NOR_TEL1 , A.NOR_TEL2 , A.NOR_TEL3 , A.RES_EMAIL , A.BIRTH_DATE, 
		case when A.GENDER ='F' then '女' else '男' end as GENDER,  
		dbo.FN_RES_GET_RES_AGE_COUNT(A.RES_CODE, 0) AS ADULT_COUNT,
		dbo.FN_RES_GET_RES_AGE_COUNT(A.RES_CODE, 1) AS CHILD_COUNT,
		dbo.FN_RES_GET_RES_AGE_COUNT(A.RES_CODE, 2) AS INFANT_COUNT,
		DBO.FN_RES_HTL_GET_TOTAL_PRICE(A.RES_CODE)  AS TOTAL_PRICE,
		DBO.FN_RES_GET_PAY_PRICE(A.RES_CODE) AS PAY_PRICE,
		A.LAST_PAY_DATE, A.CUS_REQUEST, A.CUS_RESPONSE,
		C.EMP_CODE, C.KOR_NAME, C.INNER_NUMBER1, C.INNER_NUMBER2, C.INNER_NUMBER3, 
		C.FAX_NUMBER1, C.FAX_NUMBER2, C.FAX_NUMBER3, C.EMAIL AS EMP_EMAIL, C.GREETING , 
		C.TEAM_CODE , DBO.XN_COM_GET_TEAM_NAME(C.EMP_CODE)  AS TEAM_NAME  ,
		( SELECT KEY_NUMBER FROM EMP_TEAM WITH(NOLOCK) WHERE TEAM_CODE = C.TEAM_CODE )  AS KEY_NUMBER 
	FROM RES_MASTER_damo A WITH(NOLOCK)	
	INNER JOIN  AGT_BIZTRIP_LIST ABL WITH(NOLOCK)
	ON ABL.RES_CODE = A.RES_CODE
		LEFT JOIN EMP_MASTER C WITH(NOLOCK) 
			ON A.NEW_CODE = C.EMP_CODE
	AND A.RES_CODE = @RES_CODE
	ORDER BY A.RES_CODE DESC

END
GO
