USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*================================================================================================================
■ USP_NAME					: [XP_COM_EMPLOYEE_EXCEL_INSERT]
■ DESCRIPTION				: 엑셀 업로드
■ INPUT PARAMETER			: 
■ OUTPUT PARAMETER			: 

■ EXEC						: 
	EXEC XP_COM_EMPLOYEE_EXCEL_INSERT '93874','TEST123','서울본사','서울본사','강윤석','','','1979-01-01','M','00BE2177387A08B042CB56EB822D57A571913029','--','--','--','','test@naver.com','대리','1','9999999'

■ MEMO						: 
------------------------------------------------------------------------------------------------------------------
■ CHANGE HISTORY                   
------------------------------------------------------------------------------------------------------------------
   DATE				AUTHOR			DESCRIPTION           
------------------------------------------------------------------------------------------------------------------
   2013-04-14		저스트고-백경훈			최초생성
   2017-12-07		박형만				정렬
================================================================================================================*/ 
CREATE PROCEDURE [dbo].[XP_COM_EMPLOYEE_EXCEL_INSERT]
(
	@AGT_CODE			VARCHAR(10),
	@EMP_ID				VARCHAR(20),
	@PARENTTEAM_NAME	VARCHAR(20),
	@TEAM_NAME			VARCHAR(20),
	@KOR_NAME			VARCHAR(20),
	@LAST_NAME			VARCHAR(20),
	@FIRST_NAME			VARCHAR(30),
	@BIRTH_DATE			DATE,
	@GENDER				CHAR(1),
	@PASSWORD			VARCHAR(100),
	@HP_NUMBER			VARCHAR(20),
	@COM_NUMBER			VARCHAR(20),
	@FAX_NUMBER			VARCHAR(20),
	@JOIN_DATE			DATETIME,
	@EMAIL				VARCHAR(50),
	@POS_NAME			VARCHAR(20),
	@WORK_TYPE			INT,
	@NEW_SEQ			INT
)
AS

BEGIN


--exec XP_COM_EMPLOYEE_EXCEL_INSERT

--declare 	@AGT_CODE			VARCHAR(10),
--	@EMP_ID				VARCHAR(20),
--	@PARENTTEAM_NAME	VARCHAR(20),
--	@TEAM_NAME			VARCHAR(20),
--	@KOR_NAME			VARCHAR(20),
--	@LAST_NAME			VARCHAR(20),
--	@FIRST_NAME			VARCHAR(30),
--	@BIRTH_DATE			DATE,
--	@GENDER				CHAR(1),
--	@PASSWORD			VARCHAR(100),
--	@HP_NUMBER			VARCHAR(20),
--	@COM_NUMBER			VARCHAR(20),
--	@FAX_NUMBER			VARCHAR(20),
--	@JOIN_DATE			DATETIME,
--	@EMAIL				VARCHAR(50),
--	@POS_NAME			VARCHAR(20),
--	@WORK_TYPE			INT,
--	@NEW_SEQ			INT
--select  @AGT_CODE='92524',@EMP_ID='shinwonsoo',@PARENTTEAM_NAME=N'AdvisoryCommittee',@TEAM_NAME=N'임원실',@KOR_NAME='신원수',@LAST_NAME=NULL,@FIRST_NAME=NULL,@BIRTH_DATE='1963-01-14 00:00:00',@GENDER='M',@PASSWORD='93948832D9E52BC8023633FD192DA120C4C5B281',@POS_NAME=N'임원',@WORK_TYPE=N'1',@JOIN_DATE='1900-01-01 00:00:00',@EMAIL='shinwonsoo@iloen.com',@COM_NUMBER='02-2280-7711',@HP_NUMBER='010-3644-6011',@FAX_NUMBER='--',@NEW_SEQ=2013007

DECLARE @EMP_INSSEQ INT
DECLARE @EMP_UPDSEQ INT
DECLARE @PARENTTEAM_SEQ INT
DECLARE @TEAM_SEQ INT
DECLARE @POS_SEQ INT 
DECLARE @ORDER_NUM INT
DECLARE @EMP_IDX VARCHAR(30)
DECLARE @EMP_UPDID VARCHAR(30)
DECLARE @EMP_UPDIDCHK VARCHAR(10)


	SET @EMP_UPDSEQ = (ISNULL((SELECT EMP_SEQ FROM COM_EMPLOYEE A WITH(NOLOCK) WHERE A.AGT_CODE = @AGT_CODE AND KOR_NAME = @KOR_NAME AND BIRTH_DATE = @BIRTH_DATE AND GENDER = @GENDER), 0) )
	SET @EMP_UPDID =  (ISNULL((SELECT EMP_ID FROM COM_EMPLOYEE A WITH(NOLOCK) WHERE A.AGT_CODE = @AGT_CODE AND EMP_ID = @EMP_ID), 'N') )
	SET @EMP_INSSEQ = (ISNULL((SELECT MAX(EMP_SEQ) FROM COM_EMPLOYEE A WITH(NOLOCK) WHERE A.AGT_CODE = @AGT_CODE ), 0) + 1)

	SET @PARENTTEAM_SEQ = (ISNULL((select TOP 1 TEAM_SEQ from COM_TEAM WHERE TEAM_NAME = @PARENTTEAM_NAME and  AGT_CODE = @AGT_CODE ),0))
	IF @PARENTTEAM_SEQ = 0
	BEGIN
		SET @PARENTTEAM_SEQ = (ISNULL((select MAX(TEAM_SEQ) from COM_TEAM where AGT_CODE = @AGT_CODE  ),0) + 1)
		--print @PARENTTEAM_SEQ
		IF @PARENTTEAM_NAME != '' 
		BEGIN
			INSERT INTO COM_TEAM(AGT_CODE,TEAM_SEQ, TEAM_NAME, PARENT_TEAM_SEQ, ORDER_NUM, USE_YN, NEW_DATE, NEW_SEQ)
			VALUES(@AGT_CODE,@PARENTTEAM_SEQ, @PARENTTEAM_NAME, 0, 1, 'Y', GETDATE(), @NEW_SEQ) 
		END
	END 
	ELSE
	BEGIN
		SET @PARENTTEAM_SEQ = @PARENTTEAM_SEQ
	END

	SET @TEAM_SEQ = (ISNULL((select TOP(1) TEAM_SEQ from COM_TEAM WHERE TEAM_NAME = @TEAM_NAME AND PARENT_TEAM_SEQ = @PARENTTEAM_SEQ and AGT_CODE = @AGT_CODE),1))
	--Print @TEAM_SEQ
	IF @TEAM_SEQ = 1
	BEGIN
		IF @TEAM_NAME != '' 
		BEGIN
			SET @TEAM_SEQ = (ISNULL((select MAX(TEAM_SEQ) from COM_TEAM where AGT_CODE = @AGT_CODE),1) + 1)
			INSERT INTO COM_TEAM(AGT_CODE,TEAM_SEQ, TEAM_NAME, PARENT_TEAM_SEQ, ORDER_NUM, USE_YN, NEW_DATE, NEW_SEQ)
			VALUES(@AGT_CODE,@TEAM_SEQ, @TEAM_NAME, @PARENTTEAM_SEQ, 1, 'Y', GETDATE(), @NEW_SEQ) 
		END
	END 
	ELSE
	BEGIN
		SET @TEAM_SEQ = @TEAM_SEQ
	END

	SET @POS_SEQ =(ISNULL((SELECT max(POS_SEQ) FROM COM_POSITION WHERE AGT_CODE = @AGT_CODE AND POS_NAME = @POS_NAME), 0))
	IF @POS_SEQ = 0
	BEGIN 
		SET @POS_SEQ = (ISNULL((select MAX(POS_SEQ) from COM_POSITION WHERE AGT_CODE = @AGT_CODE),1) + 1)
		SET @ORDER_NUM = (ISNULL((select MAX(ORDER_NUM) from COM_POSITION WHERE  AGT_CODE = @AGT_CODE),1) + 1)
		INSERT INTO COM_POSITION(AGT_CODE,POS_SEQ, POS_NAME, ORDER_NUM, NEW_DATE, NEW_SEQ)
		VALUES(@AGT_CODE,@POS_SEQ, @POS_NAME, @ORDER_NUM, GETDATE(), @NEW_SEQ) 
	END
	ELSE
	BEGIN
		SET @POS_SEQ = @POS_SEQ
	END


	DECLARE @RET_CODE INT 
	SET @RET_CODE = 0 

	SET @EMP_IDX = (ISNULL((SELECT EMP_ID FROM COM_EMPLOYEE WHERE AGT_CODE = @AGT_CODE AND EMP_ID = @EMP_ID and EMP_ID <> ''), 'N'))
	IF @EMP_IDX = 'N'
	BEGIN
		SET @EMP_UPDIDCHK =  (ISNULL((SELECT count(EMP_SEQ) FROM COM_EMPLOYEE WHERE AGT_CODE = @AGT_CODE  AND KOR_NAME = @KOR_NAME AND BIRTH_DATE = @BIRTH_DATE AND GENDER = @GENDER), 0))
		IF @EMP_UPDIDCHK= 0
		BEGIN
			INSERT INTO COM_EMPLOYEE (AGT_CODE, EMP_SEQ, TEAM_SEQ, EMP_ID, KOR_NAME, LAST_NAME, FIRST_NAME, BIRTH_DATE, GENDER, PASS_WORD, POS_SEQ, WORK_TYPE, JOIN_DATE, OUT_DATE
			, EMAIL, COM_NUMBER, HP_NUMBER, FAX_NUMBER, FAIL_COUNT, NEW_DATE, NEW_SEQ)
			SELECT @AGT_CODE, @EMP_INSSEQ, @TEAM_SEQ, @EMP_ID, @KOR_NAME, @LAST_NAME, @FIRST_NAME, @BIRTH_DATE, @GENDER, @PASSWORD, @POS_SEQ, @WORK_TYPE, @JOIN_DATE, NULL
				, @EMAIL, @COM_NUMBER, @HP_NUMBER, @FAX_NUMBER, 0, GETDATE(), @NEW_SEQ	

			SET @RET_CODE =  1 

		END 
		ELSE
		BEGIN
			UPDATE COM_EMPLOYEE SET EMP_ID = @EMP_ID, PASS_WORD = @PASSWORD, KOR_NAME = @KOR_NAME, LAST_NAME = @LAST_NAME, FIRST_NAME = @FIRST_NAME, BIRTH_DATE = @BIRTH_DATE, GENDER = @GENDER
			, HP_NUMBER = @HP_NUMBER, COM_NUMBER = @COM_NUMBER, FAX_NUMBER = @FAX_NUMBER, JOIN_DATE = @JOIN_DATE, EMAIL = @EMAIL
			, TEAM_SEQ = @TEAM_SEQ, POS_SEQ = @POS_SEQ, WORK_TYPE = @WORK_TYPE
			, EDT_DATE = GETDATE(), EDT_SEQ = @NEW_SEQ
			WHERE AGT_CODE = @AGT_CODE AND EMP_SEQ = @EMP_UPDSEQ;

			SET @RET_CODE =  2 
		END
	END
	ELSE
	BEGIN
		UPDATE COM_EMPLOYEE SET EMP_ID = @EMP_ID,  PASS_WORD = @PASSWORD, KOR_NAME = @KOR_NAME, LAST_NAME = @LAST_NAME, FIRST_NAME = @FIRST_NAME, BIRTH_DATE = @BIRTH_DATE, GENDER = @GENDER
			, HP_NUMBER = @HP_NUMBER, COM_NUMBER = @COM_NUMBER, FAX_NUMBER = @FAX_NUMBER, JOIN_DATE = @JOIN_DATE, EMAIL = @EMAIL
			, TEAM_SEQ = @TEAM_SEQ, POS_SEQ = @POS_SEQ, WORK_TYPE = @WORK_TYPE
			, EDT_DATE = GETDATE(), EDT_SEQ = @NEW_SEQ
		WHERE AGT_CODE = @AGT_CODE AND EMP_ID = @EMP_UPDID;

		SET @RET_CODE =  3 
	END

	SELECT @RET_CODE
END
GO
