USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_LOG_INFLOW_ERP_INSERT]
	@START_TIME		DATETIME,
	@END_TIME		DATETIME,
	@LOAD_TIME		DECIMAL,
	@IN_IP			VARCHAR(20),
	@IN_PATH		VARCHAR(200),
	@IN_QUERY		VARCHAR(200),
	@IN_POST		VARCHAR(4000),
	@EMP_CODE		VARCHAR(10)
AS
BEGIN
	INSERT INTO VGLog.dbo.SYS_INFLOW_ERP_LOG (
		START_TIME,		END_TIME,		LOAD_TIME,			IN_IP,		IN_PATH,
		IN_POST,		IN_QUERY,		IN_DATE,			EMP_CODE
	) VALUES (
		@START_TIME,	@END_TIME,		@LOAD_TIME,			@IN_IP,		@IN_PATH,
		@IN_POST,		@IN_QUERY,		GETDATE(),			@EMP_CODE
	)
END
GO
