USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


/*================================================================================================================
■ USP_NAME					: XP_ARG_LAND_DETAIL_SELECT
■ DESCRIPTION				: 랜드 평가 상세
■ INPUT PARAMETER			: 
■ OUTPUT PARAMETER			: 
■ EXEC						: 

	EXEC DBO.XP_ARG_LAND_DETAIL_SELECT '92685', '2013'
■ MEMO						: 
------------------------------------------------------------------------------------------------------------------
■ CHANGE HISTORY                   
------------------------------------------------------------------------------------------------------------------
   DATE				AUTHOR			DESCRIPTION           
------------------------------------------------------------------------------------------------------------------
   2013-07-22		김완기			
================================================================================================================*/ 
CREATE PROC [dbo].[XP_ARG_LAND_DETAIL_SELECT]
 	@AGT_CODE varchar(10),
	@DEP_YEAR varchar(4)
AS 
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED	

	-- 평가요약	
    SELECT AGT_CODE, MAX(KOR_NAME) AS AGT_NAME, AVG(AVG_NUM) AS AVG_NUM, MAX(LAST_DEP_DATE) AS LAST_DEP_DATE, MAX(AGT_GRADE) AS AGT_GRADE,
			(SELECT COUNT(MEM_CODE) FROM AGT_MEMBER WITH(NOLOCK) WHERE MEM_TYPE = '1' AND AGT_CODE = A.AGT_CODE) AS GUIDE_COUNT,
			(SELECT COUNT(DISTINCT(G.PRO_CODE))
				FROM OTR_POL_MASTER F WITH(NOLOCK) 
				INNER JOIN OTR_MASTER G WITH(NOLOCK) ON (F.OTR_SEQ = G.OTR_SEQ AND G.OTR_STATE = '3')
				WHERE F.AGT_CODE = A.AGT_CODE ) AS G_COUNT,
			(SELECT COUNT(H.RES_CODE) 
				FROM dbo.Res_master_damo H WITH(NOLOCK)
				LEFT OUTER JOIN dbo.RES_CUSTOMER_damo I WITH(NOLOCK) ON H.RES_CODE = I.RES_CODE
				WHERE H.PRO_CODE IN (SELECT DISTINCT(G.PRO_CODE)
									FROM OTR_POL_MASTER F WITH(NOLOCK) 
									INNER JOIN OTR_MASTER G WITH(NOLOCK) ON (F.OTR_SEQ = G.OTR_SEQ AND G.OTR_STATE = '3')
									WHERE F.AGT_CODE = A.AGT_CODE)) AS RESCUSTOMERCOUNT,
			(SELECT ISNULL(SUM(E.ADT_PRICE), 0) + ISNULL(SUM(E.CHD_PRICE), 0) + ISNULL(SUM(E.INF_PRICE), 0) 
				FROM ARG_MASTER C WITH(NOLOCK) 
				--INNER JOIN ARG_DETAIL D ON (C.ARG_SEQ_NO = D.ARG_SEQ_NO AND D.ARG_TYPE ='2' AND D.ARG_DETAIL_STATUS = '5')
				INNER JOIN ARG_DETAIL D WITH(NOLOCK) ON (C.ARG_CODE = D.ARG_CODE AND D.ARG_TYPE ='4')
				INNER JOIN ARG_INVOICE_DETAIL E WITH(NOLOCK) ON (C.ARG_CODE = E.ARG_CODE AND D.GRP_SEQ_NO = E.GRP_SEQ_NO)
				WHERE C.AGT_CODE = A.AGT_CODE) AS PRICE_TOTAL
		FROM (
 			SELECT A.AGT_CODE,
					MAX(C.PRO_CODE) AS PRO_CODE,
					B.KOR_NAME, 
					ISNULL(A.MEM_CODE, '') AS MEM_CODE, 
					A.GUIDE_NAME,
					(SELECT ROUND((SUM(CONVERT(INT,L.EXAMPLE_DESC)) / CONVERT(FLOAT,COUNT(K.OTR_POL_EXAMPLE_SEQ))),1)
						FROM OTR_MASTER H WITH(NOLOCK)
						INNER JOIN dbo.OTR_POL_MASTER I WITH(NOLOCK) ON H.OTR_SEQ = I.OTR_SEQ AND I.POL_TYPE ='2'
						INNER JOIN dbo.OTR_POL_QUESTION J WITH(NOLOCK) ON I.OTR_POL_MASTER_SEQ = J.OTR_POL_MASTER_SEQ AND J.QUS_TYPE='1'
						INNER JOIN dbo.OTR_POL_ANSWER K WITH(NOLOCK) ON J.OTR_POL_MASTER_SEQ = K.OTR_POL_MASTER_SEQ AND J.OTR_POL_QUESTION_SEQ = K.OTR_POL_QUESTION_SEQ
						INNER JOIN dbo.OTR_POL_DETAIL L WITH(NOLOCK) ON K.OTR_POL_MASTER_SEQ = L.OTR_POL_MASTER_SEQ AND K.OTR_POL_QUESTION_SEQ = L.OTR_POL_QUESTION_SEQ AND K.OTR_POL_EXAMPLE_SEQ =L.OTR_POL_EXAMPLE_SEQ 
						WHERE H.OTR_STATE = '3' AND I.AGT_CODE = A.AGT_CODE AND ISNULL(I.MEM_CODE, '') = ISNULL(A.MEM_CODE, '') AND I.GUIDE_NAME = A.GUIDE_NAME) AS AVG_NUM ,
					(SELECT TOP 1 Z.SIGN_CODE   
						FROM PKG_DETAIL Y WITH(NOLOCK) 
						INNER JOIN PKG_MASTER Z WITH(NOLOCK) ON Y.MASTER_CODE = Z.MASTER_CODE
						WHERE Y.PRO_CODE = MAX(C.PRO_CODE)) AS SIGN_CODE,
					(SELECT COUNT(H.RES_CODE) 
						FROM dbo.Res_master_damo H WITH(NOLOCK)
						LEFT OUTER JOIN dbo.RES_CUSTOMER_damo I WITH(NOLOCK) ON H.RES_CODE = I.RES_CODE
						WHERE H.PRO_CODE = MAX(C.PRO_CODE)) AS RESCUSTOMERCOUNT,
					(SELECT DEP_DATE FROM PKG_DETAIL WITH(NOLOCK) WHERE PRO_CODE = MAX(C.PRO_CODE)) AS LAST_DEP_DATE,
					MAX(B.AGT_GRADE) AS AGT_GRADE
			FROM OTR_POL_MASTER A WITH(NOLOCK)
			INNER JOIN OTR_MASTER C WITH(NOLOCK) ON (A.OTR_SEQ = C.OTR_SEQ AND C.OTR_STATE = '3')
			INNER JOIN AGT_MASTER B WITH(NOLOCK) ON A.AGT_CODE = B.AGT_CODE
			INNER JOIN PKG_DETAIL D WITH(NOLOCK) ON C.PRO_CODE = D.PRO_CODE
			INNER JOIN PKG_MASTER E WITH(NOLOCK) ON D.MASTER_CODE = E.MASTER_CODE
			WHERE A.POL_type ='2'
			GROUP BY A.AGT_CODE, ISNULL(A.MEM_CODE, ''), A.GUIDE_NAME, B.KOR_NAME ) A
		WHERE AGT_CODE = @AGT_CODE
        GROUP BY AGT_CODE
		
		
	-- 세부평가	
    SELECT
	   ISNULL((SELECT  AVG(CONVERT(float,E.EXAMPLE_DESC))
		         FROM  dbo.OTR_MASTER A WITH(NOLOCK)
		        INNER  JOIN dbo.OTR_POL_MASTER B WITH(NOLOCK) ON (A.OTR_SEQ = B.OTR_SEQ AND B.POL_TYPE ='2' AND B.AGT_CODE = @AGT_CODE)
		        INNER  JOIN dbo.OTR_POL_QUESTION C WITH(NOLOCK) ON (B.OTR_POL_MASTER_SEQ = C.OTR_POL_MASTER_SEQ AND C.QUS_TYPE='1')
		        INNER  JOIN dbo.OTR_POL_ANSWER D WITH(NOLOCK) ON (C.OTR_POL_MASTER_SEQ = D.OTR_POL_MASTER_SEQ AND C.OTR_POL_QUESTION_SEQ = D.OTR_POL_QUESTION_SEQ)
		        INNER  JOIN dbo.OTR_POL_DETAIL E WITH(NOLOCK) ON (D.OTR_POL_MASTER_SEQ = E.OTR_POL_MASTER_SEQ AND D.OTR_POL_QUESTION_SEQ = E.OTR_POL_QUESTION_SEQ AND D.OTR_POL_EXAMPLE_SEQ =E.OTR_POL_EXAMPLE_SEQ )
		        GROUP  BY B.AGT_CODE), 0) AS Avg_Leader_Guide,
	   ISNULL((SELECT  AVG(CONVERT(float,E.EXAMPLE_DESC))
		         FROM  dbo.OTR_MASTER A WITH(NOLOCK)
		        INNER  JOIN dbo.OTR_POL_MASTER B WITH(NOLOCK) ON (A.OTR_SEQ = B.OTR_SEQ AND B.POL_TYPE ='3' AND B.AGT_CODE = @AGT_CODE)
		        INNER  JOIN dbo.OTR_POL_QUESTION C WITH(NOLOCK) ON (B.OTR_POL_MASTER_SEQ = C.OTR_POL_MASTER_SEQ AND C.QUS_TYPE='1')
		        INNER  JOIN dbo.OTR_POL_ANSWER D WITH(NOLOCK) ON (C.OTR_POL_MASTER_SEQ = D.OTR_POL_MASTER_SEQ AND C.OTR_POL_QUESTION_SEQ = D.OTR_POL_QUESTION_SEQ)
		        INNER  JOIN dbo.OTR_POL_DETAIL E WITH(NOLOCK) ON (D.OTR_POL_MASTER_SEQ = E.OTR_POL_MASTER_SEQ AND D.OTR_POL_QUESTION_SEQ = E.OTR_POL_QUESTION_SEQ AND D.OTR_POL_EXAMPLE_SEQ =E.OTR_POL_EXAMPLE_SEQ )
		        GROUP  BY B.AGT_CODE), 0) AS Avg_Leader_Hotel,
	   ISNULL((SELECT  AVG(CONVERT(float,E.EXAMPLE_DESC))
		         FROM  dbo.OTR_MASTER A WITH(NOLOCK)
		        INNER  JOIN dbo.OTR_POL_MASTER B WITH(NOLOCK) ON (A.OTR_SEQ = B.OTR_SEQ AND B.POL_TYPE ='4' AND B.AGT_CODE = @AGT_CODE)
		        INNER  JOIN dbo.OTR_POL_QUESTION C WITH(NOLOCK) ON (B.OTR_POL_MASTER_SEQ = C.OTR_POL_MASTER_SEQ AND C.QUS_TYPE='1')
		        INNER  JOIN dbo.OTR_POL_ANSWER D WITH(NOLOCK) ON (C.OTR_POL_MASTER_SEQ = D.OTR_POL_MASTER_SEQ AND C.OTR_POL_QUESTION_SEQ = D.OTR_POL_QUESTION_SEQ)
		        INNER  JOIN dbo.OTR_POL_DETAIL E WITH(NOLOCK) ON (D.OTR_POL_MASTER_SEQ = E.OTR_POL_MASTER_SEQ AND D.OTR_POL_QUESTION_SEQ = E.OTR_POL_QUESTION_SEQ AND D.OTR_POL_EXAMPLE_SEQ =E.OTR_POL_EXAMPLE_SEQ )
		        GROUP  BY B.AGT_CODE), 0) AS Avg_Leader_Food,
	   -- 쿼리만 데이터 나올수 없음
	   ISNULL((SELECT  AVG(CONVERT(float,E.EXAMPLE_DESC))
		         FROM  dbo.OTR_MASTER A WITH(NOLOCK)
				 INNER  JOIN (
				   SELECT A.* FROM OTR_POL_MASTER A 
				   INNER JOIN (
						SELECT B.OTR_SEQ FROM OTR_MASTER A 
						INNER JOIN OTR_POL_MASTER B ON A.OTR_SEQ = B.OTR_SEQ
						GROUP BY B.OTR_SEQ, B.AGT_CODE HAVING B.AGT_CODE = @AGT_CODE
					) B ON A.OTR_SEQ = B.OTR_SEQ WHERE A.POL_TYPE = '5' AND A.CLIENT_CALL_YN ='Y'
				 ) B ON A.OTR_SEQ = B.OTR_SEQ
		        INNER  JOIN dbo.OTR_POL_QUESTION C WITH(NOLOCK) ON (B.OTR_POL_MASTER_SEQ = C.OTR_POL_MASTER_SEQ AND C.QUS_TYPE='1')
		        INNER  JOIN dbo.OTR_POL_ANSWER D WITH(NOLOCK) ON (C.OTR_POL_MASTER_SEQ = D.OTR_POL_MASTER_SEQ AND C.OTR_POL_QUESTION_SEQ = D.OTR_POL_QUESTION_SEQ AND D.OTR_POL_QUESTION_SEQ = '1')
		        INNER  JOIN dbo.OTR_POL_DETAIL E WITH(NOLOCK) ON (D.OTR_POL_MASTER_SEQ = E.OTR_POL_MASTER_SEQ AND D.OTR_POL_QUESTION_SEQ = E.OTR_POL_QUESTION_SEQ AND D.OTR_POL_EXAMPLE_SEQ =E.OTR_POL_EXAMPLE_SEQ )
		        GROUP  BY B.AGT_CODE), 0) AS Avg_Client_Guide,
	   ISNULL((SELECT  AVG(CONVERT(float,E.EXAMPLE_DESC))
		         FROM  dbo.OTR_MASTER A WITH(NOLOCK)
				 INNER  JOIN (
				   SELECT A.* FROM OTR_POL_MASTER A 
				   INNER JOIN (
						SELECT B.OTR_SEQ FROM OTR_MASTER A 
						INNER JOIN OTR_POL_MASTER B ON A.OTR_SEQ = B.OTR_SEQ
						GROUP BY B.OTR_SEQ, B.AGT_CODE HAVING B.AGT_CODE = @AGT_CODE
					) B ON A.OTR_SEQ = B.OTR_SEQ WHERE A.POL_TYPE = '5' AND A.CLIENT_CALL_YN ='Y'
				 ) B ON A.OTR_SEQ = B.OTR_SEQ
		        INNER  JOIN dbo.OTR_POL_QUESTION C WITH(NOLOCK) ON (B.OTR_POL_MASTER_SEQ = C.OTR_POL_MASTER_SEQ AND C.QUS_TYPE='1')
		        INNER  JOIN dbo.OTR_POL_ANSWER D WITH(NOLOCK) ON (C.OTR_POL_MASTER_SEQ = D.OTR_POL_MASTER_SEQ AND C.OTR_POL_QUESTION_SEQ = D.OTR_POL_QUESTION_SEQ AND D.OTR_POL_QUESTION_SEQ = '2')
		        INNER  JOIN dbo.OTR_POL_DETAIL E WITH(NOLOCK) ON (D.OTR_POL_MASTER_SEQ = E.OTR_POL_MASTER_SEQ AND D.OTR_POL_QUESTION_SEQ = E.OTR_POL_QUESTION_SEQ AND D.OTR_POL_EXAMPLE_SEQ =E.OTR_POL_EXAMPLE_SEQ )
		        GROUP  BY B.AGT_CODE), 0) AS Avg_Client_Hotel,
	   ISNULL((SELECT  AVG(CONVERT(float,E.EXAMPLE_DESC))
		         FROM  dbo.OTR_MASTER A WITH(NOLOCK)
				 INNER  JOIN (
				   SELECT A.* FROM OTR_POL_MASTER A 
				   INNER JOIN (
						SELECT B.OTR_SEQ FROM OTR_MASTER A 
						INNER JOIN OTR_POL_MASTER B ON A.OTR_SEQ = B.OTR_SEQ
						GROUP BY B.OTR_SEQ, B.AGT_CODE HAVING B.AGT_CODE = @AGT_CODE
					) B ON A.OTR_SEQ = B.OTR_SEQ WHERE A.POL_TYPE = '5' AND A.CLIENT_CALL_YN ='Y'
				 ) B ON A.OTR_SEQ = B.OTR_SEQ
		        INNER  JOIN dbo.OTR_POL_QUESTION C WITH(NOLOCK) ON (B.OTR_POL_MASTER_SEQ = C.OTR_POL_MASTER_SEQ AND C.QUS_TYPE='1')
		        INNER  JOIN dbo.OTR_POL_ANSWER D WITH(NOLOCK) ON (C.OTR_POL_MASTER_SEQ = D.OTR_POL_MASTER_SEQ AND C.OTR_POL_QUESTION_SEQ = D.OTR_POL_QUESTION_SEQ AND D.OTR_POL_QUESTION_SEQ = '3')
		        INNER  JOIN dbo.OTR_POL_DETAIL E WITH(NOLOCK) ON (D.OTR_POL_MASTER_SEQ = E.OTR_POL_MASTER_SEQ AND D.OTR_POL_QUESTION_SEQ = E.OTR_POL_QUESTION_SEQ AND D.OTR_POL_EXAMPLE_SEQ =E.OTR_POL_EXAMPLE_SEQ )
		        GROUP  BY B.AGT_CODE), 0) AS Avg_Client_Food
				/*
	   ISNULL((SELECT  AVG(CONVERT(float,E.EXAMPLE_DESC))
		         FROM  dbo.OTR_MASTER A WITH(NOLOCK)
		        INNER  JOIN dbo.OTR_POL_MASTER B WITH(NOLOCK) ON (A.OTR_SEQ = B.OTR_SEQ AND B.POL_TYPE ='5' AND B.CLIENT_CALL_YN ='Y' AND B.AGT_CODE = @AGT_CODE)
		        INNER  JOIN dbo.OTR_POL_QUESTION C WITH(NOLOCK) ON (B.OTR_POL_MASTER_SEQ = C.OTR_POL_MASTER_SEQ AND C.QUS_TYPE='1')
		        INNER  JOIN dbo.OTR_POL_ANSWER D WITH(NOLOCK) ON (C.OTR_POL_MASTER_SEQ = D.OTR_POL_MASTER_SEQ AND C.OTR_POL_QUESTION_SEQ = D.OTR_POL_QUESTION_SEQ AND D.OTR_POL_QUESTION_SEQ = '1')
		        INNER  JOIN dbo.OTR_POL_DETAIL E WITH(NOLOCK) ON (D.OTR_POL_MASTER_SEQ = E.OTR_POL_MASTER_SEQ AND D.OTR_POL_QUESTION_SEQ = E.OTR_POL_QUESTION_SEQ AND D.OTR_POL_EXAMPLE_SEQ =E.OTR_POL_EXAMPLE_SEQ )
		        GROUP  BY B.AGT_CODE), 0) AS Avg_Client_Guide,
				
	   ISNULL((SELECT  AVG(CONVERT(float,E.EXAMPLE_DESC))
		         FROM  dbo.OTR_MASTER A WITH(NOLOCK)
		        INNER  JOIN dbo.OTR_POL_MASTER B WITH(NOLOCK) ON (A.OTR_SEQ = B.OTR_SEQ AND B.POL_TYPE ='5' AND B.CLIENT_CALL_YN ='Y' AND B.AGT_CODE = @AGT_CODE)
		        INNER  JOIN dbo.OTR_POL_QUESTION C WITH(NOLOCK) ON (B.OTR_POL_MASTER_SEQ = C.OTR_POL_MASTER_SEQ AND C.QUS_TYPE='1')
		        INNER  JOIN dbo.OTR_POL_ANSWER D WITH(NOLOCK) ON (C.OTR_POL_MASTER_SEQ = D.OTR_POL_MASTER_SEQ AND C.OTR_POL_QUESTION_SEQ = D.OTR_POL_QUESTION_SEQ AND D.OTR_POL_QUESTION_SEQ = '2')
		        INNER  JOIN dbo.OTR_POL_DETAIL E WITH(NOLOCK) ON (D.OTR_POL_MASTER_SEQ = E.OTR_POL_MASTER_SEQ AND D.OTR_POL_QUESTION_SEQ = E.OTR_POL_QUESTION_SEQ AND D.OTR_POL_EXAMPLE_SEQ =E.OTR_POL_EXAMPLE_SEQ )
		        GROUP  BY B.AGT_CODE), 0) AS Avg_Client_Hotel,
	   ISNULL((SELECT  AVG(CONVERT(float,E.EXAMPLE_DESC))
		         FROM  dbo.OTR_MASTER A WITH(NOLOCK)
		        INNER  JOIN dbo.OTR_POL_MASTER B WITH(NOLOCK) ON (A.OTR_SEQ = B.OTR_SEQ AND B.POL_TYPE ='5' AND B.CLIENT_CALL_YN ='Y' AND B.AGT_CODE  = @AGT_CODE)
		        INNER  JOIN dbo.OTR_POL_QUESTION C WITH(NOLOCK) ON (B.OTR_POL_MASTER_SEQ = C.OTR_POL_MASTER_SEQ AND C.QUS_TYPE='1')
		        INNER  JOIN dbo.OTR_POL_ANSWER D WITH(NOLOCK) ON (C.OTR_POL_MASTER_SEQ = D.OTR_POL_MASTER_SEQ AND C.OTR_POL_QUESTION_SEQ = D.OTR_POL_QUESTION_SEQ AND D.OTR_POL_QUESTION_SEQ = '3')
		        INNER  JOIN dbo.OTR_POL_DETAIL E WITH(NOLOCK) ON (D.OTR_POL_MASTER_SEQ = E.OTR_POL_MASTER_SEQ AND D.OTR_POL_QUESTION_SEQ = E.OTR_POL_QUESTION_SEQ AND D.OTR_POL_EXAMPLE_SEQ =E.OTR_POL_EXAMPLE_SEQ )
		        GROUP  BY B.AGT_CODE), 0) AS Avg_Client_Food
				*/
			
	-- 월별평가		
    SELECT AGT_CODE, DEP_MONTH, MAX(KOR_NAME) AS AGT_NAME, AVG(AVG_NUM) AS AVG_NUM, MAX(LAST_DEP_DATE) AS LAST_DEP_DATE,
			(SELECT COUNT(DISTINCT(G.PRO_CODE))
				FROM OTR_POL_MASTER F WITH(NOLOCK) 
				INNER JOIN OTR_MASTER G WITH(NOLOCK) ON (F.OTR_SEQ = G.OTR_SEQ AND G.OTR_STATE = '3')
				INNER JOIN PKG_DETAIL H WITH(NOLOCK) ON G.PRO_CODE = H.PRO_CODE
				WHERE F.AGT_CODE = A.AGT_CODE AND SUBSTRING(CONVERT(VARCHAR(20), H.DEP_DATE, 112), 1, 6) =  DEP_MONTH) AS G_COUNT,
			(SELECT COUNT(H.RES_CODE) 
				FROM dbo.Res_master_damo H WITH(NOLOCK)
				LEFT OUTER JOIN dbo.RES_CUSTOMER_damo I ON H.RES_CODE = I.RES_CODE
				WHERE H.PRO_CODE IN (SELECT DISTINCT(G.PRO_CODE)
									FROM OTR_POL_MASTER F WITH(NOLOCK) 
									INNER JOIN OTR_MASTER G WITH(NOLOCK) ON (F.OTR_SEQ = G.OTR_SEQ AND G.OTR_STATE = '3')
									WHERE F.AGT_CODE = A.AGT_CODE)) AS RESCUSTOMERCOUNT,
			(SELECT ISNULL(SUM(E.ADT_PRICE), 0) + ISNULL(SUM(E.CHD_PRICE), 0) + ISNULL(SUM(E.INF_PRICE), 0) 
				FROM ARG_MASTER C WITH(NOLOCK)
				--INNER JOIN ARG_DETAIL D ON (C.ARG_SEQ_NO = D.ARG_SEQ_NO AND D.ARG_TYPE ='2' AND D.ARG_DETAIL_STATUS = '5')
				INNER JOIN ARG_DETAIL D WITH(NOLOCK) ON (C.ARG_CODE = D.ARG_CODE AND D.ARG_TYPE ='4')
				INNER JOIN ARG_INVOICE_DETAIL E WITH(NOLOCK) ON (C.ARG_CODE = E.ARG_CODE AND D.GRP_SEQ_NO = E.GRP_SEQ_NO)
				WHERE C.AGT_CODE = A.AGT_CODE AND SUBSTRING(CONVERT(VARCHAR(20), D.DEP_DATE, 112), 1, 6) = DEP_MONTH) AS PRICE_TOTAL
		FROM (
 			SELECT A.AGT_CODE, SUBSTRING(CONVERT(VARCHAR(20), D.DEP_DATE, 112), 1, 6) AS DEP_MONTH,
					MAX(C.PRO_CODE) AS PRO_CODE,
					B.KOR_NAME, 
					ISNULL(A.MEM_CODE, '') AS MEM_CODE, 
					A.GUIDE_NAME,
					(SELECT ROUND((SUM(CONVERT(INT,L.EXAMPLE_DESC)) / CONVERT(FLOAT,COUNT(K.OTR_POL_EXAMPLE_SEQ))),1)
						FROM OTR_MASTER H WITH(NOLOCK)
						INNER JOIN dbo.OTR_POL_MASTER I WITH(NOLOCK) ON H.OTR_SEQ = I.OTR_SEQ AND I.POL_TYPE ='2'
						INNER JOIN dbo.OTR_POL_QUESTION J WITH(NOLOCK) ON I.OTR_POL_MASTER_SEQ = J.OTR_POL_MASTER_SEQ AND J.QUS_TYPE='1'
						INNER JOIN dbo.OTR_POL_ANSWER K WITH(NOLOCK) ON J.OTR_POL_MASTER_SEQ = K.OTR_POL_MASTER_SEQ AND J.OTR_POL_QUESTION_SEQ = K.OTR_POL_QUESTION_SEQ
						INNER JOIN dbo.OTR_POL_DETAIL L WITH(NOLOCK) ON K.OTR_POL_MASTER_SEQ = L.OTR_POL_MASTER_SEQ AND K.OTR_POL_QUESTION_SEQ = L.OTR_POL_QUESTION_SEQ AND K.OTR_POL_EXAMPLE_SEQ =L.OTR_POL_EXAMPLE_SEQ 
						WHERE H.OTR_STATE = '3' AND I.AGT_CODE = A.AGT_CODE AND ISNULL(I.MEM_CODE, '') = ISNULL(A.MEM_CODE, '') AND I.GUIDE_NAME = A.GUIDE_NAME) AS AVG_NUM ,
					(SELECT TOP 1 Z.SIGN_CODE   
						FROM PKG_DETAIL Y WITH(NOLOCK)
						INNER JOIN PKG_MASTER Z WITH(NOLOCK) ON Y.MASTER_CODE = Z.MASTER_CODE
						WHERE Y.PRO_CODE = MAX(C.PRO_CODE)) AS SIGN_CODE,
					(SELECT COUNT(H.RES_CODE) 
						FROM dbo.Res_master_damo H WITH(NOLOCK)
						LEFT OUTER JOIN dbo.RES_CUSTOMER_damo I WITH(NOLOCK) ON H.RES_CODE = I.RES_CODE
						WHERE H.PRO_CODE = MAX(C.PRO_CODE)) AS RESCUSTOMERCOUNT,
					(SELECT DEP_DATE FROM PKG_DETAIL WITH(NOLOCK) WHERE PRO_CODE = MAX(C.PRO_CODE)) AS LAST_DEP_DATE
			FROM OTR_POL_MASTER A WITH(NOLOCK)
			INNER JOIN OTR_MASTER C WITH(NOLOCK) ON (A.OTR_SEQ = C.OTR_SEQ AND C.OTR_STATE = '3')
			INNER JOIN AGT_MASTER B WITH(NOLOCK) ON A.AGT_CODE = B.AGT_CODE
			INNER JOIN PKG_DETAIL D WITH(NOLOCK) ON C.PRO_CODE = D.PRO_CODE
			INNER JOIN PKG_MASTER E WITH(NOLOCK) ON D.MASTER_CODE = E.MASTER_CODE
			WHERE A.POL_type ='2'
			GROUP BY A.AGT_CODE, SUBSTRING(CONVERT(VARCHAR(20), D.DEP_DATE, 112), 1, 6), ISNULL(A.MEM_CODE, ''), A.GUIDE_NAME, B.KOR_NAME ) A
		WHERE AGT_CODE = @AGT_CODE AND DEP_MONTH LIKE @DEP_YEAR + '%'
        GROUP BY AGT_CODE, DEP_MONTH
		ORDER BY DEP_MONTH

END 
GO
