USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO




-- =============================================
-- Author:권윤경
-- Create date: 2008-03-25
-- Description:	쪽지 삭제 및 카테고리이동 SP

CREATE PROCEDURE [dbo].[SP_PRI_NOTE_UPDATE]
@EMP_CODE VARCHAR(7),
@NOTE_SEQ_NO VARCHAR(1000),
@RCV_SEQ_NO VARCHAR(1000),
@CAT_SEQ_NO INT,
@TYPE CHAR(1), --S : 보낸쪽지 R:받은쪽지
@MODE CHAR(1) --U : 카테고리 이동 D:삭제
AS

BEGIN
		SET NOCOUNT OFF;
		DECLARE @INDEX INT;
		DECLARE @INDEX_RCV INT;
		DECLARE @TEMP_NOTE_SEQ VARCHAR(20);
		DECLARE @TEMP_NOTE_SEQ_LIST VARCHAR(1000);
		DECLARE @TEMP_RCV_SEQ VARCHAR(20);
		DECLARE @TEMP_RCV_SEQ_LIST VARCHAR(1000);
		DECLARE @SPLIT_NOTE_INDEX INT;
		DECLARE @SPLIT_RCV_INDEX INT;

		SET @INDEX = CHARINDEX(',', @NOTE_SEQ_NO);
		SET @INDEX_RCV = CHARINDEX(',', @RCV_SEQ_NO);
		
		IF @INDEX=0
		BEGIN
			IF @MODE='D' 	--삭제일경우
			BEGIN
				IF @TYPE='S' --보낸쪽지 삭제일경우
				BEGIN
					UPDATE PRI_NOTE_RECEIPT SET SEND_DEL_YN='Y' 
					WHERE NOTE_SEQ_NO = @NOTE_SEQ_NO AND RCV_SEQ_NO = @RCV_SEQ_NO
				END
				ELSE		--받은쪽지 삭제일경우
				BEGIN
					UPDATE PRI_NOTE_RECEIPT SET RCV_DEL_YN='Y' 
					WHERE NOTE_SEQ_NO = @NOTE_SEQ_NO AND RCV_SEQ_NO = @RCV_SEQ_NO
				END
			END
			ELSE
			BEGIN
				IF @TYPE='S'--보낸쪽지 카테고리 이동일경우
				BEGIN
					UPDATE PRI_NOTE_RECEIPT SET SEND_CAT_SEQ_NO=@CAT_SEQ_NO
					WHERE NOTE_SEQ_NO = @NOTE_SEQ_NO AND RCV_SEQ_NO = @RCV_SEQ_NO
				END
				ELSE		--받은쪽지 카테고리 이동일 경우
				BEGIN
					UPDATE PRI_NOTE_RECEIPT SET RCV_CAT_SEQ_NO=@CAT_SEQ_NO  
					WHERE NOTE_SEQ_NO = @NOTE_SEQ_NO AND RCV_SEQ_NO = @RCV_SEQ_NO
				END				
			END
		END
		ELSE
		BEGIN
			SET @NOTE_SEQ_NO = @NOTE_SEQ_NO + ',';
			SET @RCV_SEQ_NO = @RCV_SEQ_NO + ',';


			WHILE NOT (@INDEX=0)
				BEGIN
					
					SET @TEMP_NOTE_SEQ = LEFT(@NOTE_SEQ_NO, @INDEX-1); 
					SET @TEMP_NOTE_SEQ_LIST = RIGHT(@NOTE_SEQ_NO, LEN(@NOTE_SEQ_NO) - @INDEX);
					
					SET @TEMP_RCV_SEQ = LEFT(@RCV_SEQ_NO, @INDEX_RCV-1); 
					SET @TEMP_RCV_SEQ_LIST = RIGHT(@RCV_SEQ_NO, LEN(@RCV_SEQ_NO) - @INDEX_RCV);
					
					IF @MODE='D' 	--삭제일경우
					BEGIN	

						IF @TYPE='S' --보낸쪽지 삭제일경우
								BEGIN
									UPDATE PRI_NOTE_RECEIPT SET SEND_DEL_YN='Y' 
									WHERE NOTE_SEQ_NO = @TEMP_NOTE_SEQ AND RCV_SEQ_NO = @TEMP_RCV_SEQ;

														
								END
						ELSE		--받은쪽지 삭제일경우
								BEGIN
									UPDATE PRI_NOTE_RECEIPT SET RCV_DEL_YN='Y' 
									WHERE NOTE_SEQ_NO = @TEMP_NOTE_SEQ AND RCV_SEQ_NO = @TEMP_RCV_SEQ;	
								END
					END
					ELSE
						BEGIN					

							IF @TYPE='S'--보낸쪽지 카테고리 이동일경우
								BEGIN
									UPDATE PRI_NOTE_RECEIPT SET SEND_CAT_SEQ_NO=@CAT_SEQ_NO  
									WHERE NOTE_SEQ_NO = @TEMP_NOTE_SEQ AND RCV_SEQ_NO = @TEMP_RCV_SEQ;	
								END
							ELSE		--받은쪽지 카테고리 이동일 경우
								BEGIN
									UPDATE PRI_NOTE_RECEIPT SET RCV_CAT_SEQ_NO=@CAT_SEQ_NO  
									WHERE NOTE_SEQ_NO = @TEMP_NOTE_SEQ AND RCV_SEQ_NO = @TEMP_RCV_SEQ;
								END				
						END

					SET @INDEX = CHARINDEX(',', @TEMP_NOTE_SEQ_LIST);
					SET @INDEX_RCV = CHARINDEX(',', @TEMP_RCV_SEQ_LIST);
					SET @NOTE_SEQ_NO = @TEMP_NOTE_SEQ_LIST
					SET @RCV_SEQ_NO = @TEMP_RCV_SEQ_LIST
					--PRINT @INDEX
				END
		END
				
			
		
END



GO
