USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_DOC_HOLIDAY_INSERT]
	@EDI_CODE		CHAR(10),
	@EMP_CODE		CHAR(7)
AS
BEGIN
	SET NOCOUNT ON;

	-- 휴가출장 내역 입력
	INSERT INTO EMP_HOLIDAY_HISTORY (
		EDI_CODE,		EMP_CODE,	APPLY_YEAR,			HOLIDAY_TYPE,	HOLIDAY_CODE,
		JOIN_DATE,		OUT_DATE,	USE_DAY,			REMARK,			NEW_CODE
	)
	SELECT
		EDI_CODE,		NEW_CODE,	YEAR(JOIN_DATE),	DOC_TYPE,		DETAIL_TYPE,
		JOIN_DATE,		OUT_DATE,	VAC_DAY,			[SUBJECT],		@EMP_CODE
	FROM EDI_MASTER_DAMO
	WHERE EDI_CODE = @EDI_CODE

	-- 변수선언
	DECLARE
	@QTYPE			CHAR(1),
	@NEW_CODE		VARCHAR(10),
	@SCH_TYPE		CHAR(1),
	@SCH_DATE		DATETIME,
	@RPT_TYPE		INT,
	@SUBJECT		VARCHAR(50),
	@CONTENTS		VARCHAR(100),	
	@SCH_GRADE		CHAR(1),	
	@START_TIME		DATETIME,
	@END_TIME		DATETIME,	
	@USERID			VARCHAR(20),
	@USERNAME		VARCHAR(20),
	@SEQ			INT,
	@PARENT_SEQ		INT

	SELECT
		@QTYPE = 'I',
		@NEW_CODE = A.NEW_CODE,
		@SCH_TYPE = (CASE WHEN A.DOC_TYPE = '1' AND A.DETAIL_TYPE = '2' THEN '7' ELSE A.DOC_TYPE END),
		@SCH_DATE = A.OUT_DATE,		@SCH_DATE = A.OUT_DATE,		@RPT_TYPE = 1,
		@SUBJECT =	A.NEW_NAME + ' [' + A.EDI_CODE + '] ',
--		@CONTENTS = (CASE DOC_TYPE WHEN '1' THEN '[휴가]' WHEN '2' THEN '[출장]' END) + ' ' + NEW_NAME,
		@CONTENTS = (
			CASE 
				WHEN A.DOC_TYPE = '1' AND A.DETAIL_TYPE = '2' THEN '[공가]'
				WHEN A.DOC_TYPE = '1' THEN '[휴가]'
				WHEN A.DOC_TYPE = '2' THEN '[출장]'
			END
		) + ' ' + A.NEW_NAME,
		@SCH_GRADE = '1',			@START_TIME = A.JOIN_DATE,	@END_TIME = DATEADD(DAY, 1, A.JOIN_DATE),
		@USERID = @EMP_CODE,		@USERNAME = (SELECT KOR_NAME FROM EMP_MASTER_damo WITH(NOLOCK) WHERE EMP_CODE = @EMP_CODE),
		@SEQ = 0,					@PARENT_SEQ = 0
	FROM EDI_MASTER_DAMO A WITH(NOLOCK)
	WHERE A.EDI_CODE = @EDI_CODE

	-- 공용 스케줄 입력
	EXEC SP_COM_SCHEDULE_INSERT @QTYPE, @NEW_CODE, @SCH_TYPE, @SCH_DATE, @RPT_TYPE, @SUBJECT
		, @CONTENTS, @SCH_GRADE, @START_TIME, @END_TIME, @USERID, @USERNAME, @SEQ, @PARENT_SEQ

END
GO
