USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
-- 2012-03-02 WITH(NOLOCK) 추가 	
*/
CREATE PROCEDURE [dbo].[SP_DOC_APPROVAL_INSERT]
	@EDI_CODE		CHAR(10),
	@APP_CODE		CHAR(7),
	@APP_NAME		VARCHAR(20),
	@APP_DATE		DATETIME,
	--@APP_STATUS		CHAR(1),
	@APP_TYPE		CHAR(1),
	@READ_YN		CHAR(1),
	@NEW_CODE		CHAR(7),
	@NEW_TEAM_NAME	VARCHAR(50),
	@NEW_DUTY_NAME	VARCHAR(20),
	@NEW_POS_NAME	VARCHAR(20)
AS
BEGIN
	SET NOCOUNT ON;
	-- 변수 선언
	DECLARE @SEQ_NO INT, @TEAM_NAME VARCHAR(50), @DUTY_NAME VARCHAR(20), @POS_NAME VARCHAR(20)

	-- @SEQ_NO SET
	IF EXISTS(SELECT 1 FROM EDI_APPROVAL WITH(NOLOCK) WHERE EDI_CODE = @EDI_CODE)
		SELECT @SEQ_NO = (MAX(SEQ_NO) + 1) FROM EDI_APPROVAL WHERE EDI_CODE = @EDI_CODE
	ELSE
		SET @SEQ_NO = 1

	-- 결재자 정보 SET
	SELECT
		@TEAM_NAME = (SELECT TEAM_NAME FROM EMP_TEAM WITH(NOLOCK) WHERE TEAM_CODE = A.TEAM_CODE ),
		@DUTY_NAME = (SELECT PUB_VALUE FROM COD_PUBLIC WITH(NOLOCK) WHERE PUB_TYPE='EMP.DUTYTYPE' AND PUB_CODE=A.DUTY_TYPE),
		@POS_NAME = (SELECT PUB_VALUE FROM COD_PUBLIC WITH(NOLOCK) WHERE PUB_TYPE='EMP.POSTYPE' AND PUB_CODE=A.POS_TYPE)
	FROM EMP_MASTER_damo A WHERE EMP_CODE = @APP_CODE

	IF NOT EXISTS(SELECT 1 FROM EDI_APPROVAL WITH(NOLOCK) WHERE EDI_CODE = @EDI_CODE AND APP_CODE = @APP_CODE AND APP_TYPE = @APP_TYPE)
	BEGIN
		-- 결재자 정보 INSERT
		INSERT INTO EDI_APPROVAL (
			EDI_CODE,		SEQ_NO,			APP_CODE,		[APP_NAME],		TEAM_NAME,		DUTY_NAME,
			POS_NAME,		APP_DATE,		APP_TYPE,		READ_YN,		NEW_CODE,		NEW_TEAM_NAME,
			NEW_DUTY_NAME,	NEW_POS_NAME
		) VALUES (
			@EDI_CODE,		@SEQ_NO,		@APP_CODE,		@APP_NAME,		@TEAM_NAME,		@DUTY_NAME,
			@POS_NAME,		@APP_DATE,		@APP_TYPE,		@READ_YN,		@NEW_CODE,		@NEW_TEAM_NAME,
			@NEW_DUTY_NAME,	@NEW_POS_NAME )
	END

END

GO
