USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*================================================================================================================
■ USP_NAME					: XP_COM_ERP_BIZTRIP_RES_CUSTOMER_LIST_SELECT
■ DESCRIPTION				: BTMS ERP 출장 현황 예약 출발자 리스트 검색
■ INPUT PARAMETER			: 
	@AGT_CODE				: 거래처 코드
	@BT_CODE				: 출장코드
■ OUTPUT PARAMETER			: 
■ EXEC						: 
	EXEC XP_COM_ERP_BIZTRIP_RES_CUSTOMER_LIST_SELECT '92756', 'BT1604010105';
	exec XP_COM_ERP_BIZTRIP_RES_CUSTOMER_LIST_SELECT @AGT_CODE=N'93881',@BT_CODE=N'BT1606020423'

■ MEMO						: 
------------------------------------------------------------------------------------------------------------------
■ CHANGE HISTORY
------------------------------------------------------------------------------------------------------------------
   DATE				AUTHOR			DESCRIPTION           
------------------------------------------------------------------------------------------------------------------
   2016-06-21		박형만			최초생성
 
================================================================================================================*/ 
CREATE PROC [dbo].[XP_COM_ERP_BIZTRIP_RES_CUSTOMER_LIST_SELECT]
	@RES_CODE RES_CODE  ,
	@RES_STATE INT  
AS 
BEGIN

	
	SELECT
		A.RES_CODE,A.SEQ_NO,(SELECT PRICE_SEQ FROM DBO.RES_MASTER_DAMO C WHERE A.RES_CODE = C.RES_CODE) AS PRICE_SEQ,
		A.RES_STATE,A.SEAT_YN,A.CUS_TYPE,B.CUS_GRADE,A.CUS_NO,A.CUS_NAME,A.LAST_NAME,A.FIRST_NAME,A.AGE_TYPE,A.GENDER,
		A.SOC_NUM1,damo.dbo.dec_varchar('DIABLO','dbo.RES_CUSTOMER','SOC_NUM2', A.SEC_SOC_NUM2) AS SOC_NUM2,
		A.NOR_TEL1,A.NOR_TEL2,A.NOR_TEL3,A.EMAIL,A.[NATIONAL],A.APIS_YN,A.VISA_YN, A.PASS_YN ,
		damo.dbo.dec_varchar('DIABLO','dbo.RES_CUSTOMER','PASS_NUM', A.SEC_PASS_NUM) AS PASS_NUM,A.PASS_EXPIRE,
		A.PASS_ISSUE,A.SALE_PRICE,A.CHG_PRICE,A.DC_PRICE,A.TAX_PRICE,A.PENALTY_PRICE,A.PENALTY_YN,A.CHG_REMARK,A.SENDING_REMARK,
		A.ROOMING_REMARK,A.ETC_REMARK,A.RETURN_YN,A.ROOMING,A.POINT_PRICE,A.POINT_YN,A.POINT_REF,A.CUS_INS_YN,A.INS_CODE,A.INS_SEQ,
		A.INS_PRICE,A.INS_DAY,A.COMM_YN,A.NEW_CODE,A.NEW_DATE,A.EDT_CODE,A.EDT_DATE,A.CXL_DATE,A.CXL_CODE,A.MOV_RES_CODE,A.COMM_RATE,
		A.COMM_AMT,POINT_RATE
		, DBO.FN_CUS_GET_EMP_NAME(A.NEW_CODE) AS [NEW_NAME]
		, DBO.FN_CUS_GET_EMP_NAME(A.EDT_CODE) AS [EDT_NAME]
		, (SELECT DEP_DATE FROM RES_MASTER_damo BB WITH(NOLOCK) WHERE BB.RES_CODE = A.RES_CODE) AS [DEP_DATE]
		, (DBO.FN_CUS_GET_WEB_TYPE(A.CUS_NO)) AS [WEB_TYPE]
		--, DBO.FN_CUS_GET_RES_COUNT( A.SOC_NUM1, damo.dbo.dec_varchar('DIABLO','dbo.RES_CUSTOMER','SOC_NUM2', A.SEC_SOC_NUM2)) RES_COUNT
		, DBO.FN_CUS_GET_RES_COUNT2(A.IPIN_DUP_INFO) AS RES_COUNT
		, ISNULL(A.IPIN_DUP_INFO,B.IPIN_DUP_INFO) AS IPIN_DUP_INFO  
		, ISNULL(A.IPIN_CONN_INFO,B.IPIN_CONN_INFO) AS IPIN_CONN_INFO  
		, A.BIRTH_DATE, A.PPT_NO
		, (CASE WHEN EXISTS(SELECT 1 FROM PPT_MASTER AA WITH(NOLOCK) WHERE AA.RES_CODE = A.RES_CODE AND AA.RES_NO = A.SEQ_NO AND AA.RCV_DATE IS NOT NULL) THEN 'Y' ELSE 'N' END) AS [APP_CONFIRM_YN]
		, G.POS_NAME , H.TEAM_NAME 

	FROM RES_CUSTOMER_damo A WITH(NOLOCK)
	LEFT JOIN CUS_CUSTOMER_damo B WITH(NOLOCK) ON A.CUS_NO = B.CUS_NO
	
	LEFT JOIN COM_EMPLOYEE_MATCHING E  WITH(NOLOCK) ON A.CUS_NO = E.CUS_NO 
	LEFT JOIN COM_EMPLOYEE F  WITH(NOLOCK) ON E.AGT_CODE = F.AGT_CODE AND E.EMP_SEQ = F.EMP_SEQ 
	LEFT JOIN COM_POSITION G  WITH(NOLOCK) ON F.AGT_CODE = G.AGT_CODE AND F.POS_SEQ = G.POS_SEQ 
	LEFT JOIN COM_TEAM H WITH(NOLOCK) ON F.AGT_CODE = H.AGT_CODE AND  F.TEAM_SEQ  = H.TEAM_SEQ 

	WHERE A.RES_CODE = @RES_CODE
		--@SEARCH
	AND (A.RES_STATE = @RES_STATE OR @RES_STATE = 9 )
	ORDER BY A.SEQ_NO

	--SELECT A.AGT_CODE, A.BT_CODE, A.PRO_CODE, B.PRO_DETAIL_TYPE, C.RES_CODE, C.PRICE_SEQ, D.SEQ_NO, C.RES_STATE, D.RES_STATE AS [CUS_RES_STATE], C.DEP_DATE
	--	, D.CUS_NO , E.EMP_SEQ , D.NOR_TEL1 , D.NOR_TEL2 , D.NOR_TEL3 , D.EMAIL , G.POS_NAME , H.TEAM_NAME 
	--	, D.CUS_NAME, D.LAST_NAME, D.FIRST_NAME, D.AGE_TYPE, D.GENDER, D.BIRTH_DATE, D.PASS_YN
	--	, DBO.FN_CUS_GET_AGE(D.BIRTH_DATE, C.DEP_DATE) AS [AGE]
	--	, damo.dbo.dec_varchar('DIABLO','dbo.RES_CUSTOMER','PASS_NUM', D.SEC_PASS_NUM) AS PASS_NUM, D.PASS_EXPIRE
	--	, D.NEW_DATE, D.ETC_REMARK 
	--FROM COM_BIZTRIP_MASTER A WITH(NOLOCK)
	--INNER JOIN COM_BIZTRIP_DETAIL B WITH(NOLOCK) ON A.AGT_CODE = B.AGT_CODE AND A.BT_CODE = B.BT_CODE
	--INNER JOIN RES_MASTER_damo C WITH(NOLOCK) ON B.RES_CODE = C.RES_CODE
	--INNER JOIN RES_CUSTOMER_damo D WITH(NOLOCK) ON C.RES_CODE = D.RES_CODE
	--LEFT JOIN COM_EMPLOYEE_MATCHING E  WITH(NOLOCK) ON D.CUS_NO = E.CUS_NO 
	--LEFT JOIN COM_EMPLOYEE F  WITH(NOLOCK) ON E.AGT_CODE = F.AGT_CODE AND E.EMP_SEQ = F.EMP_SEQ 
	--LEFT JOIN COM_POSITION G  WITH(NOLOCK) ON F.AGT_CODE = G.AGT_CODE AND F.POS_SEQ = G.POS_SEQ 
	--LEFT JOIN COM_TEAM H WITH(NOLOCK) ON F.AGT_CODE = H.AGT_CODE AND  F.TEAM_SEQ  = H.TEAM_SEQ 

	--WHERE A.AGT_CODE = @AGT_CODE AND A.BT_CODE = @BT_CODE
	--ORDER BY B.PRO_DETAIL_TYPE;

END 


GO
