USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:권윤경
-- Create date: 2008-03-25
-- Description:	쪽지 카테고리 삭제 SP
CREATE PROCEDURE [dbo].[SP_NOTE_DELETE_CATEGORY]
@CAT_SEQ_NO INT,
@EMP_CODE	VARCHAR(7)

AS
	BEGIN
		UPDATE PUB_NOTE_CATEGORY SET DEL_YN='Y' WHERE CAT_SEQ_NO=@CAT_SEQ_NO;  --카테고리 삭제

		UPDATE PUB_NOTE SET SEND_DEL_YN = 'Y', SEND_CAT_SEQ_NO=0 WHERE NEW_CODE = @EMP_CODE AND SEND_CAT_SEQ_NO = @CAT_SEQ_NO;   --보낸쪽지 삭제
		UPDATE PUB_NOTE SET DEL_YN = 'Y', CAT_SEQ_NO=0 WHERE EMP_CODE = @EMP_CODE AND CAT_SEQ_NO = @CAT_SEQ_NO;  --받은쪽지 삭제
		
--		UPDATE PUB_NOTE_CATEGORY SET DEL_YN='Y' WHERE CAT_SEQ_NO=@CAT_SEQ_NO
--
--
--		UPDATE PUB_NOTE SET CAT_SEQ_NO=NULL
--		WHERE CAT_SEQ_NO=@CAT_SEQ_NO
--		
--		UPDATE PUB_NOTE SET SEND_CAT_SEQ_NO=NULL
--		WHERE SEND_CAT_SEQ_NO=@CAT_SEQ_NO


	END
GO
