USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
사원정보 등록 
2012-03-05 외부아이피 접속여부 @ACC_OUT_YN 추가 
2015-10-26 @PASSWORD VARCHAR(20) -> (100)
*/
CREATE PROCEDURE [dbo].[SP_EMP_EMPLOYEE_INSERT]
	@EMP_CODE VARCHAR(7),
	@PASSWORD VARCHAR(100) ,
	@KOR_NAME VARCHAR(20) ,
	@ENG_FIRST_NAME VARCHAR(20),
	@ENG_LAST_NAME VARCHAR(20),
	@JOIN_DATE SMALLDATETIME,
	@OUT_DATE SMALLDATETIME,	
	@BIRTH_DATE SMALLDATETIME,	
	@SOC_NUMBER1 VARCHAR(6),
	@SOC_NUMBER2 VARCHAR(7),
	@GENDER VARCHAR(1), 
	@JOIN_TYPE VARCHAR(1),
	@WORK_TYPE VARCHAR(1),
	@DUTY_TYPE VARCHAR(1),
	@POS_TYPE VARCHAR(1),
	@GROUP_TYPE VARCHAR(1),
	@EMAIL VARCHAR(30),
	@EMAIL_PASSWORD Varchar(30),
	@MESSENGER VARCHAR(30),
	@ZIP_CODE VARCHAR(7),
	@ADDRESS1 VARCHAR(50),
	@ADDRESS2 VARCHAR(80),
	@TEL_NUMBER1 VARCHAR(4),
	@TEL_NUMBER2 VARCHAR(4),
	@TEL_NUMBER3 VARCHAR(4),
	@HP_NUMBER1 VARCHAR(4),
	@HP_NUMBER2 VARCHAR(4),
	@HP_NUMBER3 VARCHAR(4),
	@INNER_NUMBER1 VARCHAR(4),
	@INNER_NUMBER2 VARCHAR(4),
	@INNER_NUMBER3 VARCHAR(4),
	@FAX_NUMBER1 VARCHAR(4),
	@FAX_NUMBER2 VARCHAR(4),
	@FAX_NUMBER3 VARCHAR(4),
	@GREETING VARCHAR(200),
	@SALARY_CLASS VARCHAR(4),
	@TEAM_CODE VARCHAR(3),
	@PASSPORT VARCHAR(20),
	@PASS_EXPIRE_DATE SMALLDATETIME,
	@NEW_CODE VARCHAR(7),
	@ACC_OUT_YN CHAR(1) 
AS
BEGIN
	SET NOCOUNT OFF;
	DECLARE @SEQ INT;
		
	BEGIN
			
			--EXEC	[dbo].[SP_COD_GETSEQ]'EMP', @EMP_CODE OUTPUT

			INSERT INTO EMP_MASTER
				(EMP_CODE,[PASSWORD],KOR_NAME,ENG_FIRST_NAME,ENG_LAST_NAME,JOIN_DATE,OUT_DATE,BIRTH_DATE,SOC_NUMBER1,SOC_NUMBER2,
				GENDER,JOIN_TYPE,WORK_TYPE,DUTY_TYPE,POS_TYPE, GROUP_TYPE, EMAIL,EMAIL_PASSWORD,MESSENGER,ZIP_CODE,
				ADDRESS1,ADDRESS2,TEL_NUMBER1,TEL_NUMBER2,TEL_NUMBER3,HP_NUMBER1,HP_NUMBER2,HP_NUMBER3,
				INNER_NUMBER1,INNER_NUMBER2,INNER_NUMBER3, FAX_NUMBER1, FAX_NUMBER2, FAX_NUMBER3, GREETING, SALARY_CLASS,
				TEAM_CODE,PASSPORT,PASS_EXPIRE_DATE,NEW_CODE,ACC_OUT_YN)
			VALUES
			(
				@EMP_CODE,@PASSWORD,@KOR_NAME,@ENG_FIRST_NAME,@ENG_LAST_NAME,@JOIN_DATE,@OUT_DATE,@BIRTH_DATE,@SOC_NUMBER1,@SOC_NUMBER2,
				@GENDER,@JOIN_TYPE,@WORK_TYPE,@DUTY_TYPE,@POS_TYPE,@GROUP_TYPE,@EMAIL,@EMAIL_PASSWORD,@MESSENGER,@ZIP_CODE,
				@ADDRESS1,@ADDRESS2,@TEL_NUMBER1,@TEL_NUMBER2,@TEL_NUMBER3,@HP_NUMBER1,@HP_NUMBER2,@HP_NUMBER3,
				@INNER_NUMBER1,@INNER_NUMBER2,@INNER_NUMBER3, @FAX_NUMBER1, @FAX_NUMBER2, @FAX_NUMBER3, @GREETING, @SALARY_CLASS,
				@TEAM_CODE,@PASSPORT,@PASS_EXPIRE_DATE,@NEW_CODE,@ACC_OUT_YN)
	
			
			INSERT INTO EMP_TEAM_MOVE
			(EMP_CODE,TEAM_CODE,MOV_DATE,REMARK,NEW_CODE)
			VALUES
			(@EMP_CODE,@TEAM_CODE,GETDATE(),'사원등록',@NEW_CODE)
		

			UPDATE COD_SEQ SET COD_SQ  = Convert(int, Right(@EMP_CODE, 3)) WHERE COD_TYPE= 'EMP'

	END
END
GO
