USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_BBS_HISTORY_INSERT]
(
 @BBS_SEQ INT,
 @MASTER_SEQ INT
)
AS

BEGIN
SET NOCOUNT OFF;
DECLARE @SEQ INT;
DECLARE @FILE_SEQ VARCHAR(7);
DECLARE @FILENAME VARCHAR(100);
DECLARE @FILEURL VARCHAR(200);
DECLARE @HISTORY_SEQ  INT;

	SELECT TOP 1 @SEQ  = ISNULL(MAX(HISTORY_SEQ),0) + 1 FROM BBS_DETAIL_HISTORY   WITH (UPDLOCK)  WHERE BBS_SEQ=@BBS_SEQ 	AND MASTER_SEQ=@MASTER_SEQ

    --히스토리 테이블로 데이타 입력
	INSERT INTO BBS_DETAIL_HISTORY 
	 (HISTORY_SEQ,BBS_SEQ,MASTER_SEQ,CATEGORY_GROUP,CATEGORY_SEQ,[PASSWORD],[SUBJECT],NOTICE_YN,[STATUS],
	STATUS_EMP_CODE,FINISH_DATE,FINISH_EMP_CODE,COMMENT_COUNT,CONTENTS,FILE_COUNT,FILE_PATH,[LEVEL],PARENT_SEQ,READ_NUM,IPADDRESS,TEAM_CODE,TEAM_NAME,NEW_NAME,NEW_CODE,EDT_NAME,EDT_CODE)
	SELECT @SEQ,BBS_SEQ,MASTER_SEQ,CATEGORY_GROUP,CATEGORY_SEQ,[PASSWORD],[SUBJECT],NOTICE_YN,[STATUS],
	STATUS_EMP_CODE,FINISH_DATE,FINISH_EMP_CODE,COMMENT_COUNT,CONTENTS,FILE_COUNT,FILE_PATH,[LEVEL],PARENT_SEQ,READ_NUM,IPADDRESS,TEAM_CODE,TEAM_NAME,NEW_NAME,NEW_CODE,EDT_NAME,EDT_CODE
	FROM BBS_DETAIL WHERE BBS_SEQ=@BBS_SEQ AND MASTER_SEQ=@MASTER_SEQ


	--파일히스토리 테이블로 데이타 입력
	DECLARE CURSOR_BBS_FILE CURSOR GLOBAL FOR
		SELECT FILE_SEQ,BBS_SEQ,MASTER_SEQ,[FILENAME] FROM BBS_FILE
		WHERE BBS_SEQ=@BBS_SEQ AND MASTER_SEQ=@MASTER_SEQ
		--SELECT FILE_SEQ,BBS_SEQ,MASTER_SEQ,[FILENAME],FILEURL  FROM BBS_FILE WHERE  BBS_SEQ=@BBS_SEQ AND MASTER_SEQ=@MASTER_SEQ

	OPEN CURSOR_BBS_FILE

	 --FETCH NEXT FROM CURSOR_BBS_FILE INTO @FILE_SEQ,@BBS_SEQ,@MASTER_SEQ,@FILENAME,@FILEURL
	FETCH NEXT FROM CURSOR_BBS_FILE INTO @FILE_SEQ,@BBS_SEQ,@MASTER_SEQ,@FILENAME
	
		WHILE @@FETCH_STATUS=0
			BEGIN
				SELECT TOP 1 @HISTORY_SEQ  = ISNULL(MAX(HISTORY_SEQ),0) + 1 FROM BBS_HISTORY_FILE  WITH (UPDLOCK)  WHERE BBS_SEQ=@BBS_SEQ 	AND MASTER_SEQ=@MASTER_SEQ AND FILE_SEQ=@FILE_SEQ

				INSERT INTO BBS_HISTORY_FILE
				--(HISTORY_SEQ,FILE_SEQ,BBS_SEQ,MASTER_SEQ,[FILENAME],FILEURL)
				(HISTORY_SEQ,FILE_SEQ,BBS_SEQ,MASTER_SEQ,[FILENAME])
				VALUES
				--(@HISTORY_SEQ,@FILE_SEQ,@BBS_SEQ,@MASTER_SEQ,@FILENAME,@FILEURL)
				(@HISTORY_SEQ,@FILE_SEQ,@BBS_SEQ,@MASTER_SEQ,@FILENAME)
				--FETCH NEXT FROM CURSOR_BBS_FILE INTO  @FILE_SEQ,@BBS_SEQ,@MASTER_SEQ,@FILENAME,@FILEURL
				FETCH NEXT FROM CURSOR_BBS_FILE INTO @FILE_SEQ, @BBS_SEQ, @MASTER_SEQ, @FILENAME
			END




	CLOSE CURSOR_BBS_FILE
	DEALLOCATE CURSOR_BBS_FILE

END




GO
