USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_RES_SND_REQUEST_SELECT_LIST]
	@FLAG				CHAR(1),
	@PAGE_SIZE			INT,
	@PAGE_INDEX			INT,
	@START_DATE			VARCHAR(10),
	@END_DATE			VARCHAR(10)
AS
BEGIN
		SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SET NOCOUNT ON;

	DECLARE @SQLSTRING NVARCHAR(4000), @PARMDEFINITION NVARCHAR(1000), @FROM INT, @TO INT;

	SET @FROM = @PAGE_INDEX * @PAGE_SIZE + 1;
	SET @TO = @PAGE_INDEX * @PAGE_SIZE + @PAGE_SIZE;

	-- WHERE 조건 만들기
	SET @SQLSTRING = ' WHERE 1 = 1';

	IF ISNULL(@START_DATE, '') <> '' AND ISNULL(@END_DATE, '') <> ''
	BEGIN
		SET @SQLSTRING = @SQLSTRING + ' AND A.SND_DATE BETWEEN @START_DATE AND @END_DATE'
	END


IF @FLAG = 'C'					-- 전체 글수
	BEGIN
		SET @SQLSTRING = N'SELECT COUNT(*) FROM SND_REQUEST A ' + @SQLSTRING;
	END
	ELSE IF @FLAG = 'L'				-- 검색
	BEGIN
		SET @SQLSTRING = N'
		WITH DOCUMENTLIST AS
		(
			SELECT ROW_NUMBER() OVER (ORDER BY A.SND_DATE) AS [ROWNUMBER], A.*
			FROM SND_REQUEST A
			' + @SQLSTRING + '
		)
		SELECT A.ROWNUMBER, A.SND_NO, A.SND_DATE, A.AIRPORT_TYPE, A.SND_TYPE,
			   A.SUBJECT, A.NEW_CODE, A.NEW_DATE,
				(SELECT KOR_NAME FROM EMP_MASTER WHERE EMP_CODE = A.NEW_CODE) AS NEW_NAME
		FROM DOCUMENTLIST A
		WHERE A.ROWNUMBER BETWEEN @FROM AND @TO
		ORDER BY A.SND_NO;';
	END

	SET @PARMDEFINITION = N'@FROM INT, @TO INT, @START_DATE VARCHAR(10), @END_DATE VARCHAR(10)';

	--PRINT @SQLSTRING
	EXEC SP_EXECUTESQL @SQLSTRING, @PARMDEFINITION, @FROM, @TO, @START_DATE, @END_DATE;
END


GO
