USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*================================================================================================================
■ USP_NAME					: XP_COM_EMPLOYEE_SELECT_BY_CUS_NO
■ DESCRIPTION				: BTMS 거래처 직원 상세정보 검색 - 고객매핑 정보 CUS_NO 로 
■ INPUT PARAMETER			: 
	@CUS_NO INT 
	
■ EXEC						: 
	EXEC XP_COM_EMPLOYEE_SELECT_BY_CUS_NO 4228549 
■ MEMO						: 
------------------------------------------------------------------------------------------------------------------
■ CHANGE HISTORY
------------------------------------------------------------------------------------------------------------------
   DATE				AUTHOR			DESCRIPTION           
------------------------------------------------------------------------------------------------------------------
   2016-08-09		박형만			최초생성 
================================================================================================================*/ 
CREATE PROC [dbo].[XP_COM_EMPLOYEE_SELECT_BY_CUS_NO]
	@CUS_NO	INT
AS 
BEGIN		
	

	-- 기본정보
	SELECT A.AGT_CODE , (SELECT KOR_NAME FROM AGT_MASTER WHERE AGT_CODE  = M.AGT_CODE ) AS AGT_NAME 
		, A.EMP_SEQ, A.TEAM_SEQ, A.EMP_ID, A.KOR_NAME, A.LAST_NAME, A.FIRST_NAME, A.BIRTH_DATE, A.GENDER, A.PASS_WORD, A.POS_SEQ, A.WORK_TYPE
		, A.JOIN_DATE, A.OUT_DATE, A.EMAIL, A.COM_NUMBER, A.HP_NUMBER, A.FAX_NUMBER, A.SEAT_REMARK, A.AIR_REMARK, A.HOTEL_REMARK, A.FAIL_COUNT, A.MANAGER_YN, A.MAIL_RECEIVE_YN
		, A.NEW_DATE, A.NEW_SEQ
		, C.TEAM_NAME, B.POS_NAME
		, ISNULL(A.EDT_DATE, A.NEW_DATE) AS [EDT_DATE]
		, ISNULL(A.EDT_SEQ, A.NEW_SEQ) AS [EDT_SEQ]
		--, E.TEAM_NAME AS EDT_TEAM_NAME, E.POS_NAME AS EDT_POS_NAME 
		--, E.KOR_NAME AS [EDT_NAME]
		, M.CUS_NO
		, (SELECT TOP 1 CUS_NAME FROM CUS_CUSTOMER_damo WHERE CUS_NO = M.CUS_NO )  AS CUS_NAME 
		, A.VGL_DATE, A.VGL_CODE, D.KOR_NAME AS VGL_NAME 
		, M.NEW_CODE AS MAT_NEW_CODE 
		, (SELECT TOP 1 KOR_NAME FROM EMP_MASTER WHERE EMP_CODE = M.NEW_CODE )  AS MAT_NEW_NAME 
		, (SELECT TOP 1 TEAM_NAME FROM EMP_TEAM WHERE TEAM_CODE = (SELECT TOP 1 TEAM_CODE FROM EMP_MASTER WHERE EMP_CODE = M.NEW_CODE)  ) AS MAT_NEW_TEAM_NAME
		, M.NEW_DATE AS MAT_NEW_DATE 
	FROM COM_EMPLOYEE_MATCHING M
	INNER JOIN 	COM_EMPLOYEE A WITH(NOLOCK) ON M.AGT_CODE =A.AGT_CODE AND M.EMP_SEQ = A.EMP_SEQ 
	LEFT JOIN COM_POSITION B ON A.AGT_CODE = B.AGT_CODE AND  A.POS_SEQ = B.POS_SEQ	
	LEFT JOIN COM_TEAM  C ON A.AGT_CODE = C.AGT_CODE AND  A.TEAM_SEQ = C.TEAM_SEQ	
	LEFT JOIN EMP_MASTER D ON A.VGL_CODE = D.EMP_CODE
	--WHERE A.AGT_CODE = @AGT_CODE AND A.EMP_SEQ = @EMP_SEQ
	WHERE M.CUS_NO = @CUS_NO 

	---- 여권정보
	--SELECT A.AGT_CODE, A.EMP_SEQ, A.PASS_SEQ, A.NATION_CODE, B.KOR_NAME AS [NATION_NAME], A.PASS_BIRTHDATE, A.PASS_NUM, A.PASS_ISSUE, A.PASS_EXPIRE, A.NEW_DATE, A.NEW_SEQ
	--FROM COM_EMP_PASSPORT A WITH(NOLOCK)
	--INNER JOIN PUB_NATION B WITH(NOLOCK) ON A.NATION_CODE = B.NATION_CODE
	--WHERE A.AGT_CODE = @AGT_CODE AND A.EMP_SEQ = @EMP_SEQ AND USE_YN = 'Y'

	---- 비자정보
	--SELECT A.AGT_CODE, A.EMP_SEQ, A.VISA_SEQ, A.NATION_CODE, B.KOR_NAME AS [NATION_NAME], A.VISA_TYPE, A.VISA_NUM, A.VISA_ISSUE, A.VISA_EXPIRE, A.USE_YN, A.NEW_DATE, A.NEW_SEQ
	--FROM COM_EMP_VISA A WITH(NOLOCK)
	--INNER JOIN PUB_NATION B WITH(NOLOCK) ON A.NATION_CODE = B.NATION_CODE
	--WHERE A.AGT_CODE = @AGT_CODE AND A.EMP_SEQ = @EMP_SEQ AND USE_YN = 'Y'

	---- 마일리지정보
	--SELECT A.AGT_CODE, A.EMP_SEQ, A.MIL_SEQ, A.MIL_PRO_TYPE, A.MIL_CODE, A.MIL_NUM
	--FROM COM_EMP_MILEAGE A WITH(NOLOCK)
	--WHERE A.AGT_CODE = @AGT_CODE AND A.EMP_SEQ = @EMP_SEQ

END 
GO
