USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		이규식
-- Create date: 2011-08-02
-- Description:	GTA 도시코드 맵핑 프로시져
-- =============================================
CREATE PROCEDURE [dbo].[SP_HTL_GTA_CITY_MAPPING]
	-- 업체 도시코드
	@ORG_CITY_CODE VARCHAR(10),
	-- 참좋은 도시코드
	@TRG_CITY_CODE VARCHAR(10)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	--GTA매핑쿼리

	DECLARE USER_CURSOR CURSOR FOR 
		SELECT CITY_CODE, HOTEL_CODE FROM TMP_GTA_HOTEL_DETAIL_KO WHERE CITY_CODE = @ORG_CITY_CODE   --보라카이

	DECLARE @CITY_CODE VARCHAR(255)
	DECLARE @HOTEL_CODE VARCHAR(255)
	DECLARE @MASTER_CODE VARCHAR(20)
	DECLARE @BASE_CODE VARCHAR(20)
	DECLARE @CNT_CODE INT

	OPEN USER_CURSOR

	FETCH NEXT FROM USER_CURSOR INTO @CITY_CODE, @HOTEL_CODE

	BEGIN TRANSACTION T1
	
	IF NOT EXISTS(SELECT * FROM HTL_CITY_CONNECT WHERE SUP_CODE = 'GTA' AND CITY_CODE = @TRG_CITY_CODE AND PROVIDER_CITY_CODE = @ORG_CITY_CODE)
	BEGIN
		INSERT INTO HTL_CITY_CONNECT(CITY_CODE, SUP_CODE, PROVIDER_CITY_CODE)
		VALUES (@TRG_CITY_CODE, 'GTA', @ORG_CITY_CODE)
	END
	
	BEGIN TRY

		-- 호텔전체루프를돈다
		WHILE @@FETCH_STATUS = 0 
		BEGIN
				
				SET @MASTER_CODE = NULL;
				
				-- 같은호텔검색이있는지를검색한다.
				SELECT @MASTER_CODE = X.MASTER_CODE FROM HTL_MASTER X
				INNER JOIN INF_HOTEL Y ON X.CNT_CODE = Y.CNT_CODE
				WHERE EXISTS (
					SELECT * FROM TMP_GTA_HOTEL_DETAIL_KO A
					INNER JOIN TMP_GTA_CITY_2 B ON A.CITY_CODE = B.CITY_CODE
					WHERE A.CITY_CODE = @CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE AND 
						--X.NATION_CODE = B.NATION_CODE AND X.CITY_CODE = B.CITY_CODE
						X.NATION_CODE = B.NATION_CODE AND X.CITY_CODE = @TRG_CITY_CODE
						AND
						(
							dbo.FN_REMOVE_SPECIAL(Y.TEL_NUMBER) = dbo.FN_REMOVE_SPECIAL(A.TEL_NUMBER)
							or
							dbo.FN_REMOVE_SPECIAL(Y.FAX_NUMBER) = dbo.FN_REMOVE_SPECIAL(A.FAX_NUMBER)
							or
							(A.HOTEL_URL = Y.HOMEPAGE AND LEN(A.HOTEL_URL) > 5)
							or 
							dbo.FN_REMOVE_SPECIAL(X.MASTER_NAME) = dbo.FN_REMOVE_SPECIAL(A.HOTEL_NAME)
							or
							(
							ISNULL(Y.ADDRESS , '') <> '' 
							AND
							dbo.FN_REMOVE_SPECIAL(
										ISNULL(A.ADDRESS1, '') + ISNULL(A.ADDRESS2, '') + ISNULL(A.ADDRESS3,'') + ISNULL(A.ADDRESS4, '')
												) = dbo.FN_REMOVE_SPECIAL(Y.ADDRESS)
							)
						)
				)
				
				-- 같은호텔이없을경우의처리
				IF ISNULL(@MASTER_CODE, '') = ''
				BEGIN
					SET @BASE_CODE = NULL
					
					-- 베이스마스터코드를구한다. (지역+ 'H' + 'H')
					-- 참좋은도시코드와매칭이안되는도시들은일단버린다.
					SELECT @BASE_CODE = D.SIGN + 'HH' FROM TMP_GTA_HOTEL_DETAIL_KO A
					--INNER JOIN HTL_CITY_CONNECT Z ON Z.PROVIDER_CITY_CODE = @CITY_CODE AND Z.SUP_CODE = 'GTA' 
					INNER JOIN HTL_CITY_CONNECT Z ON Z.PROVIDER_CITY_CODE = @ORG_CITY_CODE AND Z.SUP_CODE = 'GTA' 
					INNER JOIN PUB_CITY B ON Z.CITY_CODE = B.CITY_CODE
					INNER JOIN PUB_NATION C ON C.NATION_CODE = B.NATION_CODE
					INNER JOIN PUB_REGION D ON D.REGION_CODE = C.REGION_CODE
					--WHERE A.CITY_CODE = @CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE
					WHERE A.CITY_CODE = @ORG_CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE
					
					IF ISNULL(@BASE_CODE, '') <> ''
					BEGIN
						-- 호텔입력을위한새로운마스터코드를할당받는다.
						SELECT @BASE_CODE = dbo.FN_GET_HOTEL_MASTER_CODE(@BASE_CODE)
						PRINT '신규입력: ' + ISNULL(@BASE_CODE, '')
						
					
						-- 신규호텔을입력한다.
						INSERT INTO HTL_MASTER(MASTER_CODE, MASTER_NAME, REGION_CODE, NATION_CODE, STATE_CODE, CITY_CODE, NEW_CODE, HTL_GRADE)
						SELECT @BASE_CODE, A.HOTEL_NAME, D.REGION_CODE, C.NATION_CODE, B.STATE_CODE, B.CITY_CODE, '9999999', A.GRADE FROM TMP_GTA_HOTEL_DETAIL_KO A
						--INNER JOIN HTL_CITY_CONNECT Z ON Z.PROVIDER_CITY_CODE = @CITY_CODE AND Z.SUP_CODE = 'GTA' 
						INNER JOIN HTL_CITY_CONNECT Z ON Z.PROVIDER_CITY_CODE = @ORG_CITY_CODE AND Z.SUP_CODE = 'GTA' 
						INNER JOIN PUB_CITY B ON Z.CITY_CODE = B.CITY_CODE
						INNER JOIN PUB_NATION C ON C.NATION_CODE = B.NATION_CODE
						INNER JOIN PUB_REGION D ON D.REGION_CODE = C.REGION_CODE
						--WHERE A.CITY_CODE = @CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE	
						WHERE A.CITY_CODE = @ORG_CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE	
						
						-- 호텔컨텐츠를입력한다.
						INSERT INTO INF_MASTER(CNT_TYPE, KOR_TITLE, ENG_TITLE, REGION_CODE, NATION_CODE, STATE_CODE, CITY_CODE, GPS_X, GPS_Y, 
						SHORT_DESCRIPTION, DESCRIPTION, NEW_CODE, COPYRIGHT_REMARK, NEW_DATE)
						SELECT 2 AS CNT_TYPE, HOTEL_NAME, 
						(SELECT HOTEL_NAME FROM TMP_GTA_HOTEL_DETAIL_EN E WHERE A.CITY_CODE = E.CITY_CODE AND E.HOTEL_CODE = A.HOTEL_CODE), 
						D.REGION_CODE, C.NATION_CODE, B.STATE_CODE, B.CITY_CODE, A.GPS_X, A.GPS_Y, 
						A.SHORT_LOCATION, HTL_INFO, '9999999' AS NEW_CODE, 'GTA', GETDATE() FROM TMP_GTA_HOTEL_DETAIL_KO A
						--INNER JOIN HTL_CITY_CONNECT Z ON Z.PROVIDER_CITY_CODE = @CITY_CODE AND Z.SUP_CODE = 'GTA' 
						INNER JOIN HTL_CITY_CONNECT Z ON Z.PROVIDER_CITY_CODE = @ORG_CITY_CODE AND Z.SUP_CODE = 'GTA'
						INNER JOIN PUB_CITY B ON Z.CITY_CODE = B.CITY_CODE
						INNER JOIN PUB_NATION C ON C.NATION_CODE = B.NATION_CODE
						INNER JOIN PUB_REGION D ON D.REGION_CODE = C.REGION_CODE
						--WHERE A.CITY_CODE = @CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE	
						WHERE A.CITY_CODE = @ORG_CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE	
						
						-- 새로추가된컨텐츠고유키번호를가져온다.
						SELECT @CNT_CODE = @@IDENTITY
						
						-- 호텔컨텐츠확장정보를입력한다.
						INSERT INTO INF_HOTEL(CNT_CODE, STAY_CODE, TEL_NUMBER, FAX_NUMBER, HOMEPAGE, ADDRESS, 
						GRADE, CHECK_IN_TIME, DETAIL_LOCATION, FLR_COUNT, ROOM_COUNT)
						SELECT @CNT_CODE, 'B' AS STAY_CODE, TEL_NUMBER, FAX_NUMBER, HOTEL_URL, 
							   ADDRESS1 + ' ' + ADDRESS2 + ' ' + ADDRESS3 + ' ' + ADDRESS4 AS ADDRESS,
							   A.GRADE, A.CHECK_IN_TIME, A.DETAIL_LOCATION, A.FLR_COUNT, A.ROOM_COUNT 
						FROM TMP_GTA_HOTEL_DETAIL_KO A
						--WHERE A.CITY_CODE = @CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE		
						WHERE A.CITY_CODE = @ORG_CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE
						
						-- 컨텐츠의분류를입력한다.
						-- 분류: 숙박
						INSERT INTO INF_TYPE(CNT_CODE, CNT_ATT_CODE)
						VALUES(@CNT_CODE, 89)
						
						-- 분류: 호텔
						INSERT INTO INF_TYPE(CNT_CODE, CNT_ATT_CODE)
						VALUES(@CNT_CODE, 90)
						
						-- 호텔정보에컨텐츠코드를업데이트한다. 
						UPDATE HTL_MASTER 
						SET CNT_CODE = @CNT_CODE
						WHERE MASTER_CODE = @BASE_CODE
						
						-- 연결코드를입력한다. (맵핑)
						IF NOT EXISTS(SELECT * FROM HTL_CONNECT WHERE SUP_CODE = 'GTA' AND MASTER_CODE = @BASE_CODE AND CONNECT_CODE = @HOTEL_CODE AND PROVIDER_CITY_CODE = @CITY_CODE)
						BEGIN
							INSERT INTO HTL_CONNECT
							VALUES(@BASE_CODE, 'GTA', @HOTEL_CODE, 'Y', @CITY_CODE)
						END
						
					END
					
					
					
				END
				ELSE
				BEGIN
					PRINT '업데이트: ' + ISNULL(@MASTER_CODE, '')

						SET @CNT_CODE = 0
						
						SELECT @CNT_CODE = CNT_CODE FROM HTL_MASTER
						WHERE MASTER_CODE = @MASTER_CODE;
						
						-- 영업부에서행사에사용한호텔은업데이트작업을진행하지않는다.
						IF NOT EXISTS( 
							SELECT DISTINCT HTL_MASTER_CODE FROM PKG_MASTER_PRICE_HOTEL
							WHERE HTL_MASTER_CODE = @MASTER_CODE
							UNION ALL 
							SELECT DISTINCT HTL_MASTER_CODE FROM PKG_DETAIL_PRICE_HOTEL				
							WHERE HTL_MASTER_CODE = @MASTER_CODE
						)
						BEGIN

							
						
							-- 호텔정보업데이트를진행한다.
							IF @CNT_CODE > 0
							BEGIN
							
								-- 호텔마스터를수정한다.
								UPDATE HTL_MASTER 
								--SET MASTER_NAME = (SELECT HOTEL_NAME FROM TMP_GTA_HOTEL_DETAIL_KO WHERE HOTEL_CODE = @HOTEL_CODE AND CITY_CODE = @CITY_CODE)
								SET MASTER_NAME = (SELECT HOTEL_NAME FROM TMP_GTA_HOTEL_DETAIL_KO WHERE HOTEL_CODE = @HOTEL_CODE AND CITY_CODE = @ORG_CITY_CODE)
								WHERE MASTER_CODE = @MASTER_CODE
								
								-- 호텔컨텐츠마스터를수정한다.
								UPDATE INF_MASTER
									SET 
										KOR_TITLE = A.HOTEL_NAME,
										GPS_X = A.GPS_X, 
										GPS_Y = A.GPS_Y,
										DESCRIPTION = A.HTL_INFO,
										EDT_CODE = '9999999',
										EDT_DATE = GETDATE()
								FROM TMP_GTA_HOTEL_DETAIL_KO A
								--WHERE INF_MASTER.CNT_CODE = @CNT_CODE AND A.CITY_CODE = @CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE;	
								WHERE INF_MASTER.CNT_CODE = @CNT_CODE AND A.CITY_CODE = @ORG_CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE;

								UPDATE INF_MASTER
									SET 
										ENG_TITLE = A.HOTEL_NAME,
										ORG_TITLE = A.HOTEL_NAME
								FROM TMP_GTA_HOTEL_DETAIL_EN A
								--WHERE INF_MASTER.CNT_CODE = @CNT_CODE AND A.CITY_CODE = @CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE;	
								WHERE INF_MASTER.CNT_CODE = @CNT_CODE AND A.CITY_CODE = @ORG_CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE;

														
							
								-- 호텔컨텐츠를수정한다.
								UPDATE INF_HOTEL
									SET 
										SHORT_LOCATION = A.SHORT_LOCATION,
										TEL_NUMBER = A.TEL_NUMBER,
										FAX_NUMBER = A.FAX_NUMBER,
										[ADDRESS] = A.ADDRESS1 + ' ' + A.ADDRESS2 + ' ' + A.ADDRESS3 + ' ' + A.ADDRESS4,
										HOMEPAGE = HOTEL_URL,
										GRADE = A.GRADE,
										DETAIL_LOCATION = A.DETAIL_LOCATION,
										FLR_COUNT = A.FLR_COUNT,
										ROOM_COUNT = A.ROOM_COUNT
								FROM TMP_GTA_HOTEL_DETAIL_KO A
								--WHERE INF_HOTEL.CNT_CODE = @CNT_CODE AND A.CITY_CODE = @CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE;
								WHERE INF_HOTEL.CNT_CODE = @CNT_CODE AND A.CITY_CODE = @ORG_CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE;

							END
							-- 호텔컨텐츠가없을경우추가해준다
							ELSE
							BEGIN
								
								-- 호텔컨텐츠를입력한다.
								INSERT INTO INF_MASTER(CNT_TYPE, KOR_TITLE, ENG_TITLE, REGION_CODE, NATION_CODE, STATE_CODE, CITY_CODE, GPS_X, GPS_Y, 
								SHORT_DESCRIPTION, DESCRIPTION, NEW_CODE, COPYRIGHT_REMARK, NEW_DATE)
								SELECT 2 AS CNT_TYPE, HOTEL_NAME, 
								(SELECT HOTEL_NAME FROM TMP_GTA_HOTEL_DETAIL_EN E WHERE A.CITY_CODE = E.CITY_CODE AND E.HOTEL_CODE = A.HOTEL_CODE), 
								D.REGION_CODE, C.NATION_CODE, B.STATE_CODE, B.CITY_CODE, A.GPS_X, A.GPS_Y, 
								A.SHORT_LOCATION, HTL_INFO, '9999999' AS NEW_CODE, 'GTA', GETDATE() FROM TMP_GTA_HOTEL_DETAIL_KO A
								--INNER JOIN HTL_CITY_CONNECT Z ON Z.PROVIDER_CITY_CODE = @CITY_CODE AND Z.SUP_CODE = 'GTA' 
								INNER JOIN HTL_CITY_CONNECT Z ON Z.PROVIDER_CITY_CODE = @ORG_CITY_CODE AND Z.SUP_CODE = 'GTA' 
								INNER JOIN PUB_CITY B ON Z.CITY_CODE = B.CITY_CODE
								INNER JOIN PUB_NATION C ON C.NATION_CODE = B.NATION_CODE
								INNER JOIN PUB_REGION D ON D.REGION_CODE = C.REGION_CODE
								--WHERE A.CITY_CODE = @CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE		
								WHERE A.CITY_CODE = @ORG_CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE
								
								-- 새로추가된컨텐츠고유키번호를가져온다.
								SELECT @CNT_CODE = @@IDENTITY
								
								-- 호텔컨텐츠확장정보를입력한다.
								INSERT INTO INF_HOTEL(CNT_CODE, STAY_CODE, TEL_NUMBER, FAX_NUMBER, HOMEPAGE, ADDRESS, 
								GRADE, CHECK_IN_TIME, DETAIL_LOCATION, FLR_COUNT, ROOM_COUNT)
								SELECT @CNT_CODE, 'B' AS STAY_CODE, TEL_NUMBER, FAX_NUMBER, HOTEL_URL, 
									   ADDRESS1 + ' ' + ADDRESS2 + ' ' + ADDRESS3 + ' ' + ADDRESS4 AS ADDRESS,
									   A.GRADE, A.CHECK_IN_TIME, A.DETAIL_LOCATION, A.FLR_COUNT, A.ROOM_COUNT 
								FROM TMP_GTA_HOTEL_DETAIL_KO A
								--WHERE A.CITY_CODE = @CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE	
								WHERE A.CITY_CODE = @ORG_CITY_CODE AND A.HOTEL_CODE = @HOTEL_CODE	
								
								-- 컨텐츠의분류를입력한다.
								-- 분류: 숙박
								INSERT INTO INF_TYPE(CNT_CODE, CNT_ATT_CODE)
								VALUES(@CNT_CODE, 89)
								
								-- 분류: 호텔
								INSERT INTO INF_TYPE(CNT_CODE, CNT_ATT_CODE)
								VALUES(@CNT_CODE, 90)
								
								-- 호텔정보에컨텐츠코드를업데이트한다. 
								UPDATE HTL_MASTER 
								SET CNT_CODE = @CNT_CODE
								WHERE MASTER_CODE = @MASTER_CODE
										
							END
						END	

						-- 연결코드를입력한다. (맵핑)
						IF NOT EXISTS(SELECT * FROM HTL_CONNECT WHERE SUP_CODE = 'GTA' AND MASTER_CODE = @MASTER_CODE AND CONNECT_CODE = @HOTEL_CODE AND PROVIDER_CITY_CODE = @CITY_CODE)
						BEGIN
							INSERT INTO HTL_CONNECT
							VALUES(@MASTER_CODE, 'GTA', @HOTEL_CODE, 'Y', @CITY_CODE)
						END
					
					
					
				END

				FETCH NEXT FROM USER_CURSOR INTO @CITY_CODE, @HOTEL_CODE
				
			END

		-- 트랜잭션을 완료한다.			
		COMMIT TRANSACTION T1
		SELECT @ORG_CITY_CODE + ' 를 ' + @TRG_CITY_CODE + ' 로 맵핑되었습니다.'

	END TRY
		
	BEGIN CATCH
		-- 롤백처리를 한다.
		ROLLBACK TRANSACTION T1
		
		SELECT ERROR_MESSAGE() AS ErrorMessage;
	END CATCH

	CLOSE USER_CURSOR
	DEALLOCATE USER_CURSOR


END
GO
