USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*==================================================================================
	기본내용
====================================================================================
- SP 명 : SP_PKG_BEST_PRODUCT_SEARCH
- 기 능 : 베스트상품 타입별 조회 
====================================================================================
	참고내용
====================================================================================
- 예제
EXEC SP_PKG_BEST_PRODUCT_SEARCH 'VGT' , '101' , 0 ,   5 
EXEC SP_PKG_BEST_PRODUCT_SEARCH 'VGT' , '1010201' , '1' , 5
EXEC SP_PKG_BEST_PRODUCT_SEARCH 'VGT' , '10314' , '2' , 5
EXEC SP_PKG_BEST_PRODUCT_SEARCH 'VGT' , '1060101' , 2, 5
====================================================================================
	변경내역
====================================================================================
- 2011-12-26 박형만 신규 작성 
- 2012-03-02 박형만 WITH(NOLOCK)추가
===================================================================================*/
CREATE PROC [dbo].[SP_PKG_BEST_PRODUCT_SEARCH]
	@SITE_CODE		VARCHAR(3),
	@MENU_CODE		VARCHAR(20),
	@SEC_SEQ		INT , 
	@TYPE_SEQ		INT 
AS 
BEGIN 

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--SELECT * FROM PKG_BEST_DETAIL
--where site_code = 'vgt' and menu_code=  '1010101'
----@SEARCH_TYPE = 1 (상품리스트용 섹션 1,2) 일때 상위검색 실행 한다

--DECLARE @SITE_CODE	VARCHAR(3),
--	@MENU_CODE	VARCHAR(20),
--	@SEC_SEQ	int , 
--	@TYPE_SEQ	int 
--SELECT  @SITE_CODE = 'VGT' 
--,@MENU_CODE = '1010201'
--,@SEC_SEQ = 1
--,@TYPE_SEQ = 5 

--SELECT DATA FROM dbo.FN_SPLIT(@SEC_SEQ_STAR,',')
--	DECLARE @TYPE_SEQ INT 
--	SET @TYPE_SEQ = 
--		ISNULL(
--		(SELECT TYPE_SEQ FROM PKG_BEST_SECTION WITH(NOLOCK)
--		WHERE SEC_SEQ = @SEC_SEQ ) , 1 ) 
	
	--기본 행사 + 마스터 테이블 조회 
	
	--IF( @TYPE_SEQ IN (5,6) ) 
	--BEGIN
		--상위검색을 위한 테이블 
		DECLARE @TMP_MENU_TABLE  TABLE ( MENU_CODE VARCHAR(20), ORDER_NO INT  ) 
		DECLARE @TMP_MENU_CODE VARCHAR(20)
		DECLARE @PLEVEL INT 

		SET @PLEVEL = 1 
		SET @TMP_MENU_CODE = @MENU_CODE 

		--데이터가 없을경우 상위 검색 , 섹션번호 들어왓을때 
		IF NOT EXISTS ( SELECT * FROM PKG_BEST_DETAIL A WITH(NOLOCK) 
				WHERE A.SITE_CODE = @SITE_CODE 
				AND A.MENU_CODE = @MENU_CODE 
				AND A.SEC_SEQ = @SEC_SEQ 
			) 
			AND @SEC_SEQ > 0 
		BEGIN
			WHILE LEN(@TMP_MENU_CODE) > 2 
			BEGIN 
				INSERT INTO @TMP_MENU_TABLE  
				VALUES (@TMP_MENU_CODE,@PLEVEL)
				
				SET @TMP_MENU_CODE = SUBSTRING(@TMP_MENU_CODE,1,LEN(@TMP_MENU_CODE)-2) 
				SET @PLEVEL = @PLEVEL + 1 
			END 
		END 
		ELSE 
		BEGIN 
			--아닐 경우 메뉴코드 equal 검색 
			INSERT INTO @TMP_MENU_TABLE  
			VALUES (@TMP_MENU_CODE,1)
		END 
		;
		WITH TMP_LIST AS 
		(
			SELECT * FROM PKG_BEST_DETAIL A WITH(NOLOCK) 
			WHERE A.SITE_CODE = @SITE_CODE
			AND A.MENU_CODE IN( SELECT MENU_CODE FROM  @TMP_MENU_TABLE ) 
			AND ( @SEC_SEQ = 0  OR  A.SEC_SEQ = @SEC_SEQ )
			
		)
		
		--기본검색
		------------------------------------------------------------------------------
		-- 마스터
		SELECT A.*, B.REGION_CODE, B.NATION_CODE, B.STATE_CODE, B.CITY_CODE, B.[FILE_NAME], B.FILE_NAME_S, B.FILE_NAME_M, B.FILE_NAME_L, B.EXTENSION_NAME, B.FILE_TYPE 
		FROM 
		(
			SELECT 
				--A.PRO_TYPE,A.A_TYPE,A.B_TYPE,A.C_TYPE,A.REG_SEQ,A.CODE_TYPE,A.CODE,A.PRICE_SEQ,A.DEFAULT_PRICE,
				1 AS CODE_TYPE , 
				A.SITE_CODE ,A.MENU_CODE , A.SEC_SEQ , A.MAP_SEQ , A1.GROUP_CODE , 
				A.DTI_ITEM1 AS CODE , 
				ISNULL(A.DTI_ITEM3,'0') AS PRICE_SEQ ,
				ISNULL(A.DTI_ITEM4,'0') AS DEFAULT_PRICE ,
				ISNULL(A.DTI_ITEM4,'0') AS TYPE_CODE , 
				A.ORDER_NO , 
				A.NEW_CODE--,A.NEW_DATE,
				, ROW_NUMBER() OVER(PARTITION BY A.MENU_CODE ORDER BY A.MENU_CODE ,A.ORDER_NO) AS REG_ROW_CNT
				, CASE WHEN ISNULL(A.DTI_ITEM5,'') <> '' THEN A.DTI_ITEM5 ELSE  B.MASTER_NAME  END AS [NAME]
				, B.PKG_COMMENT, B.PKG_SUMMARY, B.LOW_PRICE AS [PRICE], B.MAIN_FILE_CODE AS [FILE_CODE]
				, (SELECT KOR_NAME FROM PUB_REGION WHERE [SIGN] = B.SIGN_CODE) AS [SIGN_NAME]
				, B.SIGN_CODE 
				, DBO.FN_PRO_GET_GRADE_AVG_MASTER(B.MASTER_CODE) AS [GRADE]
				, B.NEXT_DATE, B.LAST_DATE
				, B.BRANCH_CODE  , B.ATT_CODE 
			FROM TMP_LIST A
				INNER JOIN PKG_BEST_MAPPING A1 WITH(NOLOCK) 
					ON A.SITE_CODE = A1.SITE_CODE 
					AND A.MENU_CODE = A1.MENU_CODE
					AND A.SEC_SEQ = A1.SEC_SEQ
					AND A.MAP_SEQ = A1.MAP_SEQ 
			INNER JOIN PKG_MASTER B
				ON A.DTI_ITEM1 = B.MASTER_CODE
				AND (A.DTI_ITEM2 = '' OR   A.DTI_ITEM2 IS NULL)    -- 마스터  
			--#검색조건
		) A
		LEFT JOIN INF_FILE_MASTER B ON A.FILE_CODE = B.FILE_CODE
		UNION ALL
		-- 행사
		SELECT A.*, B.REGION_CODE, B.NATION_CODE, B.STATE_CODE, B.CITY_CODE, B.[FILE_NAME], B.FILE_NAME_S, B.FILE_NAME_M, B.FILE_NAME_L, B.EXTENSION_NAME, B.FILE_TYPE 
		FROM 
		(
			SELECT 
				--A.PRO_TYPE,A.A_TYPE,A.B_TYPE,A.C_TYPE,A.REG_SEQ,A.CODE_TYPE,A.CODE,A.PRICE_SEQ,A.DEFAULT_PRICE,A.NEW_CODE--,A.NEW_DATE,
				2 AS CODE_TYPE , 
				A.SITE_CODE ,A.MENU_CODE , A.SEC_SEQ ,  A.MAP_SEQ , A1.GROUP_CODE , 
				A.DTI_ITEM2 AS CODE , 
				ISNULL(A.DTI_ITEM3,'0') AS PRICE_SEQ ,
				ISNULL(A.DTI_ITEM4,'0') AS DEFAULT_PRICE ,
				ISNULL(A.DTI_ITEM4,'0') AS TYPE_CODE , 
				A.ORDER_NO , 
				A.NEW_CODE--,A.NEW_DATE,
				, ROW_NUMBER() OVER(PARTITION BY A.MENU_CODE ORDER BY A.MENU_CODE ,A.ORDER_NO) AS REG_ROW_CNT
				, CASE WHEN ISNULL(A.DTI_ITEM5,'') <> '' THEN A.DTI_ITEM5 ELSE  B.PRO_NAME  END AS PRO_NAME
				, (SELECT PKG_COMMENT FROM PKG_MASTER WHERE MASTER_CODE = B.MASTER_CODE) AS [PKG_COMMENT]
				, (SELECT PKG_SUMMARY FROM PKG_MASTER WHERE MASTER_CODE = B.MASTER_CODE) AS [PKG_SUMMARY]
				, C.ADT_PRICE, (SELECT TOP 1 FILE_CODE FROM PKG_DETAIL_FILE WHERE PRO_CODE = A.DTI_ITEM2 ORDER BY SHOW_ORDER) AS [FILE_CODE]
				, (SELECT KOR_NAME FROM PUB_REGION WHERE [SIGN] = (SELECT SIGN_CODE FROM PKG_MASTER WHERE MASTER_CODE IN (SELECT MASTER_CODE FROM PKG_DETAIL WHERE PRO_CODE = B.PRO_CODE))) AS [SIGN_NAME]
				, D.SIGN_CODE 
				, DBO.FN_PRO_GET_GRADE_AVG_PRO(B.PRO_CODE) AS [GRADE]
				, B.DEP_DATE as [NEXT_DATE], B.ARR_DATE as [LAST_DATE]
				, D.BRANCH_CODE  , D.ATT_CODE 
			FROM TMP_LIST A
			INNER JOIN PKG_BEST_MAPPING A1 WITH(NOLOCK)
				ON A.SITE_CODE = A1.SITE_CODE 
				AND A.MENU_CODE = A1.MENU_CODE
				AND A.SEC_SEQ = A1.SEC_SEQ
				AND A.MAP_SEQ = A1.MAP_SEQ 
			INNER JOIN PKG_DETAIL B WITH(NOLOCK) ON A.DTI_ITEM2 = B.PRO_CODE
				AND A.DTI_ITEM2 <> ''   -- 행사 
			INNER JOIN PKG_DETAIL_PRICE C WITH(NOLOCK) ON A.DTI_ITEM2 = C.PRO_CODE AND A.DTI_ITEM3 = C.PRICE_SEQ
			INNER JOIN PKG_MASTER D WITH(NOLOCK) ON B.MASTER_CODE = D.MASTER_CODE
			--#검색조건
		) A
		LEFT JOIN INF_FILE_MASTER B WITH(NOLOCK) ON A.FILE_CODE = B.FILE_CODE
		ORDER BY MENU_CODE DESC, ORDER_NO 
		------------------------------------------------------------------------------
		
	--END 
END 

GO
