USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
2011-07-19 SP_COD_GETSEQ -> SP_COD_GETSEQ_UNLIMITED 사용으로 변경
*/
CREATE  PROCEDURE [dbo].[SP_BBS_MASTER_INSERT]
	@MASTER_SEQ INT OUTPUT,
    @MASTER_TYPE CHAR(1),
	@MASTER_SUBJECT NVARCHAR(50),
	@FILE_COUNT TINYINT,
	@SHOW_COUNT TINYINT,	
	@CATEGORY_GROUP VARCHAR(20),
	@NOTICE_YN CHAR(1),
	@HISTORY_YN CHAR(1),
	@COMMENT_YN CHAR(1),
	@USE_YN CHAR(1),
	@REALNAME_YN CHAR(1),
	@ICON_YN CHAR(1) ,
	@SCOPE_YN CHAR(1) ,
	@MANAGER_YN CHAR(1),
	@TEAM_CODE VARCHAR(3),
	@NEW_CODE VARCHAR(7),
	@MENU_CODE INT
	
AS
BEGIN
	SET NOCOUNT OFF;
		
	BEGIN
			
			EXEC	[dbo].[SP_COD_GETSEQ_UNLIMITED] 'BM', @MASTER_SEQ OUTPUT
			--print @MASTER_SEQ

			INSERT INTO BBS_MASTER
			(
				MASTER_SEQ,MASTER_TYPE,MASTER_ATTR,MASTER_SUBJECT,FILE_COUNT,NOTICE_YN,
				SHOW_COUNT,HISTORY_YN,COMMENT_YN,
				REALNAME_YN,CATEGORY_GROUP,ICON_YN,SCOPE_YN,MANAGER_YN,TEAM_CODE,NEW_CODE,NEW_DATE
			)
			VALUES
			(
				@MASTER_SEQ,@MASTER_TYPE,'10',@MASTER_SUBJECT,@FILE_COUNT,@NOTICE_YN,
				@SHOW_COUNT,@HISTORY_YN,@COMMENT_YN,
				@REALNAME_YN,@CATEGORY_GROUP,@ICON_YN,@SCOPE_YN,@MANAGER_YN,@TEAM_CODE,@NEW_CODE,GETDATE()
			)

			INSERT INTO COD_PUBLIC
			(PUB_TYPE,PUB_CODE,PUB_VALUE,PUB_VALUE2)
			VALUES
			('BOD.TYPE',@MASTER_SEQ,@MENU_CODE,@MASTER_SUBJECT)
	END
END
GO
