USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		 
-- Create date:  
-- Description:	<팩스 담당자 이동>
-- =============================================
CREATE PROCEDURE [dbo].[SP_FAX_MOVE_EMP]
	@FAX_SEQ VARCHAR(2000),
	@NEW_CODE EMP_CODE , 
	@EDT_CODE EMP_CODE
AS
BEGIN	
	SET NOCOUNT ON;
    
	DECLARE @SEQ INT;
	DECLARE @TEMP_SEQ VARCHAR(20);
	DECLARE @TEMP_SEQ_LIST VARCHAR(2000);
	DECLARE @INDEX INT;
	
	DECLARE @RCV_NUMBER1 VARCHAR(4)
	DECLARE @RCV_NUMBER2 VARCHAR(4)
	DECLARE @RCV_NUMBER3 VARCHAR(4)
	--사번으로 새 FAX 번호 담기 
	SELECT @RCV_NUMBER1 = FAX_NUMBER1 , 
		@RCV_NUMBER2 =  FAX_NUMBER2, 
		@RCV_NUMBER3 =  FAX_NUMBER3 
	FROM EMP_MASTER WHERE EMP_CODE = @NEW_CODE 
	
	
	IF( ISNULL(@RCV_NUMBER1,'') <>''
		AND ISNULL(@RCV_NUMBER2,'') <>''
		AND ISNULL(@RCV_NUMBER3,'') <>'' )
	BEGIN
		
		DECLARE @TMP_SEQ TABLE 
		( ID INT , DATA CHAR(17) ) 
		INSERT INTO @TMP_SEQ 
		SELECT ID,DATA FROM DBO.FN_SPLIT(@FAX_SEQ,',')
		--SELECT ID,DATA FROM DBO.FN_SPLIT('A,1',',')
	
		DECLARE @MAX_CNT INT 
		DECLARE @LOOP_CNT INT 
		
		SET @LOOP_CNT = 1
		SET @MAX_CNT = ( SELECT MAX(ID) FROM @TMP_SEQ ) 
		WHILE @LOOP_CNT <= @MAX_CNT 
		BEGIN 
			DECLARE @TMP_FAX_SEQ CHAR(17)
			SET @TMP_FAX_SEQ = (SELECT DATA FROM @TMP_SEQ WHERE ID = @LOOP_CNT )
	
			--FAX_GROUP 비교 하기 
			DECLARE @FAX_GROUP INT 
			SELECT @FAX_GROUP = FAX_GROUP
			FROM FAX_MASTER WHERE FAX_SEQ = @TMP_FAX_SEQ;
			
			DECLARE @TEAM_CODE VARCHAR(10)
			SELECT @TEAM_CODE = TEAM_CODE FROM EMP_MASTER WHERE EMP_CODE = @NEW_CODE 
			
			DECLARE @NEW_FAX_GROUP INT 
			SET @NEW_FAX_GROUP = ( SELECT TOP 1 PUB_VALUE2   FROM COD_PUBLIC 
				WHERE PUB_TYPE ='FAX.TEAM'
				AND PUB_CODE = @TEAM_CODE  )
				
			IF @FAX_GROUP <> @NEW_FAX_GROUP
			BEGIN 
				SET @FAX_GROUP = @NEW_FAX_GROUP 
			END 
			
			--FAX_RECEIVE 업데이트 
			UPDATE FAX_RECEIVE SET RCV_NUMBER1 = @RCV_NUMBER1, RCV_NUMBER2 = @RCV_NUMBER2, RCV_NUMBER3 = @RCV_NUMBER3
			WHERE FAX_SEQ = @TMP_FAX_SEQ;
			
			--FAX_MASTER 업데이트 , FAX_GROUP 업데이트 
			UPDATE FAX_MASTER 
			SET REMARK = ISNULL(REMARK,'') + @EDT_CODE +' '+ CONVERT(VARCHAR(10),GETDATE(),121) +'팩스이동'
				, FAX_GROUP = @FAX_GROUP
			WHERE FAX_SEQ = @TMP_FAX_SEQ;	
			
			SET @LOOP_CNT = @LOOP_CNT + 1 
		END
		SELECT @LOOP_CNT  
	END 
	ELSE 
	BEGIN
		SELECT 0 
	END 
END
GO
