USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO

-- =============================================
-- AUTHOR:김성호
-- CREATE DATE: 2011-10-21
-- DESCRIPTION:	메뉴 수정 (메뉴 등록에서도 사용)
-- =============================================

CREATE PROCEDURE [dbo].[SP_PUB_VGT_MENU_UPDATE]
	@MENU_CODE            VARCHAR(20),
	@MENU_NAME            VARCHAR(100),
	@REGION_CODE          VARCHAR(30),
	@CITY_CODE            VARCHAR(30),
	@NATION_CODE          VARCHAR(30),
	@GROUP_CODE           VARCHAR(100),
	@ATT_CODE             VARCHAR(50),
	@LINK_URL             VARCHAR(200),
	@CATEGORY_TYPE        VARCHAR(1),
	@VIEW_TYPE            VARCHAR(1),
	@ORDER_TYPE           INTEGER,
	@BEST_CODE            VARCHAR(30),
	@FONT_STYLE           VARCHAR(30),
	@FONT_COLOR           VARCHAR(30),
	@BASIC_CODE           VARCHAR(20),
	@IMAGE_URL			  VARCHAR(200),
	@EDT_CODE             EDT_CODE,
	@OLD_MENU_CODE		  VARCHAR(2)
AS
BEGIN

SET NOCOUNT ON;

	UPDATE PUB_VGT_MENU SET MENU_NAME = @MENU_NAME, REGION_CODE = @REGION_CODE, CITY_CODE = @CITY_CODE
		, NATION_CODE = @NATION_CODE, GROUP_CODE = @GROUP_CODE, ATT_CODE = @ATT_CODE, LINK_URL = @LINK_URL
		, CATEGORY_TYPE = @CATEGORY_TYPE, VIEW_TYPE = @VIEW_TYPE, ORDER_TYPE = @ORDER_TYPE
		, BEST_CODE = @BEST_CODE, FONT_STYLE = @FONT_STYLE, FONT_COLOR = @FONT_COLOR, BASIC_CODE = @BASIC_CODE
		, IMAGE_URL = @IMAGE_URL, EDT_CODE = @EDT_CODE, EDT_DATE = GETDATE()
		, OLD_MENU_CODE = @OLD_MENU_CODE
	WHERE MENU_CODE = @MENU_CODE
	
END
GO
