USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<김성호>
-- Create date: <2009-08-12>
-- Description:	<마스터행사 일정 등록 및 수정>
--	2019-03-15	박형만	네이버 관련 컬럼 추가 
-- =============================================
CREATE PROCEDURE [dbo].[SP_PKG_MASTER_INSERT_UPDATE_SCHEDULE]
	@MASTER_CODE	VARCHAR(10),
	@SCH_SEQ		INT,
	@SCH_NAME		NVARCHAR(50),
	@FLAG			CHAR(1)
AS
BEGIN
	IF @FLAG = 'I'					-- 신규
	BEGIN
		IF @SCH_NAME = NULL
			SET @SCH_NAME = '신규일정';
		
		DECLARE @NEW_SCH_SEQ INT
		SELECT @NEW_SCH_SEQ = ISNULL(MAX(SCH_SEQ), 0) + 1 FROM PKG_MASTER_SCH_MASTER   WHERE MASTER_CODE = @MASTER_CODE
		
		-- 신규 행사일정 마스터 저장
		INSERT INTO PKG_MASTER_SCH_MASTER VALUES (@MASTER_CODE, @NEW_SCH_SEQ, @SCH_NAME)
	
		IF EXISTS(SELECT 1 FROM PKG_MASTER_SCH_MASTER   WHERE MASTER_CODE = @MASTER_CODE AND SCH_SEQ = @SCH_SEQ)
		BEGIN
			-- 행사일정 일자 저장 
			INSERT INTO PKG_MASTER_SCH_DAY(MASTER_CODE, SCH_SEQ, DAY_SEQ, DAY_NUMBER, FREE_SCH_YN)  -- 자유일정유무 19.03 추가 
			SELECT MASTER_CODE, @NEW_SCH_SEQ, DAY_SEQ, DAY_NUMBER , FREE_SCH_YN FROM PKG_MASTER_SCH_DAY  
			WHERE MASTER_CODE = @MASTER_CODE AND SCH_SEQ = @SCH_SEQ

			-- 행사일정 도시 저장
			INSERT INTO PKG_MASTER_SCH_CITY(MASTER_CODE, SCH_SEQ, DAY_SEQ, CITY_SEQ, CITY_CODE, MAINCITY_YN, CITY_SHOW_ORDER)
			SELECT MASTER_CODE, @NEW_SCH_SEQ, DAY_SEQ, CITY_SEQ, CITY_CODE, MAINCITY_YN, CITY_SHOW_ORDER FROM PKG_MASTER_SCH_CITY  
			WHERE MASTER_CODE = @MASTER_CODE AND SCH_SEQ = @SCH_SEQ

			-- 행사일정 컨텐츠 저장
			INSERT INTO PKG_MASTER_SCH_CONTENT(MASTER_CODE, SCH_SEQ, DAY_SEQ, CITY_SEQ, CNT_SEQ,
				CNT_CODE, CNT_INFO, CNT_SHOW_ORDER)
			SELECT MASTER_CODE, @NEW_SCH_SEQ, DAY_SEQ, CITY_SEQ, CNT_SEQ, CNT_CODE, CNT_INFO, CNT_SHOW_ORDER FROM PKG_MASTER_SCH_CONTENT  
			WHERE MASTER_CODE = @MASTER_CODE AND SCH_SEQ = @SCH_SEQ
		END
		ELSE
		BEGIN
			DECLARE @TOURDAY INT, @SCHEDULEDAY INT
			SELECT @TOURDAY = ISNULL(TOUR_DAY, 0), @SCHEDULEDAY = 0 FROM PKG_MASTER   WHERE MASTER_CODE = @MASTER_CODE
			
			WHILE (@SCHEDULEDAY < @TOURDAY)
			BEGIN
				SET @SCHEDULEDAY = @SCHEDULEDAY + 1
				INSERT INTO PKG_MASTER_SCH_DAY (MASTER_CODE, SCH_SEQ, DAY_SEQ,DAY_NUMBER ) 
				VALUES (@MASTER_CODE, @NEW_SCH_SEQ, @SCHEDULEDAY, @SCHEDULEDAY);
			END
		END
		
		-- 일정 마스터 순번 리턴
		SELECT @NEW_SCH_SEQ
	END
	ELSE										-- 수정
	BEGIN
		UPDATE PKG_MASTER_SCH_MASTER SET SCH_NAME = @SCH_NAME WHERE MASTER_CODE = @MASTER_CODE AND SCH_SEQ = @SCH_SEQ
		-- 일정 마스터 순번 리턴
		SELECT @SCH_SEQ
	END
END





GO
