USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*================================================================================================================
■ USP_NAME					: XP_COM_BIZTRIP_AIR_USER_RULE_SELECT
■ DESCRIPTION				: BTMS 출장자 규정 검색 - 항공
■ INPUT PARAMETER			: 
	@AGT_CODE				: 거래처코드
	@EMP_SEQ				: 직원 번호
	@CLASS					: 좌석 등급 (일반석E 비즈니스석B 일등석F)
■ OUTPUT PARAMETER			: 
■ EXEC						: 

	EXEC DBO.XP_COM_BIZTRIP_AIR_USER_RULE_SELECT 92756, 103, 'E'

	EXEC DBO.XP_COM_BIZTRIP_AIR_USER_RULE_SELECT '92756', '103, 109,112,101,105,104,107'
■ MEMO						: 
------------------------------------------------------------------------------------------------------------------
■ CHANGE HISTORY
------------------------------------------------------------------------------------------------------------------
   DATE				AUTHOR			DESCRIPTION           
------------------------------------------------------------------------------------------------------------------
   2016-02-25		이유라			최초생성
   2016-02-25		정지용			디자인에 맞게 수정
   2016-02-26		정지용			그룹 순번별 TOP 1로 뽑고 ROW 식으로 쿼리변경
   2016-02-26		이유라			EMP_ROW_COUNT 컬럼추가
   2016-03-10		정지용			출장자 규정없어도 NULL로 SELECT
   2016-03-15		김성호			규정검색 수정 및 리뉴얼
   2016-08-19		이유라			정렬순서 수정
================================================================================================================*/

CREATE PROC [dbo].[XP_COM_BIZTRIP_AIR_USER_RULE_SELECT]
	@AGT_CODE	VARCHAR(10),
	@EMP_SEQ_STRING VARCHAR(500)

AS
BEGIN

	WITH EMP_LIST AS
	(
		SELECT * FROM DBO.FN_COM_BIZTRIP_GROUP_INFO(@AGT_CODE, @EMP_SEQ_STRING) A
	)
	, COUNT_LIST AS (
		SELECT A.AGT_CODE, A.EMP_SEQ, A.BT_SEQ, COUNT(*) AS [RULE_COUNT]
		FROM EMP_LIST A
		LEFT JOIN COM_AIR_RULE B ON A.AGT_CODE = B.AGT_CODE AND A.BT_SEQ = B.BT_SEQ AND B.USE_YN = 'Y'
		GROUP BY A.AGT_CODE, A.EMP_SEQ, A.BT_SEQ
	)
	SELECT 
		A.AGT_CODE, A.BT_SEQ, A.EMP_SEQ, D.KOR_NAME AS [EMP_NAME], E.POS_NAME, F.TEAM_NAME,
		B.AIR_SAME_YN, B.AIR_LIKE_YN, C.START_HOUR, C.END_HOUR, C.CLASS, A.ORDER_NUM, G.RULE_COUNT
	FROM EMP_LIST A
	LEFT JOIN COM_BIZTRIP_GROUP B WITH(NOLOCK) ON A.AGT_CODE = B.AGT_CODE AND A.BT_SEQ = B.BT_SEQ
	LEFT JOIN COM_AIR_RULE C WITH(NOLOCK) ON A.AGT_CODE = C.AGT_CODE AND A.BT_SEQ = C.BT_SEQ AND C.USE_YN = 'Y'
	LEFT JOIN COM_EMPLOYEE D WITH(NOLOCK) ON A.AGT_CODE = D.AGT_CODE AND A.EMP_SEQ = D.EMP_SEQ
	LEFT JOIN COM_POSITION E WITH(NOLOCK) ON D.AGT_CODE = E.AGT_CODE AND D.POS_SEQ = E.POS_SEQ
	LEFT JOIN COM_TEAM F WITH(NOLOCK) ON D.AGT_CODE = F.AGT_CODE AND D.TEAM_SEQ = F.TEAM_SEQ
	LEFT JOIN COUNT_LIST G ON A.AGT_CODE = G.AGT_CODE AND A.EMP_SEQ = G.EMP_SEQ AND A.BT_SEQ = G.BT_SEQ
	--ORDER BY A.AGT_CODE, A.EMP_SEQ, B.ORDER_NUM;
	ORDER BY A.AGT_CODE, B.ORDER_NUM

	--WITH TOP_GROUP_LIST AS
	--(
	--	SELECT 
	--		--ROW_NUMBER() OVER (PARTITION BY A.BT_EMP_SEQ ORDER BY MIN(B.ORDER_NUM) ASC) AS [ROW_NUMBER], 
	--		ROW_NUMBER() OVER (PARTITION BY A.BT_EMP_SEQ ORDER BY MIN(ISNULL(B.ORDER_NUM, 999999)) ASC) AS [ROW_NUMBER], 
	--		A.AGT_CODE, A.BT_SEQ, A.BTE_SEQ, A.BT_EMP_SEQ,
	--		B.ALL_YN, B.REPORT_YN, B.EMAIL_SEND_YN, B.CONFIRM_YN, B.HOTEL_LIKE_YN, B.AIR_SAME_YN, B.AIR_LIKE_YN,
	--		--B.BTG_NAME, B.ORDER_NUM
	--		B.BTG_NAME, ISNULL(B.ORDER_NUM, 999999) AS ORDER_NUM
	--	FROM COM_BIZTRIP_EMPLOYEE A WITH(NOLOCK)
	--	--INNER JOIN COM_BIZTRIP_GROUP B WITH(NOLOCK) ON A.AGT_CODE = B.AGT_CODE AND A.BT_SEQ = B.BT_SEQ AND B.USE_YN = 'Y'
	--	LEFT JOIN COM_BIZTRIP_GROUP B WITH(NOLOCK) ON A.AGT_CODE = B.AGT_CODE AND A.BT_SEQ = B.BT_SEQ AND B.USE_YN = 'Y'
	--	WHERE 
	--		A.AGT_CODE = @AGT_CODE 
	--			AND A.BT_EMP_TYPE = 'E'
	--			AND A.BT_EMP_SEQ IN (SELECT Data FROM dbo.FN_XML_SPLIT(@EMP_SEQ_STRING, ','))	
	--	GROUP BY A.AGT_CODE, A.BT_SEQ, A.BTE_SEQ, A.BT_EMP_SEQ, ORDER_NUM, B.ALL_YN, B.REPORT_YN, B.EMAIL_SEND_YN, B.CONFIRM_YN, B.HOTEL_LIKE_YN, B.AIR_SAME_YN, B.AIR_LIKE_YN, B.BTG_NAME
	--)
	--SELECT
	--	A.AGT_CODE, A.BT_SEQ, A.BTE_SEQ, A.BT_EMP_SEQ,
	--	C.KOR_NAME, D.POS_NAME, E.TEAM_NAME,
	--	A.BTG_NAME, A.ALL_YN, A.REPORT_YN, A.EMAIL_SEND_YN, A.CONFIRM_YN, A.HOTEL_LIKE_YN,
	--	B.AIR_RULE_SEQ, 
	--	B.START_HOUR, B.END_HOUR, B.CLASS,
	--	A.AIR_SAME_YN, A.AIR_LIKE_YN, A.ORDER_NUM, 
	--	(SELECT COUNT(*) FROM COM_AIR_RULE F WHERE A.BT_SEQ = F.BT_SEQ AND F.USE_YN = 'Y') AS EMP_ROW_COUNT
	--FROM TOP_GROUP_LIST A
	--LEFT JOIN COM_AIR_RULE B WITH(NOLOCK) ON A.AGT_CODE = B.AGT_CODE AND A.BT_SEQ = B.BT_SEQ AND B.USE_YN = 'Y'
	--JOIN COM_EMPLOYEE C WITH(NOLOCK) ON A.AGT_CODE = C.AGT_CODE AND A.BT_EMP_SEQ = C.EMP_SEQ
	--LEFT JOIN COM_POSITION D WITH(NOLOCK) ON C.AGT_CODE = D.AGT_CODE AND C.POS_SEQ = D.POS_SEQ
	--LEFT JOIN COM_TEAM E WITH(NOLOCK) ON C.AGT_CODE = E.AGT_CODE AND C.TEAM_SEQ = E.TEAM_SEQ
	--WHERE A.ROW_NUMBER = 1
	--ORDER BY A.ORDER_NUM ASC

--SELECT AGT_CODE, KOR_NAME, POS_NAME, TEAM_NAME, START_HOUR, END_HOUR, CLASS, AIR_SAME_YN, AIR_LIKE_YN
--FROM (
--	SELECT
--		A.AGT_CODE, A.BT_SEQ, A.BTE_SEQ, A.BT_EMP_SEQ,
--		D.KOR_NAME, E.POS_NAME, F.TEAM_NAME,
--		B.BTG_NAME, 
--		B.ALL_YN, B.REPORT_YN, B.EMAIL_SEND_YN, B.CONFIRM_YN, B.HOTEL_LIKE_YN,
--		ISNULL(STUFF((SELECT (',' + CONVERT(VARCHAR, AIR_RULE_SEQ) ) AS [text()] FROM COM_AIR_RULE C WITH(NOLOCK) WHERE A.AGT_CODE = C.AGT_CODE AND A.BT_SEQ = C.BT_SEQ AND C.USE_YN = 'Y' FOR XML PATH('')), 1, 1, '') , '') AS AIR_RULE_SEQ,
--		ISNULL(STUFF((SELECT (',' + CONVERT(VARCHAR, START_HOUR) ) AS [text()] FROM COM_AIR_RULE C WITH(NOLOCK) WHERE A.AGT_CODE = C.AGT_CODE AND A.BT_SEQ = C.BT_SEQ AND C.USE_YN = 'Y' FOR XML PATH('')), 1, 1, '') , '') AS START_HOUR,
--		ISNULL(STUFF((SELECT (',' + CONVERT(VARCHAR, END_HOUR) ) AS [text()] FROM COM_AIR_RULE C WITH(NOLOCK) WHERE A.AGT_CODE = C.AGT_CODE AND A.BT_SEQ = C.BT_SEQ AND C.USE_YN = 'Y' FOR XML PATH('')), 1, 1, '') , '') AS END_HOUR,
--		ISNULL(STUFF((SELECT (',' + CONVERT(VARCHAR, CLASS) ) AS [text()] FROM COM_AIR_RULE C WITH(NOLOCK) WHERE A.AGT_CODE = C.AGT_CODE AND A.BT_SEQ = C.BT_SEQ AND C.USE_YN = 'Y' FOR XML PATH('')), 1, 1, '') , '') AS CLASS,
--		B.AIR_SAME_YN, B.AIR_LIKE_YN, B.ORDER_NUM
--	FROM COM_BIZTRIP_EMPLOYEE A
--	JOIN COM_BIZTRIP_GROUP B ON A.AGT_CODE = B.AGT_CODE AND A.BT_SEQ = B.BT_SEQ AND B.USE_YN = 'Y'
--	JOIN COM_EMPLOYEE D ON A.AGT_CODE = D.AGT_CODE AND A.BT_EMP_SEQ = D.EMP_SEQ
--	LEFT JOIN COM_POSITION E ON A.AGT_CODE = E.AGT_CODE AND D.POS_SEQ = E.POS_SEQ
--	LEFT JOIN COM_TEAM F ON A.AGT_CODE = F.AGT_CODE AND D.TEAM_SEQ = F.TEAM_SEQ
--	WHERE 
--		A.AGT_CODE = @AGT_CODE 
--			AND A.BT_EMP_TYPE = 'E'
--			AND A.BT_EMP_SEQ IN (SELECT Data FROM dbo.FN_XML_SPLIT(@EMP_SEQ_STRING, ','))	
--) MST ORDER BY MST.ORDER_NUM ASC
/*
SELECT AGT_CODE, EMP_NAME, POS_NAME, TEAM_NAME, START_HOUR, END_HOUR, CLASS, AIR_SAME_YN, AIR_LIKE_YN
FROM (
	SELECT
		TOP 1
		A.AGT_CODE, A.BT_SEQ, A.BTE_SEQ, A.BT_EMP_TYPE, A.BT_EMP_SEQ, D.KOR_NAME AS EMP_NAME, E.POS_NAME, F.TEAM_NAME,
		B.BTG_NAME, B.ALL_YN, B.REPORT_YN, B.EMAIL_SEND_YN, B.CONFIRM_YN, B.HOTEL_LIKE_YN,
		C.AIR_RULE_SEQ, C.START_HOUR, C.END_HOUR, C.CLASS,
		B.AIR_SAME_YN, B.AIR_LIKE_YN
	FROM COM_BIZTRIP_EMPLOYEE A
	JOIN COM_BIZTRIP_GROUP B ON A.BT_SEQ = B.BT_SEQ AND B.USE_YN = 'Y'
	JOIN COM_AIR_RULE C ON A.BT_SEQ = C.BT_SEQ AND C.USE_YN = 'Y'
	JOIN COM_EMPLOYEE D ON A.BT_EMP_SEQ = D.EMP_SEQ
	JOIN COM_POSITION E ON D.POS_SEQ = E.POS_SEQ
	JOIN COM_TEAM F ON D.TEAM_SEQ = F.TEAM_SEQ
	WHERE A.AGT_CODE = @AGT_CODE AND A.BT_EMP_SEQ = @EMP_SEQ AND CLASS = @CLASS
	ORDER BY B.ORDER_NUM ASC
) MST
*/
END

GO
