USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:권윤경
-- Create date: 2008-03-25
-- Description:	쪽지 카테고리 삭제 SP
CREATE PROCEDURE [dbo].[SP_PRI_NOTE_DELETE_CATEGORY]
@CAT_SEQ_NO INT,
@EMP_CODE	VARCHAR(7)

AS
	BEGIN
		UPDATE PRI_NOTE_CATEGORY SET DEL_YN='Y' WHERE CAT_SEQ_NO=@CAT_SEQ_NO;  --카테고리 삭제

		UPDATE PRI_NOTE_RECEIPT SET SEND_DEL_YN = 'Y', SEND_CAT_SEQ_NO=0 
		WHERE NOTE_SEQ_NO IN (SELECT NOTE_SEQ_NO FROM PRI_NOTE WHERE NEW_CODE = @EMP_CODE) AND SEND_CAT_SEQ_NO = @CAT_SEQ_NO;   --보낸쪽지 삭제

		UPDATE PRI_NOTE_RECEIPT SET RCV_DEL_YN = 'Y', RCV_CAT_SEQ_NO=0 
		WHERE EMP_CODE = @EMP_CODE AND RCV_CAT_SEQ_NO = @CAT_SEQ_NO;  --받은쪽지 삭제
		
	END
GO
