USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*================================================================================================================
■ USP_NAME					: SP_SEND_MESSAGE_RES_INFO_SELECT
■ DESCRIPTION				: 알림톡 발송 기본 정보 (예약기준)
■ INPUT PARAMETER			: 
■ OUTPUT PARAMETER			: 
■ EXEC						: 
	EXEC SP_SEND_MESSAGE_RES_INFO_SELECT 'RP1805176801', ''
	EXEC SP_SEND_MESSAGE_RES_INFO_SELECT '', 'XXF777-180627'
■ MEMO						: 
------------------------------------------------------------------------------------------------------------------
■ CHANGE HISTORY                   
------------------------------------------------------------------------------------------------------------------
   DATE				AUTHOR			DESCRIPTION           
------------------------------------------------------------------------------------------------------------------  
    2018-06-19		정지용			최초생성
	2018-12-14		박형만			현재 최종계약서번호 가져오기 
	2019-12-12		박형만			개인별,팀별 대표번호 가져오기 함수 필드 추가 ( 대표번호 발송 관련 ) 
================================================================================================================*/ 
CREATE PROC [dbo].[SP_SEND_MESSAGE_RES_INFO_SELECT]
	@RES_CODE CHAR(12),
	@PRO_CODE VARCHAR(20)
AS 
BEGIN
	SELECT TOP 1
		  A.RES_CODE
		, A.PRO_TYPE
		, A.PRO_CODE
		, A.PRO_NAME
		, A.PRICE_SEQ
		, A.RES_NAME
		, A.LAST_PAY_DATE
		, DBO.FN_RES_GET_TOTAL_PRICE(A.RES_CODE) AS [TOTAL_PRICE] 
		, DBO.FN_RES_GET_PAY_PRICE(A.RES_CODE) AS [PAY_PRICE]
		, ISNULL(D.FAX_NUMBER1,'') +'-' + ISNULL(D.FAX_NUMBER2,'') +'-' +  ISNULL(D.FAX_NUMBER3,'') AS FAX_NUMBER 
		, F.TEAM_NAME
		, A.NEW_TEAM_CODE AS TEAM_CODE 
		, D.EMAIL AS EMAIL
		, A.NEW_CODE
		, D.KOR_NAME AS NEW_NAME
		, D.INNER_NUMBER1, D.INNER_NUMBER2, D.INNER_NUMBER3		
		, C.FIRST_MEET
		, G.DEP_TRANS_CODE
		, G.DEP_TRANS_NUMBER
		, DEP_DEP_DATE
		, DEP_DEP_TIME
		, (SELECT DBO.FN_PUB_GET_CITY_NAME(AA.CITY_CODE) FROM PUB_AIRPORT AA WITH(NOLOCK) WHERE AA.AIRPORT_CODE = G.DEP_DEP_AIRPORT_CODE) AS [DEP_DEP_CITY_NAME]
		, DEP_ARR_DATE
		, DEP_ARR_TIME
		, (SELECT DBO.FN_PUB_GET_CITY_NAME(AA.CITY_CODE) FROM PUB_AIRPORT AA WITH(NOLOCK) WHERE AA.AIRPORT_CODE = G.DEP_ARR_AIRPORT_CODE) AS [DEP_ARR_CITY_NAME]
		, G.ARR_TRANS_CODE
		, G.ARR_TRANS_NUMBER
		, ARR_DEP_DATE
		, ARR_DEP_TIME
		, (SELECT DBO.FN_PUB_GET_CITY_NAME(AA.CITY_CODE) FROM PUB_AIRPORT AA WITH(NOLOCK) WHERE AA.AIRPORT_CODE = G.ARR_DEP_AIRPORT_CODE) AS [ARR_DEP_CITY_NAME]
		, ARR_ARR_DATE
		, ARR_ARR_TIME			
		, (SELECT DBO.FN_PUB_GET_CITY_NAME(AA.CITY_CODE) FROM PUB_AIRPORT AA WITH(NOLOCK) WHERE AA.AIRPORT_CODE = G.ARR_ARR_AIRPORT_CODE) AS [ARR_ARR_CITY_NAME]
		, (SELECT MAX(CONTRACT_NO) FROM RES_CONTRACT  WITH(NOLOCK) WHERE RES_CODE = A.RES_CODE ) AS CONTRACT_NO
		, DBO.XN_EMP_GET_EMP_KEY_NUMBER( D.EMP_CODE ) AS EMP_KEY_NUMBER   -- 개인별 대표번호 2019-11-18 
		, DBO.XN_EMP_GET_TEAM_KEY_NUMBER( D.EMP_CODE ) AS TEAM_KEY_NUMBER   -- 팀별 대표번호 2019-12-10 

	FROM RES_MASTER_damo A WITH(NOLOCK)
	INNER JOIN PKG_MASTER B WITH(NOLOCK) ON A.MASTER_CODE = B.MASTER_CODE
	INNER JOIN PKG_DETAIL C WITH(NOLOCK) ON A.PRO_CODE = C.PRO_CODE
	INNER JOIN VIEW_EMP_MASTER D WITH(NOLOCK) ON A.NEW_CODE = D.EMP_CODE
	INNER JOIN EMP_TEAM F WITH(NOLOCK) ON D.TEAM_CODE = F.TEAM_CODE
	LEFT JOIN COD_PUBLIC E WITH(NOLOCK) ON E.PUB_TYPE = 'FAX.TEAM' AND E.PUB_CODE = D.TEAM_CODE
	LEFT JOIN PRO_TRANS_SEAT G WITH(NOLOCK) ON C.SEAT_CODE = G.SEAT_CODE

	
	WHERE ((ISNULL(@RES_CODE, '') <> '' AND RES_CODE = @RES_CODE) OR (ISNULL(@PRO_CODE, '') <> '' AND A.PRO_CODE = @PRO_CODE))
END




GO
