USE [ADCGuardian]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PerfDataQueue](
	[ServerID] [smallint] NOT NULL,
	[CounterID] [int] NOT NULL,
	[InsDate] [datetime] NOT NULL,
	[DataFloat] [float] NOT NULL,
 CONSTRAINT [PK_PerfDataQueue] PRIMARY KEY CLUSTERED 
(
	[InsDate] ASC,
	[CounterID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
