USE [ADCGuardian]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ERROR_MONITORING_SETTING](
	[SQLServerID] [smallint] NOT NULL,
	[ServerID] [smallint] NOT NULL,
	[SEVERITY] [tinyint] NOT NULL,
	[ScheduledInsertID] [int] NOT NULL,
	[TARGET_MATERIAL] [char](11) NOT NULL,
	[FILE_TARGET_DIR] [varchar](1024) NULL,
	[MAX_SIZE_MB] [smallint] NOT NULL,
	[APPLY_RESERVED] [char](1) NOT NULL,
	[USE_YN] [char](1) NOT NULL,
 CONSTRAINT [PK_ERROR_MONITORING_SETTING] PRIMARY KEY NONCLUSTERED 
(
	[SQLServerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ERROR_MONITORING_SETTING] ADD  DEFAULT ((0)) FOR [SEVERITY]
GO
ALTER TABLE [dbo].[ERROR_MONITORING_SETTING] ADD  DEFAULT ((10)) FOR [MAX_SIZE_MB]
GO
ALTER TABLE [dbo].[ERROR_MONITORING_SETTING] ADD  DEFAULT ('Y') FOR [APPLY_RESERVED]
GO
ALTER TABLE [dbo].[ERROR_MONITORING_SETTING] ADD  DEFAULT ('Y') FOR [USE_YN]
GO
ALTER TABLE [dbo].[ERROR_MONITORING_SETTING]  WITH CHECK ADD  CONSTRAINT [CK_ERROR_MONITORING_SETTING] CHECK  (([TARGET_MATERIAL]='ring_buffer' OR [TARGET_MATERIAL]='file_target'))
GO
ALTER TABLE [dbo].[ERROR_MONITORING_SETTING] CHECK CONSTRAINT [CK_ERROR_MONITORING_SETTING]
GO
